== Consideraciones sobre el Entretenimiento y la Recreación

Consideremos, el uso de los juegos, deportes, comedias y otras cosas similares,
usadas comúnmente por todo tipo de cristianos,
bajo la pretensión de entretenimiento y recreación,
y veamos si tales cosas están de acuerdo con la seriedad,
gravedad y temor santo que el evangelio exige.
Yo confieso abiertamente que la verdadera religión no consiste en reglas externas,
sino en un nacimiento interno del Espíritu, y en un crecimiento en la gracia;
pero deseo que todos consideren cuidadosamente si tales entretenimientos no contradicen,
deshonran y batallan en contra del propósito de Dios para el alma inmortal del hombre.

Dejen que cualquier hombre honestamente inspeccione las vidas de
la mayoría de quienes se llaman a sí mismos cristianos,
ya sean católicos o protestantes,
y vean si en general hay alguna diferencia con los paganos,
excepto solo en el nombre y profesión de las creencias.
Porque de hecho, ¿no abunda en todos la misma locura, la misma vanidad,
el mismo abuso del precioso e irrevocable tiempo?
¿No se hallan los mismos juegos, deportes, apuestas y la búsqueda del placer,
que dan lugar a las mismas disputas, peleas, juramentos, lujurias, obscenidades,
locuras y deleites?
¿Y cómo pueden remediarse estas cosas mientras predicadores y profesantes del cristianismo,
y aquellos que son considerados líderes del pueblo,
permitan abiertamente estas cosas y las consideren consistentes con el evangelio?
¿No es extraño ver que estas cosas son toleradas en casi todo lugar?
Y si alguno reprende a otro,
o le suplica que abandone tales cosas y que seriamente
le sirva y adore a Dios en Su propio Espíritu puro,
tal persona rápidamente se convierte en una víctima,
y a menudo es sometida a burlas o a sufrimientos crueles.
¿Tiene esto alguna relación con el cristianismo?
¿Se parecen estas cosas en algo a las iglesias de los primeros cristianos?
Realmente no, en absoluto.

Primeramente citaré algunos testimonios de las Escrituras,
y luego veré si aquellos que los obedecen pueden permitir esas cosas ya mencionadas.
El apóstol nos manda que: "`Si coméis o bebéis, o hacéis otra cosa,
hacedlo todo para la gloria de Dios.`"^
footnote:[1 Corintios 10:31]
Pero supongo que nadie será tan atrevido como para afirmar que,
en la práctica de estos deportes, juegos y recreaciones,
Dios es glorificado de esa manera.
Porque la experiencia demuestra abundantemente que, en la práctica de estas cosas,
a los hombres nada les interesa menos que la gloria de Dios,
y nada les interesa más que la satisfacción de sus propias concupiscencias,
voluntades y apetitos carnales.

En otra parte, el apóstol exhorta: "`Debido a que el tiempo es corto,
los que compran sean como si no poseyesen; y los que disfrutan de este mundo,
como si no lo disfrutasen`"^
footnote:[1 Corintios 7:26-31] etc.
Pero, ¿cómo puede encontrarse alguien en obediencia a este precepto,
cuando aboga por el uso de los juegos, la recreación y el entretenimiento?
Estos, al parecer, piensan que su tiempo aquí es muy largo,
porque en lugar de emplear el tiempo en cuidar sus almas o las necesidades de sus cuerpos,
inventan juegos y deportes para pasar el tiempo,
como si carecieran de la capacidad de servir a su Creador, o ser útiles para Su creación.

El apóstol Pedro desea que "`nos conduzcamos en temor
todo el tiempo de nuestra peregrinación aquí.`"^
footnote:[1 Pedro 1:17]
Pero, ¿dirá alguien que aquellos, quienes son dados a fiestas, comedias,
juegos y obras de teatro, en serio les importe esta escritura en el uso de estas cosas,
donde casi lo único que se ve es ligereza, vanidad, libertad carnal y obscenidad?
¿No les impiden tales cosas a los hombres tener temor de
Dios y todo tipo de reflexiones serias e importantes?
No hay ningún deber más requerido en las Escrituras,
ni uno que le concierna más al cristiano,
que el temor del Señor--que permanecer en reverencia ante Él y caminar como en Su presencia.
Pero si aquellos que se entregan al entretenimiento
y a la recreación hablaran desde sus consciencias,
deben (sin duda) declarar por experiencia que todo
piadoso temor es olvidado en su placer y regocijo.
Y si el Señor, por medio de Su luz, los tocara secretamente,
o los pusiera a pensar en la vanidad de su camino, se esforzarían por callarlo,
usando su entretenimiento como una herramienta para expulsar a su Huésped fastidioso,
y así alegrarse sobre el Testigo Justo,^
footnote:[Ver Apocalipsis 11:10]
a quién ellos han matado y crucificado en sí mismos.

Pero además, si a Cristo hay que escucharlo, quien dijo:
"`el hombre bueno del buen tesoro del corazón saca buenas cosas;
y el hombre malo del mal tesoro saca malas cosas;`"^
footnote:[Mateos 12:35]
y que "`de toda palabra ociosa que hablen los hombres,
de ella darán cuenta en el día del juicio,`"^
footnote:[Mateos 12:36]
se puede ver fácilmente de qué tipo de tesoro provienen estos divertidos inventos.
¿Cuántas palabras ociosas producen inevitablemente estas cosas?
Sí,
¿qué son las comedias y las obras de teatro sino una mezcla de palabras falsas y ociosas?
Ahora, tú que crees que tu alma es inmortal,
y que habrá un día de juicio en el que se cumplirán estas palabras de Cristo, respóndeme:
¿Cómo vas a dar cuenta en ese día tan grande y terrible,
de todas las palabras ociosas que se emplean necesariamente en juegos, obras de teatro,
fiestas y otras formas de recreación y diversión? Y sin embargo,
muchos de los que se consideran cristianos no solo permiten estas cosas,
¡sino que ocupan todo su tiempo en ellas!
Por desgracia, no se puede negar que cristianos como estos,
hacen del cuidado de sus almas el asunto de menos importancia,
provocando al Señor a retener Su bendición,
mientras pasan el tiempo de su peregrinaje en cadenas de oscuridad, ahogados en lujuria,
sensualidad y placer mundano, sin ningún sentido del temor de Dios,
o de la salvación de sus propias almas.

[.discourse-part]
Objeción:
Pero algunos objetan que el espíritu del hombre no podría subsistir
si estuviera siempre concentrado en cosas serias y espirituales,
y que por lo tanto,
es necesaria la diversión y la recreación para aliviar y refrescar la mente,
y así esta pueda aplicarse más vigorosamente a las cosas espirituales.

[.discourse-part]
Respuesta: Confesamos con libertad que,
mientras estemos vestidos de este tabernáculo de barro,
no es posible mantener una atención y enfoque perfectos en las cosas celestiales.
Sin embargo,
esto no nos permitirá en ningún momento desatender
el principal cuidado de nuestras almas,
olvidar el temor de Dios y participar activamente en aquellas cosas que
afligen al Espíritu y batallan en contra de la operación de Su gracia.

Ahora hay cosas necesarias, en las cuales todos están involucrados,
cosas que tratan con el cuidado y preservación del hombre exterior,
y que permiten relajar la mente de los deberes espirituales más serios.
Y estas cosas verdaderamente pueden cumplirse en la bendición de Dios;
porque conforme la mente se leuda con Su amor y con un sentido de Su presencia,
el alma lleva consigo la influencia divina y el sentido espiritual,
por lo cual actos tales como comer, beber, dormir, y trabajar se hacen para el Señor,
complaciéndolo y sirviéndolo y respondiendo a nuestro
propósito en la creación. Pero los malvados y profanos,
que no han llegado a este lugar, son malditos en todo lo que hacen,
de modo que su "`labrar, así como orar, es pecado.`"^
footnote:[Proverbios 21:4 (Reina Valera de Gomez), Salmo 109:7]

Ahora, si alguno alegara que, para la relajación de la mente,
puede haber libertad permitida más allá de las cosas que son de
absoluta necesidad para el sustento del hombre exterior;
no voy a contender contra eso, siempre que estas cosas no sean del todo superfluas,
y que en su naturaleza y tendencia no lleven a la mente a la lujuria,
a la vanidad y al descuido.
Hay otras diversiones inocentes que pueden servir para la relajación de la mente,
como que los amigos se visiten, o leer la historia, o seguir la jardinería,
y otras cosas de esta naturaleza.
Pero en todas estas cosas no debemos olvidarnos del Señor
(en quien vivimos, somos y nos movemos. Hechos 17:28),
como para no tener siempre alguna atención secreta hacia él,
con una sensación de Su temor y presencia,
que frecuentemente se ejerce en medio de nuestras actividades por
medio de algunos anhelos y respiraciones al Dios de nuestra vida.

Pero de nuevo, creo que es evidente para todas las personas serias que los juegos,
las obras de teatro, las comedias, las diversiones,
y las formas más comunes de entretenimiento y recreación
no hacen sino sofocar los anhelos del alma por Dios,
y sirven solo para sacar a los hombres de Su temor, haciendo que olviden el cielo,
la muerte y el juicio, mientras promueven la lujuria, la vanidad y el descuido.
