== Prefacio

Robert Barclay (1648-1690) fue un cuáquero escocés,
y uno de los escritores más eminentes de la primitiva Sociedad de los Amigos.
Su Apología de la Verdadera Teología Cristiana fue publicada por primera vez en 1675,
y llegó a considerarse la exposición y la defensa definitivas de los principios
de los Cuáqueros durante los siguientes 200 años.

Barclay nació rodeado de abundancia y fue educado
en algunas de las mejores escuelas de la época,
en las que su ingenio natural ganó la admiración de maestros y compañeros.
Además del inglés, cuando era muy joven ya era un experto en los idiomas griego, hebreo,
francés y latín,
y se destacó tanto en sus estudios que su tío (el Rector de la
Universidad de los Escoceses de Paris) le ofreció hacerlo su heredero.
Pero a los diecisiete años de edad, al entrar a una reunión del pueblo llamado Cuáqueros,
Robert Barclay dijo,
"`Sentí un poder secreto entre ellos que tocó mi corazón.`" Y continuando con ellos,
llegó "`a recibir y a dar testimonio de la Verdad,`" no siendo convencido, dijo,
"`por la fuerza de argumentos, o por una discusión particular de cada doctrina,
sino por ser secretamente alcanzado por la Vida.
Y a medida que le abría paso,
sentía que el mal se debilitaba en mí y que el bien se levantaba,
y así llegué a estar ligado y unido a este pueblo, deseando, cada vez más,
experimentar el aumento del Poder y la Vida de Cristo
por los cuales podría sentirme perfectamente redimido.`"

La Apología de la Verdadera Teología Cristiana (de la cual se extrajo este libro) fue
escrita por primera vez en latín cuando Barclay tenía solo veintisiete años de edad,
y después él mismo la tradujo al inglés. En el prefacio
de la edición original encontramos los siguientes comentarios:

"`Tal vez mi método de escribir pueda parecer no solo diferente, sino incluso contrario,
a aquel que es comúnmente usado por los hombres que se llaman teólogos;
pero esto no me preocupa.
Pues confieso que no solamente no soy un imitador ni admirador de los académicos,
sino que también estoy en contra y desestimo a aquellos por cuya
labor la religión cristiana está tan lejos de ser mejorada,
que más bien es destruida.
Tampoco he tratado de acomodar mi obra para los que tienen comezón de oír,
quienes desean comprender en su cabeza los conocimientos sublimes de la Verdad,
en lugar de abrazarlos en su corazón. Porque lo que
he escrito procede más de mi corazón que de mi cabeza;
surge de lo que he escuchado con los oídos de mi alma y visto con los ojos de mi corazón,
y de lo que mis manos han tocado de la Palabra de Vida.
Yo declaro eso que se me ha revelado internamente acerca de las cosas de Dios;
no preocupándome mucho por la elocuencia y excelencia de mis palabras,
sino deseando demostrar la eficacia y la operación de la Verdad.
Y si erro algunas veces en lo primero, no es gran cosa;
porque aquí no hago el papel del gramático o del orador, sino del cristiano;
y por lo tanto en esto he seguido la regla segura
de la Luz Divina y de las Sagradas Escrituras.
De hecho, lo que he escrito no está escrito para alimentar la sabiduría,
el conocimiento y el orgullo vano de este mundo, todo lo contrario,
para matar de hambre y contradecir estas cosas.`"

"`A ustedes les ofrezco las siguientes proposiciones;
por las cuales (si son leídas y consideradas en el temor del Señor)
podrán percibir esa verdad simple y evidente que el hombre,
por su sabiduría, ha hecho tan oscura y misteriosa.
Por desgracia,
el hombre ha agobiado al mundo con grandes y voluminosos tratados y comentarios,
y ha hecho la verdad cien veces más oscura y complicada de lo que es en sí misma.
Todo el aprendizaje escolar del hombre, que toma casi toda la vida aprender,
no lo acerca ni un poco más a Dios,
ni hace que sea menos impío o más justo de lo que era.
Por lo tanto, Dios ha desechado al sabio,
al entendido y a los disputadores de este mundo,
y ha escogido a unos pocos instrumentos despreciables y
sin estudio (como lo hizo con los pescadores de la antigüedad),
para publicar su Verdad pura,
y para liberarla de las neblinas y las brumas con las que el clero la ha nublado.
Y entre muchos otros que Dios ha escogido para dar
a conocer estas cosas--viendo que también he recibido,
en medida, gracia para ser un administrador del mismo Evangelio--me pareció bien,
de acuerdo a mi deber, ofrecerles las siguientes proposiciones.
Aunque son cortas, sin embargo, son muy importantes.
Abarcan mucho y declaran cuál es el verdadero fundamento del conocimiento, sí,
de ese conocimiento que conduce a la Vida Eterna.
De esta Vida doy testimonio,
y deseo que dicho testimonio sea considerado en la Luz de Cristo en todas sus consciencias.
Adiós.

Robert Barclay

Ury, Escocia, 25 del mes 9, 1675

Las siguientes páginas contienen cinco de las quince
proposiciones originales de la Apología de Barclay,
que tratan de la caída, redención, justificación y perfección del hombre.
En la traducción de este libro al español,
se tuvo mucho cuidado para preservar el significado e intención original de sus palabras.
Todas las citas de la Escritura en inglés son tomadas
de la versión King James (KJV) 1611,
por lo tanto, han sido usadas diferentes versiones de las Escrituras en español,
con el fin de comunicar la misma idea y conservar la fuerza de sus argumentos.
Cuando no se especifica la versión al pie de página,
quiere decir que ha sido usada la Reina Valera 1960. Sin embargo,
algunas veces la Reina Valera de Gómez (RVG), Reina Valera 1602 Purificada (RV1602P),
La Biblia de Las Américas (LBLA), y otras traducciones han sido escogidas,
porque concuerdan con más exactitud con la KJV o con los manuscritos originales.

Jason Henderson

Noviembre, 2019
