== Capítulo I. La Condición del Hombre en la Caída

Ahora vamos a examinar el estado y la condición del hombre tal
como se encuentra en la caída--cuál es su capacidad y poder,
y qué tanto puede, por sí mismo, avanzar en relación a las cosas de Dios.
En verdad, un entendimiento correcto de este asunto es de gran utilidad y servicio,
porque a partir de la ignorancia y los debates que lo han rodeado,
han surgido errores grandes y peligrosos, tanto por un lado como por el otro.
Algunos han exaltado la luz natural, o las facultades del hombre natural,
creyéndose capaces (por medio de la voluntad,
luz y poder propios del hombre) de seguir lo que
es bueno y hacer un progreso real hacia el cielo.
Otros, sin embargo, han corrido al otro extremo,
no solo confesando (correctamente) que los hombres son incapaces
de hacer bien por sí mismos y que son propensos al mal,
sino también insinuando que los bebés aun en el vientre de su madre,
antes de cometer alguna transgresión real,
están contaminados y son verdaderamente culpables, por lo cual merecen la muerte eterna.
De hecho,
muchos no han tenido temor de afirmar que los pobres bebés están condenados
eternamente y que deben sufrir los tormentos del infierno para siempre.
Pero el Dios de la Verdad,
habiendo revelado nuevamente Su Verdad mediante Su propio Espíritu,
nos ha enseñado a evitar estos dos extremos.

En este capítulo, por lo tanto, propongo mostrar,
primero--la condición del hombre en la caída,
y cuán incapaz es de entrometerse en las cosas de Dios;
y segundo--que Dios no le imputa el mal al hombre hasta que realmente se una a él.

=== La Naturaleza y Extensión de la Caída del Hombre

En cuanto a lo primero,
no es mi deseo entrar en detalles con respecto a las diversas nociones
y suposiciones que muchos han afirmado acerca de la condición de
Adán antes de la caída. Todos están de acuerdo con lo siguiente:
que debido a la transgresión Adán sufrió una pérdida muy grande,
no solo en las cosas que se relacionan con el hombre exterior,
sino con respecto a esa unidad y comunión verdadera que disfrutaba con Dios.
Esta perdida le fue expresada en el siguiente mandato:
"`Porque el día que de él comieres, ciertamente morirás.`"^
footnote:[Génesis 2:17]
Esta muerte no pudo haber sido una muerte externa, o la disolución del hombre exterior,
porque el cuerpo de Adán no murió sino hasta muchos cientos de años después.
Así que la muerte de la que se habla aquí debe necesariamente referirse
a la pérdida inmediata de la vida y comunión espiritual con Dios.

La consecuencia de esta caída también se expresa en estas palabras: "`Echó, pues,
fuera al hombre, y puso al oriente del huerto de Edén querubines,
y una espada encendida que se revolvía por todos lados,
para guardar el camino del árbol de la vida.`"^
footnote:[Génesis 3:24]
Ahora bien,
cualquiera que sea el significado literal o externo que esto pudiera haber tenido,
también podemos, sin ningún riesgo, atribuirle a este paraíso un significado espiritual,
y entenderlo correctamente como esa comunión y unidad espiritual
que los santos obtienen con Dios por medio de Jesucristo.
Estos querubines solo le dan paso a Cristo,
y a todos los que entren por Aquel que se llama a Sí mismo la Puerta.
Entonces, aunque no le atribuimos ninguna parte de la _culpa_ de Adán a los hombres,
hasta que la hagan suya por actos similares de desobediencia; sin embargo,
no es posible que los descendientes de Adán tengan algo bueno en su naturaleza,
como perteneciente a ella,
porque aquel de quien derivan su naturaleza no tenía nada bueno en sí mismo que transmitirles.

Por lo tanto,
sí podemos afirmar que Adán no retuvo en su naturaleza (como algo propio de ella) ninguna
voluntad o luz capaces de darle conocimiento o experiencia en cosas espirituales,
entonces su posteridad tampoco.
Así que, cualquier cosa verdaderamente buena^
footnote:[Nota del Editor:
Barclay no habla de cosas que se consideran buenas por la perspectiva caída,
entenebrecida y egoísta de la criatura, sino aquello que es verdaderamente bueno,
porque viene de la Fuente de la bondad Misma, y tiende hacia Su propósito eterno.]
que cualquier hombre haga, no procede de su naturaleza como hombre, o como hijo de Adán,
sino de la Semilla de Dios en él,
de una nueva visitación de la vida que le es concedida
para sacarlo de esta condición natural.
Pero, aunque este don o Semilla esté _en_ el hombre, no es _de_ él,
y esto lo declaró el Señor claramente; porque cuando hablaba del hombre caído,
testificó "`que toda imaginación de los pensamientos
de su corazón era solamente mala todos los días.`"^
footnote:[Génesis 6:5 RV1602P]
Estas palabras son muy claras y comprensivas.
Observen el énfasis de ellas: Primero,
Él dice que "`toda imaginación de los pensamientos de su corazón;`" de modo que
esto no admite la excepción de ningún pensamiento del corazón del hombre.
En segundo lugar,
que "`es solamente mala todos los días;`" no dice '`parcialmente mala
todos los días,`' ni '`completamente mala en algunos momentos:`' sino
que es _solamente_ mala y esto _¡todos los días!_
Esto ciertamente excluye la posibilidad de que algo
bueno le pertenezca naturalmente al corazón del hombre;
porque aquello que es solamente malo, y siempre malo,
no puede por su propia naturaleza producir algo bueno.
El Señor un poco después expresó nuevamente lo mismo, diciendo,
"`la imaginación del corazón del hombre es mala desde su juventud,`"^
footnote:[Génesis 8:21]
demostrando nuevamente cuán natural e inherente es
el mal para cada hijo e hija de Adán. De manera que,
si los pensamientos del hombre son malos solamente y siempre, y eso desde su juventud,
es cierto e innegable que los pensamientos del hombre le son completamente
inútiles e ineficaces en las cosas de Dios.

Además, esto se manifiesta de manera clara en aquel dicho del profeta Jeremías,
"`Engañoso es el corazón más que todas las cosas, y perverso.`"^
footnote:[Jeremías 17:9]
Porque,
¿quién puede pensar seriamente que un corazón como éste tenga algún poder en sí mismo,
o de alguna manera sea apto, para guiar a un hombre a la justicia,
viendo que su propia naturaleza es directamente lo opuesto?
Esto es tan contrario a la razón, y tan imposible naturalmente,
como decir que una piedra, por su propia naturaleza y capacidad,
podría volar hacia arriba.

El apóstol Pablo trata la condición del hombre en la caída de manera general,
tomando varias descripciones del Antiguo Testamento: "`Como está escrito: No hay justo,
ni aun uno; no hay quien entienda, no hay quien busque a Dios.
Todos se desviaron, a una se hicieron inútiles; no hay quien haga lo bueno,
no hay ni siquiera uno.
Sepulcro abierto es su garganta;
con su lengua engañan. Veneno de áspides hay debajo de sus labios;
su boca está llena de maldición y de amargura.
Sus pies se apresuran para derramar sangre; quebranto y desventura hay en sus caminos;
y no conocieron camino de paz.
No hay temor de Dios delante de sus ojos.`"^
footnote:[Romanos 3:10-18]
¿Qué más podría decirse?
Pablo parece ser particularmente cuidadoso de que
no se le atribuya ningún bien al hombre natural,
mostrando cuán contaminado está en todos sus caminos, sin justicia,
sin entendimiento y sin conocimiento de Dios,
fuera del camino correcto y completamente inútil.
Y si esta es la condición del hombre natural cuando está en la caída,
sin ninguna duda es incapaz de dar un paso verdadero hacia el cielo.

[.discourse-part]
Objeción:
Si alguien propone que este texto del apóstol no
habla de la condición de todos los hombres en general,
sino solo de algunos en particular, respondo:

[.discourse-part]
Respuesta: El texto dice claramente lo contrario en el verso anterior,
en el que el apóstol aplica estas cosas a sí mismo (en su
condición natural) y a todos los judíos y gentiles,
diciendo: "`¿Qué, pues?
¿Somos nosotros mejores que ellos?
En ninguna manera; pues ya hemos acusado a judíos y a gentiles,
que todos están bajo pecado.
Como está escrito:`" y entonces continua, mostrando que habla de la humanidad en general.

[.discourse-part]
Objeción:
Si objetan que el mismo apóstol dice en el capítulo anterior que
los gentiles "`hacen por naturaleza lo que es de la Ley,`"^
footnote:[Romanos 2:14]
y, por lo tanto, hacen por naturaleza lo que es bueno y aceptable ante los ojos de Dios,
respondo:

[.discourse-part]
Respuesta:
Aquí la palabra "`naturaleza`" no debe entenderse como la naturaleza propia del hombre,
la cual es corrupta y caída,
sino como aquella naturaleza espiritual que procede de la Semilla de Dios en el hombre,
a medida que recibe la visitación del amor de Dios y es vivificado por dicha Semilla.
Esto se muestra claramente por las palabras que siguen, donde Pablo dice, "`Éstos,
aunque no tengan ley`" (es decir, la ley escrita) "`son ley para sí mismos,
mostrando la obra de la ley escrita en sus corazones.`"
Así que cualquier obra buena que se manifieste,
es fruto del efecto de la ley de Dios escrita en el corazón. Y
viendo que la Escritura declara claramente que la ley escrita en
el corazón es parte de la dispensación del Nuevo Pacto,
esto no puede ser ninguna consecuencia o parte de la naturaleza caída del hombre.

Además,
si la "`naturaleza`" mencionada aquí pudiera entenderse
como la naturaleza propia del hombre,
entonces el apóstol inevitablemente se contradiría a sí mismo,
puesto que en otro lugar declara positivamente,
que "`el hombre natural no percibe las cosas que son del Espíritu de Dios,
porque para él son locura, y no las puede entender.`"^
footnote:[1 Corintios 2:14]
Ahora bien,
espero que todos confiesen que la Ley de Dios debe
considerarse como una de las cosas de Dios,
en especial cuando es escrita en el corazón. Y el apóstol,
en el séptimo capítulo de la misma epístola, dice que "`la Ley es santa,
justa y buena;`" y que "`la Ley es espiritual; mas yo soy carnal.`"
Ahora ¿En qué sentido es carnal,
sino según se encontraba en un estado no regenerado en la caída? Vemos
entonces que Pablo hace una clara distinción entre la Ley que es espiritual,
y la naturaleza del hombre que es carnal y pecaminosa.
Por lo tanto, así como Cristo dice que "`no se puede esperar recoger uvas de los espinos,
o higos de los abrojos,`" tampoco la ley (que es espiritual,
santa y justa) puede ser cumplida por una naturaleza que es corrupta,
caída y no regenerada.

De todo esto concluimos (y con buena razón),
que la "`naturaleza`" de la que se habla aquí (Romanos 2:14) por
la que se dice que algunos gentiles han hecho lo que es de la Ley,
no es la naturaleza común y caída de los hombres,
sino la naturaleza espiritual que surge de la ley justa y espiritual
escrita en el corazón por el dedo de Dios.

=== La Culpa es Imputada a los Transgresores

Ahora voy a hablar de la otra parte, a saber,
que esta semilla maligna y corrupta no se imputa
a los bebés hasta que realmente se unan a ella.
Porque Pablo relata en Efesios 2,
que los que son "`por naturaleza hijos de ira,`" son
_"`los que andan_ conforme al príncipe de la potestad del aire,
el espíritu que ahora opera en los hijos de desobediencia.`"
Aquí el apóstol nos dice la razón por la que son hijos de ira es,
que andan conforme al mal.
Y esto concuerda con todo el tenor del Evangelio,
donde ningún hombre jamás es amenazado o juzgado
por la iniquidad que en realidad no ha cometido.
Pero en el caso de aquellos que continúan en la iniquidad,
y que de esta manera aprueban los pecados de sus padres,
Dios visitará la maldad de los padres sobre los hijos.

Pero ¡Ay!, como ha sido declarado;
muchos entre los protestantes y católicos no se avergüenzan
de declarar abiertamente que los bebés,
incluso en el vientre de su madre, están contaminados y son verdaderamente _culpables,_
y que, por lo tanto, merecen la muerte eterna.
Ahora bien, ¿no es extraño que los hombres sostengan una opinión tan absurda en sí misma,
y tan cruel y contraria a la misericordia y a la justicia de Dios,
acerca de la cual la Escritura no dice absolutamente nada?
¿No es manifiesto que el hombre ha inventado esta opinión a partir del amor propio,
y de esa raíz amarga de la cual brotan todos los errores?
Porque la mayoría de los protestantes que sostienen esta opinión piensan que ellos y
sus hijos descansan seguros en el decreto absoluto de la elección de Dios;
y puesto que se consideran incapaces de perder la salvación,
no les es difícil designar a todos los demás, tanto adultos como jóvenes, al infierno.
Porque viendo que el amor propio (que siempre es propenso a creer
lo que desea) los llena de la esperanza de que su parte está segura,
ellos no están muy preocupados por cómo esto afecta a sus prójimos,
que resultan ser la mayor parte de la humanidad.

Los católicos, por otro lado,
usan esta opinión como un medio engañoso para aumentar la
estima de su iglesia y la reverencia de sus sacramentos,
puesto que ellos pretenden que la culpa de Adán solo se
limpia mediante su ceremonia del bautismo de niños. Estos,
tal vez, parecen un poco más misericordiosos,
ya que no dicen que los niños no bautizados van al infierno,
sino al _limbo_--sobre lo cual las Escrituras tampoco dicen absolutamente nada.

Además de no ser encontradas en las Escrituras,
estas ideas son contrarias a la tendencia evidente de ellas.
El apóstol dice claramente, "`Donde no hay ley, tampoco hay transgresión,`"^
footnote:[Romanos 4:15]
y nuevamente, "`Pero donde no hay ley, no se inculpa de pecado.`"^
footnote:[Romanos 5:13]
Ahora bien, es obvio que para los bebés no puede haber ninguna ley,
ya que son absolutamente incapaces de recibirla y comprenderla.
La ley solo puede alcanzar a aquellos que tienen, en alguna medida,
el ejercicio de su entendimiento.
Pero los que están bajo una imposibilidad física ya sea de escuchar,
conocer o entender alguna ley--cuando dicha imposibilidad
no vino sobre ellos por algún acto de ellos mismos,
sino de acuerdo al orden de la naturaleza designado
por Dios--para tales no hay ninguna ley.

Además,
¿qué podría ser más evidente que las palabras de Dios a Ezequiel?--"`El alma que pecare,
esa morirá; el hijo no llevará el pecado del padre,
ni el padre llevará el pecado del hijo.`"^
footnote:[Ezequiel 18:20]
El profeta aquí muestra primero la verdadera causa de la muerte eterna de los hombres,
la cual es su propio pecado.
Luego, como si se hubiera propuesto expresamente a excluir tal opinión, nos asegura,
"`el hijo no llevará el pecado del padre, etc.`"
De lo cual argumento de esta manera: Si el hijo no lleva la culpa de su padre,
o de sus padres inmediatos, mucho menos llevará la culpa de Adán.

Habiendo demostrado hasta ahora cuán absurda es esta opinión,
examinaré brevemente las razones por la que algunos la defienden.

[.discourse-part]
Objeción: Primero, insisten que Adán fue la cabeza de la raza humana, y, por lo tanto,
todos los hombres pecaron en él, como estando todavía en sus lomos.
Y para respaldar esto alegan Romanos 5:12, donde el apóstol dice, "`Por tanto,
como el pecado entró en el mundo por un hombre, y por el pecado la muerte,
así la muerte pasó a todos los hombres, por cuanto todos pecaron.`"

[.discourse-part]
Respuesta: a esto respondo: No negamos que Adán es la cabeza de la raza humana,
ni que a través de él se haya propagado una semilla de pecado a todos los hombres,
la cual en su propia naturaleza es pecaminosa e inclina a los hombres a la iniquidad.
Sin embargo, de esto no se debe concluir que los bebés,
quienes no se unen voluntariamente a esta semilla, son considerados culpables.
Y en cuanto a estas palabras de Pablo en su carta a los romanos,
la razón de la culpa es declarada ahí claramente, "`por cuanto todos pecaron.`"
Pero que los bebes no pueden ser contados entre los culpables
se muestra evidentemente en el siguiente versículo:
"`Pero donde no hay ley, no se inculpa de pecado.`"

[.discourse-part]
Objeción: Su segunda objeción es del Salmo 51:5, "`He aquí, en maldad he sido formado,
y en pecado me concibió mi madre.`"
Por lo tanto, dicen, es evidente que los bebés son culpables incluso desde su concepción.

[.discourse-part]
Respuesta: Por mi parte,
no veo como llegan a esta conclusión. La iniquidad y el pecado
aquí parecen ser mucho más atribuibles a los padres que al hijo.
David dijo, "`en pecado me concibió mi madre;`" No dijo que,
"`Mi madre me concibió pecador.`"
Pero inclusive si el pecado mencionado aquí se debiera atribuir al hijo,
nosotros confesamos libremente que una semilla o naturaleza
de pecado es trasmitida a todos los hombres desde Adán,
en cuya semilla a todos les es dada la ocasión e inclinación a pecar,
y esto es el origen de todas las malas acciones y
pensamientos en los corazones de los hombres.
Pero, nuevamente,
insistimos (de acuerdo a las claras afirmaciones de las
Escrituras) que este mal no es imputado o acreditado a ninguno,
hasta que, por su propio pecado, se una voluntariamente a él.

[.discourse-part]
Objeción: Tercero, objetan,
que "`la paga del pecado es muerte;`" y viendo que
los niños están sujetos a enfermedades y a la muerte,
deben, por lo tanto, ser culpables de pecado.

[.discourse-part]
Respuesta:
Confesamos que la muerte y la enfermedad son una
consecuencia de la caída y del pecado de Adán;
pero negamos que esto necesariamente implique una culpa en todos los que las experimentan.
Porque, aunque la creación entera sufrió corrupción por la caída de Adán,
según lo que fue dicho en Job que "`ni aun los cielos son limpios delante de sus ojos;`"^
footnote:[Job 15:15]
sin embargo, esto no implica que por eso las hierbas,
la tierra y los árboles son pecadores.

[.discourse-part]
Objeción: Por último, algunos son tan tontos como para objetar lo siguiente:
si el pecado de Adán no es imputado a aquellos quienes realmente no han pecado,
entonces eso significaría que todos los bebés son salvos.

[.discourse-part]
Respuesta:
Estamos dispuestos a que esta conclusión sea la consecuencia de nuestra doctrina,
en lugar de aceptar la inevitable consecuencia de la de ellos, a saber,
que incontables bebés perecen eternamente, no por ningún pecado propio,
sino solo por la iniquidad de Adán. Aquí estamos dispuestos a detener la controversia,
encomendando todo al entendimiento iluminado del lector cristiano.
