== Capítulo II. La Oferta Universal de Redención

Habiendo considerado el estado caído, perdido, corrompido y degenerado del hombre,
ahora debemos inquirir cómo, y por qué medio,
puede ser librado de esta condición miserable y depravada.

=== Reprobación Absoluta--Una Doctrina de Demonios

Debemos empezar atacando la doctrina de la elección y la reprobación absoluta,
por la cual muchos no temen afirmar que Dios, por un decreto eterno e inmutable,
ha predestinado a la condenación eterna a la mayor parte de la humanidad,
sin tener en cuenta su desobediencia o pecado,
sino solo para la demostración de la gloria de Su justicia.
Ellos dicen que estas almas miserables están destinadas
a caminar en sus propios caminos perversos,
hasta que la justicia de Dios finalmente los alcance.
Dicen que Él no solo ha retenido la predicación del Evangelio
y el conocimiento de Cristo en muchas partes del mundo,
sino que incluso en aquellos lugares donde se predica el
Evangelio y se ofrece la salvación por medio de Cristo,
Dios condena justamente por desobediencia a grandes multitudes,
a quienes les ha negado la gracia por la cual podrían haber sido salvas.
Esto (se dice) es porque Él tiene predeterminado y decretado (sin tener
en cuenta la desobediencia o el pecado) por una voluntad secreta,
desconocida para todos los hombres,
que muchos no obedezcan y que la oferta del Evangelio nunca sea efectiva para su salvación,
sino que solo sirva para ocasionar su mayor condenación.

Ahora bien, con respecto a esta horrible y blasfema doctrina,
nuestro punto de vista es el mismo de muchos otros,
quienes la han refutado de manera sabia y entendida, de acuerdo a la Escritura,
la razón y la antigüedad.
Y viendo que ya se ha escrito tanto contra esta doctrina (que muy poco se puede añadir),
seré breve en este respecto.
Sin embargo, debido a que se interpone en mi camino,
no puedo dejarla pasar completamente.

En primer lugar, sin duda alguna podemos llamar a esta doctrina una novedad,
ya que durante los primeros cuatrocientos años después
de Cristo no se hizo ninguna mención de ella.
Porque, siendo contraria tanto al testimonio de la Escritura como al tenor del Evangelio,
todos los escritores,
maestros y padres antiguos de la iglesia la pasaron por alto con profundo silencio.
Sus primeros fundamentos fueron establecidos en los últimos escritos de Agustino, quien,
en su contienda contra Pelagio,
dejó caer algunas expresiones que algunos desafortunadamente
tomaron para establecer este error.
Posteriormente, esta doctrina fue promovida por Domingo, un fraile,
y los monjes de su orden; y, por último,
fue lamentablemente tomada por Juan Calvino (un hombre admirable en algunos otros aspectos),
para la gran mancha de su reputación y la difamación del Cristianismo Protestante.
Y aunque fue confirmada por los decretos del Sínodo de Dort,
desde entonces ha perdido terreno y está siendo desacreditada por la mayoría
de los hombres de conocimiento y piedad en todas las iglesias protestantes.
Sin embargo, no contendemos contra ella por el silencio de los antiguos,
ni por los pocos que la afirman, ni por la sabiduría de sus opositores,
sino porque creemos que no tiene ningún fundamento real
en los escritos o palabras de Cristo y los apóstoles,
y la encontramos sumamente ofensiva con respecto a Dios mismo,
a Jesucristo nuestro Mediador y Redentor, al poder, virtud,
nobleza y excelencia de Su bendito Evangelio, y, por último, a toda la humanidad.

En primer lugar, es sumamente ofensiva con respecto a Dios,
porque lo convierte en el autor del pecado,
que de todas las cosas es lo más contrario a Su naturaleza.
Yo sé que los que afirman este principio niegan esta consecuencia;
pero su negación es pura ilusión,
puesto que esto se deduce muy naturalmente de su doctrina.
Porque si Dios ha decretado que ciertas personas reprobadas perezcan,
sin que esto tenga nada que ver con sus malas obras,
sino solo porque en Su propia voluntad lo ha determinado; y además,
si esto fue decretado mucho antes de que tuvieran un ser,
o alguna capacidad de hacer el bien o el mal,
de modo que no pueden evitar andar en sus caminos de iniquidad,
por los cuales son llevados a la condenación; yo les pregunto: ¿Quién, entonces,
es el primer autor y causa de esto sino Dios,
que así lo quiso y lo decretó? Esta es la conclusión más natural y, de hecho,
la única que puede existir.
Y a pesar de que muchos de los predicadores de esta doctrina han buscado diversas,
extrañas,
torcidas y engañosas distinciones para defender su opinión y evitar esta horrible conclusión,
sin embargo, algunos de los más eminentes entre ellos han sido tan francos en el asunto,
que lo han puesto más allá de toda duda.
Daré algunos ejemplos entre muchos de estos:

Lo siguiente son expresiones de Juan Calvino: "`Por la ordenación y voluntad de Dios,
Adán cayó. Dios quiso que el hombre cayera.`"^
footnote:[Calvino en el capítulo 3 de Génesis.]
"`El hombre está cegado por la voluntad y el mandamiento de Dios.`"^
footnote:[Id. 1 Inst. c. 18. s. 1.]
"`Atribuimos la causa de nuestro endurecimiento a Dios.`"^
footnote:[Id. dib. de praed.]
"`La causa más alta o fundamental del endurecimiento es la voluntad de Dios.`"^
footnote:[Idem. lib. de provid.]
"`Se concluye que el consejo secreto de Dios es la causa del endurecimiento.`"^
footnote:[Id. 3 Inst., cap. 23. s. 1.]

Theodor Beza escribe: "`Dios no solo ha predestinado a la condenación,
sino también las causas de ella, a quien sea que vio apropiado.`"^
footnote:[Beza, lib. de praed.]
"`El decreto de Dios no puede ser excluido de las causas de la corrupción.`"^
footnote:[Id. de praed. ad art. 1.]

"`Es cierto,`" dice Jerome Zanchi,
"`que Dios es la primera causa de la dureza del corazón.`"^
footnote:[Zanchi, de excaecat. q. 5.]
"`Los reprobados están sujetos tan firmemente bajo el decreto del Dios todopoderoso,
que no pueden evitar pecar y perecer.`"^
footnote:[Idem, lib. 5 de nat. Dei cap. 2. de praed.]

"`Es la opinión,`" dice David Pareus, "`de nuestros maestros,
que Dios inevitablemente decretó la tentación y la caída del hombre.
De hecho, la criatura peca necesariamente, por el más justo juicio de Dios.
Nuestros hombres afirman con toda razón que la caída del hombre fue necesaria e inevitable,
debido al decreto de Dios.`"^
footnote:[Pareus, lib. 3. de amiss. gratiae. C. 2. Ibid., c. 1.]

"`Dios,`" dice Ulrich Zwingli, "`mueve al ladrón a matar.
Él mata, Dios forzándolo a ello.
Pero ustedes dirán que es forzado a pecar; confieso que en verdad es forzado.`"^
footnote:[Zwingli, lib. de prov. c. 5.]

"`Las personas reprobadas,`" dice Piscator,
"`están destinadas de manera absoluta a este doble fin: experimentar el castigo eterno,
y necesariamente pecar;
y la razón por la que están destinadas a pecar es
para que puedan ser castigadas con justicia.`"^
footnote:[Resp. ad Vorst. part 1, p. 120.]

Tales dichos clara y evidentemente hacen a Dios el autor del pecado.
Algunos han tratado de evadir esta consecuencia inevitable,
afirmando que los hombres pecan voluntariamente; pero esto no los ayuda en lo absoluto,
ya que la voluntad y la propensión del hombre al mal, según su propio juicio,
son necesariamente impuestas sobre él por la voluntad y el decreto de Dios.
Este artificio es como si yo tomara a un niño que es incapaz
de resistirme y lo arrojara desde un gran precipicio.
El peso del cuerpo del niño ciertamente lo hace descender con rapidez,
y la violencia de la caída lo mata de inmediato.
Ahora bien, les pregunto,
aunque el niño desciende voluntariamente debido al peso de su cuerpo,
y no por un golpe directo de mi mano (quien quizás esté a una gran distancia
cuando él muera) --¿soy yo o el niño la causa verdadera de su muerte?
Por tanto, que cualquier hombre de razón juzgue,
si las citas anteriores no solo hacen a Dios el autor inmediato del pecado,
sino también más injusto que el más injusto de los hombres.

En segundo lugar,
esta doctrina es sumamente ofensiva con respecto a Dios
porque lo hace complacerse en la muerte de los pecadores,
sí, y desear que muchos mueran en sus pecados, contrario a muchas escrituras, tales como:
"`Vivo yo, dice Jehová el Señor, que no me complazco en la muerte del malvado,
sino en que se vuelva el malvado de su camino y viva.
¡Volveos, volveos de vuestros malos caminos! ¿Por qué habéis de morir,
oh casa de Israel?`"^
footnote:[Ezequiel 33:11 RV2009]
Y, "`Porque esto es bueno y agradable delante de Dios nuestro Salvador,
el cual quiere que todos los hombres sean salvos y vengan al conocimiento de la verdad.`"^
footnote:[1 Timoteo 2:3-4]
Y, "`El Señor no retarda su promesa, según algunos la tienen por tardanza,
sino que es paciente para con nosotros, no queriendo que ninguno perezca,
sino que todos procedan al arrepentimiento.`"^
footnote:[2 Pedro 3:9]
Pero si Dios ha creado a los hombres para mostrar Su justicia y
poder en ellos (como estos hombres afirman) y si para efectuar
esto no solo les ha negado los medios para hacer el bien,
sino también ha predestinado el mal para que cayeran en él--ciertamente
debe complacerse en su muerte y desear que mueran,
puesto que no hace nada en contra de Su propia voluntad.

En tercer lugar, es sumamente ofensiva con respecto a Cristo nuestro mediador,
y con respecto a la eficacia y la excelencia de Su Evangelio;
porque hace que Su mediación sea ineficaz--como si no hubiera
derribado por completo la pared intermedia con sus sufrimientos,
ni quitado la ira de Dios,
ni comprado Su amor para toda la humanidad--si realmente estuviera predeterminado que
Su muerte no sería de ningún servicio para la mayor parte de la humanidad.

En cuarto lugar, hace que la predicación del Evangelio sea una mera burla e ilusión,
si es que realmente ha sido decretado de manera irrevocable que muchos
de aquellos a quienes se les predica están excluidos de su beneficio.
Hace que la predicación de la fe y el arrepentimiento,
junto con todas las promesas y advertencias del Evangelio no tengan ninguna utilidad.
Porque, ¿de que servirían,
si todo depende de un previo decreto por el cual un hombre elegido no puede evitar
ser salvo en el tiempo señalado (aunque sea en la última hora de su vida),
y un hombre reprobado no puede evitar ser condenado,
aunque busque y espere en el Señor con diligencia?

+++[++++++[+++__ddelink__84415_1695316585]]En quinto lugar,
es sumamente ofensiva con respecto a la venida de Cristo y Su sacrificio propiciatorio,
que las Escrituras afirman que ha sido el fruto del amor de Dios para el mundo
y ejecutado por los pecados y para la salvación de todos los hombres.
Porque, si fue predeterminado que la venida de Cristo salvara a muy pocos,
y que además sirviera para endurecer y aumentar la condenación de la mayor parte de
los hombres que no creen en ella (al no poder creer en ella por causa de la predestinación),
entonces la cruz más bien serviría como un testimonio de la ira de Dios para el mundo,
y como un acto de indignación hacia la mayor parte de la humanidad.

En sexto lugar, esta doctrina es sumamente ofensiva con respecto a la humanidad,
ya que los deja en una condición mucho peor que los demonios en el infierno.
Porque los demonios estuvieron una vez en su estado correcto,
y tenían la capacidad de permanecer así; estos, pues,
sufren por su propia rebelión y culpa.
Pero, según esta doctrina,
muchos millones de hombres son atormentados para siempre por el pecado de Adán,
del cual no saben nada, ni son responsables del mismo.
De hecho, esta doctrina los hace peores que las bestias del campo,
de quienes sus maestros no requieren más de lo que pueden hacer.
Y cuando una bestia es asesinada, la muerte es el final de su dolor;
pero los elegidos para condenación son atormentados
para siempre por no hacer lo que nunca pudieron hacer.
Sí,
esto pone al hombre en una condición mucho peor que
la condición en que Faraón puso a los israelitas;
porque a pesar de que les negaba la paja,
con mucho trabajo y dolor existía la posibilidad de obtenerla.
¡Pero esta doctrina hace que Dios niegue todos los medios de salvación,
de modo que el hombre de ningún modo puede alcanzarla!

=== La Muerte de Cristo Por Todos los Hombres

Después de haber removido de manera breve esta falsa
doctrina que se interponía en mi camino,
he llegado al tema de nuestra proposición, el cual es, "`Que Dios,
que no se complace en la muerte del pecador, sino en que todos vivan y sean salvos,
por Su infinito amor, ha enviado a Su Hijo unigénito al mundo,
para que todo aquel que en Él crea sea salvo.`"
La verdad de esta declaración,
siendo prácticamente las palabras expresas de la Escritura, no requerirá mucha prueba.
Y debido a que tenemos en común esta afirmación con muchos otros que, según la Escritura,
han abogado de manera ferviente y sana por la oferta universal de redención de Dios,^
footnote:[Nota del Editor:
Ha habido muchos malentendidos y conclusiones falsas derivadas del uso del término "`universal`"
por los Cuáqueros en relación a la redención. Esta palabra era utilizada por los Amigos
para establecer un contraste intencional contra la idea prevaleciente de que Dios ofrece
el conocimiento salvador de Cristo solo a unos pocos predestinados.
Los Cuáqueros rechazaban la idea de la predestinación individual y de una "`expiación
limitada,`" insistiendo en que Cristo murió por todos los hombres,
y que una oferta de redención se extiende a todos los hijos de
Adán. Es esta invitación misericordiosa e interna la que es universal.
Cuando la luz de Cristo es recibida,
seguida y obedecida se convierte en la vida y la salvación del alma.
Cuando es rechazada, la misma luz se vuelve la condenación eterna del hombre.
Véase Juan 3:19-21. Los primeros Cuáqueros nunca creyeron ni enseñaron
la doctrina del universalismo o la reconciliación universal.]
seré breve hasta llegar a esas afirmaciones que son más particularmente nuestras.

La verdad de que Cristo murió por todos los hombres
es tan evidente en el testimonio de la Escritura,
que difícilmente se encuentre algún otro artículo
de la fe cristiana que sea afirmado tan frecuente,
clara y positivamente.
Esto es lo que hace que la predicación de Cristo sea verdaderamente llamada el Evangelio,
o el anuncio de buenas nuevas para todos.
Por lo tanto, el ángel declaró el nacimiento y la venida de Cristo a los pastores,
diciendo, "`he aquí os doy nuevas de gran gozo, que será para todo el pueblo;`"^
footnote:[Lucas 2:10]
noten que no les dice '`para unas cuantas personas.`' Ahora bien,
si esta venida de Cristo no hubiera traído una posibilidad de salvación para todos,
este anuncio debería más bien haber sido considerado malas
noticias de gran tristeza para la mayoría de las personas;
tampoco el ángel habría tenido razón para cantar, "`en la tierra paz,
buena voluntad para con los hombres`"^
footnote:[Lucas 2:14],
si la mayor parte de la humanidad inevitablemente hubiera
sido excluida de recibir algún benefició de ella.
Y ¿para qué Cristo enviaría a Sus discípulos a "`predicar el Evangelio a toda criatura?`"^
footnote:[Marcos 16:15]
De hecho, les mandó a predicar el arrepentimiento,
la remisión de pecados y la salvación a cada hijo e hija de la humanidad,
amonestando y exhortando a todo hombre, como Pablo hizo en Colosenses 1:28.

Ahora bien,
¿cómo podrían estos ministros de Cristo haber predicado el Evangelio a todo hombre,
"`en plena certidumbre,`"^
footnote:[1 Tesalonicenses 1:5]
si la salvación por dicho Evangelio no fuera posible para todos?
Qué si alguno les hubiera preguntado,
"`¿Ha muerto Cristo por mí?`" Los que niegan la muerte
universal de Cristo no pueden responder nada a esto,
y solo dan vueltas en círculos.
Pero está escrito que "`los pies de los que traen
alegres nuevas del Evangelio de la paz son hermosos,`"^
footnote:[Isaías 52:7, Romanos 10:15]
porque predican una salvación común, arrepentimiento para todos,
la oferta de una puerta de misericordia y esperanza para todos a través
de Jesucristo "`el cual se dio a sí mismo en rescate por todos.`"^
footnote:[1 Timoteo 2:6]
Sí, el Evangelio invita a todos;
y ciertamente Cristo no tenía la intención de engañar a la mayor parte de la humanidad,
ni de burlarse de ellos, cuando los invitó y clamó, diciendo,
"`Venid a mí todos los que estáis trabajados y cargados, y yo os haré descansar.`"^
footnote:[Mateo 11:28]
Si todos, entonces, deben buscarlo y esperar Su salvación,
Él tuvo que haberla hecho posible para todos.
Ciertamente,
sería una mera burla pedirles a los hombres que busquen lo que es imposible de obtener.
Y por eso,
los que niegan que por la muerte de Cristo la salvación
se hizo posible para todos los hombres,
injuriosamente hacen que Dios se burle del mundo;
porque ellos admiten que Dios les ha dado a Sus siervos
una comisión de predicar el Evangelio de salvación a todos,
y, sin embargo,
sostienen que Él ha decretado previamente que es imposible que la mayoría lo reciba.

Pero viendo que Cristo, después de resucitar y perfeccionar la obra de nuestra redención,
dio la comisión de predicar el arrepentimiento,
la remisión de pecados y la salvación a todos,
es evidente que Él en verdad murió por todos.
Porque Aquel que ha mandado a Sus siervos a predicar así, es el Dios de la Verdad,
y no un burlador de la pobre humanidad, además,
Él no exige de ningún hombre lo que simplemente le es imposible hacer.

Además, si consideramos el testimonio de la Escritura en este asunto,
no hay ni una sola escritura, que yo sepa,
que afirme de manera clara que Cristo no murió por todos,
mientras que hay muchas que afirman positiva y expresamente que lo hizo, como,
por ejemplo: "`Exhorto ante todo, a que se hagan rogativas, oraciones,
peticiones y acciones de gracias,
por todos los hombres... Porque esto es bueno y agradable delante de Dios nuestro Salvador,
el cual quiere que todos los hombres sean salvos y vengan al conocimiento
de la verdad... el cual se dio a Sí Mismo en rescate por todos,
de lo cual se dio testimonio a su debido tiempo.^
footnote:[1 Timoteo 2:1, 3-4, 6]
Nada podría confirmar más claramente lo que hemos afirmado;
porque primero el apóstol les recomienda "`orar por todos los hombres,`" y luego,
como si tratara de evitar cualquier objeción con
respecto a la voluntad de Dios en este asunto,
les dice que "`esto es bueno y agradable delante de Dios,
el cual quiere que todos los hombres sean salvos.`"
Luego manifiesta la razón de Su voluntad de que todos los hombres sean salvos,
en estas palabras: "`El cual se dio a sí mismo en rescate por todos.`"
Es como si dijera: '`Puesto que Cristo murió por todos,
y puesto que se dio a sí mismo en rescate por todos,
Él por lo tanto desea que todos los hombres sean salvos.`' Y Cristo
mismo muestra el amor de Dios para con el mundo en estas palabras,
"`Porque de tal manera amó Dios al mundo, que ha dado a su Hijo unigénito,
para que todo aquel que en él cree, no se pierda, mas tenga vida eterna.`"
Esta frase "`todo aquel`" es un término indefinido del cual ningún hombre es excluido.

Esto mismo se afirma de manera muy positiva en las siguientes palabras:
"`Pero vemos a Aquel que fue hecho un poco menor que los ángeles, a Jesús,
coronado de gloria y de honra, a causa del padecimiento de la muerte,
para que por la gracia de Dios gustase la muerte por todos.`"^
footnote:[Hebreos 2:9]
Es evidente que si "`gustó la muerte por todos`" entonces
no hay hombre por quien no haya gustado la muerte,
ni hay quien no pueda volverse un participante de su beneficio;
porque Él no vino "`para condenar al mundo, sino para que el mundo sea salvo por Él.`"^
footnote:[Juan 3:17]
"`Él no vino a juzgar al mundo, sino a salvar al mundo.`"^
footnote:[Juan 12:47]
Pero según la doctrina de nuestros adversarios, Él no vino con la intención de salvar,
sino al contrario, para juzgar y condenar a la mayor parte del mundo,
contrario a Su propio y claro testimonio.

Y tal como el apóstol Pablo (en las palabras citadas arriba)
afirma positivamente que Dios quiere la salvación de todos,
asimismo el apóstol Pedro afirma lo mismo negativamente--que
Dios "`no quiere que ninguno perezca.`"
Él escribe, "`El Señor no retarda su promesa, según algunos la tienen por tardanza,
sino que es paciente para con nosotros, no queriendo que ninguno perezca,
sino que todos procedan al arrepentimiento.`"^
footnote:[2 Pedro 3:9]
Esto coincide con las palabras de Ezequiel: "`Vivo yo, dice Jehová el Señor,
que no quiero la muerte del impío, sino que se vuelva el impío de su camino,
y que viva.`"^
footnote:[Ezequiel 33:11]
Por lo tanto, si es seguro poner nuestra confianza en Dios,
no podemos creer que tiene la intención de engañarnos
con todas estas claras expresiones de Sus siervos.
Y si Su manifiesta voluntad por nuestra salvación no ha tenido efecto,
la culpa debe ser nuestra, como se mostrará después.

Aparte de estas cosas, ¿cómo deberíamos entender la multitud de invitaciones fervientes,
de acusaciones serias y de lamentaciones dolorosas
que llenan las páginas de las Sagradas Escrituras?
Tales como, "`¿Por qué moriréis, casa de Israel?`"^
footnote:[Ezequiel 18:31, 33:11]
"`¿Porque no queréis venir a mí para que tengáis vida?`"^
footnote:[Juan 5:40]
"`Aguardaré para otorgaros mi gracia,`"^
footnote:[Isaías 30:18 RV 1977]
"`Yo quise reunirlos`"^
footnote:[Mateo 23:37]
"`He tocado la puerta de sus corazones;`"^
footnote:[Apocalipsis 3:20]
"`Te destruiste a ti mismo, oh Israel`"^
footnote:[Oseas 13:9 RVG]
"`Te extendí mis manos todo el día.`"^
footnote:[Isaías 65:2]
Si aquellos, que de esta manera son invitados por el Señor,
no realmente tienen la capacidad de ser salvos,
entonces debemos suponer que Dios es como el autor de un romance o comedia,
quien se entretiene a Sí Mismo despertando los afectos y las pasiones de los hombres,
a veces llevándolos a la esperanza y a veces a la desesperación,
mientras que desde siempre ha predeterminado cual será la conclusión.

Además, esta doctrina es confirmada ampliamente por las palabras del apóstol Juan:
"`si alguno hubiere pecado, abogado tenemos para con el Padre, a Jesucristo el justo.
Y Él es la propiciación por nuestros pecados; y no solamente por los nuestros,
sino también por los de todo el mundo.`"^
footnote:[1 Juan 2:1-2]
La manera por la que nuestros adversarios intentan
evitar este claro testimonio es muy tonta y ridícula:
ellos dicen que "`mundo`" aquí, se refiere solo al mundo de los creyentes.
Para respalda esto, no tienen nada más que su propia afirmación; porque, muéstrenme,
si pueden, en toda la Escritura,
donde la frase "`todo el mundo`" da a entender los creyentes solamente.
Yo puedo mostrarles donde muchas veces significa lo contrario.^
footnote:[Nota de Barclay: Tales como, "`El mundo no me conoce.`"
"`El mundo no me recibe.`"
"`Yo no soy de este mundo.`"
Además de todas estas escrituras: Salmos 17:14; Isaías 13:11; Mateo 18:7; Juan 7:7, 8:26,
12:19, 14:17, 15:18-19, 17:14, y 18:20; 1 Corintios 1:21, 2:12, y 6:2; Gálatas 6:14;
Santiago 1:27; 2 Pedro 2:20; 1 Juan 2:15, 3:1, y 4:4-5, y muchas más.]

Es más, el apóstol, en este mismo lugar, hace una distinción entre el mundo y los santos,
diciendo "`y no solamente por los nuestros, sino también por los de todo el mundo.`"
¿Qué quiere decir el apóstol con "`nuestros`" aquí? ¿No
está hablando claramente de los pecados de los creyentes?
¿Y no es necesariamente "`todo el mundo`" una referencia a aquellos fuera de la iglesia,
por quienes Cristo también murió, y a quienes se extiende la invitación del Evangelio?
Pero no necesitamos mejor intérprete para el apóstol que él mismo,
porque él usa la misma expresión en el quinto capítulo de la misma epístola, diciendo,
"`Sabemos que somos de Dios y que todo el mundo yace en la maldad.`"^
footnote:[1 Juan 5:19]
Viendo entonces que el apóstol Juan nos dice claramente que Cristo no
solo murió por los santos y miembros de la iglesia de Dios a quienes escribió,
sino también por todo el mundo,
entonces sostengámosla como una verdad certera e indudable,
a pesar de las disputas de aquellos que se oponen.

Lo mismo también podría probarse de muchos más testimonios de las Escrituras,
si fuera necesario.
Y, de hecho,
todos los Padres de la iglesia (así llamados) durante
los primeros cuatro siglos predicaron esta doctrina.
Estos declaraban con audacia el Evangelio de Cristo y la eficacia de Su muerte,
invitando y suplicándoles a los paganos que vinieran y participaran de sus beneficios.
Ellos no les dijeron que Dios había predestinado a algunos de ellos para la condenación,
o que les había hecho imposible la salvación,
al negarles el poder y la gracia necesarios para creer; sino al contrario,
declararon que una puerta se había abierto para que toda la humanidad
viniera y fuera salva a través de Jesucristo.

Viendo entonces que esta doctrina de la universalidad
de la muerte de Cristo es tan cierta,
estando de acuerdo tanto con el testimonio de las
Escrituras como con la antigüedad cristiana,
alguien podría preguntarse ¿cómo es posible que tantos
(algunos de los cuales no solo han sido estimados sabios,
sino también piadosos) han sido capaces de caer en un error tan
grande y extraño? Ciertamente hay unos pocos textos difíciles que
la mente no regenerada puede torcer fácilmente y malinterpretar,
pero la causa principal surge de un malentendido general del modo o método mediante
el cual la virtud y eficacia de la muerte de Cristo se ofrece a todos los hombres.
Aquí los hombres han tropezado, y recurrido a varias invenciones teológicas.
Algunos se han alejado del testimonio claro de la Escritura,
por no haber entendido este camino,
y (como hemos visto) han limitado la expiación de Cristo a unos pocos predestinados.
Otros se han equivocado hacia la otra dirección,
afirmando que aquellos que nunca han escuchado la proclamación externa acerca de Cristo,
no están obligados a creer en Él,
o que todos son salvos independientemente de su fe y obediencia al evangelio.
