== Capítulo III. La Semilla, Luz y Gracia de Dios

Así como la oscuridad de la gran apostasía no vino
sobre el mundo cristiano toda a la vez,
sino más bien en varios grados, una cosa dándole paso a otra,
hasta que ese velo grueso y pesado se extendió (con el cual las naciones fueron
cubiertas y dejadas en gran parte ciegas desde el séptimo y octavo siglo,
hasta el dieciseisavo);
y así como la oscuridad de la noche no cae sobre la creación externa toda a la vez,
sino por grados, a medida que declina el sol en el horizonte;
así tampoco la luz y conocimiento pleno y claro de la gloriosa dispensación del
Evangelio de Cristo han vuelto a aparecer en el mundo todo de una vez.
De hecho,
la labor de los primeros testigos en la reforma tenía más
que ver con testificar contra los abusos de la apostasía,
y descubrirlos, que establecer la Verdad en pureza.
Él que quiere construir una nueva ciudad,
primero debe remover los viejos escombros antes de
que pueda ver cómo poner un nuevo fundamento;
y el que llega a una casa que está muy contaminada y llena de basura,
primero barrerá y removerá la suciedad antes de poner sus propios muebles buenos y nuevos.
La luz en el amanecer es suficiente para despejar
las tinieblas y hacernos ver las cosas más obvias;
pero el claro descubrimiento y discernimiento de las cosas,
como para hacer observaciones certeras y perfectas,
está reservado para el levantamiento del sol y su brillo en pleno resplandor.

Ahora bien, a partir de cierta experiencia, podemos afirmar con confianza,
que muchos de los lamentables y perjudiciales errores entre los protestantes
han surgido por el hecho de no haber esperado a que este sol saliera más;
y así han construido con y entre muchos viejos escombros católicos,
antes de que el fundamento fuese completamente purificado.
Pero ahora, en esta nuestra era,
a nuestro Señor Dios le ha complacido comunicar y
dar a conocer nuevamente un conocimiento más completo,
evidente y perfecto de Su Verdad eterna y de la dispensación de Su Evangelio
(a pesar de que se han dado varios testimonios de lo mismo,
por personas notables en distintas épocas, como se verá más adelante).
Y con el fin de magnificar la gloria de Su gracia y de excluir toda causa de jactancia,
ha levantado a unos pocos hombres despreciables y sin educación,
en su mayor parte obreros, para que sean Sus mensajeros.
Mediante este Evangelio, todos los escrúpulos, dudas,
confusiones y objeciones mencionados anteriormente,
se responden de manera fácil y evidente,
y tanto la justicia como la misericordia de Dios
(según su armonía divina y celestial) son exhibidas,
establecidas, y confirmadas.
Es de acuerdo a esta Luz o Evangelio veraz,
conforme se nos ha manifestado el conocimiento del mismo,
por la revelación de Jesucristo en nosotros,
fortalecido por nuestra propia experiencia viva y sellado
por el testimonio del Espíritu en nuestros corazones,
que podemos afirmar con confianza, y declarar claramente,
de acuerdo al testimonio de las Sagradas Escrituras, los siguientes puntos:

[.numbered-group]
====

[.numbered]
_I+++.+++_ Que Dios (quien por su infinito amor envió a Su Hijo, el Señor Jesucristo,
al mundo para gustar la muerte por todo hombre) ha dado a cada hombre--sea judío o gentil,
turco o escita, indio o bárbaro, de cualquier nación,
país o lugar--un cierto día o tiempo de visitación,
durante el cual les es posible ser salvos y participar del fruto de la muerte de Cristo.

[.numbered]
_II._ Que Dios, para este fin,
ha comunicado y dado a cada hombre una medida de la Luz de Su propio Hijo,
una medida de gracia, o una medida del Espíritu,
que la Escritura describe con varios nombres: como a veces "`la semilla del reino;`"^
footnote:[Mateos 13:18-19]
"`la Luz que manifiesta todo;`"^
footnote:[Efesios 5:13]
"`la Palabra de Dios;`"^
footnote:[Romanos 10:17, Santiago 1:21]
o "`manifestación del Espíritu dada para provecho;`"^
footnote:[1 Corintios 12:7]
"`un talento, o mina`"^
footnote:[Mateos 25:15, Lucas 19:11]
"`una pizca de levadura;`"^
footnote:[Mateos 13:33]
// lint-disable invalid-characters line-length
"`el Evangelio predicado en toda criatura`'footnote:[Colosenses 1:23, Traducción Literal "`εν παση τη  κτισει`"]

[.numbered]
_III._ Que Dios, en y por medio de esta Luz y Semilla, invita, llama,
exhorta y contiende con cada hombre con la intención de salvarlo.
A medida que esta obra de gracia es recibida, y no es resistida,
es capaz de efectuar la salvación de todos--incluso de aquellos
que no conocen la historia de la muerte y sufrimientos de Cristo,
y de la caída de Adán--al llevarlos a un sentido de su propia miseria,
y a la comunión con los padecimientos de Cristo internamente,
y al hacerlos partícipes de Su Resurrección, llegando a ser santos, puros y justos,
y libres de sus pecados.
Por esta misma Luz y Semilla,
también se obra la salvación en aquellos que sí tienen
el conocimiento externo e histórico de Cristo,
abriendo su entendimiento para usar y aplicar correctamente
las cosas descritas en las Escrituras,
y para recibir el beneficio salvador de ellas.
Sin embargo, este don de gracia puede ser resistido y rechazado en ambos,
en los cuales se dice que Dios es resistido^
footnote:[Véase Hechos 7:51; Hebreos 2:3; Gálatas 2:21, etc]
y oprimido,^
footnote:[Amos 2:13 "`He aquí,
yo estoy oprimido debajo de vosotros como está oprimida una carreta llena de gavillas.`"
LBLA]
y que Cristo es crucificado de nuevo y expuesto a vituperio en y entre los hombres;^
footnote:[Hebreos 6:6]
y para aquellos que lo resisten y rechazan de esta manera, Él se vuelve su condenación.^
footnote:[Juan 3:19]

====

Ahora bien, de acuerdo con esta doctrina: _Primero:_
La misericordia de Dios se exhibe magníficamente,
ya que ninguno queda necesariamente excluido de la salvación; y Su justicia se demuestra,
en que Él no condena a nadie excepto a aquellos a
quienes realmente les hizo una oferta de salvación,
habiéndoles proporcionado los medios suficientes para obtenerla.

_Segundo:_ Esta doctrina, si se considera debidamente,
se hallará como el fundamento del cristianismo, la salvación, y la confianza verdaderos.

_Tercero:_
Concuerda y encaja con todo el tenor de las promesas y las amenazas del Evangelio,
y con la naturaleza del ministerio de Cristo,
de acuerdo al cual se ordena que el Evangelio,
la salvación y el arrepentimiento se prediquen a toda criatura, sin acepción de naciones,
tribus, familias o lenguas.

_Cuarto:_ Magnifica y exalta los méritos y la muerte de Cristo,
ya que no solo los considera suficientes para salvar a todos,
sino que establece que han sido puestos tan cerca de todos los
hombres que los pone en una capacidad real de ser salvos.

_Quinto:_ Exalta la gracia de Dios sobre todo,
como la fuente de todo lo que es verdaderamente bueno--desde
el más mínimo y pequeño movimiento del bien,
hasta la conversión y salvación completa del alma.

_Sexto:_ Contradice,
invalida y anula la falsa doctrina de aquellos que exaltan
la luz de la naturaleza del hombre y la fuerza de su voluntad,
porque excluye por completo al hombre natural de
tener algún lugar o porción en su propia salvación,
por cualquier tipo de acto, movimiento u obra por su cuenta,
hasta que primero sea vivificado, levantado y movido por el Espíritu de Dios.

_Séptimo:_
Y así como hace que la totalidad de la salvación
del hombre dependa única y completamente de Dios,
también hace que la condenación del hombre sea totalmente, y en todos los aspectos,
por causa de sí mismo.
Porque el hombre que niega y resiste el don de Dios que lucha y contiende con su corazón,
al final se ve forzado a reconocer el justo juicio
de Dios cuando después lo rechaza y abandona.

_Octavo:_ Quita todo motivo de desesperación,
y le da a cada hombre un motivo de esperanza y una
confianza firme de que puede ser salvo.
Sin embargo, no alimenta a nadie con una seguridad falsa,
ya que ninguno sabe con certeza cuán pronto puede expirar su día. Por lo tanto,
es una constante incitación y provocación, y un estímulo vivo para cada hombre,
a abandonar el mal y volverse a aquello que es bueno.

_Noveno:_ Exalta maravillosamente la religión cristiana entre los incrédulos,
manifestando su verdad a todos,
ya que esta doctrina es confirmada y establecida por la experiencia de todos los hombres.
Porque nunca se ha encontrado un hombre en algún lugar de
la tierra (sin importar cuan bárbaro o salvaje sea),
que no haya sentido y reconocido (en algún momento u otro,
y en alguna medida) algo en su corazón que lo reprende
por causa de algunas cosas malas que ha hecho.
Este testigo interno es el mismo en todos--tanto amenazando
con cierto horror mientras el hombre continúe en el mal,
como también prometiendo y comunicando cierta paz
y dulzura a medida que se le dé paso a la gracia,
y no la resista.

_Décimo:_ Muestra maravillosamente la excelente sabiduría de Dios,
ya que por ella ha hecho que los medios de salvación sean tan universales y completos.
Él, por lo tanto, no está obligado a hacer uso de milagros externos,
ni del ministerio de los ángeles, ni de otros medios inusuales, puesto que,
según esta doctrina verdadera, el Evangelio alcanza a todos,
independientemente de la condición, edad o nación que sean.

_Onceavo:_
Es real y efectivamente establecida y confirmada por todos los predicadores y
promotores del cristianismo en todo el mundo (aunque quizás no en sus palabras,
pero sí en sus hechos).
Porque a pesar de que según su opinión se opongan a esta doctrina, ellos, sin embargo,
le predican a cada individuo que pueden ser salvos,
implorando y deseando que crean en Cristo, quien murió por ellos,
diciéndoles que Jesucristo los llama y quiere que crean y sean salvos, y que,
si se niegan, serán condenados, y que su condenación es de ellos mismos.
De hecho, tal es la evidencia y virtud de la Verdad, que constriñe a sus adversarios,
incluso contra su propia voluntad, a abogar por ella.

=== Consideraciones Adicionales sobre las Proposiciones Anteriores.

[.numbered-group]
====

[.numbered]
_I+++.+++_ En primer lugar,
cuando hablamos de que Dios le ha dado un día y tiempo de visitación a todos los hombres,
durante el cual pueden ser salvos,
no nos referimos al tiempo completo de vida de cada hombre--aunque para
algunos se pudiera extender incluso hasta la misma hora de su muerte,
como vemos en el ejemplo del ladrón que se convierte en la cruz.
Mas bien,
entendemos este tiempo de visitación como una temporada en la que el Espíritu
contiende con el hombre por la salvación de su alma (para algunos más corta,
y para otros más larga,
de acuerdo a lo que el Señor en Su sabiduría considere apropiado),
lo cual más que suficientemente exonera a Dios de la condenación de cada hombre.
Además,
es evidentemente posible que los hombres vivan más tiempo que este día o tiempo de visitación,
después del cual no tienen ninguna posibilidad de salvación. A estos Dios
justamente permite que sean endurecidos como el debido castigo de su incredulidad,
y en ocasiones hasta los utiliza como instrumentos de ira,
y los convierte en un azote el uno contra el otro.^
footnote:[Nota de Barclay:
A los hombres en esta condición se les puede aplicar apropiadamente
aquellas Escrituras que a menudo se usan erróneamente,
para probar que Dios incita necesariamente a los hombres a pecar.]

El apóstol expresa esta doctrina de manera clara en Romanos 1,
desde el versículo 17 hasta el final, pero especialmente en el versículo 28,
"`Y como a ellos no les pareció bien tener a Dios en su conocimiento,
Dios los entregó a una mente reprobada, para hacer cosas que no convienen.`"^
footnote:[Romanos 1:28 RV1602P]
Y por el ejemplo de Esaú se muestra que muchos pueden vivir más tiempo
que este día de la visitación misericordiosa de Dios para con ellos,
porque él tuvo una vez la primogenitura, y ciertamente pudo haberla conservado;
pero después, cuando deseó heredar la bendición, fue rechazado.^
footnote:[Hebreos 12:16-17]
Esto también se evidencia del llanto de Cristo sobre Jerusalén, diciendo, "`¡Oh,
si también tú conocieses, a lo menos en este tu día, lo que es para tu paz!
Mas ahora está encubierto de tus ojos.`"^
footnote:[Lucas 19:42]
Esto demuestra claramente que hubo un tiempo en el que podían haber conocido estas cosas,
cuyo tiempo ahora les había sido removido, aunque todavía estaban vivos.

[.numbered]
_II._ En segundo lugar, nosotros decimos que hay una Semilla, o medida de Gracia,
una Palabra de Dios, o Luz,
por la cual todo hombre es iluminado (habiendo recibido una medida de ella),
que contiende contra ellos con el fin de salvarlos, y que esta Luz puede,
por la dureza e iniquidad de la voluntad del hombre, ser apagada, ahogada, herida,
oprimida, inmolada y crucificada.
Ahora bien,
nosotros no entendemos que esta Semilla sea la esencia y naturaleza propia de Dios,
hablando estrictamente, la cual no es divisible en partes ni medidas,
puesto que Él es un ser sumamente puro y singular, sin ninguna composición ni división;
y en este sentido no puede ser resistido, golpeado, herido,
crucificado o asesinado por los esfuerzos y la fuerza de los hombres.
Pero nosotros entendemos que esta Semilla es una emanación espiritual,
celestial e invisible en la cual Dios (como Padre,
Hijo y Espíritu) habita--una medida de cuya vida
divina y gloriosa es sembrada en todos los hombres,
y que, de su propia naturaleza, atrae, invita e inclina hacia Dios.
Y a esto lo llamamos la carne y sangre espiritual de Cristo, que descendió del cielo,
de la cual todos los santos se alimentan y se nutren para vida eterna.
Y así como esta Luz y Semilla testifica contra cada pensamiento o acción injusta,
y los reprueba, asimismo, por esas acciones inicuas se dice que es herida,
crucificada o asesinada, y por lo tanto se retira o huye de ellos.

Ahora bien, debido a que esta Semilla nunca se separa de Dios,
sino que donde sea que esté, Dios y Cristo están envueltos en ella,
en este sentido decimos que cuando la Semilla es resistida, entonces Dios es resistido;
y donde es oprimida, se dice que Dios es oprimido,
como una carreta que está llena de gavillas,^
footnote:[Amos 2:13 LBLA, y H. B. Pratt (1929)]
y se dice que Cristo es asesinado y crucificado en los hombres.^
footnote:[Hebreos 6:6]
Y, por el contrario, a medida que esta Semilla se recibe en el corazón,
y se le permite producir su efecto natural y propio,
Cristo llega a ser formado y resucitado.
La Escritura frecuentemente hace mención de esto, llamándolo "`el nuevo hombre,`"^
footnote:[Efesios 4:24; Colosenses 3:10]
"`Cristo formado en vosotros,`"^
footnote:[Gálatas 4:19]
o "`Cristo en vosotros, la esperanza de gloria.`"^
footnote:[Colosenses 1:27]
Y este es ese Cristo dentro del alma de quién tan a menudo hablamos y declaramos,
a quien anunciamos, exhortando a las personas a creer en la Luz y obedecerla,
para que puedan conocer a Cristo dentro de ellos, librándolos de todo pecado.

Pero al predicar esta Luz o Semilla interna,
no pretendemos en absoluto igualarnos al Señor Jesucristo,
que nació de la virgen María y en quien habita corporalmente
toda la plenitud de la Deidad,
ni destruir la realidad de Su existencia presente.
Porque, aunque afirmamos que Cristo mora en nosotros,
Su presencia en nosotros se experimenta en parte, según nuestra medida,
y a través de la mediación de Su Semilla.
Pero en ese Hombre santo, el Señor Jesucristo, la Palabra eterna (que estaba con Dios,
y era Dios) mora en plenitud y sin mediación. Él, por lo tanto, es como la cabeza,
y nosotros somos como los miembros; Él es la vid y nosotros los pámpanos.

[.numbered]
_III._ En tercer lugar, entendemos que esta Semilla,
Luz o Gracia es una sustancia espiritual y real,
que el alma del hombre es capaz de sentir y percibir,
y de la cual surge un nacimiento real, espiritual e interno en los creyentes,
lo cual en la Escritura es llamado la nueva criatura,
o el nuevo hombre en el corazón. Esto parece extraño para los hombres
de mente carnal debido a que no están familiarizados con ello,
pero nosotros lo conocemos, y lo discernimos por una experiencia verdadera y certera.
De hecho,
es imposible que un hombre en su sabiduría natural
lo comprenda hasta que llegue a sentirlo en sí mismo,
y entonces se da cuenta que sostenerlo como una mera noción le es de muy poco provecho.
Sin embargo, aunque los hombres lo nieguen, somos capaces de demostrar que es la verdad,
y de mostrar que nuestra fe al respecto no carece de un fundamento sólido.
Porque es en y por medio de esta Semilla interna y substancial en nuestros corazones,
conforme ella recibe alimento y nace en nosotros,
que llegamos a tener esos sentidos espirituales desarrollados
por los cuales somos capaces de saborear,
oler, ver y tocar las cosas de Dios.
Porque el hombre no puede alcanzar estas cosas con su espíritu y sentidos naturales,
como se ha declarado anteriormente.

[.numbered]
_IV._ En cuarto lugar, al insistir en estas cosas, no pretendemos, de ninguna manera,
restarle importancia a la expiación y sacrificio de Jesucristo, ni menospreciarlo;
sino al contrario, lo magnificamos y exaltamos.
Porque,
así como creemos todas las cosas que están registradas
en las Sagradas Escrituras respecto al nacimiento,
vida, milagros, sufrimientos, resurrección y ascensión de Cristo,
también creemos que es el deber de todos aquellos,
a quienes les han sido declaradas estas verdades, creer en las mismas.
De hecho, consideramos que es una incredulidad digna de condenación,
_no creer_ cuando estas cosas han sido presentadas correctamente.
Porque la Semilla santa que es sembrada en el hombre, cuando se le presta atención,
lleva e inclina a cada corazón a creer en las verdades
de la Escritura conforme se les dan a conocer.
Porque, aunque no revela el conocimiento externo e histórico de Cristo en todo corazón,
sin embargo, siempre asiente a ello cuando es declarado.

Y así como firmemente creemos que era necesario que Cristo viniera,
para que a través de Su muerte y padecimientos se ofreciera
a Sí mismo como un sacrificio a Dios por nuestros pecados,
"`quien llevó Él mismo nuestros pecados en su cuerpo sobre el madero;`"^
footnote:[1 Pedro 2:24]
asimismo creemos que nadie puede participar de la remisión de los pecados
de ninguna otra manera más que en y por la virtud de ese sacrificio,
que fue sumamente satisfactorio;
porque es "`por la justicia de uno que vino la gracia
a todos los hombres para justificación de vida.`"^
footnote:[Romanos 5:18 RV1602P]

Nosotros además afirmamos,
que así como todos los hombres participan del fruto de la caída de Adán
debido a esa semilla maligna que les es comunicada a través de él,
haciéndolos propensos e inclinados al mal,
a pesar de que millones no saben nada acerca la caída de Adán,
ni jamás han oído que comió del fruto prohibido--así también,
muchos pueden llegar a sentir la influencia de esta Semilla y Luz santa y divina,
y por medio de ella convertirse del mal al bien,
a pesar de que no sepan nada de la venida de Cristo en la carne,
por cuya obediencia y sufrimientos les es comprado este don.
Y,
así como afirmamos que es absolutamente necesario que aquellos a quienes Dios le ha
placido darles el conocimiento de la historia de la aparición externa de Cristo,
crean en ella; asimismo confesamos libremente,
que el conocimiento externo es muy reconfortante,
pero solo para aquellos que en alguna medida están sujetos a la Semilla y Luz interna,
y son guiados por ella.
Porque escuchar sobre el amor y los sufrimientos de Cristo, no solo tiende a humillarlos,
sino que también los fortalece en su fe y los alienta
a seguir ese excelente patrón que Él nos ha dejado,
"`quien padeció por nosotros,`" como dice el apóstol Pedro, "`dejándonos ejemplo,
para que sigamos sus pisadas.`"^
footnote:[1 Pedro 2:21]
De hecho,
muchas veces somos grandemente edificados y animados
por los dichos piadosos que han procedido de Su boca.
Por lo tanto,
la historia es verdaderamente provechosa y reconfortante
cuando se conoce junto con el misterio,
y nunca sin él;
pero el misterio puede ser provechoso sin el conocimiento
explícito y externo de la historia.

[.numbered]
_V+++.+++_ Pero, en quinto lugar, esto nos lleva a otra pregunta, a saber--si Cristo,
por lo tanto, está en todos los hombres.
Hemos dicho antes que una Luz divina,
espiritual y sobrenatural ha sido dada a todos los hombres;
que Dios y Cristo moran en ella y nunca se separan de ella;
y también que a medida que esta Luz es recibida en el corazón, y se le cede paso,
Cristo llega a ser revelado y formado en ellos.
Pero estamos muy lejos de haber dicho alguna vez
que Cristo es _recibido_ por todos los hombres,
y mucho menos _formado_ en todos los hombres; porque eso es un gran logro,
por el cual el apóstol sufría dolores de parto para que fuera formado en los Gálatas.
Tampoco Cristo está en todos los hombres en el sentido de estar unido a ellos, ni,
para hablar estrictamente, en el sentido de habitar o morar en ellos,
porque este habitar implica una unión, o la manera en que Cristo reside en los santos.
Como está escrito "`__Habitaré__ y __andaré__ entre ellos.`"^
footnote:[2 Corintios 6:16]

Sin embargo, en un sentido más general,
viendo que Cristo nunca está (ni puede estar) separado de
esa Semilla y Luz pura que testifica en todos los hombres,
se puede decir que Él está en todos.
Es en este sentido (como se observó anteriormente) que la Escritura dice
que Dios está oprimido como una carreta llena de gavillas (Amos 2:13),^
footnote:[Amos 2:13 LBLA, y H. B. Pratt (1929)]
y que Cristo está crucificado en los impíos (Hebreos
6:6)--aunque si hablamos de manera correcta y estricta,
Dios no puede ser oprimido, ni Cristo (siendo Dios) puede ser crucificado.
Pero en este respecto,
podemos dirigir a todos los hombres a buscar a Cristo dentro de sí mismos,
quien yace crucificado en ellos por causa de sus pecados e iniquidades,
para que puedan "`mirarlo a Él, a quien traspasaron,`"^
footnote:[Zacarías 12:10]
y arrepentirse.
Entonces, Aquel que ahora yace crucificado y enterrado en ellos (por así decirlo),
pueda ser resucitado, y tener dominio sobre todo en sus corazones.
De esta manera también,
el apóstol Pablo le predicó a los Corintios y Gálatas acerca de
"`Cristo crucificado en ellos,`" (_en humin_ como lo tiene el griego.)^
footnote:["`Pues me propuse no saber __en vosotros__ cosa alguna sino a Jesucristo,
y a éste crucificado.`"
1 Corintios 2:2;
"`¡Oh gálatas insensatos! ¿quién os fascinó para no obedecer a la verdad,
a vosotros ante cuyos ojos Jesucristo fue ya presentado
claramente __en vosotros__ como crucificado?`"
Gálatas 3:1 -- Traducciones literales del griego.]
Este Jesucristo era el que el apóstol deseaba conocer en ellos, y manifestarles a ellos,
para que pudieran llegar a ser conscientes de cómo
habían estado resistiendo y crucificando a Cristo,
y entonces se arrepintieran y fuesen salvos.
Y debido a que Cristo es llamado "`la Luz verdadera, que alumbra a todo hombre,`"^
footnote:[Juan 1:9]
y "`la Luz del mundo,`"^
footnote:[Juan 8:12]
se puede decir, por lo tanto, que esta luz es Cristo,
quien verdaderamente es la fuente de toda luz, y tiene Su morada en ella para siempre.
Así la Luz de Cristo algunas veces es llamada Cristo, es decir,
aquello en lo que Cristo está, y de lo que nunca se separa.

[.numbered]
_VI._ En sexto lugar, por lo que ha sido dicho anteriormente,
se muestra claramente que no vemos esta Semilla o Luz divina
como algo que sea parte de la naturaleza del hombre,
ni como alguna reliquia que haya quedado del bien que Adán perdió por su caída;
porque sabemos que es una cosa distinta y separada
del alma del hombre y de todas sus facultades.
Sin embargo, tal es la malicia de nuestros adversarios,
que no dejan de reprocharnos diciendo que predicamos una luz natural,
o la luz de la conciencia natural del hombre.
Pero nosotros sabemos con certeza que la Luz de la cual hablamos no solo es distinta,
sino de una naturaleza diferente al alma del hombre,
y a todas sus operaciones y capacidades.

No negamos que el hombre, como una criatura racional,
tiene la razón como una facultad natural de su alma,
mediante la cual puede discernir cosas que son racionales.
De hecho, esta es una propiedad natural y esencial para él,
por la cual puede conocer y aprender muchas artes y ciencias,
más allá de lo que cualquier otro animal puede hacer con sus meras facultades animales.
Tampoco negamos que el hombre, por este principio racional,
puede retener en su cerebro y en sus nociones,
un conocimiento de Dios y de cosas espirituales; sin embargo,
al no ser este el órgano correcto para el verdadero conocimiento espiritual,
no puede servirle para la salvación, sino que, al contrario, a menudo lo estorba.
Y en verdad,
la gran causa de la apostasía ha sido que el hombre ha tratado de comprender
las cosas de Dios en y por este principio natural y racional,
y edificar una religión en esto,
negando y despreciando la Luz y Semilla de Dios en el corazón.
De este modo el Anticristo se ha "`exaltado`" en cada hombre,
"`sentándose en el templo de Dios, haciéndose pasar por Dios.`"^
footnote:[2 Tesalonicenses 2:4 RV1602P]
Porque, como el apóstol dice, los hombres son "`el templo del Espíritu Santo,`"^
footnote:[1 Corintios 3:16]
y por lo tanto,
cuando la razón natural se establece por encima de la Semilla y Luz de Dios,
para reinar y gobernar como príncipe en las cosas espirituales
(mientras que la Semilla Santa está herida y maltratada),
allí está el Anticristo en cada hombre, o algo exaltado sobre y en contra de Cristo.

Sin embargo,
con esto no queremos decir que el hombre ha recibido su razón sin ningún propósito,
o que no le es de utilidad; de ninguna manera.
Porque consideramos la razón como algo apropiado
para ordenar y gobernar al hombre en las cosas naturales.
Y así como Dios dio dos grandes lumbreras para gobernar el mundo exterior,
el sol y la luna,
la lumbrera mayor para gobernar el día y la lumbrera menor para gobernar la noche;
asimismo le ha dado al hombre la Luz de Su Hijo, una Luz divina y espiritual,
para gobernarlo en las cosas espirituales, y la luz menor de la razón,
para gobernarlo en cosas naturales.
Y tal como la luna toma prestada su luz del sol, asimismo los hombres,
si quisieran ser ordenados de manera correcta y feliz en las cosas naturales,
deberán tener su razón iluminada por esta Luz divina y pura.
Porque nosotros confesamos que, en aquellos que obedecen y siguen esta Luz verdadera,
su razón iluminada puede ser útil para el hombre, incluso en cosas espirituales,
siempre y cuando permanezca subordinada y sujeta a la otra; sí,
de la misma manera que la vida biológica en el hombre,
cuando está regulada y ordenada por su razón,
lo ayuda a hacer las cosas que son racionales.

Además,
nosotros distinguimos correctamente entre la Luz
de Cristo y la conciencia natural del hombre;
porque la conciencia,
siendo eso en el hombre que surge de las facultades naturales de su alma,
puede contaminarse y corromperse.
El apóstol Pablo, hablando de los impuros, dice claramente que,
"`hasta su mente y su conciencia están corrompidas.`"^
footnote:[Tito 1:15]
Sin embargo, esta Luz nunca puede corromperse o contaminarse,
ni jamás ha aprobado el mal o la iniquidad en nadie;
porque se dice expresamente que ella "`hace manifiestas todas las cosas que son reprobadas,`"^
footnote:[Efesios 5:13 RVG]
y por lo tanto es un testigo fiel para Dios en contra de
cada manifestación de injusticia en el hombre.

Ahora bien, la palabra conciencia, para definirla correctamente,
viene del latín _conscire,_
y es ese conocimiento que surge en el corazón del hombre a partir de lo
que está de acuerdo o es contrario a cualquier cosa que haya creído,
por medio del cual este se da cuenta de que trasgrede,
al hacer algo de lo que está convencido que no debería hacer.
Entonces, cuando la mente ha sido cegada o contaminada con una creencia incorrecta,
de esta creencia surge una consciencia que la perturba cada vez que actúa en su contra.
Por ejemplo, cuando un musulmán,
que ha aceptado una falsa creencia de que le es ilícito tomar vino,
actúa contra su creencia y bebe, su consciencia lo golpea por ello;
pero sí posee muchas concubinas, su conciencia no lo perturba,
porque su juicio ya está corrompido con una falsa opinión
de que le es lícito hacer una cosa e ilícito hacer la otra.
Sin embargo, si prestara atención a la Luz de Jesucristo en su interior, lo reprendería,
no solo por cometer fornicación,
sino que también le informaría (a medida que se volviera
más obediente a ella) que Mahoma es un impostor,
de la misma manera que Sócrates, en su día,
fue informado por ella de la falsedad de los dioses paganos.

Del mismo modo, si un católico romano comiera carne durante la Cuaresma,
o no fuera suficientemente diligente en la adoración de santos e imágenes,
su consciencia lo heriría por ello,
porque su juicio ya está cegado con una falsa creencia acerca de estas cosas.
Sin embargo, la Luz de Cristo nunca aprobó ninguna de esas abominaciones.
Por lo tanto, la conciencia natural del hombre se distingue claramente de ella;
porque la consciencia _sigue_ el juicio; no lo informa.
Pero esta Luz, en la medida que es recibida y obedecida,
quita la ceguera del falso juicio,
abre el entendimiento y rectifica tanto el juicio como la conciencia.
Así, pues, confesamos que la conciencia es una cosa excelente,
siempre y cuando esté correctamente informada e iluminada desde arriba.
De hecho, algunos de nosotros la hemos comparado apropiadamente con una linterna,
y la Luz de Cristo con la llama que está adentro.
Una linterna es útil cuando la llama está encendida y brilla en su interior,
pero de lo contrario no tiene ningún uso.
Por lo tanto, es a la Luz de Cristo _en la conciencia,_
y no a la conciencia natural del hombre, que continuamente recomendamos a los hombres.
Esta es su guía segura a la vida eterna.

Por último, es evidente que esta Luz, Semilla, etc.,
no es ningún poder o facultad natural de la mente del hombre,
porque un hombre sano puede, cuando quiere, agitar,
mover y ejercitar las facultades de su alma; de hecho, es amo de ellas,
y a no ser que haya alguna causa o impedimento natural en su camino,
puede usarlas a su antojo.
Pero esta Luz o Semilla de Dios en el hombre no se
mueve ni se despierta cuando el hombre lo desea;
al contrario, se mueve,
hiere y contiende con el hombre conforme el Señor lo considera oportuno.
Porque,
aunque hay una posibilidad de salvación concedida
a todo hombre durante el día de su visitación,
aun así, el hombre no puede, en cualquier momento que le plazca,
o cada vez que tenga un sentido de su miseria,
despertar esa Luz o Gracia para procurar para sí mismo una
verdadera ternura de corazón. En lugar de esto,
debe esperarla, ya que viene a todos en ciertos tiempos y temporadas,
obrando poderosamente en el alma, enterneciéndola y quebrantándola fuertemente.
En estos tiempos, cualquiera que no la resista, sino que la reciba y la siga,
llegará a experimentar la salvación por medio de ella.
Así como el estanque de Betesda no sanaba a todos,
sino solo a aquellos que esperaban el movimiento de las aguas, de la misma manera, Dios,
en ciertos tiempos,
se mueve por amor a la humanidad mediante Su Semilla en sus corazones,
poniendo sus pecados en orden delante de ellos, invitándolos seriamente a arrepentirse,
y ofreciéndoles la remisión de los pecados y la salvación;
y aquel que reciba esta invitación puede ser salvo.

Ahora bien, no hay ningún hombre vivo (y estoy seguro de que nunca lo habrá) que,
si tratara fiel y honestamente con su propio corazón,
no se viera obligado a confesar que ha sido consciente de esto en alguna medida;
lo cual es algo que el hombre no puede producir en sí mismo con todo su esfuerzo y diligencia.
Esto, pues, oh hombre y mujer,
es el día de la visitación misericordiosa de Dios para sus almas,
y serán felices para siempre si no lo resisten.
Este es el día del Señor, que, como Cristo dice,
es como el relámpago que resplandece desde el oriente hasta el occidente,
y como el viento o Espíritu, que sopla sobre el corazón,
y ningún hombre sabe de dónde viene, ni a donde va.

====

=== La Operación de la Semilla en el Corazón

[.numbered-group]
====

[.numbered]
_VII._
En séptimo lugar,
esto me lleva a hablar respecto a la manera en que opera
esta Semilla o Luz en el corazón de todos los hombres,
lo cual demostrará aún más claramente cuánto diferimos de todos
aquellos que exaltan el poder o luz natural en el hombre,
y como nuestro principio lleva (por encima de todos los
demás) a atribuir toda nuestra salvación únicamente al poder,
Espíritu y gracia de Dios.

Algunos nos han presentado la siguiente pregunta:
Si dos hombres tienen una medida igual y suficiente de Luz y Gracia,
y uno es salvo por ella, y otro no, ¿no es, entonces,
la voluntad del hombre la verdadera causa por la cual uno fue salvo y el otro no?
A esta pregunta respondemos:
puesto que la Gracia y Luz en todos es suficiente para salvarlos a todos,
y de su propia naturaleza salvaría a todos,
ella por lo tanto contiende y lucha con todos para salvarlos.
Aquel que resiste la obra de la gracia es la causa de su propia condenación;
él que no la resiste, encuentra que se convierte en su salvación. De manera que,
en el que se salva, la obra es de la gracia, y no del hombre,
y esto se debe a su rendición y pasividad, y no a su propia actividad.
Sin embargo, después, en la medida que un hombre es forjado por la gracia,
surge una voluntad en él por la cual llega a ser un colaborador de la gracia; porque,
como dijo Agustino, "`El que nos hizo sin nosotros, no nos salvará sin nosotros.`"

Por lo tanto, el primer paso del hombre no es actuar,
sino dejar de actuar en contra de la Luz y Gracia de Dios.
Y durante estas temporadas de visitación de cada hombre,
aunque el hombre es completamente incapaz, por sí mismo, de colaborar con la gracia,
o de dar un paso fuera de su condición natural hasta que la gracia se apodere de él,
aun así, le es posible ser pasivo y no resistirla, o ser duro y resistirla.
Por lo tanto,
nosotros decimos que la gracia de Dios obra en y sobre la naturaleza del hombre, que,
aunque de sí misma está completamente corrupta y contaminada, y es propensa al mal,
es capaz de ser forjada por la gracia de Dios--sí, así como el hierro,
a pesar de que es un metal duro y frío en sí mismo,
puede calentarse y ablandarse por el calor del fuego, y la cera derretirse por el sol.
Y como el hierro o la cera,
cuando se quitan del fuego o del sol vuelven a su condición anterior de frío y dureza,
asimismo el corazón del hombre, cuando resiste o se retira de la gracia de Dios,
regresa a su condición anterior otra vez.
Se me han ocurrido una o dos analogías,
que ilustran claramente la manera en que Dios busca la salvación de todos los hombres,
las cuales añadiré aquí, para la información de otros.

La primera se trata de un hombre muy enfermo,
a quien comparo con el hombre en su condición caída y natural.
Ahora bien, algunos suponen que Dios, el gran médico,
le ofrece medicina a este pobre hombre solo después
de que él ha hecho todo lo que está en su poder,
mediante cualquier habilidad o conocimiento propio, para obtener su propia sanidad.
Estos son aquellos que dicen que,
si un hombre cultiva su razón o sus facultades naturales,
entonces Dios verá apropiado proporcionarle gracia.
Otros dicen que Dios viene y le ofrece un remedio al hombre enfermo,
pero deja a la voluntad del hombre tanto el recibirlo como el rechazarlo.
Pero nosotros decimos, que Él, es decir, el Señor, este gran médico,
viene y vierte el remedio en la boca del hombre enfermo y lo acuesta en su cama,
de modo que, si el hombre enfermo se mantiene pasivo,
este remedio necesariamente lo curará. Pero si es duro y terco,
e insiste en levantarse y salir al frío,
y en comer esas cosas que le son dañinas mientras que la medicina opera; entonces,
aunque de su naturaleza la medicina tienda a curarlo, al final le será destructiva.
Así, pues, en este ejemplo,
el hombre que perece ciertamente es la causa de su propia muerte;
y el hombre que es sanado le debe su salud enteramente al médico,
y no a alguna obra propia.

El segundo ejemplo se trata de varios hombres que están juntos en un pozo oscuro,
en el cual todos sus sentidos están tan adormecidos,
que apenas son conscientes de su propia miseria.
A esto comparo al hombre natural en su condición natural, corrupta y caída. Nuevamente,
nosotros no pensamos que Dios mire hacia abajo y,
al ver que uno está haciendo todo lo que está en su poder para librarse,
decida que ese merece ser ayudado.
Tampoco pensamos que un libertador llegue al tope del pozo,
descuelgue una escalera y espere que ellos asciendan por su propia fuerza,
entendimiento y voluntad.
En lugar de esto, creemos que el libertador llega en ciertos tiempos,
y revela e informa plenamente a los hombres de la gran miseria y peligro
en el que están si continúan en ese lugar horrible e insalubre.
De hecho,
este redentor los lleva a sentir su miseria de una manera que no la pueden negar,
(porque incluso los hombres más impíos a veces son
conscientes de ella por la visitación de Dios),
y no solo eso, sino que a veces los agarra y les da un jalón,
con el fin de levantarlos fuera de su miseria,
lo cual los salvará si ellos no lo resisten;
pero ellos sí tienen la capacidad de resistirlo.

Estos dos ejemplos, en cierta medida, ilustran el asunto,
demostrando que la gracia de Dios alcanza a todos,
aunque su efecto difiere según el objeto con el que se encuentre.
Porque esta gracia es una ministración de misericordia
y amor en todos los que no la rechazan,
sino que la reciben (Juan 1:12);
pero la misma es una ministración de ira y condenación
en los que la rechazan (Juan 3:19);
así como el sol, que por un solo acto u operación, derrite y suaviza la cera,
pero seca y endurece la arcilla.
La naturaleza del sol es beneficiar la creación,
y por lo tanto los vivos son refrescados por él,
y las flores producen un buen aroma cuando brilla sobre ellas,
y los frutos de los árboles maduran.
Sin embargo,
con un cadáver muerto (una cosa sin vida) los mismos rayos solares harán que hieda,
y lo pudrirán. Así, pues, cada hombre, durante el día de su visitación,
es iluminado por el sol de justicia y es capaz de ser influenciado por él,
para producir buen fruto y un buen aroma y ser derretido
por él. Pero cuando un hombre ha rechazado la luz, y ha perdido su día por su pecado,
entonces el mismo sol lo endurece, como lo hace con la arcilla,
y hace que su iniquidad aparezca más y se pudra, y produzca un mal aroma.

====
