== Capítulo IV. La Prueba de Nuestra Postura

Habiendo declarado de manera clara y evidente los temas en cuestión,
y dado a conocer nuestro entendimiento y juicio en estos asuntos,
hará que nuestra prueba de ellos sea más fácil y corta.

=== Un Día o Tiempo de Visitación

Lo primero que debe ser probado es que Dios ha dado
a cada hombre un día o tiempo de visitación,
en el cual le es posible ser salvo.
Si lográramos probar que hay un día y tiempo dado en el que algunos que finalmente perecieron,
pudieron haber sido salvos, nuestro objetivo estaría cumplido.
Bueno,
esto se evidencia claramente a partir de muchas expresiones de lamento
y acusación dadas por el Espíritu de Dios a lo largo de toda la Escritura,
incluso a aquellos que al final perecieron;
culpándolos por no haber aceptado o recibido la visitación
de Dios ni Su oferta de misericordia para ellos.

Fue así como el Señor se mostró a Sí mismo a Caín al principio, diciendo,
"`¿Por qué estás enojado, y por qué se ha demudado tu semblante?
Si haces bien, ¿no serás aceptado?
Pero si no haces bien, el pecado yace a la puerta.`"^
footnote:[Génesis 4:6-7 LBLA]
Eso le fue dicho a Caín antes de que matara a su hermano Abel,
cuando la semilla del mal había comenzado a tentarlo y a obrar en su corazón.
Aquí vemos como Dios le dio una advertencia a Caín a tiempo,
en el día de Su visitación a él, ofreciéndole aceptación y remisión si hacía bien;
porque esta pregunta "`¿no serás aceptado?`"
implica la siguiente afirmación, "`Serás aceptado, si haces bien.`"
Por lo tanto, si podemos confiar en Dios Todopoderoso,
la fuente de toda Verdad y equidad, entonces fue posible incluso para Caín,
por un tiempo, ser aceptado.
Porque ciertamente Dios no hubiera propuesto el hacer bien como una condición,
si no le hubiera dado también a Caín poder suficiente
mediante el cual era capaz de hacerlo.

El Señor también muestra esto, al darle un día de visitación al mundo antiguo:
"`Y dijo Jehová:
// lint-disable invalid-characters line-length
No contenderá mi Espíritu _en_ el hombre para siempre,`" (porque así debe traducirse).footnote:[Génesis 6:3, בָ אָ דָ ם --es decir, "`en el hombre`"]
Esto evidentemente implica que Su Espíritu _sí_ contendió con el hombre,
y _aún_ contiende con el hombre por un tiempo,
cuyo tiempo expira cuando Dios deja de contender con ellos con la intención de salvarlos.
Y es durante este día de visitación dado a todos los hombres
que se dice que Dios "`espera para tener piedad,`"^
footnote:[Isaías 30:18]
y que es "`tardo para la ira`"^
footnote:[Éxodos 34:6; Números 14:18; Salmos 86:15; Jeremías 15:15, etc.]
para con Su creación. El apóstol Pedro dice expresamente que "`la paciencia
de Dios esperaba en los días de Noé por los del mundo antiguo,`"^
footnote:[1 Pedro 3:20]
que siendo comparado con Génesis 6:3 (antes mencionado),
confirma suficientemente nuestra proposición. Y para que nadie pudiera
objetar que esta paciencia o lucha del Señor no era para salvarlos,
el mismo apóstol dice claramente que,
"`la paciencia de nuestro Señor es para salvación;`"^
footnote:[2 Pedro 3:15]
porque, como él lo afirma un poco antes (verso 9), "`Dios no quiere que ninguno perezca.`"

Además, en el siguiente versículo, Pedro se refiere a los escritos de Pablo,
mostrando que esto había sido la doctrina universal de la iglesia.
Y lo que añade en esta ocasión merece nuestra atención:
cómo hay algunas cosas en las epístolas de Pablo que son difíciles de entender,
que los indoctos e inconstantes tuercen para su propia perdición,
muy probablemente aludiendo a las expresiones de Pablo en Romanos 9. Muchos en realidad,
que son indoctos en las cosas espirituales,
han hecho que las palabras de Pablo contradigan la verdad de la paciencia
de Dios para con todos y de Su deseo de que ninguno se pierda,
sino que todos sean salvos.
¡Si tan solo hubieran prestado más atención a la advertencia de Pedro!

Pero la parte de los escritos de Pablo a la que Pedro aquí pareciera referirse más particularmente,
también contribuye mucho para aclarar el asunto.
Porque Pablo escribe: "`¿O menosprecias las riquezas de Su benignidad,
paciencia y longanimidad, ignorando que Su benignidad te guía al arrepentimiento?`"^
footnote:[Romanos 2:4]
Aquí él le habla a los no regenerados y a los impíos,
a quienes en el siguiente verso les dice que están
"`atesorando ira para el día de la ira.`"
Pero encomienda a tales personas, a las riquezas de la benignidad y paciencia de Dios,
mostrando que la tendencia de la benignidad de Dios es guiar a los hombres al arrepentimiento.
¿Cómo podría necesariamente tender a guiarlos al arrepentimiento,
y cómo podría llamarse riquezas o benignidad para ellos,
si no hubiera un tiempo en el que pudieran arrepentirse y llegar
a ser participantes de las riquezas ofrecidas por Él?

De todo lo cual argumento de esta manera:
Si Dios pleitea con el impío basado en la posibilidad de que sean aceptados;
si el Espíritu de Dios contiende en ellos por un tiempo para salvarlos,
aunque después perecen; si Él espera para tener piedad de ellos;
si es paciente con ellos, y esta paciencia (mientras perdura) es para salvación,
durante cuyo tiempo Dios no quiere que perezcan,
sino que les exhibe las riquezas de Su benignidad y paciencia
con el fin de guiarlos al arrepentimiento--entonces concluyo,
que hay un día de visitación dado a los hombres en el cual pueden ser salvos,
si se arrepienten.

Además, lo mismo se muestra del profeta Isaías, donde se dice:
"`¿Qué más se podía hacer a mi viña, que yo no haya hecho en ella?`"^
footnote:[Isaías 5:4]
Porque en el segundo verso él dice:
"`La había cercado y despedregado y plantado de vides escogidas;
había edificado en medio de ella una torre, etc.`"
Y, sin embargo, cuando Él "`esperaba que diese uvas, dio uvas silvestres.`"^
footnote:[Isaías 5:2]
Por lo tanto,
llama a los vecinos de Jerusalén y a los varones
de Judá para que juzguen entre Él y Su viña,
diciendo; "`¿Qué más se podía hacer a mi viña, que yo no haya hecho en ella?`"
Esta parábola fue aplicada a muchos en Israel que rechazaron
la misericordia de Dios en los días de los reyes,
y el mismo ejemplo fue usado por Cristo (Mateo 21:33; Marcos 12:1;
Lucas 20:9). Aquí Jesús muestra que una viña fue plantada,
y que todas las cosas necesarias fueron dadas a los labradores
para que recogieran el fruto y le pagaran a su dueño. El dueño
muchas veces esperó para tener misericordia de ellos,
enviando siervos tras siervos, y pasando por alto sus muchas ofensas,
antes de determinar finalmente destruirlos y echarlos fuera.
Ahora bien, esta parábola no pudo haberse dicho haciendo referencia a los santos,
o a aquellos que se arrepienten y son salvos;
porque dice claramente que Él "`los destruirá.`" Tampoco es razonable
decir que estos hombres no tuvieran la capacidad de haber hecho el bien,
porque la expectativa del Señor era clara, y, de hecho, Él dice a través del profeta,
"`¿Qué más podía hacer?`"
Por lo tanto,
por esta parábola (repetida en tres evangelios) es más que manifiesto
que Cristo mantiene Su paciencia para con los hombres,
incluso en su iniquidad, por un tiempo,
proporcionándoles un verdadero medio de salvación;
y que aquellos que aun así se resisten,
lo hacen para su propia condenación. Véase también las siguientes escrituras paralelas:
Proverbios 1:24-26; Jeremías 18:9-10; Mateo 18:32-34; Hechos 13:46.

Por último,
por el lamento de Cristo sobre Jerusalén (expresado en tres lugares distintos:
Mateo 23:37, Lucas 13:34,
y 19:41) es evidente que existe un día de visitación dado a los impíos,
durante el cual pueden ser salvos, y que, habiendo expirado este tiempo,
ya no pueden obtener la salvación. "`Y cuando llegó cerca de la ciudad, al verla,
lloró sobre ella, diciendo: ¡Oh, si también tú conocieses, a lo menos en este tu día,
lo que es para tu paz!
Mas ahora está encubierto de tus ojos.`"
Y "`¡Jerusalén, Jerusalén, que matas a los profetas,
y apedreas a los que te son enviados! ¡Cuántas veces quise juntar a tus hijos,
como la gallina a sus polluelos debajo de sus alas,
y no quisiste!`" ¿Cómo podría probarse nuestra doctrina de una manera más clara?
Porque primero,
Él da a entender que _hubo_ un día en que los habitantes de
Jerusalén pudieron haber conocido lo que era para su paz.
Y segundo, muestra que durante ese día quería juntarlos,
como la gallina junta a sus polluelos.
Esta ilustración claramente muestra que la oferta de salvación
que se les hizo no fue en vano por Su parte,
sino que fue tan real,
y ofrecida con tanta alegría y buena voluntad como la gallina cuando junta a sus polluelos.
En verdad, así como la gallina muestra amor y cuidado por sus polluelos,
así es el cuidado de Cristo para juntar a los hombres y mujeres perdidos,
y redimirlos fuera de su estado corrupto y degenerado.
Luego, en tercer lugar, se ve cómo, debido a que se negaron,
lo que era para su paz fue encubierto de sus ojos.
¿Y por qué fue encubierto?
Porque no quisieron permitirle que los juntara;
no quisieron ver aquellas cosas que eran buenas para
ellos en el tiempo del amor de Dios hacia ellos.
Y, por lo tanto, ese día habiendo expirado, no podían verlas;
y entonces Dios permitió que ellos se endurecieran en incredulidad.

Así que,
los corazones de los hombres son endurecidos _después_ de que las
verdaderas ofertas de misericordia y salvación han sido rechazadas,
y no antes.
Y así es confirmado aquel dicho, "`Porque al que tiene, se le dará; y al que no tiene,
aun lo que tiene se le quitará.`"^
footnote:[Marcos 4:25]
Esto parece un acertijo, sin embargo, es resuelto fácilmente según esta doctrina.
Él no tiene, porque ha perdido el tiempo de usar lo que tenía, y, por lo tanto,
ahora le es como nada.
Porque Cristo usa esta expresión (Mateo 25:26) en
la ocasión de quitar el único talento al siervo negligente,
y dárselo al que era diligente--cuyo talento no era
de ninguna manera insuficiente en sí mismo,
sino de la misma naturaleza que los que se les dieron a los demás. Por lo tanto,
el Señor tenía una buena razón de esperar de este talento una ganancia proporcional,
como también del resto.

Por lo tanto, digo, que es después de rechazar este día de visitación,
que el juicio de endurecimiento se inflige a hombres y mujeres,
tal como Cristo se lo pronunció a los judíos (citando Isaías 6:9,
del cual hacen mención los cuatro evangelistas: Mateo 13:14; Marcos 4:12; Lucas 8:10;
Juan 12:40). Y el apóstol Pablo,
después de que había ofrecido el Evangelio de salvación a los judíos en Roma,
hace mención de lo mismo, diciendo,
"`Bien habló el Espíritu Santo por medio del profeta Isaías a nuestros padres, diciendo:
Ve a este pueblo, y diles: De oído oiréis, y no entenderéis; y viendo veréis,
y no percibiréis; porque el corazón de este pueblo se ha engrosado,
y con los oídos oyeron pesadamente, y sus ojos han cerrado,
para que no vean con los ojos, y oigan con los oídos, y entiendan de corazón,
y se conviertan, y yo los sane.`"^
footnote:[Hechos 28:25-27]
De modo que es evidente nuevamente que Dios deseaba que ellos vieran,
pero habiendo cerrado sus ojos, fueron, por lo tanto, endurecidos justamente.

Cirilo de Alejandría habla bien sobre este asunto,
en su respuesta a la siguiente objeción: "`Puede que algunos digan,
que si Cristo ha venido al mundo para que los que ven sean cegados,
entonces no debemos culparlos a ellos por ser ciegos, sino más bien a Cristo,
quien es la causa de su ceguera.
Pero estos hablan irracionalmente, no temiendo llamar a Dios el autor del mal.
Porque,
así como el sol natural sale por nuestro horizonte para
que pueda comunicar el don de su claridad a todos,
y hacer que su luz resplandezca sobre todos, sin embargo,
si alguna persona cerrara sus párpados, o voluntariamente le diera la espalda al sol,
rechazando el beneficio de su luz, dicha persona no sería iluminada por él,
y permanecería en tinieblas.
Sin duda esto no se debe a ningún defecto del sol, sino que es culpa de la persona.
De la misma manera, Cristo, el verdadero Sol,
vino a iluminar a aquellos que estaban asentados
en tinieblas y en región de sombra de muerte,
para que pudiera comunicarles a todos el don de conocimiento y gracia,
y alumbrar los ojos internos de todos mediante Su propio esplendor espiritual.
Pero muchos rechazan el don de esta Luz celestial que les fue dado,
habiendo cerrado los ojos de sus mentes,
para que no les resplandezca la iluminación excelente de la Luz eterna.
Por lo tanto, no es por un defecto del verdadero Sol que son cegados,
sino solo por su propia iniquidad y dureza; porque, como el hombre sabio dijo,
'`su iniquidad los ha cegado.`'`"^
footnote:[John, lib.
6, cap.
21.]

De todo lo cual argumento:
Si hubo un día en el que los obstinados judíos pudieron
haber conocido lo que era para su paz,
que, debido a que lo rechazaron, fue encubierto de sus ojos;
y si hubo un tiempo en el que Cristo habría juntado a algunos quienes,
debido a que se negaron, no pudieron ser juntados;
entonces aquellos que pudieron haber sido salvos,
finalmente perecen por causa de haber despreciado
el día de la visitación de Dios para ellos.

=== Una Medida de Luz y Gracia Salvadora Dada al Hombre

Lo siguiente que debe probarse,
es la manera por la que Dios busca obrar la salvación
en el hombre durante el día de su visitación,
lo cual hace a través de una medida salvadora,
suficiente y sobrenatural de Luz y Gracia dada a cada hombre.
Esto lo probaré, con la ayuda de Dios,
a partir de varios testimonios claros y evidentes de la Escritura.

Primero, de Juan 1:9: "`Aquél era la Luz verdadera,
que alumbra a todo hombre que viene a este mundo.`"^
footnote:[Juan 1:9 RVG]
Esta escritura nos favorece tan claramente,
que algunos la llaman "`el texto de los Cuáqueros`"--porque
demuestra tan evidentemente nuestra posición,
que prácticamente no hay necesidad de interpretación ni deducción. De hecho,
este versículo es como una conclusión que procede de dos afirmaciones anteriores,
a saber, que "`En Él estaba la vida,
y la vida era la luz de los hombres,`" y "`La Luz en las tinieblas resplandece;
y las tinieblas no la comprendieron.`"

Primero observemos que este apóstol llama a Cristo "`la Luz de
los hombres,`" y nos da esto como una de Sus propiedades principales.
Y el mismo apóstol dice en otro lugar,
que es en la medida que andamos con Él en esa Luz (que Él nos comunica),
que llegamos a tener unidad y comunión con Él.^
footnote:[1 Juan 1:7]
En segundo lugar, dijo que esta "`Luz en las tinieblas resplandece;
y las tinieblas no la comprendieron.`"
Y, en tercer lugar, que esta es la "`la Luz verdadera,
que alumbra a todo hombre que viene a este mundo.`"
Aquí el apóstol, siendo dirigido por el Espíritu de Dios,
ha evitado cuidadosamente esa imaginación de nuestros adversarios,
que intentan limitar esta Luz a un cierto número de individuos.
Porque, al decir "`todo hombre,`" claramente no se excluye ningún hombre.
Y si fueran tan obstinados (como algunas veces lo son) como para decir
que esta frase "`todo hombre`" se refiere solo a cada uno de los elegidos,
entonces las siguientes palabras,
"`todo hombre que viene a este mundo,`" invalidarían su objeción. Por lo tanto,
aquí claramente se afirma que no hay hombre que venga a este mundo,
a quien Cristo no haya alumbrado en alguna medida
y en cuyo corazón oscuro esta Luz no haya resplandecido.
Aunque las tinieblas no la comprenden, aun así, ella resplandece ahí,
y su naturaleza es una que expulsaría las tinieblas,
siempre que los hombres no le cierren sus ojos.
De hecho,
el propósito por el cual es dada esta Luz se expresa en
el versículo 7--"`a fin de que todos creyesen por ella.`"
+++[+++es decir, por la Luz].^
footnote:[Nota de Barclay: __di`' autou__ (por él,
o por medio de él) concuerda muy bien con __photos__ (la Luz),
siendo el antecedente más cercano;
aunque muchos traductores lo han hecho referirse
a Juan (para encajarlo con su propia doctrina),
como si todos los hombres en el mundo tuvieran que creer por medio de Juan.
Pero todos no podrían creer a través de Juan,
porque es imposible que todos los hombres conozcan el testimonio de Juan; en cambio,
todo hombre, siendo iluminado por esta Luz puede creer por medio de ella.
Juan no resplandeció en las tinieblas; pero esta Luz resplandece en las tinieblas,
de modo que, habiendo disipado las tinieblas, puede producir y engendrar fe.
Y es por andar en esta Luz que tenemos comunión y unidad, no por andar en Juan,
lo cual no tiene sentido.
Así que esta cláusula relativa __di`' autou__ debe necesariamente referirse a la Luz (__photos__),
de la cual Juan dio testimonio, para que por medio de la luz,
con la cual Cristo ha iluminado a todo hombre,
todos los hombres tengan la posibilidad de creer.]

Viendo que esta Luz es la Luz de Jesucristo,
y la Luz por la cual los hombres llegan a creer,
considero que no se puede dudar que es una Luz sobrenatural, salvadora y suficiente.^
footnote:[Nota del Editor: Quiere decir "`suficiente`" para la salvación del alma.
Algunos adversarios de los primeros Cuáqueros,
al mismo tiempo que admitían que la Luz de Cristo es dada en medida a cada hombre,
insistían que esta es una medida o don __insuficiente para salvar el alma.__
Estos argumentaban que hay una gracia (o iluminación) "`común`" por la que todos
los hombres poseen un discernimiento moral entre el bien y el mal,
y también una gracia "`salvadora`" que es dada a los cristianos solamente.]
Si no fuera sobrenatural,
no podría llamarse apropiadamente la Luz de Jesús. Y ciertamente la Luz que ilumina
al hombre no puede ser uno de los dones o facultades naturales de su alma,
porque dice que "`resplandece en las tinieblas,`"^
footnote:[2 Corintios 4:6]
y que ellas no la pueden comprender.
Ahora,
estas "`tinieblas`" no son otra cosa más que la condición o estado natural del hombre,
en el cual el hombre puede comprender fácilmente
aquellas cosas que le son comunes como hombre.
Pero que el hombre en su condición natural es llamado tinieblas, véase Efesios 5:8,
"`Porque en otro tiempo erais tinieblas,
mas ahora sois luz en el Señor,`" y varios otros lugares, tales como Hechos 26:18,
Colosenses 1:13 y 1 Tesalonicenses 5:5,
donde la condición del hombre en su estado natural es llamada "`tinieblas.`"
Por lo tanto, digo,
esta luz que resplandece en las tinieblas no puede ser ninguna
propiedad o facultad natural del alma del hombre,
sino que debe ser el don y gracia sobrenatural de Jesucristo.

Y que esta Luz es suficiente y salvadora es evidente,
por el hecho de que fue dada "`para que todos los hombres creyesen por ella.`"
Además, nos fue dicho que al caminar en ella, tenemos comunión con los santos,
y "`la sangre de Jesucristo nos limpia de todo pecado.`"^
footnote:[1 Juan 1:7]
Y aquello que se nos manda a creer,
con el fin de que "`seamos hijos de luz,`" ciertamente debe ser un principio sobrenatural,
suficiente y salvador; porque Cristo ha dicho, "`Entre tanto que tenéis la luz,
creed en la luz, para que seáis hijos de luz.`"^
footnote:[Juan 12:36]

Algunos objetan que aquí los discípulos debían entender
que "`Luz`" se refería a la persona _externa_ de Cristo,
en la cual Él deseaba que creyeran.
Ahora bien, no negamos que ellos tenían que creer en la aparición externa de Cristo,
y reconocerlo como el Mesías que había de venir.
Pero en este lugar no veo como podría ser esa la intención de Sus palabras.
Porque las palabras "`Entre tanto que tenéis la luz,`" y aquellas del versículo anterior,
"`andad entre tanto que tenéis luz,
para que no os sorprendan las tinieblas,`" claramente implican que,
cuando esa Luz en la que debían creer fuese removida,
entonces perderían la capacidad o el tiempo de creer.
Esto no podría entenderse como la aparición externa de Cristo,
puesto que muchos creyeron eficazmente en Él (como
lo hacen todos los cristianos en este día),
mucho después de que Su presencia corporal u hombre
exterior había sido removido de entre ellos.
Así que esta Luz en la que se les mandó a creer debe ser esa Luz interna y espiritual,
que resplandece en sus corazones por un tiempo, a saber,
durante el día de la visitación del hombre.
Mientras esta Luz continua llamando, invitando y exhortando,
se dice que los hombres "`la tienen`" y que pueden "`creer
en ella;`" pero cuando los hombres rehúsan creer en ella,
y la rechazan, entonces cesa de ser una Luz que les muestra el camino,
y les deja un sentido de su infidelidad como un aguijón en sus conciencias,
que trae terror y oscuridad sobre ellos,
y en está condición de tinieblas ellos no saben a dónde ir.
Por lo tanto, para los rebeldes como estos,
está escrito que "`el día de Jehová será de tinieblas, y no de luz.`"^
footnote:[Amos 5:18]

Por lo tanto, es evidente que,
aunque muchos no reciben la Luz (puesto que las tinieblas no pueden comprenderla),
sin embargo, esta Luz salvadora resplandece en todos, para poder salvarlos.
Respecto a esto, Cirilo de Alejandría ha hablado muy bien:

[quote]
____
Con gran diligencia y vigilancia el apóstol Juan se esfuerza
por anticipar e impedir los pensamientos vanos de los hombres.
Él acababa de llamar al Hijo la Luz verdadera,
y afirmó que por medio de Él todo hombre que viene a este mundo era alumbrado; sí,
y que Él estaba en el mundo y que el mundo había
sido creado por Él. Uno entonces podría objetar,
'`Si la Palabra de Dios es la Luz,
y si esta Luz ilumina los corazones de los hombres y los
lleva a la piedad y al entendimiento verdadero de las cosas,
y si Él siempre había estado en el mundo y había sido su Creador o constructor,
entonces ¿Por qué, por tanto tiempo, el mundo no lo conoció?`' Podría parecer que,
debido a que Él era tan desconocido para el mundo,
entonces o el mundo no había sido iluminado por Él, o Cristo no era totalmente Luz.
Pero que ningún hombre acuse a la Palabra de Dios ni a Su Luz eterna,
sino más bien a su propia debilidad: porque el Hijo ilumina,
pero la criatura rechaza la gracia que le es dada y abusa
de la claridad de entendimiento que le es concedida,
por la cual pudo haber conocido a Dios.
Como el pródigo, el hombre ha vuelto su vista a la creación,
rehusando seguir hacia adelante,
y por medio de pereza y negligencia ha enterrado
la iluminación de Dios y menospreciado Su gracia.
Y fue con el fin de evitar esto mismo,
que Pablo les ordenó a los Tesalonicenses a velar y ser sobrios.

Por lo tanto, la falta debe ser atribuida a la iniquidad de aquellos que son iluminados,
y no a la Luz; porque aunque el sol se levanta sobre todos,
sin embargo él que es ciego no recibe ningún beneficio de
él. Nadie diría que esto es por culpa del brillo del sol,
sino por su propia ceguera; y este es el caso con el unigénito Hijo de Dios,
porque Él es la Luz verdadera y despliega Su resplandor sobre todos.
Pero el dios de este mundo, como dice Pablo,
ha cegado el entendimiento de los incrédulos (2 Corintios 4:4),
para que no les resplandezca la Luz del Evangelio.

Decimos, por lo tanto, que las tinieblas vienen sobre los hombres,
no porque estén completamente privados de Luz,
sino porque el hombre está embotado por sus malos hábitos y se ha vuelto peor,
y ha hecho que la medida de gracia, en cierto sentido, languidezca.
Entonces, con estas palabras de Juan,
el mundo es acusado de ser desagradecido e insensible, al no conocer a su Autor,
ni producir el buen fruto de su iluminación. Así que parece
que ahora puede decirse verdaderamente respecto a todos,
lo que antiguamente dijo el profeta respecto a los judíos:
"`Esperaba yo que diese uvas buenas, pero ha dado uvas silvestres.`"
____

Por lo antes expuesto,
se muestra que Cirilo creía que una iluminación salvadora ha sido dada a todos,
y que es de la misma naturaleza que la gracia de la que Pablo le hace mención a Timoteo,
diciendo, "`No descuides la gracia que hay en ti.`"

Ahora bien, que esta Luz o Semilla salvadora, o una medida de ella, es dada a todos,
Cristo nos lo dice claramente en la parábola del sembrador (Mateo 13:18; Marcos 4,
y Lucas 8:11). Él dice que la "`semilla`" que es sembrada en diversos tipos de
tierras es la "`Palabra del Reino,`" que el apóstol llama la "`Palabra de fe,`"^
footnote:[Romanos 10:8]
o "`la Palabra implantada, la cual puede salvar el alma;`"^
footnote:[Santiago 1:21 -- __"`ho logos emphutos`"__]
--cuyas palabras implican que es de una naturaleza salvadora,
y que en buena tierra lleva fruto abundantemente.

Observemos, pues, que esta Semilla del Reino--esta Palabra salvadora,
sobrenatural y suficiente--fue verdaderamente sembrada en la tierra pedregosa,
en la tierra de espinos, y junto al camino, donde no produjo fruto,
sino que quedó estéril en cuanto a estos terrenos.
Esta fue exactamente la misma Semilla que fue sembrada en la buena tierra.
Por lo tanto,
(de acuerdo a como Cristo Mismo interpreta la parábola) el miedo a la persecución,
el engaño de las riquezas, los afanes de este mundo y los deseos por otras cosas,
son los que impiden que esta Semilla crezca en los corazones de muchos.
No es que ella no sea suficiente en su propia naturaleza,
ya que es la misma que crece y prospera en los corazones de los que la reciben.
Así entonces, es manifiesto que aunque todos no son salvos por ella,
sin embargo hay una semilla de salvación plantada
y sembrada por Dios en el corazón de todos,
cuya semilla crecería y redimiría el alma si no fuese ahogada y estorbada.

Con respecto a esta parábola,
Víctor de Antioquía (haciendo referencia al cuarto capítulo de Marcos) dice,
"`Nuestro Señor Cristo ha sembrado generosamente la Semilla divina
de la Palabra y la ha ofrecido a todos sin acepción de personas.
Así como el que sembraba no distinguía entre una tierra y otra,
sino que simplemente arrojaba la semilla sin distinción,
asimismo nuestro Salvador ha ofrecido el alimento de la Palabra divina a todos,
a pesar de que no ignoraba lo que pasaría con muchos de ellos.
En verdad, Él actuaba de tal manera que podía decir con justicia,
'`¿Qué más se podía hacer, que yo no haya hecho?`'`"

A esto corresponde la parábola de los talentos (Mateo 25),
donde él que tenía dos talentos fue aceptado al igual que él que tenía cinco,
porque los talentos fueron usados para que el maestro obtuviera ganancias.
Y él que tenía un talento pudo haber hecho lo mismo,
ya que su talento era de la misma naturaleza que los demás,
y era igualmente capaz de producir un incremento proporcional.
De modo que,
aunque no haya una proporción igual de gracia dada a todos--a unos cinco talentos,
a unos dos talentos, y a otros solo uno--sin embargo,
se les otorga a todos una cantidad que es suficiente,
y lo que se requiere corresponde a lo que se da:
"`Porque a todo aquel a quien se haya dado mucho, mucho se le demandará.`"^
footnote:[Lucas 12:48]
Él que tenía los dos talentos y devolvió cuatro fue aceptado por el maestro
de la misma manera que él que tenía cinco talentos y devolvió diez.
Asimismo, el hombre que recibió un talento también habría sido aceptado al devolver dos;
porque sin duda uno era capaz de producir dos, así como los dos produjeron cuatro,
y los cinco diez.

Además, esta Luz salvadora y espiritual es el Evangelio,
que el apóstol dice expresamente que se predica "`en toda criatura debajo
del cielo;`" ese mismo "`Evangelio del cual Pablo fue hecho ministro.`"^
footnote:[Colosenses 1:23,
// lint-disable invalid-characters
Traducción Literal __"`εν παση τη  κτισει`"__ es decir "`en toda criatura.`"
Ver RVG, y RV1602P]
Porque el Evangelio no es la mera declaración de cosas buenas,
sino más bien "`el poder de Dios para salvación a todo aquel que cree.`"^
footnote:[Romanos 1:16]
A pesar de que la declaración externa del Evangelio a veces se considere como el Evangelio,
sin embargo, esto es en un sentido figurado y por una metonimia.^
footnote:[Una metonimia es una forma de hablar en la que una cosa o concepto es referido
por el nombre de otra cosa que está íntimamente asociada con dicha cosa o concepto.
Por ejemplo "`la corona`" se usa para referirse al poder de un rey;
o "`la espada`" para referirse a la fuerza militar.]
Porque, para hablar correctamente,
el Evangelio es el poder y vida interna que predica buenas
nuevas dentro de los corazones de todos los hombres,
ofreciéndoles la salvación y buscando redimirlos de sus iniquidades.
Por lo tanto, se dice que "`es predicado en toda criatura que está debajo del cielo,`"^
footnote:[Colosenses 1:23 RVG, RV1602P]
aunque hay muchos miles de hombres y mujeres a quienes
nunca se les ha predicado el evangelio externo.

Por lo tanto, el apóstol Pablo (en Romanos 1), donde dice que,
"`el Evangelio es el poder de Dios para salvación,`" añade que "`en él
la justicia de Dios es revelada de fe a fe;`" y también "`es revelada
la ira de Dios contra los que detienen la verdad en injusticia.`"^
footnote:[Romanos 1:17-18 RV1602P]
Y es por esta razón que Pablo, en el siguiente versículo,
dice "`Porque lo que se conoce acerca de Dios es evidente dentro de ellos;
porque Dios se lo manifestó.`"^
footnote:[Romanos 1:19 LBLA, y RV1602P]
Así entonces, lo que de Dios se puede conocer es dado a conocer por el Evangelio,
que fue manifestado dentro de ellos.
Porque estos de quienes el apóstol está hablando aquí,
no se les había predicado el evangelio externo,
de modo que era por medio de la manifestación interna del conocimiento
de Dios en ellos (que verdaderamente es el Evangelio predicado en el hombre)
que "`la justicia de Dios es revelada de fe a fe`"--es decir,
le revela al alma lo que es justo, bueno y recto,
y a medida que el alma lo recibe y cree, la justicia llega a revelarse más y más,
de un grado de fe a otro.
Porque aunque la creación externa declara el poder de Dios,
como lo dice el siguiente versículo,
sin embargo lo que de Él se puede conocer es manifiesto en el interior,
por cuya manifestación interna somos hechos capaces de ver
y discernir el eterno poder y deidad en la creación externa.
Entonces,
al igual que un hombre ciego que no puede ver ni discernir la variedad de formas y colores,
ni considerar la belleza de la creación externa,
si no fuera por esta Luz y Gracia interna,
tampoco podríamos entender las cosas invisibles de
Dios a través de la creación visible y externa.

Por lo tanto, Pablo dice primero que,
"`lo que se conoce acerca de Dios es evidente dentro de ellos`" y es en y por _esto_ que
pueden leer y entender el poder y deidad en esas cosas que son externas y visibles.
Aunque algunos insistan en que la creación externa, por sí misma,
sin ninguna Luz sobrenatural o salvadora en el corazón,
le declara al hombre natural que hay un Dios; sin embargo,
digo ¿de qué serviría tal conocimiento si no me comunicara
también la voluntad y la naturaleza de Dios,
y como podría hacer lo que le es agradable?
Porque,
aunque la creación externa pueda engendrar una persuasión de que existe
algún poder o virtud eterna mediante la cual el mundo ha tenido su comienzo,
aun así, no me informa lo que es justo, santo y recto,
o cómo puedo ser librado de mis tentaciones y afectos corruptos y alcanzar la justicia.
Verdaderamente,
esto debe ser por alguna manifestación interna en mi corazón. Pero estos Gentiles,
de quienes el apóstol habla aquí,
sabían distinguir entre el bien y el mal por esa ley y manifestación
interna del conocimiento de Dios en ellos,
como se demuestra en el siguiente capítulo de Romanos.

El profeta Miqueas, hablando del hombre en general, declara lo siguiente: "`Oh hombre,
Él te ha declarado lo que es bueno, y ¿qué pide Jehová de ti?
Solamente hacer justicia, y amar misericordia, y caminar humildemente con tu Dios.`"^
footnote:[Miqueas 6:8 RVG]
Noten que no les habla del requisito de Dios sin primero
asegurarles que Dios les ha mostrado lo que es bueno.
Ahora,
es debido a que esto les es mostrado a todos los hombres y es manifestado en ellos,
que el apóstol puede decir que "`la ira de Dios se revela
contra los que detienen la Verdad en injusticia;`" es decir,
detienen la medida de la Verdad, de la Luz, de la Semilla, de la Gracia en ellos,
porque "`esconden su talento en la tierra,`"^
footnote:[Mateo 25:25]
o en la parte terrenal e injusta de sus corazones, y no permiten que produzca fruto.
En lugar de esto, su medida o Semilla es ahogada con los afanes carnales de esta vida,
con el miedo al vituperio, y con el engaño de las riquezas,
como se manifiesta en las parábolas mencionadas anteriormente.

Pero el apóstol Pablo expone e ilustra este asunto aún más en Romanos 10,
donde declara que la Palabra que predicaba "`no está lejos,
sino cerca en el corazón y en la boca;`" (ahora bien,
la Palabra y el Evangelio que predicaba, y del cual era ministro, son uno y el mismo).
Luego plantea la objeción común de nuestros adversarios en los versículos 14 y 15:
"`¿Y cómo creerán en aquel de quien no han oído? ¿Y cómo oirán sin haber quien les predique?`"
Y a esto responde en el versículo 18, diciendo, "`Pero digo: ¿No han oído? Antes bien,
por toda la tierra ha salido la voz de ellos,
y hasta los fines de la tierra sus palabras;`"^
footnote:[Romanos 10:18, citando Salmos 19:4]
dando a entender que este Predicador divino ha hecho oír
su voz en los oídos y corazones de todos los hombres.
Porque, con respecto a las palabras de los apóstoles, esta afirmación no era cierta,
ni en ese momento, ni por muchos cientos de años después. De hecho,
hasta donde nosotros sabemos,
todavía puede haber naciones y reinos que nunca hayan
oído de Cristo o de sus apóstoles externamente.

Esta Palabra interna y poderosa de Dios se describe
aún más plenamente en la epístola a los hebreos:
"`Porque la palabra de Dios es viva y eficaz,
y más cortante que toda espada de dos filos;
y penetra hasta partir el alma y el espíritu, las coyunturas y los tuétanos,
y discierne los pensamientos y las intenciones del corazón.`"^
footnote:[Hebreos 4:12]
Aquí las virtudes de esta Palabra espiritual son enumeradas--es viva y eficaz,
y es una que examina y prueba los corazones de todos.
El corazón de ningún hombre queda exento de esto porque el apóstol dice,
que "`no hay criatura alguna que no es manifiesta a Su vista:
antes todas las cosas están desnudas y abiertas a
los ojos de Aquel a quien tenemos que dar cuenta.`"^
footnote:[Hebreos 4:13 RV1602P]
Aunque esto, en el sentido más amplio y general se refiere a Dios, sin embargo,
en un sentido más particular y directo, habla de Su Palabra o Luz, la cual, al ver todo,
claramente está en los corazones de todos.

Por lo tanto,
esta Palabra es ese testigo y mensajero fiel de Dios que da testimonio de Dios,
y de Su justicia en los corazones de todos los hombres.
Porque el Señor "`no se dejó a sí mismo sin testimonio`"^
footnote:[Hechos 14:17]
y está escrito que Él fue dado "`por testigo a los pueblos.`"^
footnote:[Isaías 55:4]
Y puesto que esta Palabra da testimonio de Dios,
no fue puesta en los hombres solo para condenarlos;
porque Aquel que fue dado por testigo, dice el profeta,
también es "`dado por guía y jefe.`"^
footnote:[Isaías 55:4 LBLA]
La Luz es dada para que todos crean por medio de ella,^
footnote:[Juan 1:7]
porque "`la fe es por el oír, y el oír, por la Palabra de Dios,`"^
footnote:[Romanos 10:17]
la cual es puesta en el corazón del hombre, tanto para ser un testigo de Dios,
como también un medio para llevar al hombre a Dios,
a través de la fe y el arrepentimiento.
Por ende, se dice que está Palabra es eficaz, capaz de dividir el alma y el espíritu,
y que es como una espada de doble filo que puede
cortar la iniquidad y separar lo precioso de lo vil.
Y debido a que el corazón del hombre es naturalmente frío y duro, como el hierro,
Dios ha puesto esta Palabra en él, que se describe como "`un fuego,
y como un martillo.`"^
footnote:[Jeremías 23:29]
Y tal como el hierro (siendo frío naturalmente) se calienta por el calor del fuego,
y por la fuerza del martillo se ablanda y se moldea de acuerdo a la mente del herrero,
asimismo,
el corazón frío y duro del hombre se calienta y se ablanda por la virtud y poder
de esta Palabra de Dios que está cerca y en el corazón (cuando no es resistida),
con el fin de recibir la impresión e imagen celestial.

La mayor parte de los padres de la iglesia ha hablado extensamente acerca de esta Palabra,
Semilla, Luz y Voz salvadora, que llama a la salvación, y es capaz de salvar.

Clemente de Alejandría dice, "`La Palabra divina ha clamado, llamando a todos,
conociendo bien quienes no quieren obedecer.
Y, sin embargo (debido a que está en nuestro poder obedecer o no obedecer),
para que ninguno alegue el pretexto de la ignorancia, ella ha hecho una invitación justa,
y, por lo tanto,
solo requiere lo que corresponde a la capacidad y fuerza de cada persona^
footnote:[Lib.
2, Stromat.]
El mismo autor, en su [.book-title]#Advertencia a los Gentiles#,
dice "`Ese embajador celestial del Señor--la gracia
de Dios que trae salvación--se ha manifestado a todos.
Esta gracia es la nueva canción venida y manifestación de
la Palabra que ahora se muestra a Sí misma en nosotros,
la cual era en el principio y era primero que todo.`"
Y de nuevo, "`Escuchen, por lo tanto, ustedes que están lejos; escuchen,
ustedes que están cerca; la Palabra no se esconde de ninguno,
la Luz es común para todos e ilumina a todos.
No hay oscuridad en la Palabra, así que apresurémonos a la salvación,
al nuevo nacimiento, para que nosotros, siendo muchos,
podamos ser reunidos en el único amor verdadero.`"

Justin Mártir, en su primera apología, dice, "`que la Palabra que era y es,
está en todos;
esa misma Palabra que anunciaba de antemano cosas por venir a través de los profetas.`"

=== La Salvación mediante la Operación Interna de la Gracia y la Luz en el Corazón

La tercera proposición que necesita probarse tiene dos partes: _Primero,_
que Dios obra la salvación de los hombres únicamente mediante esta Luz, Semilla o Gracia,
que hace que ellos participen del beneficio de la
muerte de Cristo y de la salvación comprada por Él;
y _segundo,_ que por la obra y operación de esta misma Gracia y Luz,
muchos han sido salvos (y algunos todavía pueden ser salvos) a
quienes el Evangelio nunca les ha sido predicado externamente,
y quienes (debido a circunstancias inevitables) son completamente
ignorantes de la historia externa de Cristo.

Habiendo ya demostrado que Cristo murió por todos,
que hay un día de visitación dado a todos los hombres,
durante el cual les es posible ser salvos,
y que Dios realmente ha dado una medida de Gracia y Luz salvadora a todos,
les ha predicado el Evangelio en su interior,
y ha puesto la Palabra de fe en sus corazones,
el tema de esta proposición ya podría considerarse probado.
Sin embargo,
para dar una mayor satisfacción a todos los que desean
conocer la Verdad y sostenerla conforme está en Jesús,
voy a intentar demostrar esto desde dos o tres testimonios claros de la Escritura,
y remover las objeciones más comunes que usualmente son traídas en su contra.

[.numbered-group]
====

[.numbered]
_I+++.+++_ En cuanto a lo primero, debido a que la mayoría ya lo reconoce,
trataré de demostrarlo en pocas palabras.
Primero a partir de las palabras de Cristo a Nicodemo, "`De cierto, de cierto te digo,
que el que no naciere de nuevo, no puede ver el reino de Dios.`"^
footnote:[Juan 3:3]
Ahora bien, este nacimiento no viene por la predicación externa del Evangelio,
o por una fe histórica en Cristo; porque muchos tienen esto, y creen firmemente en ello,
y, sin embargo, no están ni un poquito regenerados.
De hecho, el apóstol Pablo,
en su afirmación acerca de la necesidad y excelencia
de esta "`nueva creación,`" deja a un lado,
en cierto sentido, el conocimiento externo de Cristo,
o el conocimiento de Él según la carne.
Él dice, "`De manera que nosotros de aquí en adelante a nadie conocemos según la carne;
y aun si a Cristo conocimos según la carne,
ya no lo conocemos así. De modo que si alguno está en Cristo, nueva criatura es;
las cosas viejas pasaron; he aquí todas son hechas nuevas.`"^
footnote:[2 Corintios 5:16-17]
Aquí se manifiesta claramente que Pablo considera el conocimiento
de Cristo según la carne como los meros rudimentos,
por así decirlo, que los niños espirituales aprenden, y que después,
cuando han progresado más, les son de menos utilidad,
habiendo llegado a poseer la sustancia misma a la cual apuntaban los primeros preceptos.
Ahora bien, como toda comparación tiene sus limitaciones,
no voy a afirmar que esta sea válida en todos los aspectos;
pero creo que es cierta en este sentido:
que así como aquellos que no avanzan más allá de
los rudimentos nunca deben considerarse aprendidos,
así también los que no van más allá del conocimiento
externo de Cristo no heredarán el reino de los cielos.
Sin embargo, aquellos que han llegado a conocer este nuevo nacimiento,
a estar verdaderamente en Cristo,
a ser una nueva criatura en la que "`las cosas viejas pasaron,
y todas son hechas nuevas,`" pueden con confianza decir con el apóstol:
"`aunque hemos conocido a Cristo según la carne, ya no lo conocemos así.`"

Ahora bien,
esta nueva criatura procede de la obra de la Luz y Gracia de Cristo en el corazón. Es
engendrada por esa Palabra que es cortante y penetrante (de la cual hemos hablado),
la Palabra implantada que puede salvar el alma.
Cristo compró para nosotros esta Semilla santa,
para que por ella se produzca un nacimiento;
y esto es lo que el apóstol Pablo llama "`la manifestación
del Espíritu dada a cada uno para provecho.`"^
footnote:[1 Corintios 12:7]

El apóstol Pedro también le atribuye este nacimiento
a la misma Semilla y Palabra de Dios,
diciendo, "`Pues habéis nacido de nuevo, no de una simiente corruptible,
sino de una que es incorruptible, es decir,
mediante la palabra de Dios que vive y permanece.`"^
footnote:[1 Pedro 1:23 LBLA]
Aunque esta Semilla sea pequeña en su apariencia,
tanto que Cristo la compara con un "`grano de mostaza,
que es la más pequeña de todas las semillas,`"^
footnote:[Mateo 13:31-32]
y aunque esté escondida en la parte terrenal del corazón del hombre, aun así,
la vida y salvación para con los hijos de los hombres están envueltas ahí,
y llegan a revelarse a medida que le dan paso.
Y en esta Semilla que está en los corazones de todos
los hombres se encuentra el Reino de Dios,
como en una capacidad de ser conocido y exhibido según ella obtiene profundidad,
es nutrida y no es ahogada.
Es por eso que Cristo dijo que el Reino de Dios estaba incluso en los Fariseos^
footnote:[Lucas 17:20-21]
quienes se opusieron a Él, y lo resistieron,
y fueron considerados justamente como serpientes y como una generación de víboras.
Ahora bien,
el Reino de Dios solo pudo haber estado en estos hombres en forma de una semilla,
de la misma manera que el incremento a treinta y a ciento por uno
estaban envueltos en la pequeña semilla que estaba junto al camino,
y no brotó por falta de alimento.
Y así como el cuerpo completo de un gran árbol está
potencialmente envuelto en la semilla del árbol,
y luego es formado en su debido tiempo;
y así como la capacidad de un hombre o de una mujer no está solamente en un niño,
sino inclusive en el mismo embrión, así el Reino de Jesucristo, sí,
Jesucristo mismo--"`Cristo en vosotros,
la esperanza de Gloria,`" quien se vuelve la sabiduría, la justicia,
la santificación y la redención--es sembrado en el corazón de cada hombre,
dentro de esa pequeña Semilla incorruptible,
listo para ser formado a medida que sea abrazado y "`recibido en amor.`"^
footnote:[2 Tesalonicenses 2:10]
Porque ningún hombre puede ser peor que esos Fariseos rebeldes e incrédulos;
y sin embargo este Reino estaba dentro de ellos como una semilla,
y ellos fueron dirigidos a buscarlo allí. Por lo tanto,
no es ni "`helo aquí`" ni "`helo allí,`" en esta o la otra observancia,
que se conoce el reino,
sino solo en la medida que esta Semilla de Dios en el corazón sea atendida y amada.
Y ciertamente, es porque esta Luz,
Semilla o Gracia que aparece en el corazón del hombre es tan poco estimada y tan despreciada,
que muy pocos experimentan a Cristo engendrado y formado en ellos.

Los calvinistas consideran la gracia como un poder irresistible,
y por lo tanto descuidan y menosprecian esta Semilla eterna del Reino en sus corazones,
considerándola como una cosa baja,
insuficiente e inútil en relación a su salvación. Por otro lado, los católicos,
arminianos, y socinianos buscan exaltar su poder y voluntad naturales,
y de común acuerdo niegan que esta pequeña Semilla, esta pequeña aparición de la Luz,
pueda ser esa gracia sobrenatural y salvadora de
Dios dada a cada hombre para salvación. Por consiguiente,
el dicho del Señor Jesucristo es verificado en ellos:
"`Y esta es la condenación del mundo: que la luz vino al mundo,
y los hombres amaron más las tinieblas que la luz,`" y se añade la razón:
"`porque sus obras son malas.`"
^
footnote:[Juan 3:19] Todos confiesan que sienten esta condenación por el mal,
pero no quieren reconocer que esto viene de la virtud de la gracia.
Algunos la llaman la razón; otros la conciencia natural;
otros la llaman una reliquia de la imagen de Dios que quedó en Adán. De este modo,
así como Cristo se encontró con la oposición de todo
tipo de profesantes en Su aparición externa,
también ahora se encuentra con lo mismo en Su aparición interna.
Fue la humildad y sencillez de Su hombre exterior lo que hizo que muchos lo despreciaran,
diciendo, "`¿No es este el hijo del carpintero?
¿No están todos sus hermanos y hermanas con nosotros?
¿No es este un Galileo?
¿Alguna vez se ha levantado profeta de Galilea?`"
y otros razonamientos similares.
Porque ellos esperaban un libertador externo que, como un príncipe,
los libertara con mucha facilidad de sus enemigos externos,
y no tal Mesías que fuera crucificado vergonzosamente y, en cierto sentido,
los llevara a tantos dolores, tribulaciones y aflicciones.

De la misma manera ahora, la humildad y sencillez de la apariencia interna de Cristo,
hace que los Jesuitas astutos,
los Socinianos racionales y los arminianos aprendidos lo desprecien,
deseando en su lugar algo sobre lo que puedan ejercitar su sutileza,
razón y conocimiento, y además usar la libertad de sus propias voluntades.
Y los calvinistas (que se sienten muy seguros) quieren tener un Cristo que los
salve sin tener que pasar por ninguna aflicción. Quieren que Él destruya por
ellos a todos sus enemigos externos y no haga nada o muy poco internamente,
mientras viven seguros y tranquilos en sus pecados.
Pero cuando todo esto se examina bien,
la causa es evidente:
es "`porque sus obras son malas`" que ellos de común acuerdo
rechazan esta Luz--porque ella reprueba y reprende en secreto,
incluso al más sabio y aprendido de ellos.
De hecho, toda su lógica no puede silenciarla,
ni el más seguro entre ellos puede impedir que Su voz clame y los reprenda internamente,
a pesar de toda la confianza que tengan en el conocimiento externo de Cristo.
Porque como hemos demostrado, en algún
día o tiempo la Luz contiende y lucha con todos; y es la naturaleza no crucificada,
la primera naturaleza (el viejo Adán) que todavía vive en el más sabio y aprendido,
en el más celoso por el conocimiento externo de Cristo, que la niega,
la desprecia y la tapa para su propia condenación. Estos, por lo tanto,
caen bajo esta descripción: "`Porque todo aquel que hace lo malo,
aborrece la luz y no viene a la luz, para que sus obras no sean reprendidas.`"^
footnote:[Juan 3:20]
Por lo tanto, ahora, a partir de una experiencia verdadera y certera,
se puede decir lo mismo que fue dicho en la antigüedad:
"`La piedra que desecharon los edificadores, ha venido a ser cabeza del ángulo.`"
^
footnote:[Salmos 118:22; Mateo 21:42; Marcos 12:10; Lucas 20:17; Hechos 4:11]

Gloria a Dios por siempre,
quien se ha levantado nuevamente para litigar con las naciones, y, por lo tanto,
nos ha enviado a predicar el Evangelio eterno a todos--Cristo cerca de todos,
la Luz en todos, la Semilla sembrada en los corazones de todos,
para que los hombres vengan y se entreguen a ella.
Y nos regocijamos por haber sido llevados a dejar nuestra sabiduría y conocimiento
(aquellos de nosotros que hemos tenido algo de eso) y nuestro razonamiento carnal,
para aprender de Jesús y sentarnos a Sus pies en nuestros corazones y escucharlo,
quien hace manifiestas todas las cosas allí, y las reprueba con Su Luz.^
footnote:[Efesios 5:13 RV1602P]
Porque muchos son sabios y aprendidos en nociones,
en la letra de la Escritura (como lo eran los fariseos), y pueden hablar mucho de Cristo,
y contender fuertemente contra los infieles, los turcos y los judíos,
y quizás contra algunas herejías,
quienes al mismo tiempo están crucificando a Cristo
en la pequeña aparición de Su Semilla en sus corazones.
¡Oh sería mucho mejor ser despojado y desnudado de todo,
y tenerlo todo como basura y escoria, y hacerse ignorante por el amor de Cristo!
Entonces sentirían a Cristo enseñándoles en sus corazones;
lo experimentarían resucitado allí, sentirían la virtud de Su cruz allí,
y dirían con el apóstol, "`Pero lejos esté de mí gloriarme,
sino en la cruz de nuestro Señor Jesucristo, por quien el mundo me es crucificado a mí,
y yo al mundo.`"^
footnote:[Gálatas 6:14]
Esto es mejor que escribir miles de comentarios y predicar una multitud de sermones.

Y en verdad,
es debido a la operación de esta cruz en nuestros corazones que
hemos negado nuestra propia sabiduría y voluntad en muchas cosas,
y dejado las adoraciones, modas y costumbres vanas de este mundo.
Durante estos últimos siglos el mundo ha estado lleno de un conocimiento de Cristo seco,
infructífero y estéril, alimentándose de la cáscara y menospreciando el grano,
yendo en pos de la sombra, pero siendo extraños a la sustancia.
Al diablo no le importa cuánto abunde este conocimiento sin vida,
con tal de que siga poseyendo el corazón y gobernando en la voluntad,
crucificando la aparición de Cristo internamente,
y así impedir que la Semilla del Reino eche raíces.
De hecho, él los ha hecho mirar hacia afuera, diciendo,
"`helo aquí`" y "`helo allí,`" y pelear en un celo falso uno contra otro,
contendiendo por esta o aquella práctica religiosa,
buscando a Cristo en esta o la otra cosa externa, tales como el pan y el vino.
Algunos dicen que es este el camino; otros dicen que es otro;
algunos dicen que Él está en la Escrituras y en los libros,
otros dicen que en sociedades, en peregrinaciones y en obras.
Y otros, confiando en una fe externa y estéril,
piensan que todo está bien con solo creer firmemente que El murió por sus pecados--pasados,
presentes y futuros--mientras que Cristo yace crucificado y enterrado dentro de ellos,
y Su aparición en sus corazones es resistida y opuesta diariamente.

Y es a partir de la consciencia de esta ceguera e
ignorancia que ha venido sobre el cristianismo,
que el Señor nos ha inspirado y movido tan constante
y frecuentemente a llamarlos a todos,
invitarlos a todos y pedirles a todos que se vuelvan a la Luz en ellos,
que crean en la Luz de Cristo en ellos y le presten atención. Y en el nombre,
poder y autoridad del Señor--no en argumentos escolares ni distinciones
elevadas--les exhortamos y dirigimos a dejar a un lado su propia sabiduría,
a descender de ese conocimiento orgulloso, inflado y mental,
a cerrar sus bocas (sin importar cuán elocuentes le parezcan al oído del mundo),
a quedarse en silencio y sentarse como en el polvo,
y a atender la Luz de Cristo en sus propias conciencias.
Si ellos le prestaran atención a Cristo de esta manera,
lo hallarían como una espada aguda de dos filos en sus corazones,
y como un fuego y un martillo que golpearía y quemaría
todas esas cosas carnales y naturales que han amontonado,
y haría que hasta los más fuertes de ellos tiemblen y se vuelvan "`Cuáqueros`"^
footnote:[La palabra __Cuáqueros__ es una traducción de la palabra inglesa __Quakers__,
que significa, "`los que tiemblan`" ante Dios.]
en verdad.
Por desgracia, los que no están dispuestos a sentir esto ahora,
ni a honrar al Hijo mientras que dure su día, sino que endurecen sus corazones,
ciertamente serán forzados a sentir la Verdad cuando ya sea demasiado tarde.
Por lo tanto, como dice el apóstol, "`Examinaos a vosotros mismos si estáis en la fe;
probaos a vosotros mismos.
¿O no os conocéis a vosotros mismos, que Jesucristo está en vosotros,
a menos que estéis reprobados?`"^
footnote:[2 Corintios 13:5]

====

=== La Obra de la Gracia en Aquellos Que No Han Oído

[.numbered-group]
====

[.numbered]
_II._ En segundo lugar, lo que ahora falta por probar es lo siguiente:
que por la operación de esta Luz y Semilla,
algunos a quienes no se les ha predicado el Evangelio externamente
y que no conocen la historia de Cristo externamente han sido salvos,
y que otros todavía podrían serlo de la misma manera.
Para hacer esto más fácil,
ya hemos mostrado cómo Cristo murió por todos los hombres
y les ha dado a todos una medida de Luz y Gracia salvadora,
de modo que el Evangelio les es predicado dentro de ellos
(aunque no necesariamente de una manera externa),
poniendo a todos los hombres en una posibilidad de alcanzar la salvación.

Además de esos argumentos que ya han sido usados para demostrar
que todos los hombres tienen una medida de gracia salvadora,
voy a agregar este otro: a saber, ese excelente dicho del apóstol Pablo a Tito,
"`Porque la gracia de Dios que trae salvación se ha manifestado a todos los hombres,
enseñándonos que, renunciando a la impiedad y a las concupiscencias mundanas,
vivamos en este presente mundo, sobria, justa y piadosamente`"^
footnote:[Tito 2:11-12 RVG]
Nada podría ser más claro que esta declaración,
ya que comprende ambas partes de la controversia.
Primero, afirma claramente que esto no es ningún principio o luz natural, sino más bien,
"`la gracia de Dios que trae salvación.`"^
footnote:[Tito 2:11 RV RVG]
Segundo, no dice que se ha manifestado solo a unos pocos, sino a todos los hombres.
Además, el fruto de esta gracia muestra lo poderosa que es,
puesto que comprende todo el deber del hombre.
Primero nos enseña a abandonar el mal, a negar la impiedad y los deseos mundanos;
y luego enseña nuestro deber en todas las cosas: Primero, que vivamos sobriamente,
lo cual comprende templanza, castidad,
mansedumbre y las cosas relacionadas con uno mismo.
Segundo, que vivamos justamente, lo cual comprende la equidad,
la justicia y la honestidad, y aquellas cosas relacionadas con nuestro prójimo.
Y, por último, que vivamos piadosamente, lo cual comprende la piedad,
la fidelidad y la devoción, que son los deberes vinculados a Dios.
Por lo tanto, no hay nada que se requiera del hombre, o que sea necesario para el hombre,
que esta gracia no enseñe.

Aunque esto podría ser suficiente, sin embargo, para ponerlo más allá de toda duda,
voy a dar como ejemplo otro dicho del mismo apóstol: "`Así que,
como por el pecado de uno vino la condenación a todos los hombres, así también,
por la justicia de uno, vino la gracia a todos los hombres para justificación de vida.`"^
footnote:[Romanos 5:18 RVG]
De aquí se puede ver claramente:
que así como todos los hombres han sufrido una pérdida por causa de Adán,
que lleva a la condenación,
así también todos los hombres han recibido de Cristo un don que lleva
a la justificación. Y si este don de Cristo es recibido y obedecido,
entonces todos los hombres,
incluso aquellos que carecen del conocimiento externo de Cristo, pueden ser salvos;^
footnote:[Nota del Editor:
A esto se le puede añadir la siguiente escritura como una prueba más:
"`Le dijo Judas (no el Iscariote): Señor, ¿cómo es que te manifestarás a nosotros,
y no al mundo?
Respondió Jesús y le dijo: El que me ama, mi palabra guardará +++[+++es decir,
la Palabra implantada, gracia, o luz]; y mi Padre le amará, y vendremos a él,
y haremos morada con él.`" (Juan 14:22-23)]
porque Él fue dado como una "`Luz para revelación a los gentiles,
para que sea Su salvación hasta lo postrero de la tierra.`"^
footnote:[Isaías 49:6, Véase también Isaías 42:6, 60:3; Lucas 2:32; Hechos 13:47]

====

[.discourse-part]
Objeción: La objeción más común contra esta doctrina es sacada de las palabras de Pedro,
"`no hay otro nombre bajo el cielo, dado a los hombres, en que podamos ser salvos.`"^
footnote:[Hechos 4:12]
Por ende, los paganos que no conocen este nombre no pueden ser salvos.

[.discourse-part]
Respuesta: Aunque ellos no conocen Su nombre externamente, aun así,
pueden conocer el nombre de Jesús (que significa Salvador) internamente,
al sentir su virtud y poder librándolos del pecado y de la iniquidad en sus corazones.
Confieso que no hay otro nombre por el cual se puede ser salvo;
pero la salvación no depende de un conocimiento literal y externo,
sino de un conocimiento por experiencia.
Aquellos que tienen el conocimiento literal no son salvos
por él sin el conocimiento real y vivo de Jesús. Sin embargo,
los que tienen el conocimiento real e interno pueden ser salvos sin el nombre externo,
como lo demostrarán más ampliamente los argumentos a continuación.
Porque si el conocimiento externo de Cristo fuera necesario antes
de que los hombres pudieran recibir algún beneficio de Él,
entonces (por la regla de contrarios) los hombres no podrían sufrir ningún daño salvo
por el conocimiento externo de la caída de Adán. Pero la experiencia muestra lo contrario;
porque,
¿cuántos millones que no tienen ni idea de que alguna vez existió tal hombre en el mundo,
o que haya comido del fruto prohibido, han sido afectados por la caída de Adán? Entonces,
¿por qué algunos no podrían ser salvos mediante el don y gracia de Cristo en ellos,
haciéndolos justos y santos,
aunque no sepan con claridad como ese don les fue
comprado por la muerte y sufrimientos de Jesús,
quien fue crucificado en Jerusalén--especialmente en los casos en los
que Dios Mismo les ha hecho imposible el conocimiento externo?
Muchos son asesinados por un veneno puesto en su comida,
aunque no sepan ni cuál era el veneno, ni quién lo puso.
De la misma manera, muchos son curados de sus enfermedades con buenos remedios,
aunque no sepan cómo se prepara la medicina, ni cuáles son sus ingredientes,
ni muchas veces quién la fabricó. Lo mismo se puede decir en cosas espirituales,
como lo mostraremos más adelante.

Ahora bien,
hasta nuestros adversarios confiesan de buena gana que muchos bebes y personas
con discapacidad mental son salvos sin el conocimiento externo de Cristo.
Aquí ellos quiebran su regla general,
y no pueden alegar que es porque estos están libres de pecado,
puesto que también afirman que todos los bebes merecen condenación
y son realmente culpables ante los ojos de Dios debido al pecado
de Adán. Y con respecto a las personas con discapacidad mental,
la experiencia nos muestra que, al igual que otros hombres,
estas personas son propensas a muchas iniquidades comunes.

[.discourse-part]
Objeción: Si alguien dijera que estos niños son hijos de padres creyentes:

[.discourse-part]
Respuesta:
¿Y entonces qué? Ninguno de ellos se atrevería a decir que
los padres les transmiten gracia a sus hijos.
¿Y no afirman todos nuestros adversarios que los hijos de
padres creyentes son culpables del pecado original,
y merecen la muerte, así como los demás?

[.discourse-part]
Objeción:
Y si ellos además alegaran que estos niños están dentro del seno de la iglesia visible,
y son partícipes de los sacramentos:

[.discourse-part]
Respuesta: Nada de esto implica que sean salvos;
porque (como todos los profesantes confiesan) estos
sacramentos no otorgan gracia sin la fe del recipiente.
Y ¿acaso no reconocerán también que hay muchos otros en el "`seno de la
iglesia visible,`" que claramente no son miembros de ella?

Pero si nuestros opositores están dispuestos a extender esta caridad
hacia los bebes y las personas con discapacidad mental,
de modo que estos sean considerados capaces de ser salvos debido a que
están bajo una simple imposibilidad de conocer los medios de salvación,
¿qué razón podría alegarse para explicar por qué no debería
concederse la misma caridad a los que _son_ capaces de comprender,
mas nunca han oído el evangelio externo e histórico?
¿No tiene un hombre en China o en India (que no sabe algo que nunca
escuchó) una excusa igualmente válida como la persona discapacitada
que no puede oír o el bebé que no puede entender?

Pero la verdad de nuestra doctrina se manifiesta
evidentemente por el dicho de Pedro en Hechos:
"`Ciertamente ahora entiendo que Dios no hace acepción de personas,
sino que en toda nación el que le teme y hace lo justo, le es acepto.`"^
footnote:[Hechos 10:34-35 LBLA]
Pedro antes era propenso a ese error en el que estaban el resto de los judíos,
que consideraban que todos eran inmundos excepto ellos,
y que ningún hombre podía ser salvo sin antes convertirse a su religión y circuncidarse.
Pero Dios le mostró a Pedro lo contrario en una visión,
y le enseñó a no llamar común o inmundo lo que Él había limpiado.
Y, por lo tanto, Pedro, al ver que Dios había escuchado las oraciones de Cornelio,
quien no conocía la ley externa, ni a Jesucristo, comprendió que Dios lo había aceptado.
Y puesto que está escrito que Cornelio temía a Dios
antes de tener este conocimiento externo,
Pedro concluye que Dios acepta a cualquiera, de cualquier nación,
sin acepción de personas, que le tema y haga lo justo por medio de Él. Ahora bien,
ya hemos demostrado que a todo hombre se le ha dado una medida
de gracia por la cual puede vivir piadosa y justamente.
Y, por ende, vemos que por esta gracia Cornelio vivía así, y fue aceptado,
y que sus oraciones subieron para memoria delante de Dios,
incluso antes de que tuviera este conocimiento externo.

Además, ¿no era Job un "`hombre perfecto y recto, temeroso de Dios y apartado del mal`"?^
footnote:[Job 1:1]¿Quién le enseñó a Job estas cosas?
¿Cómo supo de la caída de Adán?^
footnote:[Job 31:33 RVG, RV1602 P, LBLA]
¿Y de cuál Escritura obtuvo ese excelente conocimiento y fe por los que
sabía que su Redentor vivía? La mayoría cree que él vivió antes de Moisés,
entonces ¿no debió haber sido la gracia interna en el corazón lo
que le enseñaba a Job a apartarse del mal y a temer a Dios?
Observen cómo reprendió la maldad de los hombres (capítulo 24).
Y después de narrar la iniquidad de ellos ¿no los condena por "`rebelarse
contra la Luz,`" y por "`no conocer sus caminos, ni estar en sus veredas`"?^
footnote:[Job 24:13]
Por lo tanto, es evidente que Job creía que los hombres tenían una Luz,
y que ellos no la conocían, ni estaban en sus veredas porque se rebelaban contra ella.
Y también a los amigos de Job (aunque erraron en algunas cosas) ¿quién les enseñó todos
los excelentes dichos y conocimiento que tenían? ¿No se los dio Dios con el fin de salvarlos?
¿Quién le enseñó a Eliú que "`hay un espíritu en el hombre,
y que el soplo del Omnipotente le hace que entienda,`"^
footnote:[Job 32:8]
O que "`El espíritu de Dios me hizo, y que el soplo del Omnipotente me dio vida.`"?^
footnote:[Job 33:4]
¿Y no aceptó el Señor un sacrificio por ellos al final?^
footnote:[Job 42:8]
¿Quién se atreve a decir que ellos están condenados?

Pero el apóstol pone esta controversia fuera de duda,
ya que (si podemos creer en su clara afirmación) nos dice que algunos
gentiles en verdad "`hicieron lo que es de la ley.`"^
footnote:[Romanos 2:14]
De todo lo cual argumento como sigue:

[.syllogism]
* En toda nación, el que teme a Dios y hace lo justo, es aceptado.
* Pero algunos de los paganos temieron a Dios, e hicieron lo justo por medio de Él.
* Por lo tanto, ellos fueron aceptados.

¿Podría haber algo más claro?
Y esto se muestra aún más claramente en otro versículo
tomado del mismo capítulo (v. 13) que dice así:
"`los hacedores de la Ley serán justificados.`"
De lo cual, a partir de pura Escritura, argumento de esta manera:

[.syllogism]
* Los hacedores de la Ley serán justificados
* Pero algunos de los Gentiles hicieron lo que es de la Ley, mostrando que la obra de la Ley estaba escrita en sus corazones.^
footnote:[Romanos 2:15]
* Por lo tanto, estos fueron justificados

Pablo, a través de todo ese capítulo,
se esfuerza como si estuviera contendiendo en este momento contra nuestros adversarios,
con el fin de confirmar esta doctrina.
Él dice, "`tribulación y angustia sobre todo ser humano que hace lo malo,
el judío primeramente y también el griego,
pero gloria y honra y paz a todo el que hace lo bueno,
al judío primeramente y también al griego;
porque no hay acepción de personas para con Dios.`"^
footnote:[Romanos 2:9-11]
Aquí el apóstol confirma claramente las palabras de Pedro a Cornelio (antes mencionadas),
mostrando que tanto los que tienen una ley externa como los que no la tienen,
cuando hacen lo bueno,^
footnote:[Nota del Editor:
Con "`hacer lo bueno`" Barclay no se refiere a las
llamadas buenas obras del hombre caído,
sino al bien que resulta de recibir y entregarse
a las manifestaciones internas de la Gracia,
la Luz o la Semilla de Dios (como fue explicado anteriormente)
por la cual el alma es sacada del pecado y la corrupción,
y hecha una nueva creación.]
serán justificados.
Así que (a menos que pensemos que Pablo no quiso decir lo que claramente
dijo) podemos concluir con confianza que estos gentiles fueron justificados,
y participaron de esa "`gloria, honra y paz,
que viene sobre todo el que hace lo bueno.`"^
footnote:[Romanos 2:10]
Y entonces vemos,
que así como tener el conocimiento externo de Cristo no puede salvar sin tener lo interno,
tampoco la falta de conocimiento externo puede condenar a los que tienen lo interno.
Y en estas escrituras se evidencia que muchos de
los que han carecido del conocimiento externo,
han llegado verdaderamente a conocer el evangelio internamente,
en virtud de la obra de esa Gracia y Luz dada a todo hombre.
Por la operación de esta gracia (al ser recibida y atendida) estos
gentiles abandonaron la iniquidad y crecieron hasta llegar a la
verdadera justicia y santidad (como fue demostrado anteriormente).
Aunque no conocían la historia de la caída de Adán, sin embargo,
eran conscientes en sí mismos de la pérdida que habían sufrido debido a ella,
sintiendo su inclinación al pecado y el poder del "`cuerpo de pecado`"^
footnote:[Romanos 6:6]
obrando en ellos.
Y de la misma manera, aunque no conocían la venida externa de Cristo, aun así,
eran conscientes de ese poder y salvación internos que vienen por Él,
tanto antes como después de Su aparición en la carne.

Por último,
me pregunto si aquellos que insisten en que el conocimiento
externo de Cristo es necesario para la salvación,
pueden probar que todos los patriarcas y los padres antes de Moisés
tenían algún conocimiento distintivo de Adán o de Cristo.
Porque viendo que Moisés ciertamente escribió acerca de Adán por revelación,
es difícil creer que antes de él los patriarcas supieran algo de
la historia del árbol del conocimiento del bien y del mal,
o de que Adán comiera el fruto prohibido; y mucho menos de Cristo,
que Él iba a nacer de una virgen, ser crucificado, resucitado, etc.

=== Unos Pocos Ejemplos de Escritores Antiguos

Así vemos que es la obra interna lo que da el conocimiento verdadero,
y no la historia y Escritura externa,
y por esta Luz interna muchos de los gentiles filósofos
eran conscientes de la pérdida sufrida por Adán,
aunque no conocían la historia externa.
Es por esto que Platón afirmó que: "`El alma del hombre ha caído en una cueva oscura,
donde solo se comunica con sombras.`"
Pitágoras dijo, "`El hombre divaga en este mundo como un extranjero,
desterrado de la presencia de Dios.`"
Y Plotino comparó "`el alma del hombre, que cayó de Dios, con una carbonilla,
o carbón muerto, del cual se ha extinguido el fuego.`"
Algunos de ellos dijeron que "`las alas del alma fueron cortadas o se han caído,
para que ellos no pudieran volar a Dios.`"
Estas,
y muchas otras expresiones podrían ser extraídas de sus escritos
para mostrar que ellos no carecían de un sentido de su pérdida,
y de la gran caída del hombre de la presencia de Dios.

Estos también experimentaron algo del conocimiento o descubrimiento
de Jesucristo en su interior como el remedio dentro de ellos,
dado para liberarlos de esa semilla maligna,
y de las inclinaciones malvadas de sus propios corazones,
aunque no usaron estos nombres específicos.
Algunos lo llamaron un Santo Espíritu, como Séneca, que dijo,
"`Hay un Santo Espíritu en nosotros que se acerca
a nosotros según nosotros nos acercamos a Él.`"^
footnote:[Epístola 41]
Cicerón lo llama una "`luz innata, constante y eterna, que llama al deber con un mandato,
y disuade del engaño prohibiéndolo.`"^
footnote:[De República, cidad]
Más adelante añade que esta luz "`no puede ser abrogada,
ni ninguno puede librarse de ella, ni por el senado ni por el pueblo; porque ella es una,
eterna y la misma siempre para todas las naciones,
de modo que no hay una en Roma y otra en Atenas.
El que no la quiere obedecer tendrá que intentar huir de sí mismo,
y en esto será atormentado grandemente, aunque logre escapar de cualquier otro castigo.`"
Plotino también lo llama Luz,
diciendo que "`tal como el sol no se puede conocer sino por su propia luz,
así Dios no puede conocerse sino por Su propia Luz.
Y así como el ojo no puede ver el sol sino al recibir su imagen,
tampoco el hombre puede conocer a Dios sino al recibir Su imagen.
Por lo tanto,
le corresponde al hombre llegar a la pureza de corazón
antes de que pueda conocer a Dios.`"
En otros lugares lo llama "`Sabiduría,`" un nombre que frecuentemente
se le da en las Escrituras--véase Proverbios 1:20 hasta el final;
y Proverbios 8:9-34, donde se dice que la Sabiduría clama,
ruega e invita a todos a venir a ella y aprender de ella.
¿Y quién es esta Sabiduría sino Cristo?
En consecuencia,
aquellos entre los paganos que llegaron a abandonar el mal y a adherirse a la justicia,
fueron llamados "`filósofos,`" es decir,
amantes de la sabiduría. Ellos sabían que esta sabiduría estaba cerca de ellos,
y que "`el mejor conocimiento de Dios y de los misterios divinos
viene por la inspiración de la sabiduría de Dios.`"77

Se podrían dar muchos más ejemplos de este tipo,
por los cuales se evidencia que algunos de estos hombres conocieron a Cristo,
y que por Su operación en ellos fueron sacados de la injusticia y llevados a la justicia,
y a amar ese poder por el que se sentían redimidos.
Así, como el apóstol dijo,
"`estos mostraron la obra de la ley escrita en sus corazones,`"
e "`hicieron lo que es de la ley,`" y así,
sin ninguna duda, fueron justificados y salvados por el poder de Cristo en ellos.
Y así como este era el juicio del apóstol,
también era la creencia de los primeros cristianos.
Por esta razón, Justino Mártir no dudó en llamar a Sócrates cristiano,
diciendo que "`todos los que han vivido conforme a la Palabra divina en ellos,
que está en todos los hombres, han sido cristianos, como Sócrates y Heráclito,
y otros entre los Griegos.`"

Agustino dijo,
"`No creo que los judíos se atrevan a afirmar que ninguno era de Dios salvo los israelitas.`"^
footnote:[Ciudad de Dios, libro 18, capítulo 47.]
Y refiriéndose a estas palabras, Ludovico Vives dice: "`Así que los Gentiles,
que no tenían ley, eran una ley para sí mismos;
y la luz de los que viven de esta manera es el don de Dios, y procede del Hijo, que,
como está escrito, alumbra a todo hombre que viene a este mundo.`"

=== Conclusión

Viendo pues, que es por este Don, Gracia y Luz interior,
que aquellos a quienes se les ha predicado el evangelio
llegan a tener a Jesús engendrado en ellos,
y a tener el uso correcto y santificado de todas
las ayudas y ventajas externas (es decir,
las Escrituras, las enseñanzas, etc.); y también, que es por esta misma Luz,
que Dios llama, invita y contiende con todos en un día de visitación,
deseando la salvación de incluso aquellos a quienes
Él les ha retenido el conocimiento externo del evangelio;
nosotros, por lo tanto,
habiendo experimentado la obra interna y poderosa
de esta Luz en nuestros corazones--a saber,
Jesucristo revelado en nosotros--no podemos cesar de proclamar
el Día del Señor que se ha levantado en nosotros,
clamando junto con la mujer Samaritana; "`Venid,
ved a Uno que me ha dicho todo cuanto he hecho.
¿No será éste el Cristo?`"^
footnote:[Juan 4:29]
Esto lo hacemos para que otros puedan llegar a la misma cosa en sí mismos,
y experimentarla,
y para que sepan que esta pequeña cosa que los reprueba en sus
corazones (por mucho que la hayan despreciado y rechazado),
no es nada menos que el Evangelio predicado en ellos--"`Cristo,
la sabiduría y poder de Dios,`" buscando salvar sus almas en, y a través de, Su Semilla.

Agustino, por lo tanto, habla de esta Luz en sus Confesiones, de la siguiente manera:
"`En el principio, oh Dios, hiciste los cielos y la tierra, en Tu Palabra, en Tu Hijo,
en Tu Virtud, en Tu Sabiduría, hablando y obrando maravillosamente.
¿Quién podrá comprenderla?
¿Quién podrá declararla?
¿Qué es eso que brilla dentro de mí y golpea mi corazón sin herirlo,
ante lo cual tiemblo y me enciendo de amor?
Tiemblo, en la medida en que no soy como Él;
y me enciendo de amor en la medida en que soy hecho semejante a Él. Es la Sabiduría,
que brilla dentro de mí y disipa mi neblina, que me había cubierto otra vez,
después de que fui separado de esa oscuridad y de la gran cantidad de mis castigos.`"^
footnote:[Lib. 11, cap.9]
Y nuevamente dice, "`Muy tarde Te he amado, o Hermosura tan antigua y tan nueva;
tarde Te he amado.
¡Y he aquí que Tú estabas adentro, y yo afuera, y ahí Te estaba buscando!
Me llamaste y clamaste, y quebraste mi sordera; brillaste y resplandeciste,
y curaste mi ceguera.`"

De esto también habla nuestro compatriota, George Buchanan, como sigue:
"`Realmente no entiendo otra cosa en este momento aparte
de esa Luz que está infundida divinamente en nuestras almas.
Porque cuando Dios formó al hombre, no solo le dio ojos para su cuerpo,
por los cuales podría evitar las cosas que le son dañinas,
y seguir las cosas que son provechosas, sino que también ha puesto delante de su mente,
por así decirlo, una Luz certera,
por la cual puede discernir entre las cosas que son viles y las cosas que son honestas.
Algunos llaman a esto un poder natural, otros la ley de la naturaleza; en verdad,
yo considero que es algo divino,
y estoy persuadido que la naturaleza y la sabiduría nunca dicen cosas contrarias.
Además, en esta luz Dios nos ha dado un resumen de la ley,
que en pocas palabras comprende el todo, a saber: que debemos amarlo de corazón,
y amar a nuestros prójimos como a nosotros mismos.
Y todos los libros de las Sagradas Escrituras que hablan de la formación de la conducta,
no contienen más que una explicación más detallada de esta única ley.`"^
footnote:[De Jure Regni apud Scotos]

Esta es la Luz,
Gracia o Palabra universal y evangélica en y por la cual
se manifiesta la salvación de Cristo a todos los hombres,
tanto judíos como gentiles, escitas como bárbaros, de cualquier país o pueblo que sean.
Por lo tanto, Dios ha levantado para Sí mismo, en esta nuestra era,
testigos y evangelistas fieles para que prediquen nuevamente Su Evangelio Eterno,
y dirijan a todos--desde los profesantes soberbios del cristianismo que se jactan
de la Ley y de las Escrituras y de su conocimiento externo de Cristo,
hasta los infieles y paganos que no lo conocen de
esa manera--a que se vuelvan a la Luz en ellos,
y conozcan a Cristo en ellos, a quien Santiago llama "`el Justo +++[+++_ton Dikaion_],
a quien han condenado y matado`" durante tanto tiempo; para que estos dejen sus pecados,
sus iniquidades, su fe falsa, sus pretensiones y su justicia externa,
para que todo esto sea crucificado mediante el poder de Su cruz en ellos,
y así conozcan a Cristo dentro de ellos como la "`esperanza
de gloria,`" y lleguen a caminar en Su Luz y ser salvos,
porque Él es "`la Luz verdadera, que alumbra a todo hombre que viene a este mundo.`"^
footnote:[Juan 1:9 RVG]
