== Capítulo V. Respecto a la Justificación

Después de hablar de la muerte de Cristo y de la
gracia que fue comunicada por dicha muerte,
la doctrina de la justificación es lo siguiente que viene en orden.
Muchas son las disputas entre los llamados cristianos acerca de la justificación;
pero sin duda,
si todos realmente le hubieran prestado atención a ese poder que justifica,
habría menos escándalo respecto a las diversas nociones y opiniones.
Primero, voy examinar brevemente la controversia tal como se encuentra entre otros,
y como a menudo y con seriedad la he considerado.
Luego estableceré lo que se relaciona con nosotros de esta controversia,
mostrando nuestro entendimiento y juicio de ella.
Y, por último,
probaré nuestra postura (si el Señor lo permite) con varios testimonios de la Escritura,
y con la experiencia verdadera de todos los que alguna
vez fueron realmente justificados.

Yo supongo que ningún Cristiano Protestante niega que la doctrina
de la justificación haya sido corrompida por la iglesia de Roma,
porque se muestra de manera evidente, y se enseña abiertamente entre los católicos,
que se obtiene remisión de pecados y justificación por los méritos de Cristo,
según estos le son aplicados a través del uso de los sacramentos de la iglesia,
y comunicados en la ejecución de diversas ceremonias, peregrinajes, indulgencias,
oraciones, penitencias y otras obras,
incluso cuando no haya renovación interna de la mente,
ni experiencia de Cristo formado internamente;
de modo que su justificación proviene de algo fuera de ellos,
y no de Alguien dentro de ellos.
Estos dicen ser perdonados y hechos justos por la virtud del sacramento mismo,
y por la autoridad de un sacerdote que los declara absueltos.
En verdad, Lutero tenía buenas razones para oponerse a ellos en este asunto,
y si él mismo no hubiera corrido hacia al otro extremo (del
cual hablaremos después) su obra habría sido mejor.
Porque en esto, como en muchas otras cosas,
él es más digno de elogio por lo que derribó de Babilonia
que por lo que él mismo edificó.

Los Protestantes dicen que "`obtienen remisión de sus pecados
y están justificados ante la vista de Dios,
por la virtud de los méritos y sufrimientos de Cristo;
no por Su justicia infundida en ellos, sino por el perdón de sus pecados,
y por considerarlos y aceptarlos como justos; no por algo forjado en ellos,
o hecho por ellos,
sino porque les imputa la obediencia y satisfacción de Cristo a través de la fe;
cuya fe no tienen por sí mismos, pues es el don de Dios.`"^
footnote:[Así dice la Confesión de Fe de Westminster, capítulo 11, sección 1.]

Por lo tanto, vemos que la justificación de ambos, católicos y protestantes,
no está puesta en alguna renovación interna de la mente,
ni en la virtud de algún nacimiento o formación espiritual de Cristo dentro de ellos,
sino solo en una simple aplicación de Su muerte y sufrimientos
que fueron realizados externamente por ellos.
Los protestantes se aferran a una fe que les es dada,
y esperan ser justificados únicamente por ella;
los católicos esperan hacer que la muerte de Cristo sea efectiva para
ellos mediante la realización de algunas oraciones y ceremonias externas.
Yo reconozco, sin embargo (porque no quiero agraviar a nadie),
que algunos católicos y protestantes modernos han dicho algunas
cosas mejores acerca de la necesidad de la santidad interna,
quienes han llegado cerca de la Verdad (como aparecerá más adelante,
por algunas citas de sus escritos).

=== Nuestra Postura

En cuanto a nuestra postura en este asunto: En primer lugar,
renunciamos a la idea de que haya algún poder o habilidad natural en nosotros
mismos para sacarnos fuera de nuestra condición perdida y caída,
es decir, de nuestra primera naturaleza;
y confesamos que no somos capaces de hacer nada bueno por nosotros mismos.
Y además de esto,
nos consideramos completamente incapaces de procurarnos la remisión de pecados
o la justificación por cualquier acto propio que haga que seamos dignos de ella,
o que cause que Dios esté en deuda con nosotros.
Al contrario, reconocemos que todo es por causa de Su amor, y a partir del mismo,
porque Su amor es el origen y la causa fundamental de nuestra aceptación.

En segundo lugar,
Dios manifestó este amor para con nosotros al enviar al mundo a Su Hijo amado,
el Señor Jesucristo,
quien se entregó a Sí mismo por nosotros como una
ofrenda y sacrificio a Dios en olor fragante,
haciendo la paz mediante la sangre de Su cruz, para reconciliarnos consigo mismo.
Jesucristo, mediante el Espíritu Eterno, se ofreció a Sí mismo sin mancha a Dios,
y sufrió por nuestros pecados, el justo por los injustos, para llevarnos a Dios.

Por lo tanto, en tercer lugar,
en vista de que todos los hombres (que han llegado al estado de hombre)
han pecado--excepto el Hombre Jesús--todos necesitan este Salvador,
para quitar de ellos la ira de Dios debido a sus ofensas.
En este respecto,
está escrito que Él verdaderamente "`llevó nuestros pecados en Su cuerpo sobre el madero,`"^
footnote:[1 Pedro 2:24]
y, por lo tanto, es el único Mediador, pues el apaciguó la ira de Dios para con nosotros,
para que nuestros pecados pasados ya no estorben nuestro camino,
siendo removidos y perdonados en virtud de Su sacrificio,
que fue sumamente satisfactorio.
Y en verdad, la remisión de los pecados no debe esperarse,
buscarse ni obtenerse de ninguna otra manera,
ni por ninguna otra obra o sacrificio (aunque, como se dijo anteriormente, algunos,
que no conocen la historia, pueden llegar a participar de esta remisión).

De este modo, Cristo nos reconcilia con Dios por medio de Su muerte y sufrimientos,
aun cuando somos enemigos--es decir,
le ofrece reconciliación al mundo y nos da la capacidad de ser reconciliados,
porque Dios está dispuesto a perdonarnos nuestras iniquidades y a aceptarnos,
como el apóstol lo expresa bien: "`Dios estaba en Cristo reconciliando consigo al mundo,
no tomándoles en cuenta a los hombres sus pecados,
y ha puesto en nosotros la palabra de reconciliación.`"^
footnote:[2 Corintios 5:19 Traducción Literal. Nota del Editor:
La mayoría de las traducciones modernas se leen
"`nos encargó a nosotros la palabra +++(+++o mensaje) de la reconciliación.`"
Pero el griego se lee "`ha puesto en nosotros la palabra de reconciliación.`"
// lint-disable invalid-characters
θέμενος ἐν ἡμῖν τὸν λόγον τῆς καταλλαγῆς]
Y por lo tanto, el apóstol, en los siguientes versículos,
les ruega "`en nombre de Cristo: Reconciliaos con Dios;`" dando a entender,
que la ira de Dios ha sido removida por la obediencia de Jesucristo,
y ahora Dios está dispuesto a reconciliarse con ellos,
y está listo para remitir los pecados pasados, si se arrepienten.

Nosotros, por lo tanto, consideramos que nuestra redención tiene dos aspectos o estados,
ambos perfectos en su propia naturaleza, aunque en su aplicación a nosotros,
uno no puede estar sin relación al otro, como se observará.

El primer aspecto, pues,
es la redención que Cristo realizó y consumó _por
nosotros_ en Su cuerpo crucificado fuera de nosotros.
El otro es la redención que obra Cristo _dentro de nosotros,_
y este segundo aspecto se llama y se considera una
redención con la misma propiedad que el primero.
El primero es aquel por el cual el hombre, estando en su condición caída,
obtiene la capacidad de ser salvo, y recibe una medida de ese poder, virtud, espíritu,
vida y gracia que estaban en Jesucristo--que, siendo el don gratuito de Dios,
es capaz de vencer y desarraigar la semilla maligna por la cual estamos
leudados naturalmente en la caída. El segundo aspecto es aquel mediante
el cual experimentamos y conocemos esta redención pura y perfecta en nosotros,
purificando, limpiando y redimiéndonos del poder de la corrupción,
y llevándonos a la unidad, favor y amistad con Dios.^
footnote:[Nota del Editor: Véase también Efesios capítulo 1,
donde Pablo escribe primero (versículo 7), "`en quien __tenemos redención__ por Su sangre,
el perdón de pecados según las riquezas de Su gracia;`" y luego
(versículo 14) declara que el Espíritu Santo es "`las arras de
nuestra herencia __hasta la redención__ de la posesión adquirida.`"]

A través del primer aspecto de estos dos, nosotros, que estábamos perdidos en Adán,
hundidos en la semilla maligna y corrupta,
sin la capacidad de hacer algo bueno por nosotros mismos,
sino más bien naturalmente ligados y unidos al mal, prontos y propensos a toda iniquidad,
siervos y esclavos del poder y espíritu de las tinieblas, a pesar de todo esto,
somos reconciliados con Dios por la muerte de Su Hijo, aun cuando éramos enemigos,
hasta el punto de darnos la capacidad de ser salvos,
y de ofrecernos las buenas nuevas del Evangelio de la paz en nosotros--que
Dios se ha reconciliado con nosotros en Cristo,
y por lo tanto nos llama e invita a Sí mismo.
En este aspecto de nuestra redención, es que entendemos las siguientes escrituras:
"`Habiendo abolido en Sí mismo la enemistad;`"^
footnote:[Efesios 2:14-15 RV1602P]
"`Él nos amó primero,`"^
footnote:[1 Juan 4:19]
"`viéndonos sucios en nuestras sangres, nos dijo: ¡Vive!;`"^
footnote:[Ezequiel 16:6]
"`quien llevó Él mismo nuestros pecados en su cuerpo sobre el madero;`"^
footnote:[1 Pedro 2:24]
y "`también Cristo padeció una sola vez por los pecados, el justo por los injustos;`"^
footnote:[1 Pedro 3:18]
etc.

Por el segundo aspecto, experimentamos que esta capacidad comienza a actuar, por la cual,
si recibimos y no resistimos lo que Él compró con Su muerte (a saber, la Luz,
Espíritu y Gracia de Cristo revelada en nosotros),
disfrutamos y poseemos una redención real,
verdadera e interna del poder y prevalencia del pecado, y así llegamos a ser redimidos,
justificados y hechos justos de manera real y verdadera,
y experimentamos una unión y amistad viva con Dios.
Por lo tanto, Él "`se dio a Sí mismo por nosotros para redimirnos de toda iniquidad,
y purificar para Sí un pueblo peculiar;`"^
footnote:[Tito 2:14 RVG]
y por ende "`lo conocemos, y el poder de Su resurrección,
y la comunión de Sus padecimientos, siendo hechos conforme a Su muerte.`"^
footnote:[Filipenses 3:10]
Este último aspecto viene en orden después del primero, y es una consecuencia del mismo,
ya que procede de él, como un efecto que procede de su causa.
Así, pues,
de la misma manera que nadie puede disfrutar del último sin que
el primero haya sido establecido (siendo esto la voluntad de Dios);
asimismo nadie puede participar realmente del primero,
salvo en la medida que experimente el último.
Así que, para nosotros, ambos aspectos son causas de nuestra justificación.

Ahora bien, nosotros no entendemos como justificación simplemente el hacer buenas obras,
incluso las obras que vienen del Espíritu de Cristo;
porque estas (como afirman correctamente los protestantes) no son la causa de la justificación,
sino más bien un efecto de ella.
En lugar de eso, entendemos que la justificación es Cristo formado en nosotros,
Cristo nacido y engendrado en nosotros,
y es de esto que proceden naturalmente las buenas obras,
así como los frutos proceden de un árbol fructífero.
Este nacimiento interno en nosotros, que produce justicia y santidad en nuestro interior,
es lo que nos justifica,
que luego de haber removido y quitado la naturaleza
y espíritu contrarios que reinaban y traían condenación,
ahora ejerce dominio sobre todo en nuestros corazones.
Aquellos, pues, que llegan a experimentar a Cristo formado de esta manera en ellos,
Lo disfrutan plena y continuamente, y Lo conocen como "`el Señor justicia nuestra.`"^
footnote:[Jeremías 23:6]
Esto es lo que significa ser revestidos de Cristo, y estar cubiertos por Él,
y a estos Dios en verdad los considera justos y rectos.

Esto difiere muchísimo de la doctrina de los católicos,
porque aquí las obras no son la causa formal de la justificación
(siendo ellas solo un efecto de la misma),
sino más bien un nacimiento interior, Jesucristo engendrado en el corazón,
quien es el amado, a quien el Padre no puede sino aceptar,
junto con todos aquellos que están rociados de esta manera
con la sangre de Jesús y lavados verdaderamente con ella.
Y mediante esto (es decir,
por ser revestidos de Cristo internamente) también llegamos
a experimentar a Cristo comunicándonos sus bienes,
por los cuales "`llegamos a ser participantes de la naturaleza divina,`"^
footnote:[2 Pedro 1:4]
como dice Pedro, y a ser hechos uno con Él, como el pámpano con la vid,
y entonces tenemos derecho a todo lo que Él ha hecho y sufrido por nosotros.
De esta manera Su obediencia se vuelve nuestra, Su justicia nuestra,
Su muerte y sufrimientos nuestros.
Y por esta cercanía a Él, a menudo llegamos a tener un sentido de Sus sufrimientos,
y de hecho sufrimos con Su Semilla que aún yace oprimida y crucificada en los
corazones de los impíos. Así nosotros sufrimos dolores de parto con ella,
y por su redención,
y por el arrepentimiento de esas almas que todavía están
crucificando al Señor de Gloria--así como el apóstol Pablo,
de quien está escrito que con sus sufrimiento "`cumplió
lo que faltaba de las aflicciones de Cristo por Su cuerpo,
que es la iglesia,`"^
footnote:[Colosenses 1:24]
aunque esto es un misterio sellado para todos los hombres sabios,
que aún son ignorantes de esta Semilla en sí mismos, y se oponen a ella.

Finalmente,
aunque nosotros decimos que la justicia y obediencia que tuvo Cristo en la carne
es el fundamento de la remisión de los pecados (como la causa principal),
y nos consideramos realmente justificados conforme
Cristo Jesús es formado y engendrado en nosotros;
aun así, no podemos excluir las obras de la justificación,
como algunos protestantes han hecho imprudentemente.
Porque, para hablar de manera correcta, no somos justificados _por_ ellas, mas,
sin embargo, somos justificados _en_ ellas, y por lo tanto son necesarias.
Negar esto no solo es contrario al testimonio de la Escritura,
sino que además ha causado un gran escándalo en la religión de los protestantes,
ha abierto las bocas de los acusadores y ha hecho que muchos sientan
una seguridad falsa en una justificación sin buenas obras.
Además, aunque no es seguro decir que las buenas obras merecen la justificación,
sin embargo, las Escrituras muestran claramente que son recompensadas,
de modo que muchos de los que son llamados Padres de la Iglesia no han tenido miedo
de usar la palabra "`mérito`" en un sentido limitado (aunque no como lo hacen los católicos).
Sin embargo, la mayoría de los protestantes no solo niegan la necesidad de buenas obras,
sino que algunas veces no les avergüenza llamarlas dañinas,
a menudo diciendo que las mejores obras, incluso las de los santos,
son inmundas y corruptas.
Ahora bien,
aunque nosotros consideramos que esto es cierto respecto
a las mejores obras hechas _por el hombre,_
tratando de cumplir la ley externa por su propia fuerza y en su propia voluntad,
sin embargo,
creemos que las obras que proceden naturalmente de este
nacimiento espiritual y de Cristo formado en nosotros,
son puras y santas, así como la raíz de la cual surgen es pura.
Por esta razón Dios las acepta, nos justifica en ellas y nos recompensa por ellas,
de Su propia gracia gratuita.

=== La Prueba de Nuestra Postura

Habiendo descrito de esta manera el estado de la controversia,
ahora deben probarse las siguientes proposiciones:

[.numbered-group]
====

[.numbered]
_Primero:_ Que por la obediencia, los sufrimientos y la muerte de Cristo,
el alma obtiene la remisión de pecados,
y que esto también es la causa que le abrió paso a la gracia por la que
Cristo (mediante sus operaciones internas) llega a formarse internamente.
De esta manera el alma es conformada a Él, y así se vuelve justa, y es justificada.
Y, por lo tanto, es con respecto a esta capacidad y oferta de gracia,
que se dice que Dios se ha "`reconciliado`" con nosotros--aunque
no en el sentido de estar realmente unido a nosotros,
o que considera realmente a alguien justo o justificado,
mientras todavía vive en sus pecados, y continúa siendo impuro e injusto.

[.numbered]
_Segundo:_ Que es por este nacimiento interno de Cristo en el hombre,
que somos hechos justos, y, por lo tanto, considerados así por Dios.
De modo que (para hablar claramente) no somos verdaderamente justificados
ante los ojos de Dios hasta que Cristo sea engendrado en nosotros;
porque en la Escritura,
el término justificación se usa más común y correctamente de acuerdo con su verdadero
significado,) que es "`hacer justo,`" y no simplemente considerar a alguien justo.

[.numbered]
_Tercero:_
Que puesto que las buenas obras fluyen naturalmente
de este nacimiento (como el calor del fuego),
por ende, son absolutamente necesarias para la justificación--no como la causa de ella,
sino como aquello en lo cual somos justificados,
y sin lo cual no podemos ser justificados.
Y aunque estas buenas obras no reciben como mérito la salvación,
ni hacen que Dios esté en deuda con nosotros,
Él no puede sino aceptarlas y recompensarlas,
porque es contrario a Su naturaleza negar lo Suyo,
especialmente cuando estas pueden ser perfectas según su género,
al proceder de un nacimiento y raíz puro y santo.
Por lo tanto,
decir que las obras más santas de los santos son
inmundas y pecaminosas ante la vista de Dios,
es algo falso y contrario a la Verdad;
porque las buenas obras que fluyen del nacimiento espiritual no son las
obras de la ley que el apóstol excluyó de la justificación.

====

En cuanto a la primera afirmación, la puedo demostrar a partir de Romanos 3:25:
"`a quien Dios puso como propiciación por medio de la fe en su sangre,
para manifestar su justicia, a causa de haber pasado por alto, en su paciencia,
los pecados pasados.`"
Aquí el apóstol expone el alcance y la eficacia de la muerte de Cristo,
mostrando que la remisión de los pecados pasados se obtiene por ella,
y por la fe en ella;
y que en esto se manifiesta la paciencia de Dios para con la humanidad.
De modo que,
aunque los hombres merecen la muerte eterna por los pecados que comenten diariamente,
en virtud de ese sacrificio de Cristo Jesús (que fue sumamente satisfactorio)
la gracia y semilla de Dios se mueve por amor a ellos durante el día de su visitación,
buscando redimirlos del mal.

En segundo lugar, si Dios estuviera perfectamente reconciliado con los hombres,
y los estimara justos cuando en realidad son injustos y continúan en sus pecados,
entonces Él no tendría ninguna controversia con ellos.
Pero entonces ¿porque a lo largo de toda la Escritura Él se queja y razona tan
frecuentemente con aquellos que nuestros adversarios afirman que están justificados?
diciéndoles que "`sus iniquidades han hecho división entre ellos y su Dios.`"^
footnote:[Isaías 59:2]
Porque no existe división donde hay una reconciliación perfecta y completa.
Pero decir que los hombres pueden estar reconciliados plenamente
con Dios incluso mientras continúan en sus pecados,
necesariamente implica que el pecado no hace la más mínima división entre ellos y Dios,
y que el hombre es justificado _en sus pecados._
Y de aquí surgiría la conclusión más abominable:
que las buenas obras y los grandes pecados son lo mismo ante los ojos de Dios,
ya que ninguno sirve para justificar, ni para romper la reconciliación con Dios.
En verdad,
tal doctrina abre una puerta para la seguridad falsa y para toda práctica inmoral.

En tercer lugar, esto anularía toda la doctrina práctica del evangelio,
y haría que tales cosas como la fe, el arrepentimiento,
la obediencia y las otras condiciones que son nuestro deber realizar^
footnote:[Nota del Editor:
Estas son realizadas en la gracia que fluye para nosotros en el pacto,
como fue mencionado anteriormente.]
sean completamente innecesarias.
Y ciertamente,
estas condiciones son de una naturaleza que no se pueden realizar de una sola vez,
sino que deben cumplirse durante toda la vida.
Pero si nosotros ya estamos reconciliados y justificados
perfectamente antes de que estas condiciones sean realizadas,
entonces no podría decirse que son necesarias,
lo cual es contrario al testimonio claro de la Escritura que todos los cristianos reconocen.
Porque leemos: "`Sin fe es imposible agradar a Dios.`"^
footnote:[Hebreos 11:6]
Y, "`porque si vivís conforme a la carne, moriréis;
más si por el Espíritu hacéis morir las obras de la carne, viviréis.`"^
footnote:[Romanos 8:13]
Y el Señor les dijo a los que ya estaban convertidos, "`quitaré tu candelero de su lugar,
si no te arrepientes,`"^
footnote:[Apocalipsis 2:5 LBLA]
y Pablo clamó, "`Vosotros corríais bien;
¿quién os estorbó para no obedecer a la verdad?`"^
footnote:[Gálatas 5:7]
Si mencionara todas las Escrituras que prueban esto de manera positiva y evidente,
tendría que trascribir casi toda la parte doctrinal de la Biblia.
Porque Cristo dijo "`consumado es,`"^
footnote:[Juan 19:30]
y ciertamente terminó Su obra hace más de mil seiscientos años,
ofreciendo Su cuerpo como un sacrificio por el pecado,
abriendo una puerta de misericordia para todos y comunicando una
medida de Su gracia por la cual todos pueden ver sus pecados,
tener la capacidad de arrepentirse,
y así experimentar en el presente Su obra interna de redención,
reconciliación y justificación. Pero si entendemos que cuando Él dijo "`consumado
es,`" quiso decir que perfeccionó y finalizó la redención del hombre,
y reconcilió completamente a todos los que serán salvos (ya sea antes de creer,
como algunos dicen, o después de confesar la verdad de la historia de Cristo,
o de ser rociados con agua, etc.) incluso aunque continúen en sus pecados,
entonces toda la parte doctrinal de la Biblia es inútil y de ningún provecho.
En vano fueron enviados los apóstoles a predicar el evangelio;
en vano las Escrituras nos advierten que no nos desviemos,
ni hagamos nula la gracia de Dios, ni perdamos nuestro primer amor,
ni permitamos que nuestros corazones se endurezcan
y así quedemos cortos de nuestro descanso, etc.
Y en vano todos los predicadores cristianos realizan su labor,
gastan sus pulmones y producen escritos,
solo para hacer lo que ya está hecho perfectamente sin ellos.

Pero finalmente,
esta doctrina también hace que la intercesión presente
de Cristo por los hombres sea nula.
Porque ¿qué sería de ese gran artículo de la fe por el cual afirmamos,
"`que Él está a la diestra de Dios, intercediendo diariamente por nosotros?`"^
footnote:[Romanos 8:34]
Y ¿con qué fin "`el Espíritu mismo intercede por nosotros con gemidos indecibles?`"^
footnote:[Romanos 8:26-27]
Porque es absurdo interceder por los que no tienen la posibilidad de ser salvos.
Y es inútil orar por los que ya están reconciliados y perfectamente justificados.
En verdad, no veo una manera real de resolver esto,
excepto al reconocer la verdad del asunto, a saber:
que Cristo por Su muerte removió la ira de Dios,
de tal manera que obtuvo la remisión de los pecados para
todos los que reciban la Gracia y Luz que Él les comunica,
y que los compró con Su sangre.
A medida que ellos creen en esto,
llegan a experimentar la remisión de sus pecados pasados,
y el poder que los salva del dominio del pecado, porque a "`todos los que lo reciben,
les da el poder de llegar a ser hijos de Dios.`"^
footnote:[Juan 1:12 NBLH]
Estos también experimentan Su poder borrando cualquier pecado presente,
en el cual puedan caer por no velar o por debilidad, si,
entregándose a sí mismos a esta gracia, se arrepienten verdaderamente.
De modo que, ninguno es hijo, ninguno está justificado, ni reconciliado,
hasta que reciba a Cristo en esa pequeña Semilla en su corazón;
y es así como se le ofrece la vida eterna "`a los que, perseverando en bien hacer,
buscan gloria y honra e inmortalidad.`"^
footnote:[Romanos 2:7]
Porque, según el profeta, "`si el justo se aparta de su justicia,
ninguna de las obras justas que ha hecho le serán recordadas.`"^
footnote:[Ezequiel 18:24 LBLA]
En consecuencia, ninguno permanece como hijo de Dios,
ni está justificado ante los ojos de Dios,
a menos de que pacientemente continúe en la justicia y en bien hacer.
Y, por lo tanto,
Cristo vive siempre para interceder durante el día de la visitación de cada hombre,
a fin de que puedan ser convertidos.
Y cuando en alguna medida han crecido en la vida,
Él intercede para que puedan continuar y seguir adelante, y no desmayen,
ni se vuelvan atrás. Se podría decir mucho más para confirmar esta verdad;
pero proseguiré a observar las objeciones comunes en contra de ella.

=== Objeciones y Respuestas

[.discourse-part]
Objeción:
La primera y principal objeción es sacada de la afirmación del apóstol (antes mencionado):
"`Dios nos reconcilió consigo mismo por Cristo:
Dios estaba en Cristo reconciliando consigo al mundo,
no tomándoles en cuenta a los hombres sus pecados.`"^
footnote:[2 Corintios 5:18-19]
De aquí ellos deducen que Cristo perfeccionó por completo la obra
de reconciliación mientras estaba en la tierra.

[.discourse-part]
Respuesta: Si se entiende por "`reconciliación`" la remoción de la ira,
y la compra de esa Gracia por la cual podemos llegar
a ser completamente reconciliados y unidos con Dios,
entonces estamos de acuerdo.
Pero es evidente del versículo mismo, que el apóstol no dice nada más que esto;
porque cuando habla en pretérito perfecto, diciendo,
"`Él nos reconcilió,`" habla de sí mismo y de los santos, quienes,
habiendo recibido la Gracia de Dios que Cristo compró,
estaban realmente reconciliados por medio de la fe en Él. Pero con respecto a los demás,
habla de la "`Palabra de reconciliación`" que fue "`puesta en ellos;`"^
footnote:[2 Corintios 5:19 Traducción Literal.
Nota del Editor: La mayoría de las traducciones modernas dicen:
"`nos encargó a nosotros la palabra de la reconciliación.`" Pero el griego dice "`poniendo
// lint-disable invalid-characters
en nosotros la Palabra de reconciliación`" - θέμενος ἐν ἡμῖν τὸν λόγον τῆς καταλλαγῆς]
y en el siguiente versículo dice, "`Así que, somos embajadores en nombre de Cristo,
como si Dios rogase por medio de nosotros; os rogamos en nombre de Cristo:
Reconciliaos con Dios.`"^
footnote:[2 Corintios 5:20]
Ahora bien,
si su reconciliación ya se había llevado a cabo perfectamente ¿qué
necesidad habría de que alguien les rogará que se reconciliaran?
Los embajadores no son enviados después de que la paz ya
se ha establecido y se ha hecho la reconciliación,
sino para ofrecer la reconciliación.

[.discourse-part]
Objeción: En segundo lugar, ellos objetan (del versículo 21 del mismo capítulo),
"`Al que no conoció pecado, por nosotros lo hizo pecado,
para que nosotros fuésemos hechos justicia de Dios en Él.`" De aquí argumentan:
que así como nuestro pecado le es imputado a Cristo, quien no tenía pecado;
de la misma manera la justicia de Cristo nos es imputada,
sin que seamos realmente justos.

[.discourse-part]
Respuesta: Pero esta interpretación es rechazada fácilmente;
porque en múltiples ocasiones el apóstol mismo demuestra que nosotros
tenemos que ser hechos _realmente_ justos por Cristo,
y no simplemente imputados o considerados justos.
De hecho,
esto se evidencia por lo que sigue en los versículos 14-16 del siguiente capítulo,
donde él, de manera amplia,
argumenta en contra de cualquier supuesto acuerdo entre la luz y las tinieblas,
o entre la justicia y la injusticia.
Pero si los hombres deben considerarse como injertados en Cristo,
y como miembros verdaderos de Él,
simplemente porque les es imputada una justicia externa,
mientras ellos continúan en su injusticia,
¿no implicaría esto una comunión entre la justicia y la injusticia?
Y de verdad,
debería considerarse extraño cómo muchos han hecho de esta "`justicia
imputada`" un artículo tan fundamental de su fe,
a pesar de ser algo tan contrario a toda la tendencia del Evangelio.
Porque Cristo jamás, en ninguno de Sus sermones y discursos piadosos,
deseó que Sus oyentes pusieran su confianza en semejante cosa, sino al contrario,
siempre los dirigió a la verdadera santificación,
a limpiar el vaso por dentro y por fuera, y a las buenas obras que glorifican al Padre,
diciendo: "`Sed, pues, vosotros perfectos,
como vuestro Padre que está en los cielos es perfecto.`"^
footnote:[Mateo 5:48]

=== La Verdadera Justificación--Cristo Formado Internamente

Así pues, he llegado a la segunda cosa que he planteado, a saber:
que es por este nacimiento interno, o por Cristo formado dentro nosotros,
que somos formalmente (por así decirlo) justificados ante los ojos de Dios.
Supongo que ya he dicho lo suficiente para demostrar lo mucho que valoramos la muerte
y los sufrimientos de Cristo como la ofrenda que satisface la justicia de Dios,
obtiene remisión de pecados y compra la Gracia y Semilla de la que procede este nacimiento.
Lo que resta por probar es: que por Cristo Jesús formado en nosotros somos justificados,
o _verdaderamente hechos justos._
Tengan en cuenta que aquí uso el término "`justificación`" en este sentido.

Por lo tanto, en primer lugar,
voy a probar esto a partir de esa Escritura del apóstol Pablo en 1 Corintios 6:11:
"`Y esto erais algunos; mas ya habéis sido lavados, ya habéis sido santificados,
ya habéis sido justificados en el nombre del Señor Jesús,
y por el Espíritu de nuestro Dios.`"
Aquí la palabra "`justificados`" debe necesariamente
significar ser hechos realmente justos,
y no simplemente ser imputados o atribuidos como tal; o de otro modo,
"`santificados`" y "`lavados`" también podrían considerarse como una simple imputación,
lo cual anularía toda la intención del contexto.
Porque en los versículos anteriores,
el apóstol les advierte a sus lectores que "`no se dejen engañar,`"
porque "`los injustos no heredarán el reino de Dios;`"^
footnote:[1 Corintios 6:9 NBLH]
y después de especificar varios tipos de iniquidad, concluye diciendo,
"`esto erais algunos de vosotros`" pero ya no lo son.
Por lo tanto, habiendo sido lavados y santificados,
entonces fueron verdaderamente justificados.
Por mi parte, no he visto,
ni jamás he oído o leído nada que indicara que la palabra "`justificados`"
en este lugar deba entenderse de otra manera que no sea según su significado
apropiado y genuino de _ser hechos justos._

Ahora bien,
esta palabra "`justificar,`" que se deriva del sustantivo "`justicia,`"
o del adjetivo "`justo,`" sin duda alguna significa hacer justo,
porque no es más que una composición del verbo _facio,_ y del adjetivo _justus,_
que forman _justifico,_ o _yo hago justo._
De la misma manera, la palabra justificado proviene de _justus_ y _fio,_
que significan _yo me vuelvo justo._
Lo mismo ocurre con otros verbos de este tipo,
como _santifico_ que proviene de _sanctus_ (santo) y _facio,_ que significan _yo hago santo._
En cada caso,
se entiende que el sujeto recibe de manera real y verdadera
de esa virtud y cualidad de la que se deriva el verbo.
Porque, así como nadie se considera santificado cuando realmente no es santo;
así tampoco nadie puede considerarse justificado,
mientras realmente sigue siendo injusto.

Sin embargo, este verbo "`justifico,`" de manera metafórica y figurativa,
ha sido usado en un sentido legal, como, por ejemplo,
cuando un hombre realmente culpable de un crimen queda libre del castigo de su pecado,
se dice que está justificado, es decir, puesto en el lugar del justo,
como si fuera justo.
Pero ¿no es extraño que los hombres sean tan superficiales en un asunto tan importante,
como para edificar el fundamento de su aceptación para con Dios
sobre un simple significado prestado y metafórico de esta palabra,
y así excluir (o al menos estimar innecesaria) esa "`santidad,
sin la cual nadie verá a Dios`"^
footnote:[Hebreos 12:14]
(como la Escritura lo dice claramente)?
De hecho ¿no sería un gran error contentarnos con una justificación
imaginaria mientras Dios requiere una real?
Y que se tenga en cuenta que en todas las cartas a los romanos, corintios,
gálatas y a cualquier otro lugar, en las que el apóstol trata este tema,
la palabra puede tomarse en su significado apropiado sin que haya nada que suene absurdo.
Por ejemplo, en sus epístolas a los romanos y a los gálatas,
Pablo afirma que "`un hombre no puede ser justificado por la ley de Moisés,
ni por las obras de la ley.`"^
footnote:[Romanos 3:28; Gálatas 2:16, 3:11]
No es absurdo ni peligroso entender la palabra justificado
en este lugar según su significado correcto,
es decir, que un hombre no puede ser hecho justo por la ley de Moisés;
especialmente cuando vemos cómo esto concuerda bien con ese dicho del mismo apóstol:
que "`la ley nada hace perfecto.`"^
footnote:[Hebreos 7:19 LBLA]
Además, donde está escrito que "`somos justificados por fe,`"^
footnote:[Romanos 3:28; Gálatas 3:24]
puede entenderse muy bien como ser hechos justos,
puesto que también está escrito que la "`fe purifica el corazón;`"^
footnote:[Hechos 15:9]
y sin duda los puros de corazón son justos, y "`el justo vive por fe.`"^
footnote:[Habacuc 2:4; Romanos 1:17; Gálatas 3:11; Hebreos 10:38]
Nuevamente, donde está escrito que somos "`justificados por Su gracia,`"^
footnote:[Romanos 3:24; Tito 3:7]
o "`justificados por Cristo,`"^
footnote:[Gálatas 2:17]o "`justificados por el Espíritu;`"^
footnote:[1 Corintios 6:11]
no es de ninguna manera absurdo entender la palabra justificados como ser hechos justos,
ya que es cierto que Él, por Su Espíritu y gracia, en verdad hace a los hombres justos.
Pero entenderla universalmente de la otra manera, como una simple aceptación legal,
ocasionaría grandes tonterías como podría probarse ampliamente;
pero debido a que considero que esto será reconocido, me abstengo en este momento,
por causa de brevedad.

Pero además,
en los lugares más importantes donde se usa la palabra "`justificar`" en la Escritura,
nuestros adversarios no pueden evitar reconocer que debe entenderse como hacer justo,
y no como una simple aceptación legal.
Esto lo hemos visto en 1 Corintios 6:11: "`Más ya habéis sido lavados,
ya habéis sido santificados, ya habéis sido justificados.`"
Pero también lo vemos en Tito 3:5-7--"`nos salvó,
no por obras de justicia que nosotros hubiéramos hecho, sino por su misericordia,
por el lavamiento de la regeneración y por la renovación en el Espíritu Santo,
el cual derramó en nosotros abundantemente por Jesucristo nuestro Salvador,
para que justificados por su gracia,
viniésemos a ser herederos conforme a la esperanza de la vida eterna.`"
Y también en esa excelente afirmación del apóstol (Romanos 8:30), "`a los que llamó,
a éstos también justificó; y a los que justificó,
a éstos también glorificó.`" Esto es comúnmente llamado la "`cadena de oro,`"
y todos reconocen que comprende el método y orden de la salvación. Pero si aquí
"`justificó`" no fuera entendido en su significado apropiado--es decir,
realmente ser hecho justo--entonces el cambio verdadero de la iniquidad
a la santidad sería completamente excluido de esta cadena.
Pero ciertamente (como la mayoría reconoce), el apóstol, en esta descripción abreviada,
usa la palabra "`justificó`" para abarcar todo lo que viene entre el llamado y la glorificación,
dando a entender que la manera por la que pasamos del llamado
a la glorificación es ser hechos realmente justos.

De hecho, muchos padres de la Iglesia y protestantes famosos dicen lo mismo:
"`Yo considero,`" dice Beza, "`el término justificación de manera general,
como algo que abarca todo lo que adquirimos de Cristo,
ya sea por imputación o por la eficacia del Espíritu al santificarnos.
De esta manera, la palabra justificación debería entenderse en Romanos 8:30.`"^
footnote:[In cap. 3. Ad Tit. Ver. 7.]
Melanchthon dice, "`Ser justificados por fe, no solo significa ser declarados justos,
sino también, de injustos ser hechos justos.`"^
footnote:[En Apol. Confess. Aug.]
También, algunos de los protestantes principales, aunque no tan claramente,
han apuntado hacia nuestra doctrina,
por la cual le atribuimos la remisión de los pecados a la muerte de Cristo,
y la obra de justificación a la gracia del Espíritu adquirida mediante Su muerte.
Martin Borrhaus, en su explicación de Romanos 4:25, donde dice,
"`el cual fue entregado por nuestras transgresiones,
y resucitado para nuestra justificación,`" dice:
"`Aquí hay dos cosas que se encuentran en Cristo,
las cuales son necesarias para nuestra justificación--la primera es Su muerte;
la otra es Su resurrección de la muerte.
Por Su muerte, los pecados de este mundo fueron expiados.
Por Su Resurrección de la muerte,
le plació a la misma bondad de Dios darnos el Espíritu Santo,
por el cual se cree el Evangelio y se restaura la
justicia que se perdió por la caída del primer Adán.`"^
footnote:[En Gen. Cap. 15. Ad verb. Cred dit Abraham Deo+++.+++, p. 161]
Y más adelante dice, "`El apóstol expresa ambas partes en estas palabras,
'`el cual fue entregado por nuestras transgresiones,
y resucitado para nuestra justificación.`' En Su
muerte se encuentra la expiación por el pecado;
en Su resurrección se encuentra el don del Espíritu Santo,
por el cual se perfecciona nuestra justificación.`"^
footnote:[Lib. 3. Reg. Cap. 9. Ver. 4., p. 681]
Y William Forbes, obispo de Edinburgh, dice,
"`Donde quiera que la Escritura haga mención de la justificación ante Dios,
es evidente que la palabra justificar no puede significar solamente declarar justo,
en un sentido legal, sino también hacer justo de manera real e inherente;
porque Dios justifica de forma diferente a los jueces terrenales.
De hecho, tanto las Escrituras como los Padres afirman:
que en la justificación de un pecador, sus pecados no solo son remitidos, perdonados,
cubiertos y no imputados, sino que también son quitados, borrados, limpiados, lavados,
purificados, y removidos muy lejos de nosotros,
como aparece en muchos lugares de las Sagradas Escrituras.`"^
footnote:[In considerat. modest. de Just. lib. 2. Sect. 8.]

=== La Revelación de Jesucristo en el Alma

Habiendo demostrado suficientemente que la palabra "`justificación`"
debe entenderse como la experiencia de realmente ser hecho justo,
ahora afirmo con confianza (no a partir de un conocimiento teórico,
sino de la experiencia verdadera,
interna y viva de la cosa misma) que la revelación
de Jesucristo en el alma es la causa inmediata,
directa o formal de la justificación de los hombres ante los ojos de Dios,
la cual cambia, reforma y renueva la mente.
Es por medio de Él (el Autor de esta obra interior),
siendo así revelado y formado dentro de nosotros,
que somos verdaderamente justificados y aceptados ante los ojos de Dios.
Porque es en la medida que somos cubiertos y revestidos
de Él (en quien el Padre siempre tiene complacencia),
que podemos acercarnos a Dios y estar de pie con confianza delante de Su trono,
siendo purificados por la sangre de Jesús derramada internamente en nuestras almas,
y revestidos con Su vida y justicia que se revelan allí. Y es este el orden y
método de salvación que el apóstol expone en esa afirmación divina (Romanos 5:10):
"`Porque si siendo enemigos, fuimos reconciliados con Dios por la muerte de su Hijo,
mucho más, estando reconciliados, seremos salvos por su vida.`"
Aquí el apóstol primero habla de la reconciliación llevada a cabo por la muerte
de Cristo (por lo cual Dios está cerca para recibir y redimir al hombre),
y luego de la salvación de los hombres y de la verdadera justificación
que es llevada a cabo por la vida de Jesús. Ahora bien,
esta vida es algo interno y espiritual que se revela en el alma,
por lo que el alma es renovada y sacada fuera de
la muerte (donde naturalmente ha estado por la caída),
y así es vivificada y resucitada para Dios.

Los apóstoles hablan frecuentemente de esta vida salvadora,
encomendado a todos los discípulos a la operación interna de su poder.
Pablo, en su despedida de los efesios, dice, "`Y ahora, hermanos, os encomiendo a Dios,
y a la palabra de su gracia,
que tiene poder para sobreedificaros y daros herencia con todos los santificados.`"^
footnote:[Hechos 20:32]
Y en su carta a los mismos,
habla de "`la supereminente grandeza de Su poder para con nosotros los que creemos.`"^
footnote:[Efesios 1:19]
Santiago dirige a sus lectores a "`la palabra implantada,
la cual puede salvar vuestras almas.`"^
footnote:[Santiago 1:21]
En otro lugar, Pablo escribe: "`aun estando nosotros muertos en pecados,
nos dio vida juntamente con Cristo (por gracia sois salvos),
y juntamente con él nos resucitó.`"^
footnote:[Efesios 2:5-6]
Ahora bien,
sin ninguna duda este "`dar de vida`" y "`resucitar
juntamente con él`" habla de la obra interna de renovación;
y por esta razón el apóstol menciona aquí que están siendo salvos por gracia,
la cual es la virtud y poder interno de Cristo en el alma.
El apóstol también habla de esto en 2 Corintios 4:10:
"`Para que también la vida de Jesús se manifieste
en nuestros cuerpos;`" y en el versículo 11:
"`Para que también la vida de Jesús se manifieste en nuestra carne mortal.`"
Y por esta vida interna de Jesucristo revelado y formado en nosotros
(como se observó anteriormente) es que "`somos salvos.`"

Además, la verdad de que somos justificados por esta revelación de Jesucristo,
y por la nueva creación engendrada en nosotros,
se muestra de manera evidente a partir de esa excelente
afirmación del apóstol en Tito 3:5:
"`Por su misericordia nos salvó,
por el lavamiento de la regeneración y por la renovación en el Espíritu Santo,
el cual derramó en nosotros abundantemente por Jesucristo nuestro Salvador,
para que justificados por su gracia,
viniésemos a ser herederos conforme a la esperanza de la vida eterna.`"
Así pues, es evidente que aquello que nos salva también es lo que nos justifica,
siendo estas palabras casi sinónimas en este respecto.
Aquí el apóstol establece claramente que la causa inmediata
de la justificación es esta obra interna de regeneración,
la cual es Jesucristo revelado y formado en el alma;
porque indudablemente este lavamiento de la regeneración es el poder y virtud
interior por el que el alma es lavada y revestida de la justicia de Cristo,
a fin de que sea preparada para presentarse delante de Dios.

Esta doctrina también se manifiesta en 2 Corintios 13:5--"`Examinaos
a vosotros mismos si estáis en la fe;
probaos a vosotros mismos.
¿O no os conocéis a vosotros mismos, que Jesucristo está en vosotros,
a menos que estéis reprobados?`"
En primer lugar,
aquí se muestra con cuánto fervor el apóstol quería
que ellos conocieran a Cristo dentro de ellos,
porque les insiste tres veces con esta exhortación. En segundo lugar,
establece como la causa de la reprobación (o de no ser justificados)
que Cristo no sea revelado y conocido internamente en el alma.
Y, por lo tanto, debe concluirse lo siguiente:
que las personas que conocen a Cristo internamente,
y están sujetas a Él en sus corazones, son aprobadas y justificadas.
Nada podría ser más claro que esto; porque si tenemos que conocer a Cristo en nosotros,
para no estar reprobados (o ser personas no justificadas),
entonces los que _sí_ lo conocen en ellos _no_ están reprobados,
y por ende son personas justificadas.
Por esta razón, el mismo apóstol dice: "`Hijitos míos,
por quienes vuelvo a sufrir dolores de parto,
hasta que Cristo sea formado en vosotros,`"^
footnote:[Gálatas 4:19]
y usa también este lenguaje--"`Cristo en vosotros, la esperanza de gloria.`"^
footnote:[Colosenses 1:27-28]

Ahora bien, al insistir en esta obra interna, no pretendemos, en lo absoluto,
negar que el origen y la causa fundamental de nuestra justificación es el amor
de Dios que fue manifestado por la aparición de Jesucristo en la carne,
quien, por Su vida, muerte, sufrimientos y obediencia,
abrió un camino para nuestra reconciliación,
al volverse un sacrificio por la remisión de los pecados pasados.
Sin embargo, "`por la justicia de uno vino la gracia a todos los hombres,`"^
footnote:[Romanos 5:18 RVG, RV1602P]
porque Él compró para nosotros Su Semilla y Gracia
de la cual surge este nacimiento interior,
y en la cual Jesucristo es recibido, formado y engendrado internamente en nosotros,
en Su propia imagen pura y santa de justicia.
Solo por esto nuestras almas viven para Dios, y son revestidas y cubiertas con Él,
tal como lo dice la Escritura (Efesios 4:23-24;
Gálatas 3:27). Estamos justificados y somos salvos en y por Él,
y por Su Espíritu y gracia (Romanos 3:24; 1 Corintios 6:11;
Tito 3:7). De este modo somos hechos partícipes de la plenitud de Sus méritos,
y ciertamente, Su sangre purificadora está cerca para lavar todo pecado y debilidad,
y para sanar todas nuestras rebeliones cada vez que nos volvemos a Él
con un arrepentimiento sincero para ser renovados por Su Espíritu.

Por lo tanto,
los que encuentran a Cristo resucitado y gobernando de esta manera en ellos,
tienen un verdadero motivo de esperanza para creer que están justificados por Su sangre.
Pero que nadie se engañe a sí mismo,
como para darse aliento con una vana esperanza o confianza de que
por la muerte y sufrimientos de Cristo están justificados,
aun cuando "`el pecado está a su puerta,`"^
footnote:[Génesis 4:7]
la iniquidad todavía prevalece,
y sus corazones permanecen sin ser renovados ni regenerados--no
sea que al final les sea dicho:
"`Nunca os conocí; apartaos de Mí.`"^
footnote:[Mateo 7:23]
Recordemos esa declaración de Cristo: "`No todo el que me dice: Señor, Señor,
entrará en el reino de los cielos,
sino el que hace la voluntad de mi Padre que está en los cielos.`"^
footnote:[Mateo 7:21]
Y con esto consideren esas excelentes afirmaciones del discípulo amado: "`Hijitos,
nadie os engañe; el que hace justicia es justo, como él es justo.
El que practica el pecado es del diablo.`"^
footnote:[1 Juan 3:7-8]
Y "`si nuestro corazón nos reprende, mayor que nuestro corazón es Dios,
y él sabe todas las cosas.`"^
footnote:[1 Juan 3:20]

Muchos protestantes famosos dan testimonio de esta justificación
por medio de Cristo revelado y formado internamente en el hombre.
Martin Borrahus dice, "`La forma de nuestra justificación es la justicia divina misma,
por la cual somos hechos justos y buenos.
Este es Jesucristo,
quien es llamado '`justicia nuestra,`' en parte por el perdón de pecados,
y en parte por la renovación y la restauración de esa integridad
que se perdió por la caída del primer Adán,
y es así que nos revestimos del nuevo y celestial Adán, de lo cual el apóstol habla:
'`de Cristo estáis revestidos.`'`"^
footnote:[En Gen, pagina 181]
Zwingli también dice, "`La santificación del Espíritu es la verdadera justificación,
esto es lo único que es suficiente para justificar.`"^
footnote:[En su epístola a la princesa de Alemania, como fue citada por Himelius, c. vii., p. 60.]
Estius, comentando 1 Corintios 6:11, dice: "`Pablo,
para que no se piense que la justicia cristiana consiste en el lavamiento solamente,
es decir, en la remisión de los pecados, añade el otro grado o parte,
'`ya habéis sido santificados;`' es decir, han alcanzado la pureza,
de modo que ahora son verdaderamente santos delante de Dios.
Por último, expresando la suma del beneficio recibido en una sola palabra,
que incluye ambas partes, el apóstol añade:
'`ya habéis sido justificados en el nombre del Señor Jesús,
y por el Espíritu de nuestro Dios.`'`" Y, por último, Richard Baxter,
el famoso predicador inglés, dice:
"`Algunos miserables ignorantes crujen sus dientes ante esta doctrina,
como si se tratara de puro catolicismo romano,
no entendiendo la naturaleza de la justicia del nuevo pacto;
la cual procede completamente de Cristo dentro de nosotros,
y es forjada por el poder del Espíritu de Cristo en nosotros.`"^
footnote:[En su libro llamado [.book-title]#Aphorisms of Justification#
(Aforismos de la Justificación), p. 80]

=== La Necesidad de las Buenas Obras

La tercera cosa que debemos considerar son las buenas obras,
las cuales (como hemos dicho) fluyen naturalmente de este nacimiento espiritual,
como el calor del fuego, y, por lo tanto,
son de absoluta necesidad para la justificación--__no como la causa__ de la justificación,
sino como aquello en lo que somos justificados,
y sin lo cual no podemos ser justificados.

Supongo que ya se ha sido dicho lo suficiente para librarnos de cualquier
acusación de ser similares a los católicos romanos en este asunto.
Pero si alguien preguntara,
si nosotros afirmamos que el hombre es justificado por las obras,
le respondo lo siguiente:
Espero que ninguno se ofenda si en este asunto usamos
el lenguaje claro de las Sagradas Escrituras,
que dicen expresamente: (Santiago 2:24) "`Vosotros veis, pues,
que el hombre es justificado por las obras, y no solamente por la fe.`"
No necesito ofrecer una prueba de la verdad de esta afirmación,
ya que lo que dice el apóstol en este capítulo es suficiente para convencer
a cualquier hombre que solo esté dispuesto a leerlo y creerlo.
Por lo tanto, solo extraeré este único argumento:

[.discourse-part]
_Argumento:_ Si ningún hombre puede ser justificado sin fe,
y si no hay fe que pueda considerarse viva o adecuada sin obras,
entonces las obras son necesarias para la justificación.

Esta verdad es tan clara y evidente en las Escrituras que podríamos
transcribir la mayoría de los preceptos del Evangelio para demostrarla.
Voy a citar unos pocos que afirman el asunto en cuestión con tanta
claridad que no se necesita ningún comentario ni más demostración,
y, luego, responderé las objeciones comunes que se hacen en contra de esto.
Hebreos 12:14, "`Seguid la paz con todos, y la santidad,
sin la cual nadie verá al Señor;`" Mateos 7:21, "`No todo el que me dice: Señor, Señor,
entrará en el reino de los cielos,
sino el que hace la voluntad de mi Padre que está en los cielos;`" Juan 13:17,
"`Si sabéis estas cosas, bienaventurados seréis si las hiciereis;`" 1 Corintios 7:19,
"`La circuncisión nada es, y la incircuncisión nada es,
sino el guardar los mandamientos de Dios;`" Apocalipsis 22:14,
"`Bienaventurados los que hacen sus mandamientos,
para que tengan derecho al árbol de la vida,
y que entren por las puertas en la ciudad;`"^
footnote:[RV1602P]
Ciertamente, se podrían dar muchos más como ejemplos, de todo lo cual argumento:

[.discourse-part]
_Argumento:_
Si solo aquellos que hacen la voluntad del Padre pueden entrar en el reino de los cielos;
si solo aquellos que hacen los mandamientos de Cristo son
considerados edificadores prudentes y bienaventurados;
si ninguna observación externa es de provecho, sino el guardar los mandamientos;
y si solo aquellos que hacen sus mandamientos tienen derecho al Árbol de la Vida,
y entran por las puertas a la ciudad;
entonces las obras son absolutamente necesarias para la salvación y la justificación.

[.discourse-part]
Objeción:
Pero ellos objetan que las obras no son necesarias para la justificación
debido a esa afirmación de Cristo en Lucas 17:10:
"`Cuando hubiereis hecho todo lo que os es mandado, decid: Siervos inútiles somos;`" etc.

[.discourse-part]
Respuesta: En cuanto a Dios ciertamente somos inútiles, porque Él no necesita nada,
y no podemos añadirle nada.
Pero en cuanto a nosotros mismos no somos inútiles,
de lo contrario podría decirse que a un hombre no
le es de provecho guardar los mandamientos de Dios,
lo cual es muy absurdo y contradiría la doctrina de Cristo a lo largo de las Escrituras.
Y, les pregunto, esos hombres que incrementaron sus talentos,
¿no fueron declarados "`siervos buenos y fieles`" por Cristo?^
footnote:[Mateo 25:14-23]
¿No les fue de provecho a ellos el haberlos incrementado?
Está escrito de aquel que escondió su talento y no lo incrementó:
"`echadle en las tinieblas de afuera.`"
Si no haber logrado incrementar el talento hizo a este hombre inútil,
entonces que los demás hayan incrementado sus talentos
verdaderamente los hizo siervos útiles,
especialmente cuando vemos cómo Cristo habló de ellos: "`Bien, buen siervo y fiel;
sobre poco has sido fiel, sobre mucho te pondré; entra en el gozo de tu Señor.`"^
footnote:[Mateo 25:23]

[.discourse-part]
Objeción: En segundo lugar, ellos objetan a partir de esos dichos del apóstol Pablo,
en los que excluye las obras de la ley de la justificación: tales como Romanos 3:20,
"`ya que por las obras de la ley ningún ser humano
será justificado delante de él,`" y verso 28,
"`Concluimos, pues, que el hombre es justificado por fe sin las obras de la ley.`"

[.discourse-part]
Respuesta: En respuesta a esta objeción, digo lo siguiente:
hay una gran diferencia entre las obras de la Ley,
y las obras de la gracia o del Evangelio.
Las primeras están excluidas, las segundas no, al contrario, son necesarias.
Las primeras se realizan en la voluntad propia del hombre y por su fuerza,
conforme a la ley y letra externa,
y por lo tanto son obras propias e imperfectas del hombre,
o las obras de la Ley que no perfeccionan nada.^
footnote:[Hebreos 7:19]
Y todas las ceremonias, purificaciones,
lavamientos y tradiciones de los judíos son de este tipo de obras.
El segundo tipo de obras son las del Espíritu de Gracia en el corazón,
realizadas conforme a la ley interna y espiritual.
Estas obras no son hechas en la voluntad del hombre, ni por su poder y habilidad,
sino en y por el poder y Espíritu de Cristo en nosotros,
y por lo tanto son puras y perfectas de acuerdo a su género.
De hecho, estas podrían ser llamadas las obras de Cristo,
porque Él es el autor y hacedor inmediato de ellas.^
footnote:[Véase Hebreos 13:20-21; Filipenses 1:11, 2:13]
Y nosotros afirmamos que las obras de este tipo son necesarias para la justificación,
de modo que un hombre no puede ser justificado sin ellas;
porque toda fe que no las tenga es muerta e inútil, como dice el apóstol Santiago.

Ahora bien, al considerar el contexto de estas afirmaciones,
aparece claramente que existe una distinción entre
las obras de la Ley y las obras de la gracia;
y también que el apóstol excluye las primeras de la justificación, pero no las segundas.
Porque en ambas de sus cartas a los romanos y a los gálatas donde habla sobre esto,
encontramos que muchos de los gentiles (que no eran de la semilla
de Abraham según la carne) se habían convertido a la fe cristiana,
y llegado a creer en Él. Sin embargo,
algunos de los judíos que se habían convertido a la fe intentaban hacer que los creyentes
gentiles se sujetaran a las ceremonias y observaciones legales de la Ley,
insistiendo en que éstas eran necesarias para su justificación.
Esto le dio al apóstol Pablo la oportunidad de demostrar de manera
amplia el uso y la tendencia de la Ley y de sus obras,
y de distinguirlas de la fe de Cristo y de la justicia de dicha fe,
mostrando que las obras de la Ley habían cesado y se habían hecho ineficaces,
pero que las obras de la gracia permanecían, y eran necesarias.
Y el tipo de obras que el apóstol excluyó es evidente
por toda la tendencia de su epístola a los gálatas.
Porque en el cuarto capítulo,
los reprende por volverse a la observación de días y de tiempos,^
footnote:[Gálatas 4:10-11]
y en el quinto y sexto les muestra la locura de aferrarse a la ceremonia de la circuncisión,
diciendo: "`Porque en Cristo Jesús ni la circuncisión vale algo, ni la incircuncisión,
sino la fe que obra por el amor.`"^
footnote:[Gálatas 5:6]
Y "`Porque en Cristo Jesús ni la circuncisión vale nada, ni la incircuncisión,
sino una nueva creación.`"^
footnote:[Gálatas 6:15]
Ahora bien, la palabra circuncisión a menudo se usa para abarcar todo el antiguo pacto,
incluyendo sus ritos ceremoniales y legales.
Pablo dice que estas obras de la Ley están excluidas,
y que por ellas ningún hombre es justificado; pero que la fe que obra por amor,
o la nueva creación, _esto_ es lo que vale y verdaderamente es necesario.
Ahora bien,
en este mismo lugar se muestra que el apóstol de ninguna
manera intenta excluir las buenas obras de la nueva creación,
porque él les dice claramente: "`No os engañéis; Dios no puede ser burlado:
pues todo lo que el hombre sembrare,
eso también segará. Porque el que siembra para su carne, de la carne segará corrupción;
mas el que siembra para el Espíritu, del Espíritu segará vida eterna.
No nos cansemos, pues, de hacer bien; porque a su tiempo segaremos, si no desmayamos.`"^
footnote:[Gálatas 6:7-9]
¿No manifiesta esto claramente cuán necesarias son estas buenas obras?
--no las ceremonias y tradiciones externas de la Ley,
sino los frutos del Espíritu mencionados un poco antes (4:22).
Pablo deseaba que todos ellos fuesen guiados por este mismo Espíritu,
en el cual quería que todos caminaran.
Las primeras son "`obras de justicia que nosotros hemos
hecho,`" realizadas en nuestra primera naturaleza caída,
por nuestra propia fuerza, en actos religiosos.
Las últimas son los frutos del "`lavamiento de la regeneración,
y de la renovación del Espíritu Santo.`"^
footnote:[Véase Tito 3:5]

[.discourse-part]
Objeción: Pero estas obras del Espíritu podrían también llamarse nuestras,
porque son hechas en nosotros, y muchas veces por nosotros también como instrumentos.

[.discourse-part]
Respuesta: Aun así,
los dos tipos de obras difieren ampliamente entre sí. En el primero
tipo aún estamos vivos en nuestro propio estado natural,
sin ser renovados, obrando por nosotros mismos,
buscando salvarnos a nosotros mismos imitando y tratando
de conformarnos a la letra externa de la Ley,
y por lo tanto esforzándonos y luchando en la mente carnal que es enemistad contra Dios,^
footnote:[Romanos 8:7 RV1602P]
y en esa voluntad condenada que aún no ha sido sometida.
Pero en el segundo tipo, estamos "`crucificados juntamente con Cristo,`"^
footnote:[Gálatas 2:20]
habiendo "`muerto con Él,`"^
footnote:[Romanos 6:3]
siendo participes de "`la comunión de Sus padecimientos,`"
y "`hechos conforme a Su muerte.`"^
footnote:[Filipenses 3:10 RV1602P]
Aquí nuestro primer hombre,
nuestro "`viejo hombre`" es enterrado y clavado en la cruz de Cristo,
junto "`con sus hechos`"^
footnote:[Colosenses 3:9]
(tanto los que son abiertamente inicuos como los que tienen la apariencia de justos),
y por lo tanto ya no somos nosotros sino Cristo vivo en
nosotros--el que hace las obras viviendo en nosotros.
De modo que, aunque en cierto sentido las obras son nuestras, sin embargo,
es en el mismo sentido del apóstol en Gálatas 2:20,
"`Con Cristo estoy juntamente crucificado, y ya no vivo yo, mas vive Cristo en mí`" o,
"`he trabajado más que todos ellos; pero no yo, sino la gracia de Dios conmigo.`"^
footnote:[1 Corintios 15:10]
Estas obras indudablemente deben atribuirse al Espíritu
de Cristo y a la gracia de Dios en nosotros,
como siendo hechas,
habilitadas o guiadas inmediatamente por Él. Y esta
manera de hablar no es para nada extraña,
más bien era familiar para los apóstoles, como a menudo aparece en las Escrituras:
como en Gálatas 2:8:
"`Porque el que obró eficazmente en Pedro para el apostolado de la circuncisión,
obró también en mí para con los Gentiles:`"^
footnote:[RV1602P]
o, "`porque Dios es el que en vosotros produce así el querer como el hacer,
por su buena voluntad,`"^
footnote:[Filipenses 2:13]
etc.

[.discourse-part]
Objeción: Algunos objetan que ninguna obra, ni siquiera las obras de Cristo en nosotros,
pueden tener lugar en la justificación,
porque nada que sea impuro puede ser útil en ella;
y todas las obras que se hagan en nosotros son impuras.
Para probar esto, ellos alegan esa afirmación del profeta Isaías:
"`todas nuestras justicias son como trapo de inmundicia;`"^
footnote:[Isaías 64:6]
añadiendo el siguiente razonamiento: puesto que somos impuros,
entonces nuestras obras deben serlo también; porque incluso las obras de Dios,
cuando son ejecutadas por nosotros, reciben una mancha de impureza,
así como el agua limpia se contamina cuando pasa a través de una tubería sucia.

[.discourse-part]
Respuesta: Confesamos que ninguna obra impura es útil para la justificación;
pero negamos que todas las obras hechas en los santos sean impuras.
Y la distinción mencionada anteriormente entre los dos tipos de obras,
también nos servirá aquí para responder a esta objeción. Porque
nosotros confesamos que las obras del primer tipo son impuras;
pero no las del segundo--porque en el primer tipo,
las obras son hechas por el hombre en el estado no regenerado,
pero en el otro son hechas por el Espíritu y gracia de Dios.
Y en cuanto a esa escritura de Isaías, debe referirse al primer tipo; porque,
aunque él dice: "`nuestras justicias son como trapo de inmundicia,`" aun así,
esto no incluye la justicia de Cristo forjada en nosotros,
sino solo aquella que nosotros obramos en nuestra propia fuerza y por nosotros mismos.
Porque si fuese lo contrario,
entonces tendríamos que desechar toda santidad y justicia como trapo de inmundicia,^
footnote:[Literalmente "`una prenda menstrual`"]
incluso los frutos del Espíritu, mencionados en Gálatas 5. Pero, contrario a esto,
está escrito que algunas de las obras de los santos han
sido un "`olor fragante en las narices del Señor;`"^
footnote:[Filipenses 4:18; 2 Corintios 2:15]
y un "`adorno de grande estima delante de Dios;`"^
footnote:[1 Pedro 3:4 RV1602P]
y está escrito de dichas obras que "`prevalecen con Él,`" y son "`aceptables para Él;`"^
footnote:[Véase Romanos 12:1-2, 14:18; Filipenses 4:18; 1 Timoteo 2:3, 5:4; 1 Pedro 2:5,
2:30.]
y esto no se puede decir de un trapo de inmundicia (como
muchos protestantes famosos han reconocido).

En cuanto a la otra parte de esta objeción--que puesto que
los mejores hombres siguen siendo impuros e imperfectos,
por lo tanto, sus obras también deben serlo--esto envuelve una gran suposición,
una que nosotros negamos,
como se discutirá ampliamente en la siguiente proposición. Sin embargo,
incluso en el caso de un hombre que no es completamente perfecto en todos los aspectos,
esto no impide que las obras buenas o perfectas (de acuerdo
a su tipo) se engendren en él por el Espíritu de Cristo;
tampoco da en el blanco el ejemplo del agua pasando por una tubería sucia;
porque aunque el agua se puede contaminar con la suciedad, el Espíritu de Dios no,
y nosotros afirmamos que dicho Espíritu es el Autor inmediato de
esas obras que tienen valor en la justificación. En consecuencia,
decimos que las obras de Jesucristo en Sus hijos son puras y perfectas,
y que Él obra en y a través de esa cosa pura de Su propia hechura y creación en ellos.

Además, si la suposición de nuestros adversarios fuera cierta,
entonces tendríamos que concluir que los mismos milagros y obras de los apóstoles,
que Cristo obró en ellos y que ellos hicieron en y por el Poder,
Espíritu y Gracia de Cristo, también fueron impuros e imperfectos.
Y, de hecho,
¿no tendríamos que concluir también que los textos de las Sagradas Escrituras (que nuestros
adversarios parecen magnificar tanto) deben necesariamente ser impuros e imperfectos,
habiendo pasado a través de vasijas impuras e imperfectas?

Pero, por último,
debido a que aquí parece apropiado mencionar algo
respecto al mérito y la recompensa de las obras,
añadiré algo en este lugar de nuestro entendimiento
y creencia en lo concerniente a este asunto.
Estamos lejos de pensar o creer que el hombre merece algo de Dios por sus obras,
porque en verdad todo es por la gracia gratuita,
y por ende siempre hemos negado la imaginación católica de __meritum ex condigno.__^
footnote:[Nota del Editor: __Meritum ex condigno,__
es la doctrina católica romana que afirma que hay un mérito intrínseco en las obras,
que Dios, si actúa de manera justa, no puede evitar recompensar con la vida eterna.]
Sin embargo, no podemos sino reconocer, que Dios,
por Su infinita bondad con la que ha amado a la humanidad,
después de haberles comunicado Su Santa Gracia y Espíritu, según su propia voluntad,
también recompensa y premia las buenas obras de Sus hijos.
Y, por lo tanto, no podemos negar que existe una especie de recompensa merecida,
en el sentido en que las Escrituras lo afirman de manera clara y positiva.
Porque la misma palabra griega _axion,_
que significa "`mérito,`" se encuentra en esos lugares donde los
traductores la expresan como "`digno,`" (como en Mateos 3:8;
1 Tesalonicenses 2:12; 2 Tesalonicenses 1:5, 11.)

Aquellos que son llamados los Padres de la iglesia frecuentemente
usaban la palabra "`mérito`" de esta manera,
y muchos protestantes no se han mostrado opuestos
a dicha palabra en el sentido en que la usamos.
La Apología de la Confesión de Augusto, art.
20, tiene estas palabras:
"`Estamos de acuerdo con que las obras son verdaderamente meritorias,
no de la remisión de los pecados o de la justificación;
sino meritorias de otras recompensas tanto naturales como espirituales,
que se experimentan tanto en esta vida como en la por venir.`"
G+++.+++ Voss, en su tesis teológica respecto a los méritos de las buenas obras, dice;
"`No hemos ido tan lejos como para condenar por completo la palabra '`mérito,`'
pues es una palabra que muchos de los antepasados han usado,
y que también aparece en las confesiones de las iglesias reformadas.
Ahora bien,
el hecho de que Dios juzga y acepta a los hombres de acuerdo con sus obras es
indudable para cualquiera que lea y considere seriamente las siguientes escrituras:
Mateos 16:27; Romanos 2:6-7, 10; 2 Corintios 5:10; Santiago 1:25; Hebreos 10:36;
1 Pedro 1:17; Apocalipsis 22:12.

=== Conclusión

Para concluir este tema: que nadie sea tan osado como para pretender burlarse de Dios,
suponiéndose justificado y aceptado ante Sus ojos
en virtud de la muerte y sufrimientos de Cristo,
mientras permanece sin santificación y sin justificación en su propio corazón,
y contaminado en sus pecados--no sea que su esperanza termine siendo la del hipócrita,
que perece.^
footnote:[Job 8:13]
Y, por otro lado, que nadie imagine tontamente que puede, por sus propias obras,
o por la realización de algunas ceremonias o tradiciones, o por dar dinero,
o por un duro trato de su cuerpo en un culto voluntario y en una humildad falsa,
o por tontamente esforzarse por cumplir la letra externa de la ley,
halagarse a sí mismo pretendiendo que merece algo delante de Dios,
o que Dios está en deuda con él. De hecho,
que nadie piense que los hombres tienen poder para
hacer que esas cosas sirvan para justificarlos,
no sea que sean hallados como los que tontamente se jactan
y al mismo tiempo son extraños a Cristo y a Su Justicia.
Pero son bienaventurados por siempre aquellos que verdaderamente
han sentido su propia indignidad y pecaminosidad,
y han visto que todos sus propios esfuerzos y obras son inútiles y vanos.
Sí, bienaventurados aquellos que han contemplado su propio vacío,
y la vanidad de su propia esperanza, fe, y confianza, siendo compungidos,
perseguidos y condenados internamente por el testigo santo de Dios en sus corazones.
Porque estos, habiéndose entregado a este testigo interno,
y permitido que Su gracia obre en ellos,
han sido transformados y renovados en el espíritu de su mente,
han pasado de muerte a vida, y han llegado a experimentar a Jesús resucitado en ellos,
produciendo tanto el querer como el hacer.
Estos en verdad se han "`vestidos del Señor Jesucristo,`"^
footnote:[Romanos 13:14]
y están cubiertos con Él, y participan de Su justicia y naturaleza,
y por lo tanto pueden acercarse al Señor con confianza,
sabiendo que son aceptos en y por Aquel en quien el Padre tiene complacencia.
