== Capítulo VI. Respecto a la Perfección

Puesto que hemos establecido que la justificación
se obtiene al experimentar a Jesucristo siendo revelado,
formado y engendrado en el corazón--haciendo allí Sus obras de justicia y produciendo
los frutos del Espíritu--ahora nos corresponde responder la siguiente pregunta:
¿Qué tanto puede Él prevalecer en nosotros mientras estamos en esta vida?
O ¿Qué tanto podemos prevalecer sobre los enemigos de nuestra alma, en y por Su fuerza?

Aquellos que abogan por una justificación que se
realiza por un acto de Dios fuera de ellos,
mediante una justicia imputada,
(negando la necesidad de ser revestidos de justicia de manera real e interna)
consecuentemente afirman que es "`imposible`" que un hombre,
incluso "`el mejor de los hombres, sea libre de pecado en esta vida,
lo cual,`" dicen ellos, "`nunca ha sucedido.`"
Por el contrario, insisten en que nadie puede, "`ni por sí mismo,
ni por ninguna gracia que se reciba en esta vida +++[+++¡Oh perverso
dicho contra el poder de la Gracia de Dios!],
guardar perfectamente los mandamientos de Dios,
sino que todo hombre quiebra los mandamientos de Dios en pensamiento, palabra y obra.`"^
footnote:[Estas son las palabras del Catecismo de Westminster (versión completa).]
A partir de esto ellos también afirman (como se observó anteriormente):
que hasta las mejores acciones de los santos, incluso sus oraciones y su adoración,
son impuras y están contaminadas.

Ahora bien,
nosotros reconocemos libremente que esto es cierto
con respecto al hombre natural y caído,
en su primer estado, cualesquiera que sean sus creencias o pretensiones,
siempre que permanezca en un estado no convertido y no regenerado.
Sin embargo, creemos que, para aquellos en quienes Cristo llega a formarse,
y en quienes el nuevo hombre es engendrado y nacido de la semilla incorruptible,
es posible mantenerse en la voluntad de Dios de tal manera
que no sean hallados transgrediendo diariamente Su ley,
ya que ese nacimiento (y el hombre en unión con él)
naturalmente hace la voluntad de Dios.
Y, para establecer de manera más clara la controversia, téngase en cuenta lo siguiente:

Primero,
que esta posibilidad no se encuentra en la voluntad y capacidad propias del hombre,
como un hombre, como hijo del Adán caído, o como en su estado natural,
sin importar cuán sabio o docto sea,
o cuán dotado esté del conocimiento intelectual y literal de Cristo,
tratando por sí mismo de conformarse a la letra de la ley externa.

Segundo, le atribuimos esto completamente al hombre cuando es nacido de nuevo,
renovado en su mente, resucitado por Cristo; cuando experimenta a Cristo viviendo,
reinando y gobernando en él, guiándolo y dirigiéndolo por Su Espíritu,
y revelando en él la ley del Espíritu de vida--que
no solo manifiesta y reprende el pecado,
sino que también da poder para salir de él.

Tercero,
con esto no nos referimos a un tipo de perfección que no permita un crecimiento diario,
y, por lo tanto, no queremos decir que llegamos a ser tan puros,
santos y perfectos como Dios en Sus atributos divinos de sabiduría,
conocimiento y pureza.
Mas bien, hablamos de una perfección proporcional y adecuada a la medida del hombre,
mediante la cual somos guardados de transgredir la ley de Dios
y capacitados para responder lo que Él requiera de nosotros.
Así como un poquito de oro es tan perfecto (según su género) como una gran cantidad,
y así como un niño tiene un cuerpo tan perfecto como el de un hombre,
aunque cada día crece más y más. De la misma manera,
se dice que Cristo (Lucas 2:52) "`crecía en sabiduría y en estatura,
y en gracia para con Dios y los hombres,`" aunque nunca había pecado antes de ese tiempo,
y sin duda, en un sentido verdadero y correcto, era perfecto.

Cuarto,
aunque un hombre puede experimentar esto por un tiempo
(y por lo tanto todos deben esforzarse por ello),
sin embargo, aquellos que lo han alcanzado en medida, pueden,
por las artimañas y las tentaciones del enemigo, caer en iniquidad,
y a veces perderlo si no son vigilantes y si no se aferran con diligencia
a esa Semilla de Dios en el corazón. Y no dudamos que muchos hombres buenos
y santos han tenido algunos altos y bajos de este tipo,
porque, aunque todo pecado debilita a un hombre en cuanto a su condición espiritual,
aun así, no necesariamente lo destruye por completo,
o lo hace incapaz de levantarse otra vez.

Por último,
aunque afirmo que después de que un hombre ha llegado
a dicha condición en la que está libre de pecado,
aun así, puede caer y pecar de nuevo, sin embargo,
no voy a negar que existe un estado alcanzable en esta vida,
en el cual hacer justicia se vuelva tan natural para el alma regenerada,
que en la estabilidad de esta condición no puede pecar.
Otros quizás puedan hablar con mayor certeza de este estado,
si han llegado a él. Con respecto a mí mismo, hablaré modestamente,
reconociendo que no he llegado.
Sin embargo, no me atrevo a negar que exista tal estado,
porque el apóstol lo afirma tan claramente en las siguientes palabras:
"`Todo aquel que es nacido de Dios, no practica el pecado,
porque la simiente de Dios permanece en él; y no puede pecar,
porque es nacido de Dios.`"^
footnote:[1 Juan 3:9]

Habiendo, pues, establecido la controversia,
primero procederé a demostrar cuán absurda es esa doctrina
que aboga por el pecado durante toda la vida,
incluso en los santos.
En segundo lugar,
probaré nuestra doctrina de la perfección a partir
de muchos testimonios claros de las Sagradas Escrituras.
Y, por último, responderé los argumentos y objeciones de nuestros adversarios.

=== La Locura de Contender por el Pecado

Primero,
la doctrina que establece que los santos nunca podrán ser libres de pecar en esta vida,
es inconsistente con la sabiduría de Dios y con Su glorioso poder y majestad,
quien es "`de ojos demasiado puros para mirar el mal,
y no puede contemplar la iniquidad.`"^
footnote:[Habacuc 1:13 Versión Moderna H.B. Pratt (1929)]
Porque Aquel que se propuso en Sí mismo reunir a
un pueblo para que lo adore en Espíritu y en verdad,
y para que dé testimonio de Él en la tierra,
sin duda es capaz de santificarlos y purificarlos.
Dios no se deleita en la iniquidad, más bien aborrece la transgresión,
y aunque Él considera al hombre en la transgresión (hasta el punto de
compadecerse de él y proporcionarle un medio para salir de ella) sin embargo,
Dios no se deleita en el hombre mientras permanece en ese estado.
Porque si los hombres siempre tienen que permanecer unidos a su pecado,
entonces Dios siempre estará distanciado de ellos, como está escrito (Isaías 59:2),
"`vuestras iniquidades han hecho división entre vosotros y vuestro Dios,
y vuestros pecados han hecho ocultar de vosotros su rostro.`"
De hecho, está escrito expresamente que no hay "`comunión entre la luz y las tinieblas.`"^
footnote:[2 Corintios 6:14]
Ahora bien, Dios es Luz, y cada pecado es tinieblas en una medida.
Entonces, ¿qué podría manchar más la sabiduría de Dios,
que decir que Él carece de un medio por el cual Sus
hijos podrían servirlo y adorarlo perfectamente;
o que no ha provisto una manera por la cual podrían dejar de servir al diablo?
Porque "`el que hace pecado, esclavo es del pecado,`"^
footnote:[Juan 8:34; Romanos 6:16]
y cada pecado es un acto de servicio y obediencia al diablo.
Entonces, si los santos no pueden dejar de pecar diariamente, en pensamiento,
palabra y obra,
y si su servicio mismo a Dios está mezclado con pecado (como insisten nuestros oponentes),
entonces sin duda ¡sirven al diablo tanto o más de lo que sirven al Señor!

Ahora bien, ¿qué maestro entre los hombres no sería considerado necio,
que a pesar de estar dispuesto y ser capaz de proporcionar un camino
por el cual sus hijos y siervos podrían servirlo enteramente,
aun así, se niega a hacerlo,
y en lugar de eso permite que sus siervos sirvan
con más fidelidad y plenitud a su enemigo directo?
Entonces ¿qué deberíamos pensar de una doctrina que
inferiría esta locura acerca del omnipotente,
único y sabio Dios?

En segundo lugar, esta doctrina es inconsistente con la justicia de Dios.
Porque, dado que Dios requiere que Sus hijos sean puros,
y con frecuencia les ordena que se abstengan de toda iniquidad (como se verá más adelante);
y puesto que Su "`ira se revela contra toda impiedad e injusticia de los hombres,`"^
footnote:[Romanos 1:18]
por lo tanto,
debe necesariamente haberles dado a los hombres la capacidad de responder a Su voluntad;
de lo contrario, Él requiere más del poder que ha dado para hacer.
De hecho, esto sería declararlo abiertamente injusto, y decir con el siervo negligente,
"`¡Tú eres un maestro duro!`"
Anteriormente hemos hablado de la injusticia que nuestros oponentes le atribuyen a Dios,
al alegar que Él condena a los impíos sin jamás haberles
proporcionado los medios para que sean salvos.
Pero esta es una acusación aún más irracional e inconsistente:
decir que Dios no quiere proporcionarles a Sus propios escogidos (a quienes
ellos confiesan que Él ama) los medios para agradarlo.

¿Qué podría resultar de una doctrina tan extraña?
Esta imperfección en los santos o procede de Dios,
o de ellos mismos.
Si procede de ellos,
es porque quedan cortos en el uso del poder que se les da--la
gracia por la cual son hechos capaces de obedecer.
Pero si no viene de ellos mismos, entonces la imperfección debe ser de Dios,
quien no ha considerado apropiado conceder suficiente
gracia para responder a Su propio requerimiento.
Y, de nuevo, esto no es más que atribuirle a Dios la más grande injusticia,
¡decir que Él requiere que Sus hijos abandonen el pecado,
incluso cuando no les provee los medios para hacerlo!
Sin duda esto hace a Dios más injusto que los "`hombres
malos`" de quienes Cristo habló en Su sermón en el monte;
porque hasta ellos, cuando "`sus hijos les piden pan, no les darán una piedra,
o si les piden un pescado, no les darán una serpiente.`"^
footnote:[Mateo 7:9-11]
Y aunque nuestros adversarios dicen que todos deben
buscar poder de Dios para ser redimidos del pecado,
sin embargo, ellos creen y enseñan que nadie debe jamás esperar recibir tal poder.
¿No es esto hacer a Dios tan injusto con Sus hijos como Faraón lo fue con los Israelitas,
al exigirles ladrillo y no darles paja?
Pero bendito sea Dios,
Él no trata de esta manera a aquellos que verdaderamente confían y esperan en Él,
como estos hombres vanamente imaginan.
Porque los fieles verdaderamente encuentran que Su gracia es suficiente para ellos,
y saben cómo vencer al maligno por medio del don de Su poder y Espíritu.

En tercer lugar,
esta perversa doctrina es sumamente despectiva con respecto a Jesucristo,
y deroga en gran medida el poder y virtud de Su sacrificio,
quitando la eficacia de Su venida y ministerio.
Porque, una de las razones principales por las que Cristo vino en la carne,
fue eliminar el pecado y reunir a una generación
justa para poder servir al Señor con pureza de mente,
y caminar delante de Él en temor.
Fue Él quien "`trajo la justicia perdurable,`"^
footnote:[Daniel 9:24]
y la perfección del evangelio que la Ley no podía efectuar.^
footnote:[Véase Colosenses 1:28; Hebreos 7:19, 9:9, 10:1]
Por ende está escrito que Él "`se dio a sí mismo por nosotros para
redimirnos de toda iniquidad y purificar para sí un pueblo propio,
celoso de buenas obras.`"^
footnote:[Tito 2:14]
Estas palabras del apóstol ciertamente fueron dichas con respecto a los santos,
cuando todavía estaban en la tierra.
Pero contrario a esto,
nuestros adversarios afirman que nunca realmente seremos redimidos de toda iniquidad,
y por lo tanto anulan y dejan sin efecto el hecho de que Cristo "`se dio a Sí mismo
por nosotros,`" negando que Él realmente "`purifica para sí un pueblo propio.`"
Pero, pregunto,
¿Cómo puede un pueblo ser celoso de buenas obras cuando diariamente comete malas obras?
¿Y cómo es que aquellos que todavía viven en impureza y pecan continuamente,
son un pueblo purificado?
Está expresamente escrito que: "`El Hijo de Dios se manifestó con este propósito:
para destruir las obras del diablo,`"^
footnote:[1 Juan 3:8 LBLA]
y, "`sabéis que Él apareció para quitar nuestros pecados.`"^
footnote:[1 Juan 3:5]
Pero estos hombres dejan sin efecto este propósito,
porque ellos no están dispuestos a creer que el Hijo
de Dios destruye las obras del diablo en este mundo,
ni que Cristo apareció para quitar nuestros pecados,
puesto que abogan por una necesidad de vivir siempre en ellos.
Y para que nadie tuerza esta Escritura diciendo que
habla solo de quitar la _culpa_ del pecado,
el apóstol (como si tratara intencionalmente de evitar tal objeción) añade inmediatamente,
"`Todo aquel que permanece en él, no peca;`" e "`Hijitos, nadie os engañe;
el que hace justicia es justo, como él es justo.
El que practica el pecado es del diablo.`"^
footnote:[1 Juan 3:6-8]

Ahora bien,
si Cristo apareció para quitar el pecado ¿no es extraño cómo estos hombres revocaron
la doctrina de Cristo al decir que el pecado nunca es quitado aquí? Oh,
consideren ¿cuán ofensivo es esto con respecto a
la eficacia y poder de la aparición de Cristo?
¿No vino Cristo a sacar a un pueblo fuera del pecado para reunirlo en la justicia;
fuera del reino de Satanás para trasladarlo al reino del amado Hijo de Dios?
Y aquellos que son reunidos por Él ¿no se convierten en Sus siervos, Sus hijos,
Sus hermanos y Sus amigos?
De hecho, está escrito respecto a ellos que: "`como Él es, así son ellos en este mundo`"^
footnote:[1 Juan 4:17]
--santos, puros y sin mancha.
¿Y no continúa Cristo velando y orando por ellos,
apoyándolos y preservándolos con Su Poder y Espíritu,
andando en ellos y habitando entre ellos, así como el diablo, por el otro lado,
lo hace entre los reprobados?
¿Por qué los siervos de Cristo serían menos capaces de servir
a su Maestro que los siervos del diablo al suyo?
¿O es que Cristo no quiere que Sus siervos sean completamente puros (una blasfemia terrible,
y contraria a muchas escrituras)?
¿O que Cristo no es capaz, mediante Su poder,
de preservar y capacitar a Sus hijos para que le sirvan (una blasfemia igual de terrible)?
Porque ciertamente, si los santos pecan diariamente en pensamiento, palabra y obra,
como estos hombres afirman, entonces sirven al diablo diariamente,
y continúan sujetos a su poder, y por lo tanto él prevalece más en ellos que Cristo,
y los mantiene en esclavitud, incluso en contra de la voluntad de Cristo.
Pero esto contradice grandemente el propósito de la venida de Cristo,
porque el apóstol dice: "`Así como también Cristo amó a la iglesia,
y se entregó a sí mismo por ella; para santificarla,
purificándola en el lavamiento del agua por la palabra,
para que la presentase a sí mismo, iglesia gloriosa, que no tuviese mancha, ni arruga,
ni cosa semejante; sino que fuese santa y sin mancha.`"^
footnote:[Efesios 5:25-27 RV1602P]
Ahora bien, si Cristo realmente cumplió el propósito por el cual vino,
entonces los miembros de Su cuerpo no tienen que estar pecando siempre en pensamiento,
palabra y obra.
De lo contrario, no hay diferencia entre el santificado y el que no ha sido santificado,
entre el limpio y el inmundo, el santo y el impío,
entre aquel que diariamente es manchado con pecado y aquel que no tiene mancha.

En cuarto lugar, esta doctrina hace que la obra del ministerio,
la predicación de la Palabra,
los textos de la Escrituras y las oraciones de los
hombres santos sean completamente inútiles e ineficaces.
En cuanto a lo primero (Efesios 4:11-13),
está escrito que los pastores y maestros son dados
para "`perfeccionar a los santos,`" etc.,
"`hasta que todos lleguemos a la unidad de la fe y del conocimiento del Hijo de Dios,
a un varón perfecto, a la medida de la estatura de la plenitud de Cristo.`"
Ahora bien, si es imposible dejar de pecar diariamente y en todas las cosas,
entonces no podría haber perfección. Además, estos ministros,
que nos aseguran que no deberíamos jamás esperar ser redimidos
del pecado ¿no hacen que su propia labor sea innecesaria?
Porque ¿qué necesidad hay de predicar contra el pecado, si nunca se puede dejar de pecar?
Y con respecto a las Escrituras,
nuestros adversarios las exaltan muchísimo en sus palabras,
a menudo elogiando su utilidad y perfección. Y ciertamente,
el apóstol nos dice (2 Timoteo 3:17) que la "`Escritura es útil para enseñar,
para redargüir, para corregir, para instruir en justicia,
a fin de que el hombre de Dios sea perfecto,
enteramente preparado para toda buena obra.`"
Pero si se niega que esto sea alcanzable en esta vida,
entonces las Escrituras no tienen ningún beneficio, porque,
¿qué utilidad tendrán en la próxima vida?
Además,
esta doctrina también hace que las oraciones de los santos sean completamente inútiles;
porque,
si no es posible que Dios por Su Espíritu y gracia nos libre del mal y nos liberte del
pecado ¿por qué orar diariamente por ello (como todos confiesan que es nuestro deber)?
Sin embargo, los santos apóstoles oraron fervientemente por este fin,
y por lo tanto (sin duda) creían que era posible alcanzarlo aquí. Porque ellos
estaban "`siempre esforzándose intensamente a favor de ellos en sus oraciones,
para que estuvieran firmes,
perfectos y completamente seguros en toda la voluntad de Dios.`"^
footnote:[Colosenses 4:12 LBLA]
Ellos oraban a fin de que Dios "`afirmara sus corazones irreprensibles en santidad`"^
footnote:[1 Tesalonicenses 3:13 LBLA]
y los "`santificara por completo; espíritu, alma y cuerpo,`"^
footnote:[1 Tesalonicenses 5:23]
etc.

Pero, en quinto lugar,
esta doctrina es contraria al sentido común y a la razón. Porque el pecado y la justicia
son como dos semillas opuestas--una gobierna en los hijos de las tinieblas,
la otra en los hijos de la Luz.
Y conforme los hombres son leudados y gobernados respectivamente por ellas,
son considerados reprobados o justificados, ya que "`el que justifica al impío,
y el que condena al justo, ambos son igualmente abominación al Señor.`"^
footnote:[Proverbios 17:15 LBLA]
Ahora bien,
decir que los hombres no pueden ser leudados por una semilla
de tal manera que lleguen a ser libres de la otra,
es, en palabras claras, afirmar que el pecado y la justicia son compatibles,
y que un hombre puede ser verdaderamente considerado justo,
aunque peque diariamente en todo lo que hace.
Y si esto es así, entonces ¿qué diferencia hay entre lo bueno y lo malo?
¿No es esto caer en la gran abominación de "`tener las tinieblas por luz
y la luz por tinieblas,`" y de "`llamar al mal bien y al bien mal?`"^
footnote:[Isaías 5:20 LBLA]
Porque ellos dicen que hasta las mejores acciones
de los hijos de Dios están contaminadas y corrompidas,
y que aquellos que pecan diariamente en pensamiento,
palabra y acción son hombres y mujeres buenos,
incluso los santos y siervos puros del Dios santo y puro.
¿Podría haber algo más repugnante a la razón común que esto?
¿Dónde están los purificados de quienes hablan las Escrituras?
¿Dónde están aquellos que antes eran impíos,
pero que ahora han sido lavados y santificados;^
footnote:[1 Corintios 6:11]
quienes antes eran tinieblas pero que ahora son luz en el Señor?^
footnote:[Efesios 5:8]
Ciertamente, según esta doctrina pecaminosa no puede haber ninguno.

=== Evidencia de la Escritura

Para mayor demostración de la verdad, proseguiré a la segunda cosa que propuse, a saber,
probar nuestra postura a partir de varios testimonios de las Sagradas Escrituras.

Primero,
la pruebo a partir del mandato absoluto y positivo
de Cristo y Sus apóstoles a guardar los mandamientos,
y a ser perfectos en este sentido, sabiendo que Dios no demanda nada imposible.
Ahora bien, el hecho de que esto ha sido claramente ordenado en el Nuevo Testamento,
sin necesidad de comentarios o deducciones,
es evidente en los siguientes testimonios de las Escrituras: Mateo 5:48, "`Sed, pues,
vosotros perfectos, como vuestro Padre que está en los cielos es perfecto.`"
1 Corintios 7:19, "`La circuncisión nada es, y la incircuncisión nada es,
sino el guardar los mandamientos de Dios.`"
1 Juan 2:3-6, "`Y en esto sabemos que nosotros le conocemos,
si guardamos sus mandamientos.
El que dice: Yo le conozco, y no guarda sus mandamientos, el tal es mentiroso,
y la verdad no está en él; pero el que guarda su palabra,
en éste verdaderamente el amor de Dios se ha perfeccionado;
por esto sabemos que estamos en él.`" 1 Juan 3:5-10,
"`Y sabéis que él apareció para quitar nuestros pecados,
y no hay pecado en él. Todo aquel que permanece en él, no peca; todo aquel que peca,
no le ha visto, ni le ha conocido.
Hijitos, nadie os engañe; el que hace justicia es justo, como él es justo.
El que practica el pecado es del diablo; porque el diablo peca desde el principio.
Para esto apareció el Hijo de Dios, para deshacer las obras del diablo.
Todo aquel que es nacido de Dios, no practica el pecado,
porque la simiente de Dios permanece en él; y no puede pecar, porque es nacido de Dios.
En esto se manifiestan los hijos de Dios, y los hijos del diablo:
todo aquel que no hace justicia, y que no ama a su hermano, no es de Dios.`"
Véase también, Mateo 7:21, Juan 13:17;
2 Corintios 13:11. Todas estas Escrituras implican
un mandato positivo de guardar Sus mandamientos,
y declaran la necesidad absoluta de ello.
Por lo tanto,
como si hubieran sido escritas intencionalmente para
responder las objeciones de nuestros opositores,
muestran la locura de aquellos que se atreven a considerarse
a sí mismos hijos o amigos de Dios,
mientras hacen lo contrario.

En segundo lugar, tal libertad del pecado es posible,
porque es precisamente el propósito por el que recibimos el Evangelio.
Esto se nos promete claramente según llegamos a estar bajo el dominio de la gracia,
como se muestra en estas Escrituras: Romanos 6:14,
"`Porque el pecado no se enseñoreará de vosotros; pues no estáis bajo la ley,
sino bajo la gracia.`"
Romanos 8:3-4, "`Pues lo que la ley no pudo hacer,
ya que era débil por causa de la carne, Dios lo hizo:
enviando a su propio Hijo... para que el requisito de la ley se cumpliera en nosotros,`"^
footnote:[Romanos 8:3-4 LBLA] etc.
Porque si esto no fuera una condición necesaria y posible bajo el Evangelio,
no habría diferencia entre "`la ley, que nada hizo perfecto,`"^
footnote:[Hebreos 7:19 LBLA]
y "`la introducción de una mejor esperanza,`"^
footnote:[Hebreos 7:19]
ni entre aquellos que están bajo el Evangelio y los que están bajo la ley.
Pero el apóstol, argumenta a lo largo de todo el capítulo seis de Romanos,
no solo la posibilidad,
sino la necesidad de ser libres del pecado al llegar
a estar bajo el Evangelio y la Gracia,
y no estar más bajo la Ley.
En los versos 2-7 declara que esta es su propia condición
y la de aquellos a quienes escribe;
y luego en el 11-13 y 16-18 argumenta tanto la posibilidad
como la necesidad de ser libres del pecado,
diciendo: "`No reine, pues, el pecado en vuestro cuerpo mortal,
de modo que lo obedezcáis en sus concupiscencias,`" y,
"`habiendo sido librados del pecado, sois hechos siervos de la justicia.`"^
footnote:[Romanos 6:18 RV1602P]
Finalmente, en el verso 22,
declara que sus lectores en cierta medida habían alcanzado esta condición,
con estas palabras:
"`Mas ahora que habéis sido libertados del pecado y hechos siervos de Dios,
tenéis por vuestro fruto la santificación, y como fin, la vida eterna.`"

Ahora bien,
así como esta perfección o libertad del pecado se alcanza y se hace posible
donde se recibe y se experimenta el Evangelio o la ley interna del Espíritu,
asimismo desconocer esta vida y poder interno,
ha sido y es la razón por la que muchos se oponen a esta verdad.
Porque el hombre,
por no prestar atención a la Luz o Ley dentro de
su corazón (que no solo descubre el pecado,
sino que guía fuera de él),
sigue siendo ajeno a esa nueva Vida y Nacimiento que procede de Dios,
que naturalmente hace Su voluntad, y que no puede, por su propia naturaleza,
trasgredir Sus mandamientos.
Tal hombre, en su estado natural, mira los mandamientos de Dios de manera externa,
como algo fuera de él, en la letra,
y se halla a sí mismo reprobado y condenado internamente,
y la letra en vez de vivificarlo, lo mata.
Y así, hallándose a sí mismo herido,
y no entregándose internamente a esa Luz y Gracia que puede curarlo,
se esfuerza en su propia voluntad por conformase a la Ley según está escrita en palabras,
lo cual nunca puede lograr, sino que descubre que mientras más se esfuerza,
más corto queda.
Y aunque estos tengan una noción del cristianismo, y una fe externa en Cristo,
en realidad, todavía están en el estado del judío, con su mandamiento carnal,
su ley externa, en el estado del primer pacto que "`no puede hacer perfecto,
en cuanto a la conciencia,
al que lo practica`" (Hebreos 9:9). Esto los ha hecho forzar y torcer las Escrituras
para soportar una justicia imputada que venga completamente desde afuera,
a fin de cubrir su continua impureza, e imaginar que es posible que Dios los acepte,
aun cuando consideren imposible obedecer los mandamientos de Cristo.

Pero ay ¡oh almas engañadas!
Esto no servirá en el Día en el que Dios juzgará a "`cada uno según lo que haya hecho,
sea bueno o sea malo.`"^
footnote:[2 Corintios 5:10]
Decir que era necesario pecar diariamente en pensamiento, palabra y obra, no te salvará;
porque aquellos que lo hacen sin ninguna duda han "`obedecido a la injusticia.`"^
footnote:[Romanos 2:8]
Y ¿cuál es el fin de estos sino tribulación y angustia, indignación e ira?
Así como se promete gloria, honor,
paz e inmortalidad a aquellos que han hecho lo bueno y han perseverado en bien hacer.
Entonces, si deseas sentir la posibilidad de esta perfección y libertad del pecado,
vuelve tu mente a la Luz y Ley espiritual de Cristo en el corazón,
y sométete a sus reprobaciones.
Lleva el juicio y la indignación de Dios sobre la
naturaleza injusta en ti según es revelado,
lo cual Cristo ha hecho tolerable para ti;
y entonces permite que el "`juicio`" en ti sea "`llevado a la victoria.`"^
footnote:[Mateo 12:20]
De esta manera serás participes de los padecimientos de
Cristo y llegarás a ser semejante a Él en Su muerte.^
footnote:[Filipenses 3:10]
Te sentirás a ti mismo crucificado con Él al mundo por el poder de Su cruz obrando en ti,
para que muera esa vida que antes estaba viva en ti para este mundo,
y para su amor y sus deseos, y se levante una nueva vida,
por la cual puedas vivir de ahora en adelante para Dios y no para o por ti mismo.
Entonces realmente podrás decir con el apóstol,
"`Con Cristo estoy juntamente crucificado, y ya no vivo yo, mas vive Cristo en mí.`"^
footnote:[Gálatas 2:20]
Entonces serás un cristiano de verdad, y no solo uno de nombre, como lo son muchos.
Entonces sabrás qué es "`haberse despojado del viejo hombre con
sus hechos,`" quien ciertamente peca a diario en pensamiento,
palabra y obra; y qué es ser "`revestido del nuevo,
el cual es renovado en conocimiento conforme a la imagen de Aquel que lo creó`"^
footnote:[Colosenses 3:9-10 RV1602P]
y "`es creado en justicia y santidad verdadera.`"^
footnote:[Efesios 4:24 Versión Moderna H.B. Pratt (1929)]
Y así podrás sentirte a ti mismo como la "`hechura de Dios,
creado en Cristo Jesús para buenas obras.`"^
footnote:[Efesios 2:10]
Y aunque "`el yugo de Cristo`" sea pesado para el viejo Adán,
para este nuevo hombre "`es fácil, y ligera su carga.`"^
footnote:[Mateo 11:30]
Sí, los mandamientos de Dios no son gravosos para él;
porque es su comida y bebida ser hallado cumpliendo la voluntad de Dios.

=== Objeciones Consideradas

Pero ahora procederé a responder las objeciones y argumentos de nuestros oponentes.

[.discourse-part]
Objeción: Comenzaré con su argumento principal y más grande,
el cual está basado en las siguientes palabras del apóstol Juan:
"`Si decimos que no tenemos pecado, nos engañamos a nosotros mismos,
y la verdad no está en nosotros.`"^
footnote:[1 Juan 1:8]
Ellos piensan que esto es invencible.

[.discourse-part]
Respuesta: Pero esta objeción no concuerda con su propósito,
porque Juan no está hablando de pecar diariamente en pensamiento, palabra y obra,
y mucho menos dice que las buenas obras que Dios mismo obra
en nosotros por medio de Su Espíritu son pecado.
De hecho,
el siguiente versículo muestra claramente que sobre la base de confesión
y arrepentimiento no solo somos perdonados sino también limpiados:
"`Él es fiel para perdonar nuestros pecados, y limpiarnos de toda maldad.`"
Aquí está tanto el perdón y la remoción de la culpa,
como la purificación o remoción de la inmundicia;
porque sería absurdo y repetitivo sugerir que tanto el perdón como
la purificación se refieren a la eliminación de la culpa.
Por esta razón, habiendo experimentado que la culpa y la inmundicia han sido removidas,
el apóstol continúa en tiempo pasado en el versículo 10, diciendo:
"`Si decimos que __no hemos pecado,__ le hacemos a él mentiroso.`"

Además, como Agustino bien observó en su exposición sobre la epístola a los Gálatas,
"`Una cosa es no pecar, y otra cosa no tener pecado.`"
Las palabras del apóstol no son, "`Si decimos que no cometemos pecado diariamente,
nos engañamos a nosotros mismos;`" sino "`si decimos que no tenemos pecado.`"
Y ¡hay una gran diferencia entre estas dos declaraciones!
Porque nosotros reconocemos libremente que todos han pecado,
y que en este sentido se puede decir que todos tienen pecado.
Además,
aquí la palabra "`pecado`" se puede tomar como haciendo referencia
a la semilla de pecado que está en todos los hombres,
incluso en aquellos que ya han sido redimidos de vivir en pecado.
Pero, en cuanto a las tentaciones y provocaciones que proceden de esta semilla,
cuando los siervos de Dios no ceden, sino que resisten por la gracia de Dios en ellos,
entonces el pecado se atribuye al diablo que tienta, y no al hombre que es preservado.

Pero toda esta controversia es innecesaria, ya que el mismísimo apóstol,
en varios lugares de la misma epístola,
afirma de manera clara y positiva la posibilidad de ser libres de pecado,
como ya ha sido mencionado.

[.discourse-part]
Objeción: Su segunda objeción viene de dos lugares de las Escrituras,
que dicen prácticamente lo mismo.
Una es de 1 Reyes 8:46, "`porque no hay hombre que no peque.`"
La otra de Eclesiastés 7:20, "`Ciertamente no hay hombre justo en la tierra,
que haga el bien y nunca peque.`"

[.discourse-part]
Respuesta: En primer lugar,
estos versículos no hablan de pecar de manera diaria y continua,
del cual nunca seremos redimidos, sino solo que todos han pecado,
o que no hay nadie que no peque.
En segundo lugar, se debe reconocer el pacto y dispensación en que se escribieron;
porque incluso si se debe conceder que en el tiempo
de Salomón no hubo nadie que no pecara,
esto no necesariamente implica que ahora no haya ninguno que no peque,
o que ahora no sea posible dejar de pecar por medio de la gracia de Dios bajo el Evangelio.
Y, por último, toda esta objeción se basa en una falsa interpretación de la Escritura;
porque la palabra Hebrea __yekhta`'__ se puede leer en el modo potencial, traduciéndose así,
"`No hay hombre que no __pueda__ pecar,`" que de hecho es como Junius y Tremellius,
y también Vatablus, lo traducen del hebreo.
La misma palabra se traduce de manera similar en el modo potencial en Salmos 119:11,
"`En mi corazón he guardado tus dichos, para no pecar contra ti.`"^
footnote:[Literalmente, el modo potencial expresa algo como:
"`No hay hombre que __no tenga la posibilidad__ de pecar;`"
y "`En mi corazón he guardado tus dichos,
para que __tenga la posibilidad de__ no pecar contra ti.`"]
Y puesto que esta traducción es más congruente con la tendencia universal de las Escrituras,
con el testimonio de la Verdad y con el sentido de casi todos los intérpretes,
sin duda debe entenderse así.

[.discourse-part]
Objeción: En tercer lugar,
ellos objetan basados en algunas expresiones del apóstol Pablo en Romanos capítulo 7:
"`Porque no hago el bien que quiero, sino el mal que no quiero, eso hago.`"^
footnote:[Romanos 7:19]
Y "`¡Miserable de mí! ¿quién me librará de este cuerpo de muerte?`"^
footnote:[Romanos 7:24]

[.discourse-part]
Respuesta:
No hay nada en el texto que indique que él está hablando de su condición presente,
o de una condición en la que siempre estará. Por el contrario,
en el capítulo anterior (como se mencionó ampliamente), él insiste en que los cristianos,
estando "`muertos al pecado,`" ya no deben vivir en él. Es evidente, entonces,
que aquí el apóstol habla de una condición que había experimentado anteriormente,
o que él personifica (por el bien de sus lectores) la condición
de alguien que aún no ha alcanzado la madurez,
lo cual es común en las Escrituras.

Ahora bien, es evidente que Pablo no habla aquí de su condición presente,
porque antes en este capítulo, dice:
(versículo 5) "`Porque mientras estábamos en la carne,
las pasiones pecaminosas que eran por la ley obraban en nuestros miembros llevando
fruto para muerte;`" y (versículo 9) "`Y yo sin la ley vivía en un tiempo;
pero venido el mandamiento, el pecado revivió y yo morí.`" Y luego dice (versículo 14),
"`Porque sabemos que la ley es espiritual; más yo soy carnal, vendido al pecado.`"
Pero ¿cómo vamos a creer que el apóstol Pablo era
un hombre carnal al momento de escribir su epístola?
¿No nos informa claramente cómo él no fue dejado en esta condición,
sino que en verdad experimentó la libertad de ella?
Porque después de exclamar, "`¿quién me librará de este cuerpo de muerte?`"
él contesta alegremente su propia pregunta, diciendo, "`Gracias doy a Dios,
por Jesucristo Señor nuestro,`"^
footnote:[Romanos 7:25]
y luego afirma que "`la ley del Espíritu de vida en Cristo Jesús`"
lo había "`librado de la ley del pecado y de la muerte,`" para
que "`la justicia de la ley se cumpliese en nosotros,
que no andamos conforme a la carne, sino conforme al Espíritu.`"^
footnote:[Romanos 8:2-4]

[.discourse-part]
Objeción: En cuarto lugar,
ellos objetan basados en las faltas y pecados de algunos santos eminentes, como Noé,
David, etc.

[.discourse-part]
Respuesta: Esto no prueba en lo absoluto el caso de nuestros oponentes;
porque la cuestión no es si los hombres buenos no
pueden caer en pecado (lo cual no negamos),
sino si es imposible para ellos no pecar.
Además, que estos hombres hayan pecado en ciertas ocasiones,
no significa que nunca dejaron de pecar,
o que nunca experimentaron tiempos de verdadera libertad del pecado.

[.discourse-part]
Objeción: Finalmente, objetan basados en la oración de nuestro Señor,
donde les enseñó a Sus discípulos a decir: "`perdónanos nuestras deudas,
como también nosotros perdonamos a nuestros deudores.`"^
footnote:[Mateo 6:12]

[.discourse-part]
Respuesta: Nosotros no negamos que "`todos hemos pecado,
y estamos destituidos de la gloria de Dios,`"^
footnote:[Romanos 3:23]
y que, por lo tanto, todos necesitan rogar que sus pecados pasados sean borrados,
y que ellos sean preservados diariamente de pecar.
Pero si alguno se atreve a decir que tener la esperanza de ser libres de pecado,
y creer que esto es posible, anula la oración por el perdón del pecado, entonces,
aplicando la misma regla,
se concluiría que debemos "`perseverar en el pecado para que la gracia abunde;`"^
footnote:[Romanos 6:1]
porque mientras más pecado comentan los hombres,
mayor será la ocasión de pedir perdón de pecado.
Pero el apóstol, en su respuesta a esta misma controversia,
ha refutado suficientemente estas tonterías con las que pretenden defender el pecado,
diciendo: "`En ninguna manera.
Porque los que hemos muerto al pecado, ¿cómo viviremos aún en él?`"^
footnote:[Romanos 6:2]

Para concluir--bienaventurados son los que creen en Aquel que tiene
tanto el poder como el deseo de redimir de todo pecado,
a todos los que vienen a Él con un verdadero arrepentimiento,
y que no resuelven (como lo hacen nuestros adversarios)
ser los siervos del diablo durante toda su vida,
sino que siguen adelante diariamente, dejando la injusticia,
olvidando aquellas cosas que quedan atrás y "`prosiguiendo a la meta,
al premio del supremo llamamiento de Dios en Cristo Jesús.`"^
footnote:[Filipenses 3:14]
Tales como estos encontrarán que su fe y confianza no han sido en vano,
y a su debido tiempo serán hechos vencedores por medio de Aquel en quien han creído;
y así, como vencedores,
serán establecidos como "`columnas en el templo de
Dios,`" de tal modo que "`nunca más saldrán de allí.`"^
footnote:[Apocalipsis 3:12]
