[quote.epigraph, , Salmo 62:5]
____
Alma mía, en Dios solamente reposa.
Porque de él es mi esperanza.
____

[quote.epigraph, , Lamentaciones 3:25-29]
____
Bueno es Jehová a los que en él esperan, al alma que le busca.
Bueno es esperar en silencio la salvación de Jehová.
Bueno le es al hombre llevar el yugo desde su juventud.
Que se siente solo y calle, porque es Dios quien se lo impuso; ponga su boca en el polvo,
por si aún hay esperanza.
____

[quote.epigraph, , Salmo 130:5-6]
____
Esperé yo a Jehová, esperó mi alma; en su palabra he esperado.
Mi alma espera a Jehová, más que los centinelas a la mañana,
más que los vigilantes a la mañana.
____

[quote.epigraph, , Salmo 123:2]
____
He aquí, como los ojos de los siervos miran a la mano de sus señores,
y como los ojos de la sierva a la mano de su señora,
así nuestros ojos miran a Jehová nuestro Dios,
hasta que tenga misericordia de nosotros.
____

== Prefacio

Foo bar baz.

La mayor parte de este folleto es una versión actualizada de la décima primera
proposición de la Apología para la Verdadera Teología Cristiana de Robert Barclay.
Todo el volumen de la Apología de Barclay (que consiste de quince proposiciones en total)
es una obra maravillosa y convincente que recomiendo a todo buscador serio de la Verdad.
He escogido modernizar y publicar de nuevo esta única proposición porque
me parece que la invaluable práctica de esperar en el Señor ha sido especialmente
abandonada y prácticamente ha desaparecido de la iglesia de hoy.

El breve apéndice que inicia en la página 64 es un extracto
de Los Escritos de Isaac Penington acerca del mismo tema.

[.signed-section-signature]
Jason R. Henderson

[.signed-section-context-close]
Abril, 2016
