== Esperando en el Señor

Ahora paso a hablar de la adoración, o de aquellas cosas--ya sean privadas o públicas,
generales o individuales--mediante las que el hombre le rinde a Dios esa
parte de su deber que se relaciona directamente con Él. Ahora,
ya que se nos ha dicho que "`el obedecer es mejor que los sacrificios,`" entonces,
ningún sacrificio es aceptable excepto el que es
hecho según la voluntad de Aquel a quien se le ofrece.
Pero los hombres,
encontrando más fácil hacer sacrificios en su propia
voluntad que obedecer la voluntad de Dios,
han amontonado sacrificios sin obediencia,
pensando engañar a Dios (como se engañan unos a otros),
dándole un espectáculo de reverencia, honor y adoración,
mientras están internamente alejados y apartados de Su santa y justa vida,
y son totalmente ajenos a los soplos puros de Su Espíritu,
en los cuales únicamente se ofrece el verdadero sacrificio y adoración. Como resultado,
no hay deber del hombre hacia Dios que haya sido
más pervertido (entre todo tipo de personas),
ni en el que el diablo haya prevalecido más,
que en corromper la mente del hombre concerniente a la adoración a Dios.

Ahora bien,
apruebo libremente todo lo que los protestantes han reformado
de los católicos romanos con respecto a esto.
También rechazo, como parte de la verdadera adoración a Dios,
la abominable superstición e idolatría de la misa papal,
la adoración a los santos y a los ángeles, la veneración de reliquias,
la visitación de sepulcros, y todas las demás ceremonias supersticiosas,
y las interminables peregrinaciones de la sinagoga romana.
Sin embargo,
corresponde a los protestantes considerar cuidadosamente
si han realizado una reforma clara y perfecta,
pues, ciertamente, encontramos que muchas de las ramas muertas fueron cortadas por ellos,
pero que la raíz aún permanece, es decir,
_una adoración llevada a cabo en y desde la voluntad y el espíritu del hombre,
y no por y desde el Espíritu de Dios._
Porque la verdadera adoración cristiana y espiritual a Dios se perdió muy tempranamente,
y la sabiduría y voluntad del hombre se mezclaron tan rápida y completamente con ella,
que la apostasía, en lo que respecta a la adoración, se ha hecho muy grande, y por tanto,
una verdadera reforma que arranque esta raíz maligna se ha vuelto sumamente difícil.

Por lo tanto, que el lector no tropiece con nuestra proposición en este asunto, más bien,
que nos escuche con paciencia mientras damos nuestra explicación.
Espero (con la ayuda de Dios) mostrar que,
a pesar de que nuestra perspectiva en este tema puede
parecer muy diferente de la de los demás cristianos,
está más de acuerdo con la pura religión cristiana, y en verdad,
de suma importancia observar y seguir.

En primer lugar, considérese que lo que aquí se afirma,
se dice con respecto a la adoración de Dios en estos tiempos del evangelio,
y no a la adoración que existía bajo o antes de la Ley.
Porque los mandamientos particulares que Dios dio a los hombres en aquellos tiempos,
no bastan para autorizarnos a hacer hoy las mismas cosas; de lo contrario,
podría sugerirse en el presente ofrecer sacrificios de animales
como entonces se hacía (lo cual todos reconocen que ha cesado).
De hecho, algunas de las cosas que bajo la Ley eran encomiables y aceptables,
si se practicaran hoy bajo el evangelio,
serían apropiadamente llamadas superstición o idolatría. Porque muchas de las ceremonias
que Dios instituyó para los judíos no eran esenciales para la verdadera adoración espiritual,
ni necesarias en sí mismas para experimentar la santa comunión entre Él y Su pueblo,
sino que fueron dadas en condescendencia a un pueblo inclinado a la idolatría. Así que,
aunque la Sustancia fue disfrutada bajo la Ley por los que eran verdaderamente espirituales,
aún estaba velada y rodeada de muchos ritos y ceremonias
que no nos son lícitos usar hoy bajo el Evangelio.

En segundo lugar, a pesar de que digo que esta adoración no se limita a tiempos, lugares,
ni personas,
no debo ser entendido como si intentara hacer a un lado todos los tiempos y lugares
determinados de la adoración. Dios me libre de tal opinión. No,
no somos de aquellos que "`dejan de congregarse,`" sino que, en efecto,
tenemos ciertos lugares y tiempos en los cuales nos reunimos con
diligencia para esperar en Dios y adorarle (y no hemos dejado de
hacerlo por las muchas amenazas y persecuciones de los hombres).
Creemos que reunirnos es necesario para el pueblo de Dios,
porque mientras estemos revestidos de este tabernáculo externo,
hay necesidad de una comunión conjunta y visible,
de llevar un testimonio externo a favor de Dios,
y de también vernos los unos a los otros,
de modo que nos reunimos en nuestras personas externas,
así como también en nuestros espíritus.
Reunirnos externamente en este amor interno y unidad de espíritu,
contribuye en gran manera a animar y refrescar a los santos.

Sin embargo, insistimos en lo siguiente: Primero,
que el Espíritu de Dios debe ser el que opera, mueve,
persuade e influye directamente al hombre en todos los actos
particulares de adoración cuando los santos se reúnen.
Segundo, que este Espíritu no debe ser limitado en Sus operaciones,
lo cual sucede cuando se establece a un hombre u hombres en particular
para predicar y orar en su voluntad o en la de otros hombres,
mientras todos los demás quedan excluidos aun de creer que deben
esperar a que el Espíritu de Dios los use en estas cosas.
Al hacerlo, desatienden al Espíritu que los vivificaría en sí mismos; y entonces,
al no esperar para sentir ni obedecer las respiraciones puras del Espíritu de Dios,
son conducidos a depender solamente del predicador y a escuchar lo que él va a decir.

Pues todos los que ministran,
deben reunirse para encontrarse con el Señor y esperar
los movimientos y operaciones internos de Su Espíritu,
y así orar cuando sientan al Espíritu respirar a través de ellos y en ellos,
y predicar cada vez que se encuentren siendo movidos y motivados
por el Espíritu de Dios según Él les da que hablen.
Sólo entonces podrán hablar una palabra oportuna para refrescar las almas abatidas,
conforme a lo que requiera la condición y el estado
presente de los corazones de las personas,
permitiendo que Dios, por medio de Su Espíritu,
tanto prepare los corazones de las personas como dé también al predicador
lo que ha de hablar de manera conveniente y oportuno para ellos.
Pero los ministros de hoy arman un sermón en sus oficinas, conforme a su propia voluntad,
mediante su sabiduría humana y literatura,
hurtando las palabras de la Verdad de la letra de las Escrituras
y remendándolo junto con otros escritos y observaciones de hombres.
Así,
diseñan un sermón que los mantendrá hablando durante
una hora mientras el reloj de arena se agota,
sin haber esperado o sentido la influencia interna del Espíritu de Dios,
o sin saber si el sermón es apropiado u oportuno para la condición de las personas.
Luego, cuando ha terminado su sermón, dice su oración en su propia voluntad,
y allí se da por terminado el asunto.
Esta forma habitual de adoración no es en modo alguno aceptable para Dios,
y la condición actual de las naciones declara suficientemente cuán infructuosa
e improductiva es para los que se encuentran en ella.

Por ende, no estamos en absoluto en contra de los tiempos establecidos para la adoración,
y de hecho designamos dichos tiempos para conveniencia externa.
No creemos, sin embargo--como los católicos romanos--que estos días sean santos,
ni dirigimos a las personas a una observación supersticiosa de estos,
pues estamos persuadidos de que todos los días son iguales antes los ojos de Dios.

=== Esperando en el Señor en Silencio

Hemos llegado al tema de la controversia.
Con respecto a la adoración pública,
juzgamos que es deber de todos congregarse con diligencia, y que, una vez reunidos,
la gran labor de cada uno debe ser esperar en Dios,
volviéndose de sus propios pensamientos e imaginaciones,
para sentir la presencia del Señor y experimentar una verdadera "`reunión
en Su Nombre,`" en la que Él está "`en medio`" según Su promesa.
Y al estar así reunidos,
congregados tanto internamente en sus espíritus como externamente en sus personas,
se experimentan el poder secreto y la virtud de la vida que refrescan el alma,
y se siente el levantamiento de los movimientos y suspiros puros del Espíritu de Dios.
A partir de esto brotan palabras de declaración, oraciones o alabanzas,
y se experimenta la adoración aceptable, la cual edifica a la Iglesia y agrada a Dios.
Así nadie limita al Espíritu de Dios, ni saca su propio material investigado y reunido,
sino que todos expresan aquello que el Señor pone en su corazón,
y lo dice no en la voluntad ni sabiduría del hombre,
sino "`con demostración del Espíritu y de poder.`"
Sí, y aunque no se diga una palabra,
la verdadera adoración espiritual es llevada a cabo y el cuerpo de Cristo es edificado.

Puede ser así, y ciertamente ha sucedido a menudo entre nosotros,
que varias reuniones transcurran sin que se diga una sola palabra; no obstante,
nuestras almas han sido grandemente edificadas y refrescadas,
y nuestros corazones maravillosamente conmovidos
por el sentido secreto del poder y Espíritu de Dios,
el cual--sin palabras--ha sido ministrado de una vasija a otra.
Esto es, en verdad, algo extraño e increíble para el hombre meramente natural y carnal,
quien está listo para juzgarlo todo como tiempo perdido
si no se dice algo que sea obvio para los sentidos externos.
Por lo tanto, insistiré un poco en este tema,
como alguien que puede hablar desde cierta experiencia (y no por simple oídas) de esta
maravillosa y gloriosa adoración. Pues aunque es contraria a la naturaleza del espíritu,
voluntad y sabiduría del hombre, rebosa de la sabiduría y gloria de Dios.

Puesto que no hay nada más opuesto a la voluntad y sabiduría
natural del hombre que esta espera silenciosa en Dios,
no puede, por tanto, ser obtenida o correctamente comprendida por el hombre,
excepto cuando este rinde su propia voluntad y sabiduría
y se contenta con estar completamente sujeto a Dios.
En consecuencia, tal espera en Él no será predicada, ni podrá ser practicada,
sino por aquellos que no hallan en una ceremonia externa, ni en observaciones,
ni en palabras (sí, ni aun en las mejores o más puras palabras,
incluso las palabras de las Escrituras),
algo que pueda satisfacer a sus almas cansadas y afligidas.
Porque aunque todas estas cosas estén presentes, puede faltar aun la vida,
el poder y la virtud que las hacen eficaces.

Tales almas desesperadas hallaron necesario acabar con todas
las cosas externas y guardar silencio delante del Señor;
y al ser dirigidas a ese don interno de Vida y Luz
en ellas mismas como el más excelente Maestro,
el cual "`nunca más les será quitado`" (Isaías 30:20),
llegaron así a aprender a esperar en Dios en la medida de vida y gracia recibida de Él,
y a cesar de sus propias palabras y acciones apresuradas
en la voluntad y comprensión natural,
anhelando experimentar esta Semilla de Vida interna.
Aquí encontraron, que cuando esta Semilla se mueve, pueden moverse con ella,
y que cuando son impulsados por Su poder, entonces son influenciados ya sea a orar,
predicar o cantar.
Y así,
a partir de este principio--que el hombre debe mantenerse en silencio y no actuar
en las cosas de Dios hasta que primero sea movido por la luz y la gracia de Dios
en el corazón--surgió de manera natural esta forma de sentarse juntos en silencio
y de esperar unánimes en el Señor. De modo que estos,
congregados en el temor puro del Señor, no se dedicaron de inmediato a hablar, orar,
cantar, etc.,
teniendo temor de ser hallados actuando anticipadamente en sus propias voluntades.
En su lugar,
cada uno se ocupaba en retirarse internamente a la medida de gracia en sí mismo,
no sólo guardando silencio en cuanto a palabras,
sino incluso absteniéndose de sus propios pensamientos, imaginaciones y deseos,
velando en santa dependencia del Señor,
y congregándose no sólo externamente en un mismo lugar,
sino internamente en un mismo Espíritu y en el único nombre de Jesús,
el cual es Su poder y virtud.

De esta manera, estos han llegado a disfrutar y a sentir los levantamientos de esta Vida,
la cual, cuando prevalece en cada persona,
se convierte en un refrescante torrente que se esparce
por toda la reunión. Porque a medida que el hombre,
junto con su habilidad y sabiduría, es negado y encadenado en cada individuo,
y Dios es exaltado, y Su gracia se levanta en dominio en el corazón,
así Su nombre llega a ser uno en todos, y Su gloria irrumpe y los cubre a todos.
En efecto, a menudo hay tal temor santo y reverencia sobre cada alma,
que si en alguien se levanta la parte natural, o la parte sabia del hombre,
o cualquier cosa que no sea uno con la Vida, es inmediatamente encadenada y juzgada.
Y cuando alguno es constreñido (mediante la irrupción del poder
del Señor) a pronunciar una palabra de exhortación o de alabanza,
o a respirar ante el Señor en oración, entonces todos son hechos sensibles a ello,
porque la misma Vida que hay en ellos responde "`como en el agua
el rostro corresponde al rostro`" (Proverbios 27:19).

Esta es la adoración divina y espiritual que el mundo ni conoce ni entiende,
dentro de la cual el ojo de buitre no puede ver.^
footnote:[Ver Job 28:7]
Con todo,
son muchas y grandes las ventajas que mi alma (como
muchas otras) ha gustado por medio de ella,
las cuales serían halladas por todos aquellos que con seriedad se apliquen a ella.
Porque cuando las personas se reúnen de esta manera,
no sólo para oír a los hombres o depender de ellos, sino que, en su lugar,
son enseñadas internamente a poner sus mentes en el Señor
(Isaías 26:3) y a esperar Su aparición en sus corazones,
entonces se frena y se impide que la apresurada obra del
espíritu del hombre se mezcle con la adoración de Dios.
De hecho,
esta forma de adoración está tan desnuda y vacía de todo esplendor externo y mundano,
que no hay lugar alguno para que la sabiduría del
hombre ejerza superstición e idolatría. En su lugar,
hay una quietud interna y un retiro de la mente,
el testigo de Dios se levanta en el corazón, y la Luz de Cristo brilla,
mediante la cual el alma llega a ver su propia condición.
Y cuando muchos están unidos en esta misma obra,
hay un esfuerzo y lucha interior,
y mientras cada uno permanece en su propia medida de gracia,
se siente que el poder y el espíritu de las tinieblas son vencidos.
En consecuencia,
a menudo somos en gran manera fortalecidos y renovados
en el espíritu de nuestras mentes sin una sola palabra,
y disfrutamos y poseemos la santa unión y "`comunión del cuerpo y de la
sangre de Cristo,`" por medio de la cual nuestro hombre interior es alimentado
y nutrido (lo cual también hace que no nos enfoquemos en el agua,
el pan y el vino exteriores en nuestros asuntos espirituales).

Ahora bien, conforme aquellos que se reúnen de esta manera crecen en la fortaleza,
el poder y la virtud de la Verdad,
y la Verdad llega a tener victoria y dominio en sus almas,
entonces reciben palabra y hablan con firmeza para la edificación de sus hermanos,
y la Vida pura tiene libre paso a través de ellos
y lo que así se habla edifica verdaderamente al cuerpo.
A veces, cuando alguno ha llegado a la reunión y no ha sido vigilante,
divaga en su mente o está distraído por asuntos externos,
y por tanto no está internamente reunido con el resto,
tan pronto como se retira a su interior,
este Poder (que está en buena medida levantado en toda la
reunión) repentinamente se apodera de su espíritu,
y le ayuda maravillosamente a levantar la Semilla en él,
y a participar de la experiencia del mismo Poder.
Esto ablanda y calienta su corazón,
así como el calor natural toma a un hombre que tiene frío cuando se acerca a una estufa,
o como una llama se prende de un poco de material combustible que está cerca de ella.

O si sucede que varios están divagando en sus mentes,
a pesar de que guardan silencio exteriormente,
y por tanto están distraídos de la medida de gracia que hay en sí mismos
(lo cual puede ocurrir por negligencia y por obra del enemigo),
y llega otro que está atento y en quien la Vida está en gran medida levantada, éste,
mientras se mantiene en su lugar,
sentirá una recóndita lucha por los demás en solidaridad
con la Semilla que es oprimida en los otros,
y que es detenida en Su levantamiento por sus pensamientos y divagaciones.
Y mientras este fiel espera en la Luz y se mantiene en esta obra divina,
Dios a menudo responde a esta lucha secreta y a los
suspiros de Su propia Semilla a través de él,
de modo que los demás se sienten tocados en secreto, sin palabras,
y el fiel llega a ser como una partera, por los dolores de parto en su alma,
y da a luz la Vida en los otros.
De esta manera,
la Vida de Cristo es levantada en todos y las vanas imaginaciones derribadas,
y los demás sienten que este fiel les ministra vida sin palabras.

Sí, a veces,
aun cuando no se pronuncia una sola palabra en la
reunión y todos están esperando en silencio,
y entra alguien grosero y malvado,
en quien prevalece el poder de las tinieblas (tal
vez con la intención de burlarse o de hacer mal),
si toda la reunión está recogida en la Vida,
y la Vida se halla en buena medida levantada,
Ella aterrorizará a la persona y esta se sentirá incapaz de resistirla.
En verdad,
la fuerza secreta y la virtud de la Vida encadenará el poder de las tinieblas en ella,
y si el día de su visitación no ha expirado,
alcanzará la medida de gracia en ella y la levantará para redención de su alma.
Hemos sido testigos de esto a menudo,
así que hemos tenido muchas ocasiones para renovar el antiguo dicho:
"`¿Está Saúl también entre los profetas?`"
Porque muchos han llegado a convencerse de la Verdad de esta manera,
de lo cual yo mismo soy, en parte, un verdadero testigo.
Porque no fue por la fuerza de los argumentos, ni por la discusión de cada doctrina,
ni por el convencimiento de mi entendimiento que
llegué a recibir y a dar testimonio de la Verdad,
sino al ser alcanzado en lo secreto por esta Vida.
Pues cuando acudía a las reuniones en silencio del pueblo de Dios,
sentía un poder entre ellos que tocaba mi corazón, y en la medida que le daba paso,
hallaba que el mal se debilitaba en mí y el bien se levantaba.
De este modo fui ligado y unido a ellos,
anhelando cada vez más el incremento del Poder y de la Vida del Señor,
mediante lo cual podría sentirme perfectamente redimido.
En efecto, esta es la forma más segura de llegar a ser cristiano, y luego,
el conocimiento y el entendimiento de los principios no faltarán,
sino que vendrán naturalmente (tanto como sea necesario)
como el fruto de esta buena raíz,
y tal conocimiento no será estéril ni infructuoso.

Deseamos, por lo tanto,
que todo el que se acerque a nosotros sea convertido a este Poder y esta Vida.
Porque sabemos que,
aunque miles fueran convencidos en sus entendimientos de todas las verdades que sostenemos,
si no son conscientes de esta Vida interna y sus
almas no son cambiadas de injusticia a justicia,
no pueden añadirnos nada.
Porque este es el cemento con el cual estamos unidos
"`como al Señor`" y unos a los otros,
y sin esto, nadie puede adorar con nosotros.
Sí, aunque algunos vinieran entre nosotros y,
a partir del entendimiento y convencimiento que tienen de la Verdad,
hablaran cosas muy verdaderas, y las expresaran con gran excelencia de palabras,
si carecen de esta Vida, eso no nos edificará en absoluto,
sino que será como "`metal que resuena, o címbalo que retiñe`" (1 Corintios 13:1).

=== El Papel del Creyente en la Adoración

Por consiguiente, cuando nos congregamos,
nuestra labor y nuestra adoración consisten en que cada
uno vele y espere la aparición de Dios en sí mismo,
y sea recogido en Él, fuera de todas las cosas visibles.
Y cuando todos están vueltos y esperando, hallan que el bien se levanta sobre el mal,
y lo puro sobre lo impuro, y que Dios se revela y se acerca a cada individuo; y así,
Él está en medio de la asamblea.
De este modo,
cada uno no sólo participa del refrescamiento y de la fortaleza
particular que provienen de la obra del Señor en su interior,
sino que también es partícipe de la totalidad del cuerpo, al ser un miembro vivo de él,
y tener compañerismo y comunión juntamente con todos.

Ahora bien, a medida que esta adoración se predica y se guarda con firmeza,
llega a ser fácil, aunque al principio es muy difícil para el hombre natural,
cuyas imaginaciones errantes y sucesivos deseos mundanos
no son llevados tan fácilmente al silencio.
Por tanto, cuando alguien se vuelve al Señor con verdaderos deseos de esperar en Él,
pero encuentra gran dificultad por el extravío de su mente,
el Señor muchas veces (en Su misericordia y compasión) hace
que Su Poder irrumpa en una manera más fuerte y poderosa.
Luego, cuando la mente se sumerge y espera la aparición de la Vida,
y el poder de las tinieblas en el alma es hallado luchando y obrando contra ella,
entonces la buena Semilla se levanta y funciona como medicina en el alma.
Esto sucede, especialmente,
cuando alguien débil se encuentra en la asamblea reunido con muchos otros,
en quienes la vida se ha levantado en mayor dominio.
Y debido a la obra contraria del poder de las tinieblas,
a menudo hay una lucha interna en el alma,
tan espiritualmente real como alguna vez lucharon Esaú y Jacob en el vientre de Rebeca.
Y a partir de esta aflicción interna, mientras las tinieblas buscan oscurecer la Luz,
y la Luz busca atravesar las tinieblas (lo cual siempre
hará si el alma no cede su fuerza a la oscuridad),
se produce una angustia tan dolorosa en el alma que
incluso se puede manifestar en el hombre exterior.
Así, pues, a menudo, por la obra de esta lucha,
el cuerpo del individuo se sacude en gran medida, con muchos gemidos,
suspiros y lágrimas, como la angustia de una mujer en labor de parto.

En otras ocasiones,
el enemigo (que está presente cuando los hijos de Dios se reúnen para ver si puede entorpecer
su tranquilidad) parece prevalecer en cierta medida sobre toda la reunión,
obrando arduamente contra ella al esparcir y propagar su oscuro poder,
y alejar las mentes de la Vida en ellos.
Pero cuando los que están reunidos son conscientes del poder que obra contra ellos,
y comienzan a luchar contra él por medio de las "`armas de la luz,`"
a veces el poder de Dios irrumpe en toda la reunión. Entonces ocurre
tal lucha interna por las obras fuertes y contrarias de estos dos
poderes opuestos (como el movimiento de dos mareas contrarias),
que cada individuo es severamente ejercitado como en un día de batalla.
Aquí, un temblor y movimiento del cuerpo sobrevienen a la mayoría, si no a todos, que,
a medida que prevalece el poder de la Verdad,
llevará a la asamblea de los dolores y gemidos al
dulce sonido de la acción de gracias y alabanza.
De aquí el nombre "`Cuáqueros,`" es decir, los que tiemblan,
el cual nos fue dado en desprecio.
Pero, aunque este nombre no fue de nuestra elección,
en este sentido no estamos avergonzados de él,
sino que más bien tenemos motivos para regocijarnos,
siendo conscientes de Su Poder entre nosotros.
De hecho,
este mismo Poder de Dios a menudo se ha apoderado
de nuestros adversarios haciendo que cedan ante nosotros,
se unan a nosotros y confiesen la Verdad antes de
tener un conocimiento claro de nuestras doctrinas.
A veces muchos han sido convencidos de esta manera en una misma reunión,
y otras veces este Poder ha alcanzado y obrado maravillosamente hasta en niños pequeños,
para la admiración y asombro de muchos.

Son muchas las benditas experiencias que podría contar
acerca de este silencio y manera de adorar.
No obstante,
no recomiendo ni hablo del silencio como si tuviéramos
una regla para excluir la oración o la predicación,
ni como si estuviéramos atados al silencio; de ninguna manera.
Pues, así como nuestra adoración no consiste en palabras,
tampoco consiste en el silencio como si el silencio fuera el fin.
Más bien consiste en una santa dependencia de la mente en Dios,
a partir de la cual sigue necesariamente el silencio en primer lugar,
hasta que puedan ser expresadas las palabras que provienen del Espíritu de Dios.
Y Dios no deja de moverse en Sus hijos para producir
palabras de exhortación o de oración cuando es necesario,
de modo que, de las muchas reuniones y encuentros entre nosotros,
son muy pocas las que transcurren enteramente en silencio,
sin que Dios haga que alguien ministre a sus hermanos.
Porque cuando muchos se reúnen verdaderamente en esta única Vida y Nombre, Él,
más natural y frecuentemente los induce a orar,
a alabar y a animarse los unos a los otros por medio
de la exhortación e instrucción mutua.
Aun así, seguimos considerando necesario que primero haya un tiempo de silencio,
para que en ese tiempo todos puedan recogerse internamente en la Palabra y Don de gracia.
Entonces, a partir de esta gracia,
el que ministra puede recibir la fortaleza para transmitir lo que ministra,
y los que escuchan pueden recibir un sentido de discernimiento
entre lo precioso y lo vil,
y no apresurarse en el ejercicio de estas cosas tan pronto como suena la campana,
como lo hacen otros Cristianos.

No obstante, también sabemos con toda certeza y podemos testificar,
que una reunión puede ser buena y refrescante, aun cuanto,
desde que nos sentamos hasta que nos levantamos,
no se haya dicho una sola palabra externamente.
Porque en estas reuniones, se siente que la Vida sigue abundando en cada individuo,
y muchos han experimentado un crecimiento interno en y por el poder del Señor.
Y aun cuando podrían haberse expresado palabras aceptables desde la Vida,
a veces no hay absoluta necesidad de que alguno lo haga,
y todos pueden elegir más bien poseer y disfrutar
al Señor en quietud y silencio dentro de sí mismos.
En efecto,
esto es muy dulce y consolador para el alma que ha aprendido
a recogerse fuera de todos sus propios pensamientos y obras,
y a sentir al Señor producir el querer como el hacer (lo cual muchos
de nosotros podemos testificar por experiencia bendita).

Esta doctrina es decididamente difícil de ser creída o recibida por el hombre natural,
y por lo tanto debe ser conocida mediante una experiencia palpable y al ponerse a prueba,
más que por argumentos;
porque no basta con creerla si no llegan también a disfrutarla y poseerla.
No obstante,
por consideración a aquellos que tal vez estén más dispuestos a entregarse
a su práctica y experiencia si encuentran su entendimiento convencido,
y además ven que está fundamentada en las Escrituras y en la razón,
hallo libertad de añadir unas pocas consideraciones para mayor confirmación,
además de lo mencionado anteriormente acerca de nuestra experiencia.

Supongo que nadie negará que esperar en el Señor y vigilar delante de Él,
es un deber que nos incumbe a todos;
y que esto también forma parte de la adoración no se cuestionará,
ya que difícilmente haya otra cosa que con tanta
frecuencia se ordene en las santas Escrituras,
como es evidente en los siguientes versículos: Salmos 27:14; 37:7,34; Proverbios 20:22;
Isaías 30:18; Oseas 12:6; Zacarías 3:8; Mateo 24:42; 25:13; 26:41; Marcos 13:33,35,37;
Lucas 21:36; Hechos 1:4; 20:31; 1 Corintios 16:13; Colosenses 4:2; 1 Tesalonicenses 5:6;
2 Timoteo 4:5; 1 Pedro 4:7. Además,
este deber es a menudo recomendado con preciosas y grandes promesas,
como aparecen en Salmos 25:3; 37:9; 69:6; Isaías 40:31;
Lamentaciones 3:25-26. "`Pero los que esperan en Jehová tendrán nuevas fuerzas,`" etc.

Ahora bien, ¿cómo puede uno esperar en el Señor o velar delante de Él,
sino por medio de este silencio del que hemos hablado?
Este es, claramente, un deber grande y principal,
y necesariamente precede a todos los demás (tanto
por su naturaleza como con respecto al tiempo).
Pero para que se entienda más perfectamente, no sólo como un silencio externo del cuerpo,
sino también como un silencio interno de la mente,
libre de todas sus propias imaginaciones y pensamientos,
considérese que el hombre debe entenderse en un doble sentido; es decir,
en su estado natural, no regenerado y caído, y en la condición espiritual y renovada.
De aquí se levanta la distinción entre el "`hombre natural`"
y el "`hombre espiritual`" tan usada por el apóstol,
y estos dos nacimientos en la mente o corazón proceden respectivamente
de las dos semillas que hay en el hombre;
a saber, la buena Semilla y la mala.
Ahora bien, de esta mala semilla no sólo procede toda clase de maldad evidente,
abominable y profana, sino también la hipocresía,
y aquella maldad que las Escrituras llaman "`espiritual`" (Efesios 6:12),
porque es la serpiente obrando en y por medio del
hombre natural en las cosas que son espirituales.
Estas cosas pueden tener una fachada y apariencia de bien,
pero son las más dañinas y peligrosas,
"`porque el mismo Satanás se disfraza como ángel de luz.`"
Por esta razón,
la Escritura echa y excluye con tanta firmeza y frecuencia
al hombre natural de inmiscuirse en las cosas de Dios,
rechazando sus esfuerzos en ellas,
aunque sean llevadas a cabo por las más eminentes facultades del hombre,
como es la sabiduría y la elocuencia.

Además,
esta maldad espiritual es de dos clases (aunque ambas son de una misma naturaleza,
ya que proceden de la misma raíz). La primera es cuando el hombre
natural se inmiscuye y actúa en las cosas de la religión,
y desde sus propias concepciones y deducciones,
afirma o propone ideas y opiniones falsas y equivocadas
acerca de Dios y de las cosas espirituales,
e inventa supersticiones, ceremonias,
observancias y ritos en la adoración. De este clase de maldad,
han surgido todas las herejías y supersticiones que existen hoy entre los cristianos.
La segunda es cuando el hombre natural,
movido por una mera convicción en su entendimiento,
se adelanta en su propia voluntad y esfuerzo natural
sin la influencia y guía del Espíritu de Dios,
y trata ya sea de entender o imaginar las cosas de Dios,
o incluso de llevarlas a cabo por medio de la oración y predicación. Ahora,
la primera de estas carece tanto de la sustancia como de la forma.
La segunda, es posible que conserve la forma externa del cristianismo,
pero está desprovista de la Vida y la Sustancia.
Porque la auténtica religión cristiana,
no consiste en una mera creencia de doctrinas verdaderas,
ni en una mera ejecución de buenos actos, o de lo contrario,
las simples palabras de las Escrituras,
aunque fueran pronunciadas por un borracho o un demonio,
podrían ser llamadas Espíritu y vida,
lo cual considero que nadie será tan absurdo como para afirmarlo.

Ahora, aunque esta última clase no es tan mala como la primera,
aun así le ha abierto camino.
Porque los hombres,
habiéndose apartado primero de la Vida y la Sustancia
de la verdadera religión y adoración--es decir,
del poder y virtud internos del Espíritu por los cuales deben obrar--solamente
pueden entonces conservar la forma y la apariencia externa,
es decir, palabras verdaderas y buenas apariencias.
Luego, como estos continúan actuando en su propia voluntad natural y no renovada,
la forma no puede sino también decaer rápidamente y corromperse.
Pues el afanoso espíritu del hombre no quiere permanecer
dentro de la simplicidad y sencillez de la Verdad,
sino que pronto da paso a múltiples invenciones e imaginaciones,
de modo que la forma se acomoda a ellas,
hasta que (gradualmente) la apariencia de piedad se pierde, junto con el poder.
Con este tipo de idolatría, el hombre ama, idolatra y abraza sus propias concepciones,
invenciones y los productos de su propio entendimiento.
De hecho, esto es tan inherente en él y está tan asentado en su naturaleza caída,
que mientras su espíritu natural siga siendo el primer autor y actor en él,
y sea aquel por el cuál es guiado y movido en su adoración
a Dios (sin esperar primero a otro Guía que lo dirija),
nunca podrá llevar a cabo la adoración espiritual pura,
ni producir algo más que el fruto de la primera raíz caída, natural y corrupta.

Pero el tiempo designado por Dios hace ya mucho tiempo que llegó,
en el cual se ha complacido en restaurar la verdadera
adoración espiritual por medio de Cristo Jesús. Y,
una vez que la forma,
el tiempo y la manera externa de la adoración señalada
por Dios a los judíos llegó a su fin,
encontramos que Jesucristo (el Autor del cristianismo) no prescribe,
bajo la administración más pura del Nuevo Pacto,
ninguna forma fija de adoración a Sus hijos,
aparte de insistir en que la adoración ahora sea espiritual y en el Espíritu.
Debe observarse que, en todo el Nuevo Testamento,
no se da ningún orden ni mandato específico acerca de la manera o forma de adoración,
excepto que los creyentes sigan la revelación del Espíritu y no dejen
de congregarse (algo muy querido y practicado diligentemente por nosotros).
Es cierto que se hace mención de los deberes de la oración, predicación y alabanza;
pero en cuanto al orden o método que se debe mantener al hacerlo,
o si deben realizarse inmediatamente, tan pronto como los santos estén reunidos;
no hay una sola palabra.
De hecho,
estos deberes (como se mostrará más adelante) siempre
se mencionan en asociación con la asistencia,
guía y movimientos del Espíritu de Dios.

Puesto que el hombre, en su estado natural,
está excluido de actuar o moverse en las cosas espirituales, ¿cómo, o de qué manera,
debe ejercitar su primer y previo deber de esperar en Dios,
sino llevando la parte natural al silencio?
Y esto no se logra sino absteniéndose de sus pensamientos e imaginaciones,
y de todas las obras y movimientos de su propia mente,
tanto en las cosas ilícitas como en las lícitas, para que, estando en silencio,
Dios pueda hablar en él, y la buena Semilla se pueda levantar.
A pesar de que esto es difícil para el hombre natural, es tan consecuente con la razón,
e incluso con la experiencia natural en otras cosas, que no puede ser negado.
Porque aquel que desea aprender de un maestro,
si espera escuchar a su maestro y ser instruido por él,
no debe hablar sin cesar de lo que debe ser enseñado y nunca guardar silencio;
de otro modo, ¿cómo tendría su maestro tiempo para instruirlo?
Y aún si el estudiante está demasiado deseoso de aprender,
el maestro tendría buenas razones para reprenderlo,
si siempre se está entrometiendo y hablando,
y no esperando en silencio para escuchar pacientemente la instrucción de su maestro.
Es claro que el estudiante no debe abrir su boca
hasta que su maestro se lo ordene o se lo permita.

O si alguien fuera llamado a servir a un gran príncipe,
debe esperar con paciencia y disposición,
a fin de poder responder en cuanto el príncipe le hable,
manteniendo siempre su mirada en él para observar los más
pequeños movimientos e inclinaciones de su voluntad,
y luego obrar en consecuencia.
Pero sin duda sería considerado un siervo impertinente e imprudente si, en lugar de esto,
ensordeciera al príncipe con discursos (aunque fueran alabanzas para él),
y corriera de un lado a otro haciendo cosas que quizás fueran buenas en sí mismas,
pero sin haber recibido instrucción alguna para hacerlas.
¿Aceptarían los reyes de la tierra un siervo así?

Puesto que se nos manda "`esperar en Dios con diligencia,`" y al hacerlo,
se nos promete que "`nuestras fuerzas serán renovadas,`" este esperar no puede
realizarse sino por medio del cese o silencio de nuestra parte natural,
ya que Dios se manifiesta a Sí mismo, no tanto al hombre externo o a los sentidos,
sino al hombre interno, es decir, al alma y al espíritu.
Ahora bien, si el alma continúa pensando y obrando en su propia voluntad,
y está ocupada ejercitándose en sus propias imaginaciones
(aunque las cosas en sí mismas sean buenas,
o incluso concernientes a Dios),
con ello se incapacita para discernir el "`susurro apacible y delicado`" del Espíritu,
y se hace a sí misma un gran daño al desatender su
principal deber de esperar en el Señor. En efecto,
esto sería como alguien que clama y habla continuamente acerca de su negocio,
mientras que al mismo tiempo, desatiende a otro que le está susurrando al oído,
dándole información necesaria sobre su negocio.

Por lo tanto,
dado que el principal deber de un cristiano es experimentar
la voluntad natural (y sus movimientos) crucificada,
para que Dios pueda obrar en él tanto el querer como el hacer,
así también el Señor estima en gran manera la profunda sujeción
y negación del yo que implica el esperar en Él. Porque hay muchos
que se complacen a sí mismos en las cosas de la religión,
satisfaciendo sus propias voluntades y caprichos
carnales con especulaciones ambiciosas y curiosas,
haciéndose así un nombre y una reputación. Otros, por costumbre o por educación,
encuentran la religión placentera y habitual.
Pero estas personas muchas veces no están ni una pizca más regeneradas ni santificadas
internamente en sus espíritus que otras que abiertamente satisfacen sus deseos.
En verdad,
ambos tipos son igualmente dañinos para los hombres y pecaminosos ante los ojos de Dios,
produciendo únicamente el fruto y el efecto del espíritu
y voluntad naturales y no renovadas del hombre.
Porque incluso si un hombre, por conciencia de pecado y temor al castigo,
tratara de evitar pecar multiplicando pensamientos de muerte, infierno y juicio,
y también presentando en su imaginación los deleites del cielo,
y multiplicara plegarias y otros actos religiosos,
estas cosas no podrían librarlo de una sola iniquidad sin
el poder interno y secreto del Espíritu y la gracia de Dios.
En efecto,
esto lograría lo mismo que las hojas de higuera con las que Adán pensó cubrir su desnudez,
porque esas cosas son el mero producto de la voluntad del hombre natural,
que proceden del amor propio y del deseo de salvarse a sí mismo,
y no surgen exclusivamente de esa Semilla divina de justicia que
es dada por Dios a todos para gracia y salvación. Por tanto,
dicha religión es rechazada por Dios y de ninguna manera aceptable para Él,
ya que el hombre natural, con todas sus artes, habilidades y actividades,
es condenado por Él mientras permanece en ese estado natural.

Entonces,
este gran deber de esperar en Dios debe ejercitarse necesariamente en la negación del yo,
tanto interna como externamente, en una dependencia quieta y total en Dios.
El hombre debe retirarse de toda obra, imaginación y especulación de su propia mente,
de modo que,
vaciado de sí mismo y crucificado en una medida a los frutos naturales del yo,
sea hecho apto para recibir al Señor,
quien no tendrá copartícipe ni competidor en Su gloria y poder.
Y cuando el hombre se posiciona de esta manera delante del Señor,
la pequeña Semilla de justicia que Cristo ha comprado y Dios ha plantado en el
alma--la medida de gracia y vida que se ve oprimida y crucificada por los pensamientos
e imaginaciones naturales del hombre--recibe un lugar para incrementarse y llegar
a ser un nacimiento o generación santa en el hombre.
Este es ese don celestial de vida en y por el cual
el alma y espíritu del hombre son leudados.
Y al esperar en este don, el hombre llega a ser acepto delante de Dios,
a estar en Su presencia,
escuchar Su voz y observar los movimientos de Su Santo Espíritu.

Así pues, le corresponde al hombre esperar en esto.
Y aquí,
cuando se presentan en su mente pensamientos concernientes
a Dios o relacionados con la religión,
su alma puede involucrarse en ello sin perjuicio alguno,
sino más bien con gran beneficio tanto para sí mismo como para los demás,
porque aquí las cosas no brotan de su propia voluntad, sino del Espíritu de Dios.
Y a medida que el Espíritu se levanta, se mueve y enseña en su mente,
él puede involucrarse en el pensamiento y la meditación,
o en la predicación y la oración. Por esto,
también puede verse que no estamos en contra de la
meditación (como algunos nos han acusado falsamente);
sino que estamos en contra de los pensamientos e
imaginaciones del hombre natural en su propia voluntad,
a partir de lo cual provienen todos los errores y las herejías
concernientes a las religión cristiana en el mundo entero.

Pero si en algún momento le agrada a Dios, cuando uno o más esperan en Él,
no mostrarles cosas que tienden a ejercitar sus mentes con pensamientos e impresiones,
sino simplemente mantenerlos en una dependencia santa, y al persistir en esto,
hacer que Su refrigerio secreto y el toque puro de Su vida santa fluya sobre ellos,
entonces tienen buenas razones para estar contentos.
Porque por medio de esto (como sabemos por experiencia buena y bendita),
el alma es más fortalecida, renovada y afianzada en el amor de Dios,
y armada contra el poder del pecado, que por cualquier otro medio.
En efecto,
esto es un anticipo de ese gozo real y palpable de
Dios que los santos en el cielo poseen cada día,
y que Dios con frecuencia proporciona a Sus hijos aquí, para su aliento y consuelo,
especialmente cuando se reúnen para esperar en Él.

Porque hay dos poderes o espíritus contrarios, a saber:
el poder y espíritu de este mundo, en el que gobierna el príncipe de la oscuridad,
y por tanto reina sobre todos los que son movidos por él y obran desde él;
y el poder del Espíritu de Dios, en el cual Dios obra y gobierna,
y por tanto reina sobre todos los que obran en y desde él. Entonces,
cualquier cosa que el hombre piense o haga,
por muy espiritual o religiosa que parezca la idea o forma,
mientras actúe y se mueva en la voluntad y espíritu natural y corrupto (y no desde,
en y por medio del Poder de Dios), peca en todo lo que hace,
y no es acepto delante de Dios.
Así que, tanto la "`oración es abominable, como el labrar de los impíos, son pecado.`"
(Proverbios 28:9; 21:4). Por consiguiente,
todo lo que hace el hombre en y desde el Espíritu y poder de Dios,
teniendo su entendimiento y voluntad influenciados y movidos por Él,
ya sea en cosas religiosas, civiles o incluso naturales,
es acepto ante los ojos de Dios y bienaventurado en ellas (Santiago 1:25).

Además,
la excelencia de esta silenciosa espera en Dios también
se manifiesta en que es imposible para el enemigo (es decir,
el diablo) falsificarla, y así engañar o seducir a quienes la practican correctamente.
Ahora bien, en todos los demás asuntos,
él puede mezclarse con la mente natural del hombre, y,
disfrazándose (ver 2 Corintios 11:14), engañar al alma,
ocupándola con otras cosas (quizás inocentes en sí mismas),
mientras sigue impidiéndole ver la Luz pura de Cristo y conocer y hacer Su voluntad.
Porque el espíritu envidioso de la felicidad eterna del hombre,
sabe muy bien cómo acomodarse y ajustar sus trampas a las
diversas disposiciones e inclinaciones de los hombres.
Si encuentra a una persona que no es apta para ser
tentada con pecados abiertos o deseos mundanos,
siendo más bien reacia a tales cosas y más inclinada a lo religioso,
puede seducirla permitiendo que sus pensamientos e imaginaciones corran a asuntos espirituales,
impulsándola a obrar, actuar, meditar, etc., en su propia voluntad.
Él sabe muy bien que mientras el yo domine,
y el Espíritu de Dios no sea el actor principal y supremo,
el hombre no ha salido de su alcance.
De esta manera, el enemigo de la humanidad puede acompañar al sacerdote al altar,
al predicador al púlpito, al celoso en sus oraciones, y al teólogo a su estudio.
Y aquí,
de buena gana permitirá que los cristianos profesantes
se esfuercen y trabajen entre sus libros religiosos;
sí,
incluso les ayudará a descubrir e inventar sutiles distinciones y mezclas
mediante las cuales tanto sus mentes como las de otros a través de ellos,
sean apartadas de atender a la Luz de Dios en su conciencia y de esperar en Él.

Por lo tanto,
no hay ninguna actividad en la que el enemigo no pueda entrar y
ocupar un lugar principal (a menudo sin que el alma lo discierna),
excepto en esta silenciosa espera en Dios.
Porque solo puede obrar en y por medio del hombre natural y de sus facultades,
actuando secretamente sobre sus imaginaciones y deseos.
Por tanto, mientras el hombre esté pensando y meditando por sí mismo,
no puede estar seguro de que el diablo no lo esté influenciando.
Pero cuando el hombre natural es llevado al silencio
y a la nadedad con respecto a sus propias obras,
y la luz pura de Dios brilla en él, entonces el enemigo debe cesar,
porque no puede soportar la presencia ni el resplandor de la luz de Dios.

Es cierto que el enemigo no deja de asistir a nuestras reuniones, y en efecto,
él puede entrar y obrar en una reunión que guarda silencio solo en cuanto a las palabras,
ya sea manteniendo la mente ocupada en diversos pensamientos e imaginaciones,
o entorpeciéndola y abrumándola con un espíritu de pesadez y pereza.
Pero cuando nos retiramos de todo, y nos volvemos al Señor en nuestro interior,
y somos diligentes y vigilantes por un lado,
y también silenciosos y retirados de todos nuestros pensamientos por el otro,
y permanecemos en este lugar seguro, nos sentimos lejos de su alcance.
Sí, muchas veces el poder y la gloria de Dios irrumpen y aparecen,
así como el sol resplandeciente atraviesa las nubes y la neblina,
para disipar ese poder de las tinieblas que a menudo sentimos palpablemente,
buscando nublar y oscurecer la mente, y apartarla de esperar por completo en Dios.

Además,
la grandeza de esta adoración se muestra en que no puede ser detenida
o interrumpida por la malicia de los hombres o de los demonios,
como sí sucede con las otras formas de adoración. Ahora bien,
las interrupciones y suspensiones de la adoración pueden ocurrir de dos maneras:
ya sea porque se nos impide reunirnos usando de violencia externa,
separándonos unos de otros; o bien, cuando se nos permite reunirnos,
somos interrumpidos por tumultos,
ruidos y confusión que los malvados emplean para maltratarnos o distraernos.
Pues bien,
en ambos casos esta adoración supera con creces a todas las demás. En primer lugar,
aunque se nos impida reunirnos,
como cada uno se recoge internamente en la medida de vida en sí mismo,
disfrutamos de una comunión y unidad secreta que el diablo
y todos sus instrumentos nunca podrán romper o impedir.
En segundo lugar, en cuanto a los disturbios que ocurren cuando nos reunimos,
hemos podido (gracias a la naturaleza de esta adoración)
mantenernos sin interrupción delante de Dios,
y también dar un ejemplo de paciencia cristiana hacia todos,
a menudo incluso al punto de conmover y convencer a nuestros oponentes.
Porque hoy en día no hay ningún tipo de adoración practicada por otros,
que pueda continuar sin estar autorizada y protegida por el magistrado,
o defendida por armas carnales.
Sin embargo, nosotros muchas veces ejercemos nuestra adoración a Dios,
soportando también con paciencia las afrentas y agravios
que Cristo profetizó que serían frecuentes para los cristianos.
¿Acaso pueden los católicos celebrar su misa si hay
alguien presente para estorbarlos e interrumpirlos?
Basta con quitarles el misal, el cáliz, la hostia o las vestiduras del sacerdote,
o derramar el agua o el vino, o apagar las velas, y todo el asunto queda suspendido.
Quita a los luteranos o episcopales su liturgia o el Libro de Oración Común,
y no podrán llevar a cabo ningún servicio.
Quita a los calvinistas, arminianos, independientes o anabautistas, el púlpito,
la Biblia y el reloj de arena, o haz ruido para que no se oiga la voz del predicador,
o quítale su Biblia y sus libros, y entonces tendrán que permanecer en silencio.
Porque todos estos han declarado herejía esperar para hablar según el Espíritu da palabra,
y por tanto, toda su adoración puede ser fácilmente estropeada.

Sin embargo,
cuando las personas se reúnen y su adoración no depende de que alguien hable,
ni consiste en actos externos, sino en sentarse a esperar en Dios,
y reunirse fuera de todo lo visible para sentir al Señor en Espíritu,
entonces ninguna de estas cosas puede obstaculizarlos.
De esto, podemos decir, en verdad, que tenemos mucha experiencia personal.
Porque cuando los magistrados, incitados por la malicia y envidia de nuestros oponentes,
han usado todos los medios posibles para impedir que nos reunamos--por medio de multas,
golpes, azotes,
destierros e incluso la muerte--todo ha resultado ineficaz
para hacernos desistir de nuestras santas asambleas.
En efecto,
sería casi increíble relatar la maldad que los hombres (que
pretenden ser cristianos) han volcado sobre nosotros.
Porque muchas veces nos han golpeado,
y durante nuestras reuniones nos han arrojado agua y tierra.
Allí han bailado, brincado, cantado y hablado todo tipo de palabras profanas e impías;
han ejercido violencia y se han comportado vergonzosamente
contra mujeres y vírgenes sobrias;
se han mofado, burlado y escarnecido preguntándonos: "`¿No ha llegado aún el Espíritu?`",
y mucho más que sería tedioso relatar.

Pero a pesar de todo esto, hemos continuado, seria y silenciosamente,
sentándonos juntos y esperando en el Señor. De modo que, por todas estas cosas,
nuestra comunión interna y espiritual con Dios y entre nosotros en la vida pura de justicia,
no ha sido estorbada.
Por el contrario, el Señor,
teniendo conocimiento de nuestros sufrimientos y afrentas por causa de Su testimonio,
ha hecho que Su poder y gloria abunden aún más entre nosotros,
y nos ha refrescado poderosamente mediante la experiencia de Su amor,
el cual ha llenado nuestras almas y ha hecho que nos sintamos reunidos
en el "`nombre del Señor,`" que es la "`torre fuerte`" del justo.
Sí, algunas veces, en medio del tumulto y oposición,
Dios nos ha movido poderosamente por Su Espíritu,
tanto a testificar de ese gozo del que disfrutamos,
como a declarar con poder (en la evidencia y demostración
del Espíritu) en contra de su insensatez y maldad.
Y así, a veces,
hemos visto el poder de la Verdad llevarlos a cierta medida de quietud y silencio,
frenando las impetuosas corrientes de su furia y locura.

De hecho, así como Moisés, con su vara,
dividió las aguas del Mar Rojo para que los israelitas pasaran, así también Dios,
por medio de Su Espíritu,
nos ha abierto camino en medio de esta furiosa maldad
para que podamos disfrutarlo y poseerlo en paz,
y rendirle nuestra adoración. Y en algunas de estas ocasiones,
varios de nuestros oponentes e perturbadores han sido convencidos de la Verdad,
y transformados de perseguidores a sufrientes junto con nosotros.
Y no debe olvidarse, sino quedar registrado y permanecer como un constante recuerdo,
que en estas acciones bestiales y brutales usadas
para molestarnos en nuestras reuniones espirituales,
ninguno ha estado más ocupado que los jóvenes estudiantes de las
universidades que estaban estudiando filosofía y teología,
y (en muchos casos) preparándose para el ministerio.
Si pusiéramos por escrito todas las abominaciones
cometidas en este sentido por los jóvenes clérigos,
no sería un volumen pequeño.

Así sabemos que somos participantes de la dispensación del Nuevo Pacto,
y verdaderos discípulos de Cristo,
compartiendo con Él en esa adoración espiritual que
se lleva a cabo en Espíritu y en Verdad,
"`pues como Él es,
así somos nosotros en este mundo`" (1 Juan 4:17).
Porque la adoración del Antiguo Pacto tenía una gloria,
un templo y ceremonias externas, y estaba lleno de esplendor y majestad externos,
con un tabernáculo y altar externos, embellecido con oro, plata y piedras preciosas.
Sus sacrificios eran atados a un lugar externo en particular, es decir,
el Monte Sion externo,
y los que oraban lo hacían con sus rostros vueltos hacia ese templo externo.
Todo esto tenía que ser protegido por un brazo externo,
porque los judíos no podían disfrutar pacíficamente de estas cosas,
excepto cuando eran resguardados de la violencia de sus enemigos externos.
Por tanto, cuando en algún momento sus enemigos prevalecían sobre ellos,
su gloria se oscurecía,
sus sacrificios cesaban y la expresión de su adoración perdía su belleza.
Por esta razón, se quejaban,
lamentaban y lloraban la destrucción del templo como una pérdida irreparable.

Pero Jesucristo, el autor y fundador de la adoración del Nuevo Pacto,
testifica que Dios no debe ser adorado en este u otro lugar,
sino en Espíritu y en Verdad.
Y como Su "`reino no es de este mundo,`" su adoración
tampoco consiste en cosas del mundo,
ni requiere de la sabiduría, gloria,
riquezas o esplendor de este mundo para embellecerla o adornarla,
ni necesita un poder externo o brazo de carne para sostenerla, apoyarla o protegerla.
Antes bien, puede ser realizada por hombres espirituales a pesar de toda la oposición,
violencia y malicia de los hombres.
Porque al ser completamente espiritual,
está fuera del alcance de los hombres naturales para interrumpirla o molestarla.

Ahora bien,
es muy cierto que Jesucristo experimentó y poseyó
Su reino espiritual aun mientras era oprimido,
perseguido y rechazado por los hombres.
Y a pesar de la malicia y furia del diablo,
"`despojó a los principados y a las potestades...triunfando sobre ellos;
para destruir por medio de la muerte al que tenía el imperio de la muerte, esto es,
el diablo.`"
Por consiguiente, todos los seguidores de Cristo pueden adorarle, y de hecho lo hacen,
no solo sin un brazo de carne que los proteja, sino incluso cuando son oprimidos,
porque su adoración (siendo espiritual) es defendida y mantenida por el poder del Espíritu.
Pero aquella adoración que es carnal y consiste en
ceremonias y observancias externas y carnales,
necesita de un brazo externo y carnal que la proteja y defienda,
de lo contrario no puede permanecer ni subsistir.
Por lo tanto,
es evidente que la adoración de nuestros oponentes (tanto protestantes como católicos),
no es la verdadera adoración espiritual y del Nuevo Pacto de Cristo Jesús,
porque se ha observado desde hace mucho tiempo que no pueden permanecer
sin el consentimiento y protección del magistrado externo,
ni pueden realizar su adoración en medio de la menor oposición,
porque no están en la paciencia de Jesús, para servirle y adorarle con sufrimientos,
deshonra, calumnias y afrentas.
Y de aquí han brotado todas las guerras, contiendas,
persecuciones y derramamientos de sangre entre los cristianos,
cuando cada grupo se ha esforzado (por medio del brazo de
carne) por defender y proteger su propia forma y adoración.

Ahora, la naturaleza de esta adoración,
que es llevada a cabo por la operación del Espíritu (estando en silencio el hombre natural),
es declarada en estas palabras de Cristo (Juan 4:23-24): "`Mas la hora viene, y ahora es,
cuando los verdaderos adoradores adorarán al Padre en Espíritu y en Verdad:
porque el Padre tales adoradores busca que le adoren.
Dios es Espíritu; y los que le adoran, en Espíritu y en Verdad es necesario que adoren.`"
Esta declaración debe ser cuidadosamente observada, pues es el primer,
principal y más amplio testimonio dado por Cristo de la verdadera adoración cristiana,
mostrando que es distinta y separada de la adoración bajo la Ley.
Aquí Él muestra que ha llegado el tiempo en que la
adoración debe ser "`en Espíritu y en Verdad;
porque el Padre tales adoradores busca que le adoren.`"
Entonces,
ya no se trata de una adoración que consiste en observancias externas
llevadas a cabo por el hombre en tiempos u ocasiones determinados,
que pueden hacer en su propia voluntad y mediante su propia fuerza natural,
pues si así fuera, no diferiría en sustancia, sino sólo en algunos detalles,
de la adoración bajo la ley.
Y en cuanto a la razón de esta adoración,
no podemos dar una mejor que la que Cristo da aquí,
la cual debería ser suficiente para satisfacer a cada Cristiano, a saber:
que "`DIOS es ESPÍRITU, y los que le adoran,
en Espíritu y en Verdad es necesario que adoren.`"
Y aunque esto debería ser recibido por todos, simplemente por ser palabras de Cristo,
además se funda en una demostración clara de la razón.
Porque Cristo argumenta de manera simple y excelente,
que siendo Dios Espíritu, debe ser adorado en Espíritu.
Esto es tan evidente y cierto, que no admite contradicción alguna.

Porque bajo la Ley,
cuando Dios instituyó y señaló esa adoración ceremonial para los judíos,
siendo esa adoración externa,
consideró necesario condescender con ellos de manera especial,
morando entre los querubines en el tabernáculo,
y más tarde haciendo del templo en Jerusalén Su habitación. También hizo
que algo de su gloria y majestad externa se manifestara a ellos,
haciendo descender fuego del cielo para consumir
los sacrificios y llenando el templo con una nube.
De estas maneras (todas visibles al ojo externo),
Él se manifestó proporcionalmente a esa adoración externa que les había ordenado realizar.

Pero ahora, bajo el Nuevo Pacto, Dios ha considerado apropiado,
en Su sabiduría celestial, dirigir a Sus hijos por un camino más celestial y espiritual,
con la intención de frustrar las observaciones externas y carnales,
para que Su pueblo ponga su mirada más en la gloria y reino interno que en lo externo.
Él ha establecido una adoración interna y espiritual,
y por tanto ya no ata a su pueblo al templo de Jerusalén,
ni a ceremonias y observancias externas,
sino que toma el corazón de cada cristiano como templo para morar en él,
y allí aparece directamente y enseña cómo servirle en cualquier acto externo.
Dado que Cristo dice: "`Dios es Espíritu,`" ahora debe ser adorado _en el Espíritu,_
en donde Él se revela y mora con el quebrantado de corazón. De hecho,
el corazón del hombre se ha convertido ahora en el templo de Dios, donde será adorado,
y ya no más en templos externos particulares (pues, como está escrito:
"`El Altísimo no habita en templos hechos de mano`"). Y así como en el
pasado la gloria del Señor descendía para llenar el templo externo,
y por ello era necesario que fuese purificado y limpiado, quitando toda la contaminación,
sí, y que las cosas del tabernáculo fuesen recubiertas con el oro más precioso,
y con metales limpios y costosos; así también,
antes de que Dios pueda ser adorado en el templo interno del corazón,
éste también debe ser purgado de su propia inmundicia,
y de todos sus pensamientos e imaginaciones,
para que esté preparado para recibir al Espíritu
de Dios y ser movido por Él. Por lo tanto,
esta adoración es en Espíritu,
y es también "`en Verdad,`" lo que significa (por las razones arriba mencionadas),
que es la única adoración correcta y verdadera,
que no puede ser falsificada por el enemigo, ni realizada por el hipócrita.

Ahora bien,
aunque esta adoración espiritual es de hecho muy diferente de las
diversas adoraciones establecidas e inventadas entre los cristianos,
y por ello puede parecer extraña a muchos, sin embargo ha sido testificada,
encomendada y practicada por los más piadosos de toda índole, en todas las edades.
Esto se puede demostrar fácilmente por una multitud de testimonios,
y es a partir de la profesión y práctica de estas
cosas que ha surgido el nombre de "`místicos.`"
Estos llamados místicos son una secta generalmente
elogiada por todos (tanto católicos como protestantes),
y sus escritos están llenos tanto de explicaciones como de elogios a este tipo de adoración,
insistiendo en la introversión interior y en la abstracción de la mente (como lo llaman),
de todas las imágenes, pensamientos y oraciones de la voluntad del hombre.
De hecho, ellos consideran esta adoración como la cumbre de la religión cristiana,
de modo que algunos de ellos, aunque profesan el catolicismo romano,
afirman con valentía: "`Aquellos que han alcanzado este método de adoración,
o están encaminados hacia él,
no deben preocuparse ni ocuparse de confesiones frecuentes e innecesarias,
ni de ejercicios corporales y austeridades,
ni de la práctica de oraciones voluntarias y verbales,
de la asistencia a numerosas misas, de devociones programadas,
celebraciones a los santos, oraciones por los muertos, indulgencias,
ni enredarse con votos y promesas;
porque esas cosas tienden a impedir que el alma observe
las operaciones del Espíritu divino en el interior,
y tenga libertad de seguir al Espíritu donde sea que lo dirija.`"^
footnote:[[.book-title]#Sancta Sophia,# por Augustine Baker, ofrecido por los Ingleses Benedictinos,
publicados en Douay, año 1657, trat. I, sec. ii, cap. 5]
Y sin embargo,
¿quién no sabe que la sustancia misma de la religión católica
romana consiste en tales observancias y prácticas externas?
No obstante,
se desprende de este y muchos otros pasajes de sus propios escritores místicos,
que estos hombres y mujeres consideraban que esta
adoración espiritual era superior a todas las demás,
y que aquellos que la habían alcanzado, no tenían necesidad de las otras.
En efecto, aquellos que la habían probado,
confesaron rápidamente que todas las otras formas
y ceremonias de adoración les eran inútiles;
ni las llevaban a cabo como cosas necesarias,
sino solamente por el bien del orden o del ejemplo.^
footnote:[La Vida de Balthazar Alvares, en la misma [.book-title]#Sancta Sophia,#
trat. III, sec. i, cap. 7]

Así pues,
a pesar de que algunos de estos hombres y mujeres permanecieron
oscurecidos por las tinieblas comunes de su profesión religiosa,
no por ello dejaban de afirmar que la adoración espiritual debía ser conservada y buscada,
incluso si requería la omisión de sus ceremonias externas.
Así lo expresó Bernard de Clairvaux cuando escribió:
"`Presten atención al gobierno de Dios, el reino de Dios está en vosotros;`" y después,
al decir que sus leyes y reglas externas debían ser guardadas, añadió:
"`Pero cuando suceda que una de estas dos deba ser omitida,
en tal caso deben ser mucho antes omitidas las leyes externas que las internas; pues,
cuanto más excelente y noble es el Espíritu que el cuerpo,
tanto más provechosos son los ejercicios espirituales que los corporales.`"^
footnote:[En su Epístola a William, un abad del mismo orden.]

¿No debería, pues,
ser seguida y cumplida aquella clase de adoración que los mejores
hombres de todos los tiempos y de todas las sectas han elogiado,
y que además es la más conforme a la doctrina de Cristo?
¿No deberían todos los hombres adorarle en Espíritu y en Verdad,
especialmente ahora que ha levantado un pueblo para testificar
y predicar de esta adoración ante todo el mundo,
a pesar de la gran oposición? Y estos ministros de Cristo no hacen ahora
(como erróneamente lo hicieron los místicos) de esta adoración un misterio
reservado solo para unos pocos hombres o mujeres en un claustro,
ni sugieren que sea alcanzado solo tras haberse afanado
bajo muchas ceremonias y observancias externas,
como si fuera el fruto de tales esfuerzos.
Más bien, predican el amor gratuito de Dios, que no hace acepción de personas,
que estaba cerca para oír y revelarse a Sí Mismo a Cornelio, un centurión y un romano,
y a Simeón y a Ana; que reveló Su gloria a María, una pobre sierva,
y a los humildes pastores,
antes que a los sumos sacerdotes y conversos devotos
entre los judíos. Y en y conforme a Su amor gratuito,
estos ministros están viendo que Dios está revelando
y estableciendo esta adoración en multitudes,
y haciendo que muchos comerciantes pobres (sí,
incluso niños y niñas) sean testigos de ella.
Y están suplicando e instando a todos que dejen a un lado su propio culto voluntario,
y los actos realizados en sus propias voluntades y por medio de su propia fuerza
y poder natural (sin retirarse de sus imaginaciones y pensamientos vanos,
ni sentir que el Espíritu puro de Dios los mueve y despierta),
para que así puedan llegar a practicar esta adoración
aceptable que es "`en Espíritu y en Verdad.`"

=== Objeciones Contestadas

[.no-indent]
Pero contra esta adoración objetan:

[.discourse-part]
Objeción: En primer lugar,
parece ser un ejercicio infructuoso que un hombre no haga ni piense en nada.
Sería mucho mejor ocupar el tiempo meditando en algún buen tema, orando o alabando a Dios.

[.discourse-part]
Respuesta: Respondo,
aquello que es absolutamente necesario antes de que todos los otros deberes
puedan llevarse a cabo de manera aceptable (como hemos demostrado),
no puede ser infructuoso.
Además, aquellos que imaginan que Dios se complace por sus propios esfuerzos y acciones,
no tienen más que una comprensión carnal y bestial de Dios y de las cosas de Su reino.
Porque, como se ha demostrado con claridad,
el primer paso del hombre hacia el temor del Señor es cesar de sus propios pensamientos
e imaginaciones y permitir que el Espíritu de Dios obre en él;
porque debemos "`dejar de hacer lo malo,`" antes de "`aprender
a hacer el bien`" (Isaías 1:16-17). De hecho,
esta intromisión en las cosas espirituales por medio del entendimiento natural del hombre,
es uno de los males más grandes y más peligrosos a los que está inclinado el hombre,
siendo la razón de la caída de nuestros primeros padres, a saber:
adelantarnos a desear conocer las cosas, y entrometernos en ellas,
tanto sin el mandato del Señor como en contra de él.

[.discourse-part]
Objeción: En segundo lugar, algunos argumentan,
"`Si su adoración consiste simplemente en retirarse internamente al Señor,
sintiendo Su Espíritu levantarse en ustedes,
y luego hacer cualquier obra que Él los guíe a realizar,
¿qué necesidad tienen de reunirse públicamente en tiempos y lugares determinados,
ya que todos pueden disfrutar de esto en casa?
¿No debería cada uno quedarse en casa hasta que sea
movido a ir a un lugar o hacer algo en particular?
¿No es acaso reunirse en lugares y tiempos determinados
una observancia y ceremonia externas,
contrario a lo que afirman?`"

[.discourse-part]
Respuesta: Respondo,
reunirse en tiempos o lugares determinados no es
en sí un acto religioso o una parte de la adoración,
sino sólo una conveniencia externa,
necesaria para vernos los unos a los otros mientras
estamos revestidos de este tabernáculo exterior.
No obstante, mientras Sus hijos estén en este mundo,
Dios ha visto oportuno valerse de los sentidos externos
como medios para transmitir la vida espiritual,
mediante acciones como hablar, orar, alabar, etc.,
las cuales no pueden realizarse para la mutua edificación
excepto cuando nos oímos y nos vemos unos a otros.

Por lo tanto,
el Señor a menudo hace que la vida interna (que muchas
veces no se transmite por los sentidos externos),
abunde aún más cuando Sus hijos se congregan diligentemente para esperar en Él. Así que,
vernos unos a otros mientras todos estamos reunidos internamente en la Vida,
se da oportunidad para que la Vida se levante secretamente y pase de vasija en vasija,
así como "`hierro con hierro se aguza.`"
O incluso,
como muchas velas en un solo lugar incrementan grandemente la luz y la hacen brillar más,
así también, cuando muchos se reúnen en la misma Vida, hay más de la gloria de Dios,
y Su poder se manifiesta para refrescar a cada individuo,
quien participa no solo de la Luz y la Vida que se levantan en sí mismo,
sino también de las que se levantan en todos los demás. De este modo,
Cristo ha prometido una bendición particular a quienes se reúnen en Su Nombre,
diciendo que Él estaría "`en medio de ellos`" (Mateo 18:20).

Además, el autor de la epístola a los Hebreos prohíbe expresamente descuidar este deber,
por considerarlo de consecuencias muy peligrosas y terribles, diciendo:
"`Y considerémonos unos a otros para estimularnos al amor y a las buenas obras;
no dejando de congregarnos, como algunos tienen por costumbre&hellip;
Porque si pecáremos voluntariamente
después de haber recibido el conocimiento de la verdad,
ya no queda más sacrificio por los pecados`" (Hebreos 10:24-26). Por tanto,
el Señor ha manifestado una consideración particular
hacia aquellos que se congregan de esta manera,
no solo para la edificación mutua de cada miembro,
sino también para que se mantenga un testimonio público
de Él en la tierra y Su Nombre sea glorificado.
Y ciertamente, aquellos que son rectos en sus espíritus,
son naturalmente atraídos a perseverar en las reuniones del pueblo de Dios,
y nunca les falta de la influencia del Espíritu que los conduce a ello.

[.discourse-part]
Objeción: Por último,
algunos objetan que esta forma de adorar en silencio no se halla en todas las Escrituras.

[.discourse-part]
Respondo: Primero, no hacemos del silencio el asunto principal de nuestra adoración,
ya que (como mencioné previamente) son muy pocas
las reuniones que transcurren en completo silencio,
sin que alguno sea movido a predicar, orar, o alabar al Señor. De este modo,
creemos que nuestras reuniones se asemejan mucho a las reuniones
de las iglesias primitivas que se describen en las Escrituras,
pues incluso nuestros adversarios confesarán que
ellos no predicaban ni oraban sino por el Espíritu.
Por tanto,
¿no es probable que hubiera momentos en la iglesia primitiva
en que el Espíritu no los movía a hablar ni a actuar,
y que entonces guardaran silencio?
De hecho,
no cabe duda de que hubo momentos de silencio antes
de que el Espíritu viniera sobre ellos.
Porque les fue dicho: "`Quedaos en la ciudad de Jerusalén,
hasta que seáis investidos de poder desde lo alto.`"
Y cuando "`estaban todos unánimes juntos;`" entonces,
el Espíritu cayó de repente sobre ellos.
No se hace mención aquí de que alguno hablara en ese momento,
y no es absurdo concluir que guardaron silencio durante un rato.

Pero si se insiste que en las Escrituras no se halla una reunión completa en silencio,
yo respondo: aunque tal cosa no estuviera registrada en las Escrituras, no se concluye,
por lo tanto, que sea ilícito,
ya que se desprende naturalmente de otros preceptos bíblicos ya mencionados.
Porque las Escrituras nos mandan a menudo esperar en el Señor y también congregarnos.
Y cuando estamos reunidos, las Escrituras prohíben orar o la predicar,
excepto cuando el Espíritu mueve y dirige.
Por tanto, si las personas se han reunido y el Espíritu no las mueve a hablar o actuar,
necesariamente se deducirá que deben guardar silencio.
De hecho,
bien pudo haberse realizado entre los santos de la antigüedad muchas
cosas semejantes que no hayan sido registradas en las Escrituras;
con todo,
tenemos suficiente testimonio en ellas que manifiesta
que tales reuniones sí tuvieron lugar.
Pues Job estuvo sentado en silencio por siete días junto con sus amigos (Job 2:13);
he aquí una larga reunión en silencio.
Ver también Esdras 9:4, y Ezequiel 14:1 y 20:1.

Así, habiendo mostrado la excelencia de esta adoración,
probado con las Escrituras y la razón,
y respondido a las objeciones que por lo general se hacen en su contra,
agregaré algo más en particular acerca de la predicación, la oración y el canto.

=== La Predicación

La predicación,
tal como se practica tanto entre los católicos romanos como en los protestantes,
consiste en que un hombre toma un pasaje de las Escrituras,
y luego habla sobre él por una hora o dos,
según lo que ha estudiado y premeditado en su aposento,
y ha recogido a partir de sus propias invenciones,
o a partir de los escritos y observaciones de otros.
Luego, tras haberlo memorizado (como hace un escolar con su lección),
lo presenta y lo repite delante de la congregación. Y cuanto
más animada y fuerte sea la invención del hombre,
y cuanto más industrioso y laborioso sea en reunir sus observaciones
y en exponerlas con excelencia de palabras y elocuencia humana,
tanto más se le considera un predicador excelente y capaz.

A esto nos oponemos, creyendo que, cuando los santos se reúnen,
cada uno debe volverse internamente al don y gracia de Dios dentro de sí mismo,
y que aquel que ministra debe ser movido a ello por
el surgimiento de la gracia en sí mismo.
Él debe hablar lo que el Espíritu de Dios le da que hable,
sin prestar atención a la elocuencia ni a la sabiduría de las palabras,
sino a la demostración del Espíritu y poder.
Aquí,
él puede interpretar alguna parte de las Escrituras que
el Espíritu traiga a su mente y lo dirija a compartir,
u ofrecer palabras de exhortación, consejo, reprensión e instrucción,
o relatar el significado de algunas experiencias espirituales,
todo lo cual será conforme a las Escrituras,
aunque quizás no esté basado en algún capítulo o versículo en particular como texto base.

Examinemos ahora y consideremos cuál de estos dos tipos de predicación
está más de acuerdo con los preceptos y prácticas de Cristo,
de Sus apóstoles y de la iglesia primitiva, tal como se registra en las Escrituras.
Primero, en cuanto a la predicación basada en un texto,
si esta no fuera meramente habitual y premeditada,
sino llevada a cabo por la directa operación del Espíritu,
no tendríamos nada en su contra.
Pero hacerlo de la manera que es común entre la mayoría
de los cristianos profesantes de hoy día,
no tiene--por lo que puedo observar--ni precepto ni práctica en todo el Nuevo Testamento.

[.discourse-part]
Objeción: Se alega que Cristo tomó el libro de Isaías,
leyó de él y luego habló a partir de ese texto.
Y, del mismo modo, que Pedro predicó a partir del pasaje del profeta Joel.

[.discourse-part]
Respuesta: Cristo y Pedro no lo hicieron sino en cuanto fueron influenciados
y movidos directamente por el Espíritu de Dios,
y sin premeditación (lo cual supongo que nuestros adversarios no negarán);
en cuyo caso lo aprobamos con gusto.
Pero esto dista mucho de la forma acostumbrada e inventada en que se practica hoy,
sin esperar ni anhelar los movimientos ni la guía del Espíritu de Dios.
Además,
es claro que ni Cristo ni Pedro hicieron esto como una costumbre o forma establecida
que debía ser practicada constantemente por todos los ministros de la iglesia,
pues no aparece en la mayoría de los sermones de Cristo y de Sus apóstoles
que han quedado registrados en las Escrituras (véase Mateo 5:1;
Marcos 4:1; las predicaciones de Pablo a los Atenienses y a los Judíos;
etc.). Muy por el contrario, cuando Cristo envió a Sus discípulos,
les mencionó expresamente que ellos no debían hablar desde sí mismos,
o preparar algo de antemano,
sino "`lo que el Espíritu Santo os enseñará en la misma hora,`" tal como
es mencionado particularmente por los tres evangelistas (Mateo 10:20;
Marcos 13:11; Lucas 12:12).

Ahora bien, si Cristo dio esta orden a Sus discípulos antes de separarse de ellos,
como algo que debían practicar,
con cuánta más razón debían hacerlo después de Su partida,
ya que entonces recibirían con mayor plenitud al Espíritu quien los guiaría
a toda la verdad y les recordaría todo lo que Él les había dicho.
(Ver Juan 14:26;
16:13) Y si debían hacerlo así cuando comparecieran
ante los magistrados y príncipes de la tierra,
cuánto más en su adoración a Dios,
estando delante de Aquel cuya adoración debe ser en Espíritu.
Por tanto, después de que recibieron el Espíritu Santo, se dice que:
"`comenzaron a hablar, según el Espíritu les daba que hablasen`" (Hechos 2:4),
y no según lo que habían estudiado y reunido de los libros de manera premeditada.

Francis Lambert habla acertadamente y expone su hipocresía, diciendo:

[quote]
____
¿Dónde están ahora aquellos que se glorían en sus invenciones espirituales, diciendo:
"`¡Qué gran invención! ¡Qué gran invención!`",
refiriéndose a lo que han inventado a partir de las Escrituras?
Pero ¿qué tienen que ver los fieles con tales invenciones?
No, no queremos invenciones, sino más bien cosas que sean sólidas, invencibles,
eternas y celestiales; no lo que los hombres han inventado,
sino lo que Dios ha revelado.
Porque si creemos las Escrituras, nuestras invenciones no aprovechan para nada,
sino para provocar a Dios a nuestra destrucción.
____

Y después escribe:

[quote]
____
Guárdate de determinar hablar con precisión lo que has meditado con anticipación,
sea lo que sea.
Porque si bien es lícito decidir el texto que vas a exponer, no así la interpretación;
no sea que, al hacerlo, arrebates al Espíritu lo que Le pertenece, a saber:
dirigir tu hablar para que profetices en el nombre del Señor,
despojado de todo conocimiento, meditación y experiencia.
Debes entregar tu corazón, tu lengua y a ti mismo por completo a Su Espíritu,
no poniendo confianza alguna en tu estudio o meditación previa,
sino diciendo dentro de ti mismo (con gran confianza en la divina promesa):
"`El Señor dará la palabra con poder a los que verdaderamente predican el evangelio.`"

Pero sobre todas las cosas, ten cuidado de no seguir la costumbre de los hipócritas,
quienes han escrito casi palabra por palabra lo que van a decir,
como si fueran a repetir algunas líneas en el teatro.
De hecho, éstos le piden al Señor que dirija su lengua,
pero mientras tanto obstaculizan al Espíritu Santo,
habiendo decidido no decir nada excepto lo que han escrito.
¡Oh infeliz clase de profetas!
Sí, verdaderamente malditos son los que no dependen del Espíritu
de Dios sino de sus propios escritos y meditaciones.
¿Por qué oras al Señor, falso profeta,
para que te dé Su Espíritu Santo mediante el cual hablar cosas provechosas,
y sin embargo rechazas Su Espíritu?^
footnote:[Trat. 5, de la Profecía, capítulo 3]
____

Ahora,
esta forma de predicación premeditada (como todos afirman) puede ser llevada a cabo,
y a menudo lo es, por hombres malos o carentes de la gracia verdadera; por tanto,
no solo falla en edificar a la iglesia o en engendrar y nutrir la verdadera fe,
sino que es destructiva para ella,
siendo directamente contraria a la naturaleza del ministerio
cristiano y apostólico mencionado en las Escrituras.
Porque el apóstol predicó el evangelio "`no con sabiduría de palabras,
para que no se haga vana la cruz de Cristo`" (1 Corintios 1:17). Mas esta predicación,
al no ser realizada por la obra y movimiento del Espíritu de Dios,
sino por la invención y elocuencia del hombre,
en su propia voluntad y por medio de su conocimiento y habilidades naturales y adquiridas,
está claramente basada en la sabiduría de palabras, y por lo tanto,
la cruz de Cristo se hace vana.

La palabra y predicación del apóstol no fueron "`con
palabras persuasivas de humana sabiduría,
sino con demostración del Espíritu y de poder,`" para que la fe
de los oyentes "`no esté fundada en la sabiduría de los hombres,
sino en el poder de Dios`" (1 Corintios 2:3-5). Pero la predicación premeditada,
que no tiene nada del Espíritu ni del poder en ella (pues tanto los predicadores
como los oyentes confiesan libremente que no esperan tal cosa,
ni suelen ser conscientes de ello),
debe necesariamente consistir en palabras persuasivas de humana sabiduría.
Y puesto que esta predicación es buscada por la sabiduría del hombre,
y expresada con la fuerza de la elocuencia del hombre y las palabras persuasivas,
no es de extrañar que la fe de los que oyen y dependen de tales predicadores y predicaciones,
esté fundada en la sabiduría humana y no en el poder de Dios.
Los apóstoles declararon que ellos hablaron "`no
con palabras enseñadas por sabiduría humana,
sino con las que enseña el Espíritu`" (1 Corintios 2:13). Sin embargo,
estos predicadores confiesan que son ajenos al Espíritu
Santo y a Sus movimientos y operaciones,
ni tampoco esperan sentirlos.
Por tanto,
hablan con las palabras que les enseña su propia sabiduría natural y su conocimiento,
mezclándolas y añadiéndoles las palabras que hurtan de las Escrituras y de otros libros,
y así no hablan lo que enseña el Espíritu Santo.

Además,
esta predicación es contraria al método y orden de la iglesia
primitiva mencionado por el apóstol en 1 Corintios 14:30,
etc., donde, al predicar,
cada uno debía esperar su revelación y dar lugar
unos a otros según eran reveladas las cosas.
Pero ahora no se espera la revelación,
y aun así el predicador debe hablar--no lo que le ha sido revelado,
sino lo que ha preparado y premeditado de antemano.

Por último, mediante este tipo de predicación,
el Espíritu de Dios--quien debe ser el principal instructor y maestro del pueblo de Dios,
y cuya influencia es la única que hace que toda predicación sea efectiva
y beneficiosa para la edificación de las almas--queda excluido,
y en su lugar se establece y se exalta la sabiduría,
el conocimiento y las habilidades naturales del hombre.
Esta (sin duda) es una de las principales razones por las que la predicación
entre la mayoría de los cristianos es tan infructuosa e ineficaz.
De hecho, según esta doctrina, el diablo podría predicar, y debería ser también oído,
puesto que conoce la verdad y tiene tanta elocuencia como cualquiera.
Pero ¿de qué sirve la excelencia de palabras,
si la demostración y el poder del Espíritu que toca la consciencia no está presente?
Vemos en las Escrituras que, aun cuando el diablo confesaba la verdad,
Cristo no recibía su testimonio.
Y así como estos testimonios de las Escrituras prueban que esta
clase de predicación es contraria a la doctrina de Cristo,
asimismo prueban que la nuestra es confirmada.

[.discourse-part]
Objeción: ¿Acaso no se han beneficiado muchos--sí,
incluso han sido convertidos y edificados--por el ministerio
de aquellos que han premeditado sus predicaciones?
¿Y no ha obrado muchas veces el Espíritu, mediante Su influencia divina,
con predicaciones premeditadas,
de modo que algunas han impactado poderosamente las almas de los oyentes para su beneficio?

[.discourse-part]
Respuesta: Aunque esto se conceda (pues no lo voy a negar),
no implica que la práctica sea buena en sí misma,
así como tampoco se puede sugerir que la aparición de Cristo a Pablo en el camino
a Damasco pruebe que él obraba bien en su labor de perseguir a los santos.
Porque, como hemos dicho en otro lugar,
ni las acciones particulares ni las congregaciones enteras deben ser evaluadas
por los actos de condescendencia de Dios en tiempos de ignorancia.
De hecho, ha sucedido a menudo que Dios,
teniendo en cuenta la simplicidad e integridad del predicador o de los oyentes,
ha descendido sobre el corazón del predicador con Su poder y santa influencia,
y por medio de ello le ha guiado a hablar cosas que no estaban en su discurso premeditado,
o quizás cosas que nunca antes había concebido.
Y estas exclamaciones pasajeras y exhortaciones no premeditadas, pero vivas,
han resultado a menudo más beneficiosas y refrescantes tanto para
el predicador como para los oyentes que todos sus sermones premeditados.
Aun así, la amable condescendencia del Señor de esta manera en este sentido
no debería animar la continuación de aquellas cosas que,
en sí mismas, no son aprobadas, sino que, de hecho,
son contrarias a la práctica de los apóstoles,
especialmente ahora que Dios está levantando un pueblo para
que le sirva según la pureza y espiritualidad primitivas.
En realidad,
tales actos de la misericordia de Dios en los tiempos de tinieblas e ignorancia deberían
comprometernos más a seguirle según Él revela Su camino más perfecto y espiritual.

=== La Oración

Habiendo hablado de la predicación, es conveniente ahora hablar de la oración,
acerca de la cual surge una controversia similar.
Nuestros adversarios, cuya religión es principalmente externa,
y cuyas acciones son meros productos de la voluntad y habilidades naturales del hombre,
pueden orar así como predican--cuando lo deseen--y por
ello tienen sus oraciones particulares determinadas.
No pretendo entrometerme en las controversias entre ellos sobre esto,
ya que algunos de ellos prefieren oraciones establecidas, como una liturgia, y otros,
oraciones concebidas de forma extemporánea.
Me basta que todos ellos estén de acuerdo en esto:
que los movimientos e influencias previos del Espíritu de Dios no son necesarios.
Por tanto, ellos han establecido momentos de oración en su adoración pública,
como antes y después de la predicación, y también en sus devociones privadas,
como en las mañanas y en las tardes, o antes y después de las comidas,
y en otras ocasiones semejantes,
en las cuales realizan sus oraciones pronunciando palabras a Dios,
ya sea que sientan o no algún movimiento o influencia del Espíritu.
De hecho,
algunos de los principales entre ellos han confesado que han orado
de esta manera sin los movimientos y asistencia del Espíritu,
reconociendo que han pecado al hacerlo, y sin embargo,
consideran que es su deber hacerlo.

Confesamos libremente que la oración es un deber muy provechoso y necesario,
ordenado y apropiado para ser practicado con frecuencia por todos los cristianos.
Sin embargo, así como no podemos hacer nada sin Cristo,
tampoco podemos orar sin la obra y asistencia de Su Espíritu.
Ahora bien, para que se entienda mejor el estado de esta controversia,
conviene considerar primero que la oración es de dos maneras: interna y externa.
La oración interna es ese vuelco secreto de la mente hacia Dios, por el cual,
al ser secretamente tocada y despertada por la Luz de Cristo en la conciencia,
y humillada bajo el sentido de su iniquidad, indignidad y miseria,
levanta su mirada hacia a Dios, y luego,
uniéndose con los destellos internos de la Semilla de Dios,
suspira constantemente deseos y aspiraciones secretos hacia Él. Es en este sentido que
con tanta frecuencia se nos ordena en las Escrituras a "`orar sin cesar`" (Lucas 18:1;
1 Tesalonicenses 5:17; Efesios 6:18; Lucas 21:36),
lo cual no puede entenderse como si se refiriera a la oración externa,
porque es imposible que los hombres estén siempre de rodillas,
expresando palabras de oración, etc.
De hecho,
esto les impediría cumplir con los otros deberes
que las Escrituras ordenan con no menos claridad.

La oración externa, entonces,
es cuando el alma (ya estando en el ejercicio del retiro interno y sintiendo
el aliento del Espíritu de Dios levantarse poderosamente) recibe fuerza
y libertad por un movimiento e influencia adicional del Espíritu,
para producir suspiros, gemidos o palabras audibles, ya sea en reuniones públicas,
en privado, en las comidas, etc.

Ahora bien, la oración interna es necesaria en todos los tiempos,
y por eso al hombre nunca le falta alguna influencia
(en diversos grados) para la práctica de ella,
mientras dure el día de su visitación. Porque tan pronto
retira su mente y se considera en la presencia de Dios,
se halla a sí mismo en la práctica de ella.
Pero el ejercicio de la oración externa (como necesita una
influencia o un movimiento del Espíritu mayor y adicional),
no puede ser practicada efectivamente hasta que la mente
se familiarice de alguna manera con la oración interna.
Por esta razón, los que son diligentes y vigilantes en sus mentes,
y perseveran retirados en el ejercicio de esta oración interna,
son más capaces de emplear con frecuencia la oración externa,
porque esta santa influencia los acompaña más constantemente.
Y ellos,
al estar más familiarizados y acostumbrados a los movimientos del Espíritu de Dios,
pueden percibir y discernir fácilmente Sus influencias.
Y puesto que aquellos que son más diligentes en este
camino experimentan un acceso cercano a Dios,
así también Él se deleita en atraerlos por Su Espíritu para que se acerquen y le invoquen.

Así, cuando muchos se reúnen en este estado retirado y vigilante de mente,
Dios frecuentemente derrama el Espíritu de oración entre ellos,
y los mueve a orar verbalmente para la edificación
y fortalecimiento los unos a los otros en amor.
Pero como esta oración externa depende de la interna,
y no puede llevarse a cabo aceptablemente sino por
una influencia y movimiento adicional del Espíritu,
no podemos, por tanto, fijar tiempos determinados para orar externamente,
ni hacer necesario pronunciar palabras en tales y cuales
momentos sintamos o no la influencia y asistencia celestial.
Pues esto, según nuestro juicio,
sería tentar a Dios y acercarse a Él sin la debida preparación. En lugar de esto,
creemos conveniente presentarnos primero delante
de Él por medio de este retiro interno de la mente,
y luego avanzar solo en la medida que Su Espíritu nos ayude y nos atraiga.

En verdad, hallamos que el Señor acepta esto,
aunque algunas veces Él considera oportuno ejercitarnos
en silencio sin permitirnos hablar,
para probar nuestra paciencia y enseñarnos a no depender de actos externos,
ni a complacernos a nosotros mismos (como muchos
hacen) con muchas palabras o muchas oraciones.
De esta manera, nuestra dependencia hacia Él se vuelve más firme y constante,
mientras esperamos que nos extienda Su cetro y nos
conceda la habilidad de orar por medio de Su Espíritu.
No obstante, no negamos que Dios, en ocasiones particulares,
puede muy repentinamente (incluso cuando la mente apenas ha comenzado a volverse a Él),
dar poder y libertad para expresar palabras u ofrecer?
actos de oración externa, de modo que el alma apenas puede discernir un movimiento previo.
Sin embargo, en todos los casos el dicho de Bernard es verdadero:
"`Toda oración es tibia si no la precede una inspiración divina.`"

Ahora bien, aunque afirmamos que nadie debe orar sin que el Espíritu lo mueva a ello,
también sostenemos que desatender la oración es pecado;
siendo el pecado no acudir al lugar donde con certeza
se sentiría al Espíritu guiarlo a ella.
De hecho, no dudamos que muchos,
al desatender esta vigilancia y retiro interior de la mente,
pierden muchas preciosas oportunidades de orar,
y de este modo incurren en culpa ante los ojos de Dios; y, sin embargo,
también sería pecado si se pusieran a orar antes
de sentir primero la influencia del Espíritu.
Porque un siervo claramente ofende a su amo cuando se acuesta en su cama y duerme,
descuidando los negocios de su señor. No obstante,
si de pronto se levantara y sin vestirse ni tomar consigo las herramientas
e instrumentos necesarios (sin los cuales no podría trabajar),
se lanzara a una gran actividad sin propósito,
estaría tan lejos de enmendar su falta anterior,
que incurriría justamente en una nueva reprensión. Y así como alguien que,
por descuido y por estar ocupado en otros asuntos,
puede dejar de oír a otro que le habla, o incluso no oír el fuerte repique de un reloj,
así también muchos, por negligencia, dejan de oír los frecuentes llamados de Dios,
por los cuales se les concede acceso a orar a Él. Sin embargo,
esto de ninguna manera les permite orar en sus propias
voluntades sin recibir la libertad de Dios.

Por último, aunque este es el único método verdadero y correcto de oración,
y el único que es aceptable para Dios,
no negamos que muchas veces Él ha respondido las oraciones y ha
consentido los deseos de aquellos (especialmente en tiempos de
oscuridad) que se han equivocado grandemente en estas cosas.
No dudamos que muchos se han conformado con oraciones formales,
y a pesar de estar muy equivocados tanto en el tema como en la manera de orar,
y sin la asistencia o influencia del Espíritu de Dios,
aun así han encontrado que Él aprovecha la ocasión para irrumpir en sus almas,
enterneciéndolos y refrescándolos maravillosamente.
Con todo, como se observó antes respecto a la predicación,
la amable condescendencia de Dios no implica Su aprobación
de las formalidades supersticiosas y vacías,
ni debe disuadir a nadie de llegar a practicar esa oración pura,
espiritual y aceptable que Dios está restaurando
de nuevo y a la que está guiando a Su pueblo.

Ahora me propongo probar primero la legitimidad de esta oración
espiritual mediante algunas consideraciones breves de las Escrituras,
y luego responder a las objeciones comunes de nuestros opositores,
lo cual también servirá para refutar su método y manera.

_Primero:_ La necesidad de un recogimiento previo de la mente,
a fin de poder sentir al Espíritu atrayendo a la oración,
se ve claramente en numerosas Escrituras.
De hecho, en la mayoría de los lugares donde se ordena orar,
se menciona "`velar`" como aquello que necesariamente debe preceder a la oración. Ver,
por ejemplo, Mateo 24:42; Marcos 13:33 y 14:38; Lucas 21:36,
donde es evidente que este velar debe preceder a la oración. Ahora,
¿con qué propósito se manda a velar?
¿O qué es este velar,
sino esperar sentir que el Espíritu de Dios nos guía a la
oración para que pueda ser hecha de manera aceptable?
Puesto que se nos dice que debemos "`orar en todo tiempo en el Espíritu,`"
y no podemos orar por nosotros mismos aceptablemente sin Él,
este velar debe ser recomendado para este propósito, a saber:
para que velemos y esperemos el momento oportuno para orar,
que es cuando el Espíritu nos mueva a ello.

_Segundo:_ Esta necesidad de que el Espíritu mueva y haga posible orar,
se manifiesta abundantemente en las palabras del apóstol Pablo en Romanos 8:26-27:
"`Y de igual manera el Espíritu nos ayuda en nuestra debilidad;
pues qué hemos de pedir como conviene, no lo sabemos,
pero el Espíritu mismo intercede por nosotros con gemidos indecibles.
Mas el que escudriña los corazones sabe cuál es la intención del Espíritu,
porque conforme a la voluntad de Dios intercede por los santos.`"
Primero, esta Escritura muestra la incapacidad de los hombres, por sí mismos,
de orar o invocar a Dios en sus propias voluntades,
incluso aquellos que han recibido la fe de Cristo y han sido en alguna
medida santificados por ella (como era el caso de la iglesia en Roma,
a la que el apóstol se dirigió entonces).
Segundo, esta Escritura señala al único que puede ayudar y asistir a los hombres a orar,
el cual es el Espíritu, e insiste en que, sin Él,
no pueden orar de manera aceptable a Dios, ni de forma provechosa para sus propias almas.
Tercero, establece la forma y el modo de la intercesión del Espíritu,
que es "`con gemidos indecibles.`"
Y cuarto,
afirma que Dios recibe con misericordia las oraciones
que se presentan y se ofrecen a Él por el Espíritu,
sabiendo que son según Su voluntad.
Y puesto que lo que afirma el apóstol es muy consistente con otros testimonios
de las Escrituras que elogian y recomiendan el uso de la oración,
argumento: Si el hombre no sabe cómo orar, ni puede hacerlo sin la ayuda del Espíritu,
entonces no tiene propósito ni provecho para él orar sin Él.

_Tercero:_
La necesidad del Espíritu en la verdadera oración se evidencia
en Efesios 6:18 y Judas 1:20. Porque en su carta a los efesios,
el apóstol nos manda a "`orar en todo tiempo en el Espíritu,`" y añade,
"`velando en ello;`" que es lo mismo que decir que
no debemos orar sin el Espíritu ni sin velar.
Y Judas nos muestra que solo las oraciones que son "`en el Espíritu Santo`" contribuyen
a la "`edificación de nosotros mismos sobre nuestra santísima fe.`"

_Cuarto:_
El apóstol Pablo dice expresamente en 1 Corintios
12:3 que "`nadie puede llamar a Jesús Señor,
sino por el Espíritu Santo.`"
Entonces, si Jesús no puede ser correctamente nombrado excepto por el Espíritu Santo,
mucho menos puede ser invocado aceptablemente en oración. En consecuencia,
el mismo apóstol declara (en la misma carta,
1 Corintios 14:15) que él "`orará con el Espíritu,`" dando
clara evidencia de que no era su método orar sin Él.

_Quinto:_ La confianza que tienen los santos de que Dios los escuchará,
está en "`si pedimos alguna cosa conforme a Su voluntad`" (1 Juan 5:14). Así que,
si la oración no es conforme a Su voluntad,
no hay motivo para confiar en que Él escuchará. Porque, de hecho,
pedirle a un hombre que ore sin el Espíritu es lo mismo que pedirle ver sin ojos,
trabajar sin manos o caminar sin pies.
Y esperar que un hombre comience a orar antes de
sentir que el Espíritu lo mueve y lo capacita,
es como esperar que vea antes de abrir los ojos,
que camine antes de levantarse o que trabaje antes de mover las manos.

_Por último:_ De esta práctica de orar sin el Espíritu,
y de creer que no es necesario esperar ser movido y capacitado por Él,
ha procedido toda forma de superstición,
idolatría y abominación entre los llamados cristianos,
con lo que el Señor es a menudo provocado y Su Espíritu contristado.
De hecho,
muchos se engañan a sí mismos ahora (como lo hicieron
antes los judíos) con una paz falsa con Dios,
pensando que todo está bien porque ellos han ofrecido
sus sacrificios de oraciones matutinas y vespertinas.
No obstante,
es manifiesto que el uso constante de tales oraciones
no influye en sus vidas ni conducta en lo más mínimo,
porque permanecen, en su mayor parte, tan malos como siempre.
Sí, es frecuente tanto entre católicos romanos como entre protestantes,
que abandonen de golpe (por así decirlo) de sus conversaciones vanas,
ligeras y profanas en tiempos y momentos señalados,
para entregarse a su acostumbrada devoción. Pero luego,
cuando apenas han terminado con esto,
y sus palabras hacia Dios apenas han salido de sus bocas,
regresan inmediatamente a su anterior manera profana de hablar.
Por lo tanto,
es evidente que el mismo espíritu malvado de este mundo actúa en ellos en ambas actividades.
Ahora bien,
si existe tal cosa como vanas ofrendas u oraciones que son una
abominación que Dios no escucha--como ciertamente las hay,
porque las Escrituras así lo testifica, Isaías 66:3;
Jeremías 14:12--ciertamente estas oraciones hechas
en la voluntad del hombre y en su propia fuerza,
sin el Espíritu de Dios, deben contarse entre ellas.

Baste esto como prueba.
Ahora voy a proceder a responder algunas objeciones de nuestros opositores.

[.discourse-part]
Objeción: Primero,
objetan que si tales influencias particulares del
Espíritu son necesarias para actos externos de adoración,
entonces deberían ser también necesarias para actos internos, como esperar,
desear y amar a Dios, así como también para los deberes morales externos,
como honrar a los padres o hacer lo correcto al prójimo, etc.

[.discourse-part]
Respuesta: Lo ya dicho responde suficientemente a esta objeción.
Porque en cuanto a los deberes generales del hombre hacia Dios y hacia su prójimo,
el hombre nunca carece de una influencia celestial mientras el día de su visitación dura;
durante ese tiempo,
Dios siempre está cerca de él y lucha con él por medio de Su Espíritu para volverlo
a Él. Pero en cuanto a los actos externos de predicación y oración--los cuales Dios
ha mandado que se lleven a cabo por medio de Su Espíritu (ver 1 Corintios 12:4-11;
1 Pedro 4:11) y que son para el beneficio de la reunión
pública--estos necesitan un mover y una influencia más especial,
como ya ha sido demostrado.

[.discourse-part]
Objeción: Segundo, objetan que, de acuerdo con esta doctrina,
los hombres perversos pueden descuidar la oración por años,
alegando que carecen del mover de Dios para hacerlo.

[.discourse-part]
Respuesta:
Las falsas pretensiones de los hombres malvados no invalidan la verdad de esta doctrina.
Pues, aunque concedemos que no deben orar sin el Espíritu, aun así,
deberían mantenerse en un estado de vigilancia donde
son capaces de sentir los movimientos del Espíritu.
Es cierto que, ellos pecan al no orar,
pero la causa de este pecado es que no velan para poder orar.

[.discourse-part]
Objeción: Tercero,
objetan que muchas oraciones que comenzaron sin el Espíritu resultaron eficaces,
y que incluso las oraciones de hombres malvados en ocasiones
han sido escuchadas y aceptadas (como en el caso de Acab).

[.discourse-part]
Respuesta: Esta objeción se resolvió anteriormente;
porque los actos de compasión e indulgencia de Dios,
en ciertos momentos y hacia ciertas personas, en ocasiones singulares o extraordinarias,
no deben ser la regla de nuestras acciones.
Porque si hacemos de tales cosas nuestra regla, se producirán grandes complicaciones,
como es evidente y será reconocido por todos.
Además,
no negamos que los hombres malvados son a veces conscientes de los movimientos y operaciones
del Espíritu de Dios antes de que el día de su visitación haya expirado.
Y, a partir de estas influencias del Espíritu, algunas veces oran aceptablemente,
aunque no para permanecer en la iniquidad, sino para crecer en piedad.

[.discourse-part]
Objeción: Por último,
algunos objetan que el llamado Padre Nuestro es una forma
prescrita de oración o adoración dada por Cristo a Sus discípulos.

[.discourse-part]
Respuesta: En primer lugar, esta oración fue dada a los discípulos mientras aún débiles,
antes de haber recibido la dispensación del Espíritu en el nuevo pacto;
y no fue dada como un método o formalidad, ni como el único medio para dirigirse a Dios,
sino más bien para mostrarles a Sus discípulos, por medio de un ejemplo,
cómo debían diferenciarse sus oraciones de las oraciones largas y sin vida de los fariseos.
En segundo lugar,
que la oración del Padre Nuestro no fue dada a la iglesia como un método prescrito
se puede apreciar claramente en las oraciones registradas de los apóstoles,
quienes nunca hicieron uso de esta oración, ni la repitieron,
sino que usaron otras palabras según el Espíritu les daba que hablasen.
En tercer lugar, el apóstol dice: "`Qué hemos de pedir como conviene, no lo sabemos,
pero el Espíritu mismo intercede por nosotros.`"
Pero si el Padre Nuestro hubiera sido dado como una
forma prescrita de oración a la iglesia,
entonces esta Escritura no sería cierta,
ni ellos habrían sido ignorantes respecto a qué pedir,
ni habrían necesitado la ayuda del Espíritu para enseñarles.

=== El Canto

En cuanto al canto de salmos, no es necesario un discurso largo,
ya que el caso es exactamente el mismo que en los dos primeros:
la predicación y la oración. Confesamos que esto forma parte de la adoración a Dios,
y es muy dulce y refrescante cuando procede de un
verdadero sentido del amor de Dios en el corazón,
y surge de la influencia divina de Su Espíritu.
Porque el Espíritu a veces guía a las almas a exhalar una suave melodía,
o palabras adecuadas a su condición presente,
que pueden consistir en palabras que han sido previamente usadas por los
santos y registradas en las Escrituras (como los Salmos de David),
o bien en otras palabras dadas espontáneamente por
el Espíritu (como los himnos y canciones de Zacarías,
Simeón y la virgen María).

Pero en cuanto a la manera acostumbrada y formal de cantar que abunda en el presente,
no tiene fundamento en las Escrituras ni en el verdadero cristianismo.
Y además de todos los abusos que usualmente acompañan a la oración y la predicación,
esta forma de canto tiene otra ofensa particular:
que muchas veces se cantan grandes y horrendas mentiras en la presencia de Dios.
Porque toda clase de personas malvadas y profanas se toman la atribución
de cantar las experiencias y condiciones del bendito David,
que son completamente falsas en lo que a ellos respecta.
En efecto, en sus himnos algunas veces cantan:
"`Fueron mis lágrimas mi pan de día y de noche.`"
O: "`Como un tiesto se secó mi vigor, y mi lengua se pegó a mi paladar,
y me has puesto en el polvo de la muerte.`"
O: "`Me he consumido a fuerza de gemir; todas las noches inundo de llanto mi lecho,
riego mi cama con mis lágrimas.`"
Hombres y mujeres cantan a Dios muchas otras cosas semejantes,
sabiendo que son falsas en cuanto a ellos.
Ahora bien, ¿quién podrá suponer que Dios acepta tales engaños? En verdad,
este tipo de canto agrada más a los oídos carnales
de los hombres que a los oídos puros del Señor,
quien aborrece toda mentira e hipocresía.

Entonces,
el canto que complace a Dios debe proceder de aquello
que es puro en el corazón (es decir,
de la Palabra de Vida en el interior).
Es en y por medio de esta Palabra que habita abundantemente en nosotros,
que los cánticos e himnos espirituales regresan al Señor,
según las palabras del apóstol (Colosenses 3:16).

=== Conclusión

La última gran ventaja de esta verdadera adoración a Dios
que profesamos y practicamos es que no consiste en la sabiduría,
las artes o la industria del hombre, ni necesita de la gloria, pompa,
riquezas o esplendor de este mundo para embellecerla.
En realidad, esta adoración es de naturaleza espiritual y celestial, y por lo tanto,
parece demasiado simple y despreciable para la mente y la voluntad naturales del hombre,
que no hallan deleite en ella,
porque no encuentran lugar para sus imaginaciones e invenciones,
ni oportunidad para gratificar sus sentidos externos y carnales.
Por esta razón,
es poco probable que alguien permanezca por mucho tiempo en esta
adoración sin un sentido acompañante del poder de Dios;
porque sin el poder, está desnuda y vacía,
y no tiene nada que invite y tiente a los hombres a estimarla.

Sin embargo, la adoración de nuestros adversarios,
al ser realizada en sus propias voluntades, es autocomplaciente,
pues es una actividad en la que pueden ejercitarse
ampliamente en sus destrezas e invenciones naturales.
Y debido a que tiene algo de esplendor externo y mundano
(atractivo para los sentidos carnales y mundanos),
pueden continuar placenteramente en ella y satisfacerse
incluso sin el Espíritu ni el Poder,
los cuales, admiten, no son esenciales para llevarla a cabo; y por lo tanto,
ni esperan ni ponen sus expectativas en ello.

Para concluir: la adoración, la predicación,
la oración y el canto por los cuales abogamos son aquellos que proceden
del Espíritu de Dios y siempre están acompañados de Su influencia.
Comienzan por el movimiento del Espíritu,
se llevan a cabo únicamente por Su poder y fuerza,
y así son una adoración puramente espiritual,
tal como declaran las Escrituras (Juan 4:23-24; 1 Corintios 14:15; Efesios 6:18, etc.).

Pero la adoración, la predicación, la oración y el canto que nuestros adversarios abogan,
y a los que nos oponemos, es una adoración que comienza,
continúa y concluye en la propia voluntad y fuerza naturales del hombre,
sin el movimiento o ni la influencia del Espíritu de Dios,
que ellos juzgan no necesario esperar, y por lo tanto, puede ser realizada,
tanto en contenido como en forma, por el más perverso de los hombres.
Tal fue la adoración y las vanas ofrendas que Dios siempre rechazó,
como se muestra en Isaías 66:3; Jeremías 14:12, etc.; Isaías 1:13; Proverbios 15:29;
Juan 9:31.
