== Esperando en el Señor

Vengo a hablarles de adoración, o de aquellas cosas, ya sean privadas o públicas,
generales o individuales,
por las que el hombre le rinde a Dios esa parte de su deber
que se relaciona inmediatamente con Él. Ahora,
ya que se nos ha dicho que "`el obedecer es mejor que los sacrificios,`" entonces,
ningún sacrificio es aceptable excepto aquel que es hecho
según la voluntad de Aquél a quién se le ofrece.
Pero los hombres,
encontrando más fácil hacer sacrificios en su propia
voluntad que obedecer la voluntad de Dios,
han amontonado sacrificios sin obediencia,
pensando engañar a Dios (como hacen los unos a los otros),
dándole un espectáculo de reverencia, honor, y adoración,
mientras están internamente alejados y apartados de Su santa y justa vida,
y son totalmente ajenos a los soplos puros de Su Espíritu,
en los cuales únicamente se ofrece el verdadero sacrificio y adoración. Como resultado,
no hay algo relacionado con el deber del hombre hacia Dios
(entre todo tipo de personas) que haya sido más pervertido,
y en el cual el diablo haya prevalecido más,
que en corromper la mente del hombre concerniente a la adoración a Dios.

Ahora,
apruebo libremente todo lo que los Protestantes han reformado
de los Católicos Romanos con respecto a esto.
También rechazo, como parte de la verdadera adoración de Dios,
la abominable superstición e idolatría de la misa Papal,
la adoración a los santos y a los ángeles, la veneración de reliquias,
la visitación de sepulcros,
y todas las otras ceremonias supersticiosas y las
interminables peregrinaciones de la sinagoga Romana.
Sin embargo,
le concierne a los Protestantes considerar cuidadosamente
si han realizado una reforma clara y perfecta,
pues, ciertamente, hemos encontrado muchas de las ramas muertas cortadas por ellos,
pero la raíz aún permanece, es decir,
_una adoración llevada a cabo en y desde la voluntad y el
espíritu del hombre y no por y desde el Espíritu de Dios._
Porque la verdadera adoración Cristiana y espiritual
de Dios se perdió mucho tiempo atrás,
y la sabiduría y voluntad del hombre se mezclaron tan rápida y completamente con ella,
que la apostasía, en lo que respecta a la adoración, se ha hecho muy grande, y así,
una verdadera reforma de esta mala raíz se ha vuelto sumamente difícil.

Por lo tanto, que el lector no tropiece con nuestra proposición en este asunto,
más bien, escúchenos pacientemente mientras nos damos a entender.
Espero (con la ayuda de Dios) mostrar que a pesar de que nuestra perspectiva
en este tema puede parecer muy diferente de todos los demás tipos de Cristianos,
está más de acuerdo con la más pura religión Cristiana,
y de verdad es la más necesaria de ser observada y seguida.

Primero, considere que lo que se afirma aquí,
se habla con respecto a la adoración de Dios en estos tiempos del Evangelio,
y no de la adoración que estaba bajo o antes de la Ley.
Pues los mandamientos particulares de Dios a los hombres en aquellos tiempos
no son suficientes para autorizarnos a hacer las mismas cosas ahora;
de lo contrario podría sugerirse en el presente ofrecer sacrificios de
animales como ellos lo hicieron (los cuales todos reconocen haber cesado).
En efecto, algunas de las cosas que fueron encomiables y aceptables bajo la Ley,
si se practicaran bajo el Evangelio,
serían apropiadamente llamadas superstición o idolatría. Porque muchas de las ceremonias
dispensadas por Dios a los Judíos no eran esenciales para la adoración verdadera y espiritual,
o necesarias en sí mismas para experimentar la santa comunión entre Él y Su pueblo,
sino que fueron dadas en condescendencia a un pueblo inclinado a la idolatría. Así que
la Sustancia fue disfrutada bajo la Ley por los que eran verdaderamente espirituales,
sin embargo,
estaba velada y rodeada de muchos ritos y ceremonias que no son
lícitos para ser usados ahora bajo el Evangelio.

En segundo lugar, a pesar de que digo que esta adoración no se limita a tiempos,
lugares, ni personas,
no debo ser entendido como si intentara hacer a un lado todos los tiempos y lugares
determinados de la adoración. Dios me libre de tal opinión. No,
no somos de aquellos que "`dejan de congregarse,`" más bien tenemos ciertos lugares
y tiempos en los cuales nos reunimos cuidadosamente para esperar en Dios y adorarle
(ni hemos dejado de hacerlo por las muchas amenazas y persecuciones de los hombres).
Creemos que es necesario, como pueblo de Dios, reunirnos,
porque mientras nos encontremos revestidos por este tabernáculo externo,
hay necesidad de una comunión conjunta y visible,
de llevar un testimonio externo para Dios,
y de también vernos los rostros los unos a los otros,
de modo que nos reunamos en nuestras personas externas
así como también en nuestros espíritus.
Estar reunidos externamente en este amor interno y unidad de espíritu,
tiende a animar y a refrescar grandemente a los santos.

Sin embargo, insistimos en las siguientes cosas: Primero,
que el Espíritu de Dios debe ser el que opera, mueve,
persuade e influye inmediatamente al hombre en todos los actos
particulares de la adoración cuando los santos se reúnen.
Segundo, que este Espíritu no debe ser limitado en Sus operaciones,
lo cual sucede cuando se pone a un hombre u hombres en particular
para predicar y orar en su voluntad o en la de otros hombres,
mientras todos los demás quedan excluidos al punto de creer que
no deben esperar que el Espíritu de Dios los use en estas cosas.
Cuando estas personas hacen esto,
están desatendiendo al Espíritu que los vivificaría en sí mismos; y entonces,
al no esperar sentir ni obedecer las respiraciones puras del Espíritu de Dios,
son conducidos a depender solamente del predicador y a escuchar lo que él va a decir.

Pues todos los que ministran, deben reunirse para encontrarse con el Señor,
y esperar los movimientos y operaciones internos de Su Espíritu,
y así orar cuando sientan al Espíritu respirar a través de ellos y en ellos,
y predicar cada vez que se encuentren siendo movidos y motivados
por el Espíritu de Dios según Él les da que hablen.
Sólo entonces podrán hablar una palabra oportuna para refrescar las almas abatidas,
conforme a lo que requiera la condición y el estado
presente de los corazones de las personas,
permitiéndole a Dios por medio de Su Espíritu que prepare tanto
los corazones de las personas como también del predicador para
que hable lo que sea conveniente y oportuno para ellos.
Pero los ministros hoy en día,
construyen un sermón en sus oficinas conforme a su propia voluntad,
a través de su sabiduría humana y literatura,
hurtando las palabras de la Verdad de la letra de las Escrituras
y remendándolo junto con otros escritos y observaciones de hombres.
Así es como ellos diseñan un sermón que los mantendrá hablando
durante una hora mientras el reloj de arena se agota,
sin haber esperado o sentido la influencia interna del Espíritu de Dios,
o sin saber si el sermón es apropiado u oportuno para la condición de las personas.
Luego, cuando el ministro termina con su sermón dice su oración en su propia voluntad,
y allí se da por terminado el asunto.
Esta forma habitual de adoración no es de ninguna manera aceptable para Dios,
y la condición presente de las naciones declara suficientemente cuán infructuosa
e improductiva es para los que se encuentran en ella.

Por ende, no estamos en contra de los tiempos establecidos para la adoración,
en absoluto, y de hecho designamos dichos tiempos para conveniencia externa.
No creemos, sin embargo, como los Católicos Romanos, que estos días sean santos,
ni dirigimos a las personas a una observación supersticiosa de estos,
pues estamos persuadidos de que todos los días son iguales antes los ojos de Dios.

=== Esperando en el Señor en Silencio

Hemos llegado al tema de la controversia.
Con respecto a la adoración pública,
juzgamos que es deber de todos congregarse diligentemente, y cuando están reunidos,
la gran labor tanto de uno como de todos debe ser esperar en Dios,
volviéndose de sus propios pensamientos e imaginaciones,
para sentir la presencia del Señor y conocer una verdadera "`reunión
en Su Nombre,`" en la que Él está "`en medio`" según Su promesa.
Y cuando todos están así reunidos, y por tanto congregados internamente en sus espíritus,
así como externamente en sus personas,
se conoce el poder secreto y la virtud de vida que refrescan el alma,
y se siente el levantamiento de los movimientos y
respiraciones puras del Espíritu de Dios.
A partir de esto, brotan palabras de declaración, oraciones, o alabanzas,
y se experimenta la adoración aceptable,
la cual edifica la Iglesia y es agradable para Dios.
De esta manera ningún hombre limita al Espíritu de Dios,
ni saca sus propias cosas investigadas y reunidas,
sino que todos presentan aquello que el Señor pone en sus corazones, y lo dice,
no en la voluntad y sabiduría del hombre,
sino "`con demostración del Espíritu y de poder.`"
Sí, y aunque no se diga una palabra,
con todo la verdadera adoración espiritual es llevada
a cabo y el cuerpo de Cristo es edificado.

En realidad puede ser, y ha sucedido a menudo entre nosotros,
que pasen varias reuniones sin que se diga una sola palabra,
y sin embargo nuestras almas son edificadas grandemente y refrescadas,
y nuestros corazones son maravillosamente vencidos
por el sentido secreto del poder y Espíritu de Dios,
el cual ha sido ministrado de una vasija a otra sin palabras.
De verdad, esto es extraño e increíble para el mero hombre natural y carnal,
quien está listo para juzgarlo todo como "`tiempo perdido`" en
donde no se dice algo que sea obvio para los sentidos externos.
Por lo tanto insistiré un poco en este tema,
como alguien que puede hablar desde cierta experiencia (y no por simple oídas) de esta
maravillosa y gloriosa adoración. Pues aunque es contraria a la naturaleza del espíritu,
voluntad y sabiduría del hombre, sin embargo desborda con la sabiduría y gloria de Dios.

Puesto que no hay nada más opuesto a la voluntad y sabiduría
natural del hombre que este esperar silenciosamente en Dios,
no puede ser obtenido o correctamente comprendido por el hombre,
excepto cuando este rinde su propia voluntad y sabiduría
y se contenta con estar completamente sujeto a Dios.
Por tanto, tal espera en Él no será predicada, ni puede ser practicada,
excepto por aquellos que no encuentran una ceremonia externa, ni observaciones,
ni palabras (sí, ni las mejores o más puras palabras,
ni siquiera las palabras de las Escrituras),
capaces de satisfacer sus almas cansadas y afligidas.
Porque aunque todas estas cosas estén presentes, aún así puede faltar la vida,
el poder y la virtud que las hacen eficaces.

Tales almas desesperadas encontraron necesario acabar con
todas las cosas externas y estar en silencio ante el Señor;
y siendo dirigidas a ese don interno de Vida y Luz
en ellas mismas como el más excelente Maestro,
el cual "`nunca más les será quitado`" (Isaías 30:20),
llegaron a aprender a esperar en Dios en la medida de vida y gracia recibida de Él,
y a cesar de sus propias palabras y acciones apresuradas
en la voluntad y comprensión natural,
deseando sentir esta Semilla de Vida interna.
Aquí encontraron, que cuando esta Semilla se mueve, pueden moverse con ella,
y cuando son movidos por Su poder, entonces son influenciados ya sea a orar, predicar,
o cantar.
Y así,
a partir de este principio de que el hombre se mantenga en silencio y no actué en las
cosas de Dios hasta que primero sea movido por la luz y la gracia de Dios en el corazón,
surgió, de forma natural, esa manera de sentarse juntos en silencio,
y de esperar unánimes en el Señor. De modo que estos,
congregados en el temor puro del Señor, no se dedicaron de inmediato a hablar, orar,
cantar, etc.,
teniendo temor de ser encontrados actuando anticipadamente en sus propias voluntades.
En lugar de ello,
cada uno hizo su trabajo de retirarse internamente en la medida de gracia en sí mismo,
no sólo estando en silencio en cuanto a palabras,
sino incluso absteniéndose de sus propios pensamientos, imaginaciones y deseos,
velando en santa dependencia del Señor,
y congregándose no sólo externamente en algún lugar,
sino internamente en un Espíritu y en el único nombre de Jesús,
el cual es Su poder y virtud.

Es así como estos han llegado a disfrutar
y a sentir los levantamientos de esta Vida,
la cual, en tanto prevalezca en cada persona,
llega a ser como una refrescante inundación que se esparce por
toda la reunión. Porque a medida que el hombre y la habilidad y
sabiduría del hombre son negadas y encadenadas en cada individuo,
y Dios es exaltado y Su gracia levantada en dominio en el corazón,
así Su nombre llega a ser uno en todos y Su gloria irrumpe y los cubre a todos.
En efecto, a menudo hay tal temor santo y reverencia sobre cada alma,
que si se levantara la parte natural en alguno, o la parte sabia del hombre,
o lo que no es uno con la Vida, sería inmediatamente encadenado y juzgado.
Y cuando alguno es constreñido (mediante la irrupción del poder
del Señor) a pronunciar una palabra de exhortación o alabanza,
o a respirar ante el Señor en oración, entonces todos se hacen sensibles a ello,
porque la misma Vida que hay en ellos responde "`como en
el agua el rostro corresponde al rostro`" (Proverbios 27:19).

Esta es esa adoración divina y espiritual que el mundo ni conoce ni entiende,
ni dentro de la cual el ojo de buitre puede ver.
Con todo,
son muchas y grandes las ventajas que mi alma (como
muchas otras) ha gustado por medio de ella,
las cuales serían encontradas por todos aquellos que seriamente se dediquen a ella.
Porque cuando las personas se reúnen de esta manera,
no sólo para oír a los hombres o depender de ellos, sino que en su lugar,
son enseñadas internamente a mantener sus mentes en el Señor
(Isaías 26:3) y a esperar Su aparición en sus corazones,
entonces la apresurada obra del espíritu del hombre se frena y
se impide que se mezcle a sí mismo con la adoración de Dios.
De hecho, esta forma de adoración está tan desnuda y vacía de todo esplendor mundano,
que cualquier oportunidad para que la sabiduría del hombre sea ejercida
en superstición e idolatría no tiene lugar aquí. En lugar de esto,
hay una quietud interna y un retiro de la mente,
el testigo de Dios se levanta en el corazón y la Luz de Cristo brilla,
mediante la cual el alma llega a ver su propia condición.
Cuando hay muchos unidos en la misma obra,
hay una batalla y lucha interna,
y mientras cada uno permanece en su propia medida de gracia,
se siente que el poder y el espíritu de las tinieblas son vencidos.
En consecuencia,
somos a menudo fortalecidos y renovados en gran manera
en el espíritu de nuestras mentes sin una sola palabra,
y disfrutamos y poseemos la santa unión y "`comunión con el cuerpo y sangre de Cristo,`"
por medio de la cual nuestro hombre interior es alimentado y nutrido (lo cual también
hace que en nuestros asuntos espirituales no nos enfoquemos en el agua,
pan y vino externos).

Ahora, conforme los que están reunidos de esta manera crecen en fortaleza,
poder y virtud de la Verdad,
y conforme la Verdad llega a tener victoria y dominio en sus almas,
reciben la capacidad de hablar y hablan cuidadosamente para la edificación de sus hermanos,
y entonces la Vida pura tiene paso libre a través
de ellos y lo que se habla edifica realmente al cuerpo.
Algunas veces, cuando alguno ha llegado a la reunión y no ha sido vigilante,
vaga en su mente o está distraído por asuntos externos,
y por lo tanto no está internamente reunido con el resto,
tan pronto como se retira internamente,
este Poder (estando en buena medida levantado en toda la reunión) repentinamente
se asirá de su espíritu y maravillosamente ayudará a levantar la Semilla
en él y lo engendrará en la experiencia del mismo Poder.
Esto ablanda y calienta su corazón,
así como el calor natural se apodera de un hombre
que tiene frío cuando se acerca a una estufa,
o como una llama se apoderará de un poco de material combustible que está cerca de ella.
O, si sucede que varios se desvían en sus mentes,
a pesar de que están externamente en silencio,
y por tanto están distraídos de la medida de gracia que hay en sí mismos
(lo cual puede ocurrir por negligencia y por obra del enemigo),
y llega otro que está atento y en quién la Vida está en gran medida levantada,
según este mantiene su lugar,
sentirá una recóndita lucha por los demás en solidaridad con la Semilla que es oprimida
en los otros y detenida en su levantamiento por sus pensamientos y divagaciones.
Y mientras este fiel espera en la Luz, y se mantiene en esta obra divina,
Dios responde a menudo a esta lucha secreta y a los
soplos de Su propia Semilla a través de él,
para que los demás se encuentren a sí mismos golpeados internamente sin palabras,
y el fiel llegue a ser como una partera y saque a la luz la Vida en los otros,
a través de los dolores de parto en su alma.
De esta forma la Vida de Cristo es levantada en todos y las vanas imaginaciones derribadas,
y este fiel es sentido por el resto ministrándoles vida a ellos sin palabras.

Sí, a veces cuando no se ha pronunciado una sola palabra en la reunión,
pero todos están esperando en silencio, y llega alguien que es grosero y malvado,
en el cual el poder de las tinieblas prevalece (tal
vez con la intención de burlarse o de hacer mal),
si toda la reunión está recogida en la Vida, y la Vida está en buena medida levantada,
Ella lo aterrorizará y este se sentirá incapaz de resistirla.
En verdad,
la fuerza secreta y la virtud de la Vida encadenará el poder de las tinieblas en él,
y si el día de su visitación no ha expirado,
alcanzará la medida de gracia en él y será levantada para la redención de su alma.
Hemos sido testigos de esto a menudo,
así que hemos tenido muchas ocasiones para renovar el viejo dicho:
"`¿Está Saúl también entre los profetas?`"
Porque muchos han llegado a convencerse de la Verdad de esta manera,
de lo cual yo mismo soy, en parte, un verdadero testigo.
Porque no fue por la fuerza de los argumentos,
la discusión de cada doctrina o por el convencimiento de mi entendimiento
que llegué a recibir y a dar testimonio de la Verdad,
sino al ser alcanzado secretamente por esta Vida.
Porque cuando llegué a las reuniones en silencio del pueblo de Dios,
sentí un poder entre ellos que tocó mi corazón, y en la medida que le daba paso,
encontré que el mal se debilitaba en mí y el bien se levantaba.
De este modo me ligué y me uní a ellos,
cada vez más hambriento en busca del incremento del Poder y de la Vida del Señor,
mediante lo cual podría sentirme perfectamente redimido.
En efecto, esta es la forma más segura de llegar a ser cristiano,
y después no faltarán el conocimiento y el entendimiento de los principios,
sino que vendrán naturalmente (tanto como sea necesario)
como el fruto de esta buena raíz,
y tal conocimiento no será estéril ni infructuoso.

Deseamos, por lo tanto,
que todo el que venga entre nosotros sea convertido por este Poder y esta Vida.
Porque sabemos que,
aunque miles fueran convencidos en sus entendimientos de todas las verdades que sostenemos,
si no son conscientes de esta Vida interna y sus
almas no son cambiadas de injusticia a justicia,
entonces no pueden añadirnos nada.
Porque este es el cemento con el cual estamos unidos
"`como para el Señor`" y unos con otros,
y sin esto, nadie puede adorar con nosotros.
Sí, si tales vinieran entre nosotros y,
a partir de un entendimiento y convencimiento que tienen de la Verdad,
hablaran cosas tan verdaderas, y las expresaran con tanta excelencia de palabras,
aún así, si carecieran de esta Vida, eso no nos edificaría en absoluto,
sino que serían como "`metal que resuena, o címbalo que retiñe`" (1 Corintios 13:1).

=== El Rol del Creyente en la Adoración

Por consiguiente, cuando nos congregamos,
nuestra labor y nuestra adoración es que cada uno vele y espere
en la aparición de Dios en sí mismo y ser reunido en Él,
fuera de todas las cosas visibles.
Y cuando todos estén vueltos y esperando así,
encontrarán que el bien se levanta sobre el mal,
lo puro sobre lo impuro y que Dios se revela y se acerca a cada individuo;
así Él está en medio de la asamblea.
De este modo,
cada uno no solo participa del refrescamiento y fortaleza
particulares que provienen de la obra del Señor en sí mismo,
sino que también es partícipe de la totalidad del cuerpo,
al ser un miembro vivo del cuerpo y tener un compañerismo conjunto y comunión con todos.

Ahora, cuando esta adoración es firmemente predicada y mantenida,
se vuelve fácil, aunque al principio es muy difícil para el hombre natural,
cuyas vagabundas imaginaciones y sucesivos deseos mundanos
no pueden ser llevados tan fácilmente al silencio.
Por tanto, cuando alguno se vuelve al Señor con verdaderos deseos de esperar en Él,
pero encuentran gran dificultad por el extravío de su mente,
el Señor a menudo (en Su misericordia y compasión) hace
que Su Poder surja en una forma más fuerte y poderosa.
Luego, cuando la mente se sumerge y espera la aparición de la Vida,
y el poder de las tinieblas en el alma es hallado luchando y obrando contra ella,
entonces la buena Semilla se levanta y funciona como medicina en el alma.
Esto sucede, especialmente,
cuando alguien débil se encuentra en la asamblea de muchos otros,
en quienes la vida se ha levantado en mayor dominio.
Debido a la obra contraria del poder de las tinieblas,
a menudo se encuentra una lucha interna en el alma, tan espiritualmente real,
como alguna vez se enfrentaron Esaú y Jacob en el vientre de Rebeca.
Y a partir de estos dolores de parto internos mientras
las tinieblas busquen oscurecer la Luz,
y la Luz busque atravesar las tinieblas (lo cual siempre
hará si el alma no cede su fuerza a la oscuridad),
existirá tal dolor de parto en el alma que incluso se manifestará en el hombre exterior.
Así, pues, a menudo, por la obra de esta lucha,
el cuerpo del individuo es grandemente sacudido, y se apoderarán de él muchos gemidos,
suspiros y lágrimas, como la angustia de una mujer en labores de parto.

En otras ocasiones,
pareciera que el enemigo (quién está presente cuando los hijos de Dios se reúnen para
ver si puede entorpecer su tranquilidad) prevalece en cierta medida sobre toda la reunión,
al trabajar arduamente contra ella esparciendo y propagando su oscuro poder,
alejando las mentes de la Vida en ellos.
Pero, cuando los que están reunidos son conscientes del
poder que está obrando en contra de ellos,
y comienzan a luchar en contra de él por medio de las "`armas de la luz,`"
algunas veces el poder de Dios irrumpe en toda la reunión. Entonces ocurre
tal lucha interna por las obras fuertes y contrarias de estos dos poderes
opuestos (como el movimiento de dos mareas contrarias),
que cada individuo es severamente ejercitado como en un día de batalla.
Aquí, un temblor y movimiento del cuerpo sobrevienen a la mayoría, si no es que a todos,
los cuales, mientras prevalezca el poder de la Verdad,
llevarán a la asamblea de dolores punzantes y gemidos
al sonido más dulce de acción de gracias y alabanza.
Es de ahí que el nombre de "`Cuáqueros,`" es decir, los que tiemblan,
nos fue dado en desprecio.
Pero, aunque este nombre no es de nuestra escogencia, no estamos avergonzados de él,
sino más bien tenemos una razón para regocijarnos de eso, siendo conscientes de Su Poder.
De hecho,
este mismo Poder de Dios a menudo se ha apoderado de nuestros
adversarios y los ha hecho ceder a favor de nosotros,
y unirse a nosotros,
y confesar la Verdad antes de que tengan cualquier conocimiento claro de nuestras doctrinas.
Algunas veces muchos han sido convencidos de esta manera en una misma reunión,
y otras veces este Poder ha alcanzado y ha obrado maravillosamente hasta
en niños pequeños para la admiración y asombro de muchos.

Son muchas las bendecidas experiencias que
puedo contar de este silencio y manera de adorar.
No obstante,
no recomiendo y hablo del silencio como si tuviéramos
una regla para excluir la oración o la predicación,
o limitarnos al silencio; de ninguna manera.
Pues, así como nuestra adoración no consiste en palabras,
tampoco consiste en el silencio como si el silencio fuera el fin.
Más bien consiste de una santa dependencia de la mente en Dios,
a partir de la cual el silencio necesariamente sigue en primer lugar,
hasta que puedan surgir las palabras que provengan del Espíritu de Dios.
Y Dios nunca falla en moverse en sus hijos para producir
palabras de exhortación o de oración cuando sea necesario,
de modo que, de las muchas reuniones y encuentros entre nosotros,
hay muy pocas que pasan enteramente en silencio,
en las que Dios no provoca que alguien ministre a sus hermanos.
Porque cuando muchos se encuentran verdaderamente reunidos bajo esta única Vida y Nombre,
con mucha naturalidad y frecuencia, Él los induce a orar, a alabar,
y a animarse los unos a los otros por medio de una
mutua exhortación e instrucción. Aún así,
consideramos necesario que haya un tiempo de silencio en primer lugar,
para que en ese tiempo todos puedan ser reunidos
internamente en la Palabra o Don de gracia.
Entonces, a partir de esta gracia,
aquel que ministra puede recibir la fortaleza para producir lo que ministra,
y aquellos que escuchan pueden recibir un sentido
de discernimiento entre lo precioso y lo vil,
y no apresurarse en el ejercicio de estas cosas tan pronto como suena la campana,
como lo hacen otros Cristianos.

Sin embargo,
ciertamente sabemos y podemos testificar que una reunión puede ser buena y refrescante
aunque no se diga una sola palabra durante toda la reunión. Porque en estas reuniones,
se siente que la Vida sigue abundando en cada individuo y muchos han experimentado
un crecimiento interno que ocurre en y por el poder del Señor. E incluso cuando
las palabras pudieron haberse expresado por la Vida de manera aceptable,
aún así hay veces en las que a ninguno le es puesto la necesidad de declararlas,
y más bien todos pueden elegir poseer y disfrutar
al Señor tranquila y silenciosamente en sí mismos.
En efecto,
esto es muy dulce y consolador para el alma que ha aprendido a
estar reunida fuera de todos sus propios pensamientos y obras,
y a sentir al Señor producir el querer como el hacer (lo cual muchos
de nosotros podemos testificar de nuestra propia experiencia bendita.

Definitivamente,
esta es una doctrina difícil de ser creída o recibida por el hombre natural,
y por lo tanto debe ser conocida a través de una
experiencia sensible y al hacer una prueba de ella,
y no por argumentos;
porque no es suficiente creerla si no vienen también a gustarla y a poseerla.
No obstante,
en consideración de aquellos que puedan estar más dispuestos
a aplicarse en la práctica y experiencia de la misma,
si encuentran su entendimiento convencido y además ven que
está fundamentada en las Escrituras y en la razón,
siento la libertad de añadir algunas consideraciones para confirmación adicional,
además de lo que hemos mencionado anteriormente acerca de nuestra experiencia.

Supongo que ninguno negará que esperar en el Señor y vigilar ante Él,
es un deber que nos incumbe a todos;
y que esto también es una parte de la adoración que no se cuestionará,
ya que difícilmente haya otra cosa que esté ordenada
a hacer con tanta frecuencia en las santas Escrituras,
como se evidencia a partir de los siguientes versículos: Salmo 27:14; Proverbios 20:22;
Isaías 30:18; Oseas 12:6; Zacarías 3:8; Mateo 24:42; 25:13; 26:41; Marcos 13:33, 35, 37;
Levítico 21:36; Hechos 1:4; 20:31; 1 Corintios 16:13; Colosenses 4:2; 1 Timoteo 5:6;
2 Timoteo 4:5; 1 Pedro 4:7. Además,
este deber a menudo es recomendado con preciosas y grandes promesas,
como aparecen en Salmo 25:3; 37:9; 69:6; Isaías 40:31; Lamentaciones 3:25-26,
"`Pero los que esperan en Jehová tendrán nuevas fuerzas,`" etc.

Ahora, ¿cómo es que uno espera en el Señor, o vigila delante de Él,
si no es por medio de este silencio del cual hemos hablado?
Esto claramente es un gran y principal deber que necesariamente
precede a todos los demás (tanto en naturaleza y tiempo).
Pero, para que pueda ser entendido perfectamente,
no solo como siendo un silencio externo del cuerpo,
sino de un silencio interno de la mente,
fuera de todas sus propias imaginaciones y pensamientos,
permítase considerar que el hombre tiene que ser
comprendido en un doble sentido--es decir,
en su estado natural, no regenerado y caído, y en la condición espiritual y renovada.
A partir de esto se levanta la distinción entre el hombre
"`natural`" y el "`espiritual`" que tanto usaba el apóstol,
y estos dos nacimientos que ocurren en la mente o corazón proceden
respectivamente de las dos semillas que hay en el hombre--a saber,
la buena Semilla y la mala.
Ahora,
a partir de la mala semilla no solo procede todo
tipo de iniquidad e impiedad abominable y evidente,
sino también hipocresía y la malicia que la Escritura llama
"`espiritual,`" (Efesios 6:12) porque es la serpiente trabajando
en y por medio del hombre natural en las cosas que son espirituales.
Puede ser que estas cosas se muestren y aparenten ser buenas, pero son, por el contrario,
las más dañinas y peligrosas, "`porque el mismo Satanás se disfraza como ángel de luz.`"
Por esta razón es que la Escritura, con tanta firmeza y frecuencia,
deja fuera y excluye al hombre natural de entrometerse en las cosas de Dios,
rechazando sus esfuerzos en ellas,
aunque sean realizados y llevados a cabo por la más
eminente de las habilidades del hombre,
como es la sabiduría y el discurso.

Además,
esta maldad espiritual es de dos índoles (aunque estos dos son de un mismo género,
ya que provienen de la misma raíz). Una es cuando el hombre
natural se inmiscuye y opera en las cosas de la religión,
y a partir de sus propias percepciones y deducciones,
afirma o propone conceptos y opiniones falsas y equivocadas
acerca de Dios y de cosas espirituales,
e inventa supersticiones, ceremonias, observaciones,
y ritos en la adoración. A partir de este tipo,
han surgido todas las herejías y supersticiones que
existen entre los Cristianos hasta el día de hoy.
La otra es cuando el hombre natural desde una mera convicción en su entendimiento,
se precipita en su propia voluntad y esfuerzo natural
sin la influencia y guía del Espíritu de Dios,
y trata ya sea de entender o imaginar las cosas de Dios,
o realmente llevarlas a cabo por medio de la oración y predicación. Ahora,
la primera de estas carece tanto de la sustancia como de la forma.
La segunda, es posible que conserve la forma externa del Cristianismo,
pero está desprovista de la Vida y la Sustancia.
Porque la auténtica religión Cristiana,
no consiste en una mera creencia de doctrinas verdaderas,
o una mera ejecución de buenos actos, si no, las simples palabras de la Escritura,
aunque sean habladas por un borracho o un demonio,
podrían decirse que son Espíritu y vida,
lo cual considero que ninguno será tan absurdo como para afirmarlo.

Ahora, aunque el último tipo no es tan malo como el primero, sin embargo,
ha abierto un camino para este.
Porque los hombres,
habiéndose primero apartado de la Vida y la Sustancia
de la verdadera religión y adoración--es decir,
del poder y virtud internos del Espíritu,
como para actuar por ellos--solamente pueden conservar la forma y la manera, es decir,
las palabras verdaderas y las buenas apariencias.
Luego, mientras éstos continúan actuando en su propia voluntad natural y no renovada,
la forma no puede sino también decaer rápidamente y volverse corrupta.
Porque el espíritu incansable del hombre no permanecerá
dentro de la simplicidad y sencillez de la Verdad,
sino que rápidamente abre camino a sus propias numerosas invenciones e imaginaciones,
de modo que la forma se adapta a sus propias invenciones
hasta que (gradualmente) la apariencia de piedad se pierde,
junto con el poder.
Con este tipo de idolatría, el hombre ama, idolatra, y abraza sus propias concepciones,
invenciones, y los productos de su propio cerebro.
De hecho, esto es tan inherente en él y está tan enraizado en su naturaleza caída,
que mientras su espíritu natural siga siendo el primer autor y actor en él,
y sea aquel por el cuál es guiado y movido en su adoración
hacia Dios (sin primero esperar por otra Guía que lo dirija),
nunca podrá llevar a cabo la adoración espiritual pura,
ni engendrar algo más que el fruto de la primera raíz caída, natural y corrupta.

Pero el tiempo designado por Dios ha llegado desde hace mucho,
en el cual Él se ha complacido en restablecer la verdadera adoración
espiritual por medio de Cristo Jesús. Y después de que la forma,
tiempo,
y manera externas de la adoración que fue señalada
por Dios a los Judíos llegó a un final,
encontramos que Jesucristo (el Autor del Cristianismo) no prescribe ninguna forma
de adoración a Sus hijos bajo la administración más pura del Nuevo Pacto,
excepto insistir en que la adoración ahora sea espiritual y en el Espíritu.
Debe observarse que en todo el Nuevo Testamento,
no hay un orden específico o mandamiento que sea
dado acerca de la manera o forma de adoración,
excepto que los creyentes sigan la revelación del Espíritu,
y no dejen de congregarse (algo muy querido y practicado diligentemente por nosotros).
Es cierto que se hace mención de los deberes de la oración, predicación y alabanza;
pero qué orden o método deben mantenerse al hacerlo,
o si éstos deberían realizarse inmediatamente, tan pronto como los santos estén reunidos;
no hay ni una sola palabra que hable al respecto.
De hecho,
estos deberes (como se mostrará más adelante) siempre
se mencionan en asociación con la asistencia,
guía, y movimientos del Espíritu de Dios.

Puesto que el hombre, en su estado natural,
está excluido de actuar o moverse en las cosas espirituales, ¿Cómo o de qué manera,
debería ejercitar su primer y previo deber de esperar
en Dios salvo trayendo la parte natural al silencio?
Y esto no se hace de otra forma, sino absteniéndose de sus pensamientos e imaginaciones,
y de todas sus obras y los movimientos de su propia mente,
tanto en las cosas ilícitas como en las lícitas, de modo que, estando en silencio,
Dios pueda hablar en él, y por ende la buena Semilla se pueda levantar.
A pesar de que esto es difícil para el hombre natural, es tan consecuente con la razón,
e incluso con la experiencia natural en otras cosas, que no puede negarse.
Porque aquel que desea aprender de un maestro,
si él espera escuchar a su maestro y ser instruido por él,
no debe hablar sin cesar de lo que debe ser enseñado y nunca quedarse callado;
de otro modo, ¿Cómo tendrá su maestro tiempo para instruirlo?
Y aún si el estudiante está demasiado deseoso de aprender,
el maestro tendría una buena razón para reprenderlo si él siempre está entrometiéndose,
hablando y no esperando en silencio para escuchar
pacientemente la instrucción de su maestro.
Claramente,
el estudiante no debe abrir su boca hasta que sea
ordenado o permitido hacerlo por su maestro.

O si alguien ha sido llamado para servir a un gran príncipe,
éste debe esperar pacientemente y estar preparado para que
pueda responder al príncipe en cuanto le hable,
siempre manteniendo su mirada en él para observar los más
pequeños movimientos e inclinaciones de su voluntad,
y entonces actuar correspondientemente.
Pero, seguramente sería considerado un sirviente impertinente e imprudente si,
en lugar de esto,
él ensordece al príncipe con un discurso (aunque sean alabanzas para él),
y va de un lado a otro haciendo cosas que quizás son buenas en sí mismas,
pero sin ninguna instrucción en particular para hacerlas.
¿Aceptarían los reyes de la tierra a tal sirviente?

Puesto que estamos ordenados a "`esperar diligentemente en Dios,`" y al hacerlo,
se nos promete que tendremos "`nuevas fuerzas,`" este esperar no puede
realizarse si no es por medio del cese o silencio de nuestra parte natural,
viendo que Dios se manifiesta a Sí mismo, no tanto al hombre externo o a los sentidos,
sino al hombre interno, es decir al alma y al espíritu.
Ahora,
si el alma aún está pensando y obrando en su propia voluntad y está ocupada ejercitándose
en sus propias imaginaciones (a pesar de que las cosas puedan ser buenas en sí mismas,
o incluso concernientes a Dios), a pesar de todo,
el alma se incapacita a sí misma de discernir al
"`susurro apacible y delicado`" del Espíritu,
haciéndose un gran daño,
al desatender a su deber principal de esperar en el Señor. En efecto,
esto sería como alguien que clama y habla continuamente de su negocio,
desatendiendo mientras tanto a alguien que le está susurrando silenciosamente al oído,
informándole de algo crítico de su negocio.

Por lo tanto,
dado que el principal deber de un Cristiano es experimentar
la voluntad natural crucificada (y sus movimientos),
para que Dios pueda obrar en él tanto el querer como el hacer,
es por eso que el Señor estima en gran manera la profunda sujeción y abnegación inherentes
en el esperar en Él. Porque hay muchos quienes se satisfacen en las cosas de la religión,
gratificando sus propias voluntades y caprichos carnales en ambiciosas y curiosas especulaciones,
haciéndose de esta manera, un nombre y una reputación. Otros,
debido a costumbres o educación, encuentran la religión placentera y habitual.
Pero tales personas,
por lo general no son ni una pizca más regeneradas o internamente santificadas
en sus espíritus que otros quienes abiertamente satisfacen sus deseos.
En efecto, ambos tipos son igualmente dañinos para los hombres,
y pecaminosos ante los ojos de Dios,
produciendo nada más que el fruto y el efecto del espíritu
y de la voluntad no renovadas y naturales del hombre.
Porque incluso si un hombre,
tratara de evitar pecar a partir de un sentido de pecado y temor al castigo,
multiplicando pensamientos de muerte, infierno, y juicio, y también,
presentando a su imaginación los deleites del cielo, múltiples plegarias,
entre otros actos religiosos,
estas cosas no podrían librarlo de una sola iniquidad sin
el poder interno y secreto del Espíritu y gracia de Dios.
En efecto,
esto lograría lo mismo que las hojas de la higuera
con las que Adán pensó cubrir su desnudez,
porque esas cosas son meramente el producto de la voluntad del hombre natural,
que proceden del amor propio y de la auto-conservación,
y no surgen exclusivamente de esa Semilla divina de justicia que
es dada por Dios a todos para gracia y salvación. Dicha religión,
es por ende rechazada por Dios y de ninguna manera aceptable para Él,
ya que el hombre natural, con todas sus artes, habilidades y actividades,
es condenado por Él mientras se mantenga en ese estado natural.

Entonces, este gran deber de esperar en Dios,
debe ejercitarse necesariamente en la negación del yo,
tanto internamente como externamente, en una quieta y total dependencia en Dios.
El hombre debe retirarse de todas las obras,
imaginaciones y especulaciones de su propia mente,
para que estando vaciado de sí mismo y crucificado
en medida a los frutos naturales del yo,
pueda estar apto para recibir al Señor,
quién no tendrá un copartícipe o competidor en Su gloria y poder.
Y cuando el hombre se posiciona de esta forma delante del Señor,
la pequeña Semilla de justicia que Cristo ha comprado y Dios ha plantado en el alma,
es decir la medida de gracia y vida (la cual está oprimida y crucificada
por los pensamientos e imaginaciones naturales del hombre),
recibe un lugar para incrementarse y se convierte
en un nacimiento o alumbramiento santo en el hombre.
Este es ese don celestial de vida en y por el cual
el alma y espíritu del hombre llega a ser leudado.
Y al esperar en este don, el hombre llega a ser aceptado delante de Dios,
para estar en Su presencia,
escuchar Su voz y observar los movimientos de Su Santo Espíritu.

Entonces, el lugar del hombre es esperar en esto.
Y aquí,
cuando cosas concerniente a Dios o relacionadas a la religión se presentan a su mente,
su alma puede estar involucrada en esto no para perjudicar,
sino más bien para el gran beneficio tanto de sí mismo como de los demás,
porque aquí las cosas no brotan a partir de su propia voluntad,
sino del Espíritu de Dios.
Y a medida que el Espíritu se levante, se mueva y enseñe a su mente,
él puede involucrarse en el pensamiento y la meditación,
o en la predicación y la oración. Por esto, también se puede apreciar,
que no estamos en contra de la meditación (como algunos nos han acusado falsamente);
sino que estamos en contra de los pensamientos e
imaginaciones de la voluntad propia del hombre natural,
a partir de los cuales provienen todos los errores y las herejías en el mundo entero,
concernientes a las religión Cristiana.

Pero, si en algún momento a Dios le agrada,
cuando uno o más se encuentran esperando en Él,
no mostrarles tales cosas que tienden a ejercitar sus mentes en pensamientos e impresiones,
sino simplemente mantenerlos en una dependencia santa,
y causar (según ellos persisten en dicha dependencia) que Su refrigerio
secreto y el toque puro de Su vida santa fluya sobre ellos,
entonces ellos tienen una buena razón para estar contentos.
Porque por esto (como sabemos por la buena y bendita experiencia),
el alma es más fortalecida, renovada y afianzada en el amor de Dios,
y armada contra el poder del pecado, que por cualquier otro medio.
En efecto,
esto es un anticipo de ese gozo real y sensible de
Dios que los santos en el cielo poseen a diario,
el cual Dios con frecuencia proporciona aquí a Sus hijos para su aliento y consuelo,
especialmente cuando se reúnen para esperar en Él.

Porque hay dos poderes o espíritus contrarios, estos son:
el poder y espíritu de este mundo, en el que reina el príncipe de la oscuridad,
y por tanto reina sobre todos los que son movidos y obran de parte de él;
y el poder del Espíritu de Dios, en el cual Dios obra y gobierna,
y por tanto reina sobre todos los que obran en y desde él. Entonces,
cualquier cosa que el hombre piense o haga,
independientemente de qué tan espiritual o religiosa sea la noción o forma,
mientras él actúe y se mueva en la voluntad y espíritu natural y corrupto (y no desde,
en y por medio del Poder de Dios), él peca en todo lo que hace,
y no es aceptado por Dios.
Así es que "`tanto la oración como los pensamientos de los impíos,
son pecado`" (Proverbios 28:9, 21:4). Por lo tanto,
lo que sea que haga un hombre en y desde el Espíritu y poder de Dios,
teniendo su entendimiento y voluntad influenciada y movida por él,
ya sea en cosas religiosas, civiles o incluso naturales,
él es acepto en lo que hace bajo la mirada de Dios y es
bienaventurado en lo que hace (Santiago 1:25).

Además,
la excelencia de este esperar en silencio en Dios también
aparece en que es imposible para el enemigo (este es,
el diablo) falsificarlo,
y por lo tanto engañar o burlar a quienes lo practican correctamente.
Ahora, en todas las otras formas él puede mezclarse con la mente natural del hombre,
y "`disfrazándose`" (2 Corintios 11:14) puede engañar al alma,
ocupándola con otras cosas (quizás inocentes en sí mismas),
mientras les sigue impidiendo ver la Luz pura de Cristo, y conocer y hacer Su voluntad.
Porque el espíritu envidioso de la felicidad eterna del hombre sabe muy bien cómo acomodarse
y ajustar sus trampas a todas las diversas disposiciones e inclinaciones de los hombres.
Si él encuentra a una persona que no está en condiciones
de ser tentado con pecados abiertos o deseos mundanos,
siendo más bien reacio a tales cosas y más inclinado a lo religioso,
él puede tentarle permitiendo que sus pensamientos
e imaginaciones corran a asuntos espirituales,
emocionándolos a obrar, actuar, meditar, etc., en su propia voluntad.
Ciertamente, él bien sabe que mientras el yo domine,
y el Espíritu de Dios no sea el mayor y principal actor,
entonces el hombre aún no ha salido de su alcance.
De esta manera, el enemigo de la humanidad puede acompañar al sacerdote al altar,
al predicador al púlpito, al entusiasta en sus oraciones,
y al doctor de la divinidad a su estudio.
Y aquí,
él fácilmente permitirá a los Cristianos profesantes que
se esfuercen y trabajen entre sus libros religiosos,
sí,
incluso les ayuda a descubrir e inventar distinciones sutiles y
mezclas mediante las cuales pueden impedir que tanto sus mentes,
como otras a través de ellas,
le presten atención a la Luz de Dios en su consciencia y esperen en Él. Por lo tanto,
no hay ninguna actividad en la que el enemigo pueda entrar y tener
un lugar principal (a menudo sin que el alma lo discierna),
excepto por este esperar en silencio en Dios.
Porque él solo puede obrar en y por medio del hombre natural y de sus facultades,
actuando secretamente sobre sus imaginaciones y deseos.
Por tanto, mientras que el hombre esté pensando y meditando en sí mismo,
él no puede estar seguro de que el diablo no le esté influenciando.
Pero cuando el hombre natural es llevado al silencio
y a la nadedad con respecto a sus propias obras,
y la luz pura de Dios está brillando en él, ahí el enemigo también cesa,
porque no puede soportar la presencia y la brillante luz de Dios.

Es cierto que el enemigo no falla en asistir a nuestras reuniones, y en efecto,
él puede entrar y obrar en una reunión que se encuentra en silencio solo de palabras,
ya sea manteniendo la mente en varios pensamientos e imaginaciones,
o embotando y abrumándola con un espíritu de pesadez y pereza.
Pero cuando nos retiramos de todo, y estamos vueltos internamente al Señor,
y estamos por un lado diligentes y alertas,
y por el otro en silencio y retirados de todos nuestros pensamientos,
y mientras permanecemos en este lugar seguro, nos sentimos lejos de su alcance.
Sí, a menudo el poder y la gloria de Dios irrumpirá y aparecerá,
así como el sol brillante atraviesa las nubes y la neblina para disipar ese poder
de las tinieblas el cuál a menudo sentimos buscando nublar y oscurecer la mente,
evitando que espere por completo en Dios.

Además,
la grandeza de esta adoración se muestra en que no puede ser detenida
o interrumpida por la malicia de los hombres o de los demonios,
como sucede con las otras formas de adoración. Ahora,
pueden ocurrir interrupciones y cesaciones de la adoración de dos maneras:
ya sea porque se nos impida reunirnos usando de violencia externa,
separándonos unos de los otros; o cuando se nos permite reunirnos,
pero somos interrumpidos por un tumulto, ruido,
y confusión que los maliciosos hacen para maltratarnos o distraernos.
Ahora, en ambos casos, esta adoración sobrepasa al resto, porque, en primer lugar,
aunque se nos impida reunirnos,
mientras todos se encuentren internamente reunidos en la medida de vida en sí mismos,
se disfruta de una comunión y unidad secreta,
la cual el diablo junto con todos sus instrumentos nunca podrá romper o impedir.
Segundo, concerniente a los disturbios que ocurren cuando nos reunimos,
hemos podido (gracias a la naturaleza de esta adoración)
mantenernos ininterrumpidos en cuanto a Dios,
y también para mostrar un ejemplo de la paciencia del Cristiano hacia todos,
a menudo incluso conmoviendo y convenciendo a nuestros oponentes.
Porque ahora no hay ningún tipo de adoración empleada por otros
que persista sin estar autorizada y protegida por el magistrado,
o defendida por armas carnales.
Sin embargo,
a menudo ejercitamos nuestra adoración hacia Dios mientras estamos
también soportando pacientemente los reproches y abusos que Cristo
profetizó que serían frecuentes en los Cristianos.
Porque,
¿Cómo los Católicos pueden decir su Misa si hay algún
presente para ocasionar un disturbio e interrumpirlos?
Simplemente quite el Misal, el cáliz, el anfitrión, o las vestiduras del sacerdote,
o derrame el agua o el vino, apague las velas, y todo el asunto se detiene.
Quite de los Luteranos o Episcopales su liturgia o el Libro
de Oración Común y no se puede llevar a cabo ningún servicio.
Elimine de los Calvinistas, Arminianos, Independientes o Anabautistas, el púlpito,
la Biblia, y el reloj de arena,
o hagan un ruido para que la voz del predicador no pueda ser escuchada,
o despójelo de su Biblia y de sus libros, y entonces él tiene que permanecer en silencio.
Porque todos estos han declarado hereje esperar para
hablar según el Espíritu les da que hablen,
y entonces toda su adoración puede ser fácilmente estropeada.

Sin embargo,
cuando las personas se reúnen y su adoración no consiste en actos externos,
ni depende de que alguien hable, sino en estar sentados para esperar en Dios,
y estar reunidos fuera de todo lo visible para sentir en Espíritu al Señor,
entonces ninguna de estas cosas puede obstaculizarlos.
De esto, verdaderamente podemos decir que tenemos mucha experiencia personal.
Porque cuando los magistrados, suscitados por la malicia y envidia de nuestros oponentes,
han usado todos los medios posibles para impedir que nos reunamos--por medio de multas,
golpes, azotes,
destierro e incluso la muerte--todo ha demostrado ser ineficaz
para atemorizarnos de nuestras santas asambleas.
En efecto,
sería casi increíble declarar la maldad que los hombres
(que pretenden ser Cristianos) han traído sobre nosotros.
Porque a menudo nos han golpeado y arrojado agua y tierra durante nuestras reuniones.
Allí han bailado, brincado, cantado y hablado todo tipo de palabras profanas e impías,
han deparado violencia y vergonzosos comportamientos a mujeres y vírgenes sobrias,
nos han abucheado, burlado y escarnecido, preguntándonos,
"`si el Espíritu aún no ha llegado,`" y mucho más que sería tedioso relatar.
Pero a pesar de todo esto, hemos continuado seria y silenciosamente,
sentados juntos y esperando en el Señor,
de modo que por medio de estas cosas nuestra comunión interna y
espiritual con Dios y el uno con el otro en la luz pura de justicia,
no ha sido obstaculizada.
Por el contrario, el Señor,
teniendo conocimiento de nuestros sufrimientos y reproches por el bien de Su testimonio,
ha ocasionado que Su poder y gloria abunden aún más entre nosotros,
y nos ha refrescado poderosamente por medio del sentido de Su amor,
el cual ha llenado nuestras almas y nos ha hecho sentir reunidos
en el "`nombre del Señor,`" que es la "`torre fuerte`" del justo.
Sí, algunas veces, en medio de este tumulto y oposición,
Dios nos ha movido poderosamente por Su Espíritu
tanto para testificar de ese gozo del que disfrutamos,
como para declarar poderosamente (en la evidencia y demostración del Espíritu),
en contra de su locura y maldad.
Y así,
a veces hemos sido testigos del poder de la Verdad
que los lleva a cierta medida de quietud y silencio,
frenando las impetuosas corrientes de su furia y locura.
En efecto, como Moisés con su vara,
dividió las olas del Mar Rojo para que los Israelitas pudieran atravesarlo,
así también Dios, por medio de Su Espíritu,
ha hecho un camino para nosotros en medio de esta furiosa
maldad para disfrutarlo y poseerlo a Él pacíficamente,
y para llevar a cabo nuestra adoración a Él. Y algunas veces, en tales ocasiones,
varios de nuestros oponentes e interferentes han sido en ese momento,
convencidos de la Verdad y han llegado a ser de perseguidores
a convertirse en víctimas junto con nosotros.
Que no se olvide, sino que quede registrado y permanezca como un constante recuerdo,
que en estas bestiales y brutales crueldades usadas
para molestarnos en nuestras reuniones espirituales,
ninguno ha sido tan constante como los estudiantes jóvenes de las
universidades que estaban estudiando filosofía y teología,
muchos de los cuales estaban preparándose para el ministerio.
Si ponemos por escrito todas las abominaciones que se han cometido por los jóvenes cleros,
haría un volumen nada pequeño.

Por lo tanto, sabemos que somos partícipes de la dispensación del Nuevo Pacto,
y verdaderos discípulos de Cristo,
compartiendo con Él en esa adoración espiritual la
cual es llevada a cabo en el Espíritu y en Verdad,
pues como Él es,
así somos nosotros en este mundo (1 Juan 4:17). Porque
la adoración del Antiguo Pacto tuvo una gloria,
un templo, y ceremonias externas, y estaba lleno de esplendor y majestad externa,
con un tabernáculo y altar externo, embellecido con oro, plata y piedras preciosas.
Sus sacrificios fueron atados a un lugar en particular externo,
es decir el Monte Sion externo,
y los que oraban lo hacían con sus rostros hacia ese templo externo.
Todo esto tenía que ser protegido por un brazo externo,
porque los judíos no podían disfrutar pacíficamente de estas cosas,
excepto cuando eran resguardados de la violencia de sus enemigos externos.
Por ende, cuando en cualquier momento sus enemigos prevalecían sobre ellos,
su gloria era oscurecida, sus sacrificios cesaban,
y la expresión de su adoración perdía su belleza.
Por esta razón, ellos se quejaban, lamentaban,
y se afligían por la destrucción del templo como una pérdida irreparable.

Pero Jesucristo, el autor y fundador de la adoración del Nuevo Pacto,
testifica que Dios no debe ser adorado en este u otro lugar,
sino en Espíritu y en Verdad.
Ya que Su "`reino no es de este mundo,`" entonces
su adoración no consiste en cosas mundanas,
ni requiere nada de la sabiduría, gloria, riquezas,
o esplendor de este mundo para embellecerla o adornarla,
ni necesita un poder o brazo de carne externo para sostener, apoyar o protegerla.
Más bien,
puede ser realizada por aquellos que tienen una mente
espiritual a pesar de toda la oposición,
violencia y la malicia de los hombres.
Puesto que es completamente espiritual,
está lejos del alcance de los hombres naturales para interrumpirla o molestarla.

Ahora,
es muy cierto que Jesucristo experimentó y poseyó Su reino espiritual aún estando oprimido,
perseguido y rechazado por los hombres.
Y a pesar de la malicia y furia del diablo,
"`despojó a los principados y a las potestades, los exhibió públicamente,
triunfando sobre ellos;
para destruir por medio de la muerte al que tenía el imperio de la muerte, esto es,
el diablo.`"
Por ende, todos los seguidores de Cristo pueden y lo adoran,
no solo sin un brazo de carne que los proteja, sino incluso cuando están oprimidos,
porque su adoración (siendo espiritual) es defendida y mantenida por el poder del Espíritu.
En cambio,
la adoración que es carnal y consiste en ceremonias y consideraciones externas y carnales,
necesita de un brazo externo y carnal para protegerla y defenderla,
de lo contrario no puede permanecer y subsistir.
Por lo tanto,
es evidente que la adoración de nuestros oponentes
(tanto los Protestantes como los Católicos),
no es la verdadera adoración espiritual y del Nuevo Pacto de Cristo Jesús,
porque se ha observado durante mucho tiempo que ellos no pueden
permanecer sin el consentimiento y protección del magistrado externo,
ni su adoración se puede realizar en medio de la mínima oposición,
porque no están en la paciencia de Jesús, para servir y adorarle con sufrimientos,
deshonra, calumnia y reproches.
A partir de aquí han surgido todas las guerras, batallas,
persecuciones y derramamiento de sangre entre los Cristianos,
cuando cada uno (por medio del brazo de carne) se ha esforzado
por defender y proteger su propia forma y adoración.

Ahora, la naturaleza de esta adoración,
la cual es llevada a cabo por la operación del Espíritu
(estando el hombre natural en silencio),
es declarada en estas palabras de Cristo (Juan 4:23-24): "`Mas la hora viene, y ahora es,
cuando los verdaderos adoradores adorarán al Padre en espíritu y en verdad:
porque el Padre tales adoradores busca que le adoren.
Dios es Espíritu; y los que le adoran, en espíritu y en verdad es necesario que adoren.`"
Esta declaración debe observarse cuidadosamente, pues es el primero,
principal y más amplio testimonio dado por Cristo de la verdadera adoración Cristiana,
mostrando ser distinta y separada de la adoración que está bajo la Ley.
Aquí Él muestra que el tiempo ha llegado en que la
adoración debe ser "`en Espíritu y en Verdad,
porque el Padre tales adoradores busca que le adoren.`"
Entonces,
ya no se trata de una adoración que consiste en observaciones externas
para ser llevadas a cabo por el hombre en tiempos u ocasiones establecidos,
los cuales puede hacer en su propia voluntad y en su propia fuerza, de lo contrario,
no diferiría en sustancia,
sino solo en algunas cosas particulares de la adoración bajo la ley.
Y en cuanto a la razón de esta adoración no podemos
dar ninguna mejor que la que Cristo da aquí,
la cual debería ser suficiente para satisfacer a cada Cristiano, a saber,
que "`DIOS es ESPÍRITU,
y los que le adoran es necesario que adoren en Espíritu y Verdad.`"
Y aunque esto debería ser recibido por todos por
la simple virtud de ser las palabras de Cristo,
está además fundado sobre una demostración clara de la razón. Porque
Cristo declara simple y excelentemente que puesto que Dios es Espíritu,
entonces debe ser adorado en Espíritu.
Esto es tan evidente y seguro que no permite alguna contradicción.

Porque bajo la Ley,
cuando Dios instituyó y señaló esa adoración ceremonial a los Judíos,
puesto que esa adoración era externa,
El consideró necesario compadecerlos de una manera especial,
y morar entre los querubines en el tabernáculo, y más tarde hacer el templo en Jerusalén,
Su habitación. El también hizo que algo de su gloria y majestad externa se les apareciera,
lloviendo fuego del cielo para consumir los sacrificios,
y llenando el templo con una nube.
De esta manera (siendo todo visible al ojo externo),
Él se les manifestó proporcionalmente a esa adoración
externa que les había ordenado que hicieran.
Pero ahora, bajo el Nuevo Pacto,
ha visto idóneo en Su sabiduría celestial dirigir
a sus hijos en un camino más celestial y espiritual,
con la intención de derogar las observaciones externas y carnales,
para que Su pueblo ponga su mirada más en la gloria y reino interno que en lo externo.
Él ha establecido una adoración interna y espiritual,
y por ende ahora no vincula a su pueblo con el templo de Jerusalén,
ni a ceremonias u observaciones externas,
más bien toma el corazón de cada Cristiano como un templo para morar en él,
y ahí Él aparece directamente y enseña cómo servirle en cualquier acto externo.
Ya que, como dice Cristo, "`Dios es Espíritu,`" debe ser adorado ahora en el Espíritu,
en donde Él se revela y mora con el quebrantado de corazón. De hecho,
el corazón del hombre es el que se ha convertido
ahora en el templo de Dios en donde Él será adorado,
y ya no más en templos externos particulares (pues, como está escrito,
"`El Altísimo no habita en templos hechos de mano`"). Y así como
la gloria del Señor descendió para llenar el templo externo,
y por lo tanto era necesario que fuese purificado y limpiado,
teniendo toda la contaminación removida, sí,
y las cosas del tabernáculo recubiertas con el oro más precioso,
y con metales limpios y costosos; así también,
antes de que Dios pueda ser adorado en el templo interno del corazón,
y este también debe ser purgado de su propia inmundicia,
y de todos sus propios pensamientos e imaginaciones,
para que esté preparado para recibir el Espíritu de Dios y ser movido por éste.
Por lo tanto, esta adoración es en Espíritu,
y es también "`en Verdad,`" lo que significa (por las razones arriba mencionadas),
que es la única adoración correcta y verdadera,
que no puede ser falsificada por el enemigo, o realizada por el hipócrita.

Ahora,
aunque esta adoración espiritual es de hecho muy diferente de las
diversas adoraciones establecidas e inventadas entre los Cristianos,
y por lo tanto puede parecer extraña para muchos, sin embargo ha sido testificada,
encomendada y practicada por los más piadosos de todos los géneros, en todas las edades.
Esto se puede demostrar fácilmente por una multitud de testimonios,
y es a partir de la profesión y la práctica de estas cosas,
que ha surgido el nombre de "`místicos.`"
Estos llamados místicos son una secta generalmente
encomiada por todos (tanto Católicos como Protestantes),
y sus escritos están llenos tanto de la explicación
como de la aprobación de este tipo de adoración,
insistiendo en la introversión y abstracción de la mente (tal como lo llaman),
de todas las imágenes, pensamientos, y oraciones de la voluntad del hombre.
De hecho, ellos consideran esto como la cima de la religión Cristiana,
así que a pesar de que algunos de ellos profesan el Catolicismo Romano,
afirman atrevidamente,
"`Que aquellos que han alcanzado este método de adoración o lo están buscando,
no deben preocuparse ni ocuparse de confesiones frecuentes e innecesarias,
de ejercer labores corporales y austeridades,
de la práctica de oraciones voluntarias y verbales, de escuchar una cantidad de misas,
de devociones programadas, celebraciones a los santos, oraciones para los muertos,
indulgencias, o involucrarse con votos y promesas;
porque esas cosas tienden a estorbar al alma de percibir
las operaciones del Espíritu divino en lo interno,
y de tener la libertad de seguir al Espíritu donde sea que lo dirija.`"^
footnote:[Sancta Sophia, Ofrecido por los Benedictos Ingleses, publicados en Douay,
año 1657, trat.
I, sec.
ii, cap.
5]
Y sin embargo,
¡quién no sabe que la mismísima sustancia de la religión de los
Católicos Romanos consiste en tales observancias y actos externos!
No obstante,
pareciera por este y muchos otros pasajes de sus propios escritores místicos,
que estos hombres y mujeres consideraban que esta
adoración espiritual era superior a todas las demás,
y que aquellos que la habían alcanzado, no tenían necesidad de las otras.
De hecho, los que habían probado de esto,
confesaron rápidamente que todas las otras formas
y ceremonias de adoración eran inútiles para ellos;
ni las llevaban a cabo como cosas necesarias,
sino solamente por el bien del orden o del ejemplo.^
footnote:[La Vida de Balthazar Alvares, en la misma Sancta Sophia, trat.
III, sec.
i, cap.
7]
Por tanto,
a pesar de que algunos de estos hombres y mujeres permanecieron
nublados con las usuales tinieblas de su profesión religiosa,
aún así afirmaban que la adoración espiritual debía ser retenida y buscada,
incluso si requiriera la omisión de sus ceremonias externas.
En consecuencia, Bernard de Clairvaux una vez escribió,
"`Presten atención al gobierno de Dios,
el reino de Dios está en vosotros;`" y después de decir
que sus leyes y reglas externas deben ser guardadas,
añadió, "`Pero si sucediera que uno de estos dos debe ser omitido, en este caso,
es mucho mejor omitir las leyes externas que las internas;
pues por cuanto el Espíritu es más superior y noble que el cuerpo, por este tanto,
los ejercicios espirituales son más provechoso que los corporales.`"^
footnote:[En su Epístola a William, un abad del mismo orden.]

Por lo tanto,
¿No debería ser seguida y cumplida aquella clase de adoración que los
mejores hombres en todos los tiempos y en todas las sectas han elogiado,
y la cual también está más de acuerdo con la doctrina de Cristo?
¿No deberían todos los hombres adorarlo en Espíritu y en verdad,
especialmente dado que ahora Él ha levantado un pueblo para
testificar y predicar de esta adoración ante todo el mundo,
a pesar de la gran oposición? Y estos ministros de Cristo ahora no hacen
de esta adoración (como los hicieron erróneamente los místicos),
un misterio que solamente puede ser alcanzado por
unos pocos hombres o mujeres en un claustro,
o sugieren que sea alcanzado sólo tras haber trabajado
bajo muchas ceremonias y observaciones externas,
como si fuera la consecuencia de tal esfuerzo.
Más bien, ellos predican del amor gratuito de Dios, que no hace acepción de personas,
y que estuvo cerca para escuchar y revelarse a Sí mismo a Cornelio,
un centurión y un Romano, y a Simeón y a Ana, y quién reveló Su gloria a María,
una pobre sierva, y a los pastores pobres,
en lugar de los sumos sacerdotes y conversos devotos entre los Judíos. Asimismo,
en y según Su libre amor,
ellos encuentran que Dios está revelando y estableciendo esta adoración en multitudes,
y haciendo que muchos comerciantes pobres (sí,
incluso niños y niñas) sean testigos de esto.
Y estos están suplicando e implorando a todos que dejen a un lado su propio culto voluntario
y actos realizados en sus propias voluntades y por medio de su propia fortaleza y poder
natural (sin retirarse de sus imaginaciones y pensamientos vanos,
o sentir el Espíritu puro de Dios moverse y despertarse en ellos),
para que ellos puedan practicar esta adoración aceptable
la cual es "`en Espíritu y en Verdad.`"

=== Objeciones Contestadas

[.no-indent]
Pero en contra de esta adoración, ellos objetan:

[.discourse-part]
Objeción: Primero,
pareciera ser un ejercicio infructuoso para un hombre que haga o piense en nada.
Uno podría estar mejor ocupado ya sea meditando sobre
un buen tema u orando o alabando a Dios.

[.discourse-part]
Respuesta: Yo respondo,
lo que es absolutamente necesario antes de que todos los otros deberes
puedan llevarse a cabo de manera aceptable (como hemos demostrado),
no puede ser infructuoso.
Además, aquellos que imaginen que Dios está complacido por sus propias obras y acciones,
tienen una aprensión carnal e inculta de Dios y de las cosas de Su reino.
Porque claramente, como se ha demostrado,
el primer paso del hombre hacia el temor del Señor es cesar de sus propios pensamientos
e imaginaciones y permitirle al Espíritu de Dios que obre en él;
porque debemos "`dejar de hacer lo malo,`" antes de que
"`aprendamos a hacer el bien`" (Isaías 1:16-17). De hecho,
esta intromisión en las cosas espirituales por el entendimiento natural propio del hombre,
es uno de los más grandes y más peligrosos males
a los cuales el hombre se encuentra inclinado,
siendo la razón de la caída de nuestros primeros antepasados, a saber:
adelantarnos a desear conocer las cosas,
y entrometernos en ellas sin el mandato del Señor, y siendo contrarios a él.

[.discourse-part]
Objeción: En segundo lugar, algunos discrepan,
"`Si su oración consiste simplemente en retirarse internamente al Señor,
sintiendo Su Espíritu levantarse en usted,
y haciendo entonces cualquier acto que sea guiado por Él,
entonces ¿qué necesidad tiene usted de reunirse públicamente en tiempos y lugares determinados,
ya que todos pueden disfrutar de esto en casa?
¿No deberían todos quedarse en casa hasta que sean
movidos a ir a un lugar o hacer algo en particular?
¿Y reunirse en lugares y tiempos determinados, no es una observación y ceremonia externa,
contrario a lo que usted declara?`"

[.discourse-part]
Respuesta: Yo respondo,
reunirse en tiempos o lugares determinados no es un acto
religioso o una parte de la adoración en sí misma,
sino sólo una reunión externa, que es necesaria para vernos los unos a los otros,
mientras estemos vestidos con este tabernáculo externo.
No obstante, Dios ha visto oportuno, mientras Sus hijos estén en este mundo,
utilizar los sentidos externos como un medio para transmitir la vida espiritual,
mediante cosas como hablar, orar, alabar, etc.,
lo cual no se puede hacer para la edificación mutua excepto cuando nos oímos y nos vemos.
Por lo tanto,
el Señor a menudo ocasiona que la vida interna (la cual
muchas veces no es transmitida por los sentidos externos),
abunde más cuando Sus hijos se congregan diligentemente
para esperar en Él. Así que verse unos a otros,
cuando están todos reunidos internamente en la Vida,
se da una oportunidad para que la Vida se levante secretamente y pase de vasija en vasija,
como "`hierro con hierro se aguza.`"
O incluso como cuando muchas velas en un lugar incrementan la luz y la hacen brillar más,
así también cuando hay muchos reunidos en la misma Vida, hay más de la gloria de Dios,
y su poder aparece para refrescar a cada individuo,
quien participa no solo de la Luz y Vida que se levantan en sí mismo,
sino que en todo el resto también. De este modo,
Cristo ha prometido una bendición particular para
aquellos que se reúnen juntos en Su Nombre,
diciendo que Él estará "`en medio de ellos`" (Mateo 18:20).

Además, el autor de los Hebreos expresamente prohíbe desatender este deber,
ya que tiene una consecuencia muy peligrosa y terrible, diciendo:
"`Y considerémonos unos a otros para estimularnos al amor y a las buenas obras;
no dejando de congregarnos,
como algunos tienen por costumbre... Porque si pecáremos voluntariamente
después de haber recibido el conocimiento de la verdad,
ya no queda más sacrificio por lo pecados`" (Hebreos 10:24-26). Por eso,
el Señor ha manifestado una consideración particular
para aquellos quienes se congregan de esta forma,
no solo para la mutua edificación de cada miembro,
sino también para que un testimonio público de Él pueda
mantenerse en la tierra y Su Nombre pueda ser glorificado.
Y ciertamente,
aquellos que son rectos en sus espíritus naturalmente se sienten
atraídos por mantener las reuniones del pueblo de Dios,
y nunca carecen de la influencia del Espíritu para motivarlos a seguir reuniéndose.

[.discourse-part]
Objeción: Finalmente,
algunos objetan que esta forma de adorar en silencio no aparece en toda la Escritura.

[.discourse-part]
Respuesta: Yo respondo; primero,
no hacemos del silencio el asunto principal de nuestra adoración,
ya que (como mencioné previamente) son muy pocas
las reuniones que son completamente en silencio,
donde alguno no es movido ya sea a predicar, orar, o alabar al Señor. De este modo,
creemos que nuestras reuniones son muy parecidas a las reuniones
de las iglesias primitivas que se han registrado en la Escritura,
pues incluso nuestros adversarios confesarán que
ellos ni predicaron ni oraron salvo por el Espíritu.
Por consiguiente,
¿No debió haber habido momentos en la iglesia primitiva
cuando el Espíritu _no_ los movió a hablar o actuar,
y entonces guardaron silencio?
De hecho,
no cabe duda en que hubo momentos de silencio antes
de que el Espíritu viniera sobre ellos.
Porque les fue dicho "`quedaos vosotros en la ciudad de Jerusalén,
hasta que seáis investidos de poder desde lo alto.`"
Y cuando "`estaban todos unánimes juntos;`" entonces,
el Espíritu cayó de repente sobre ellos.
Aquí no se hace mención de alguien hablando en ese momento,
y no se puede considerar absurdo concluir que estuvieron en silencio durante un rato.

Pero si se insiste que una reunión entera
en silencio no se puede encontrar en las Escrituras,
yo respondo; suponiendo que tal cosa no fue registrada en la Escritura,
no significa por lo tanto que no sea lícito,
viendo que naturalmente sigue de otros preceptos Bíblicos ya mencionados.
Porque a menudo la Escritura nos ordena que esperemos
en el Señor y también que nos reunamos.
Y cuando estamos reunidos, la Escritura prohíbe las oraciones o la predicación,
excepto cuando el Espíritu se mueve y dirige.
Por ende, si las personas se han reunido y el Espíritu no los mueve a hablar o actuar,
lo que necesariamente sucederá es que se queden en silencio.
De hecho,
es posible que se hayan hecho muchas cosas similares entre los santos de la antigüedad,
que, sin embargo, no fueron registradas en la Escritura;
aún así tenemos suficiente en la Escritura que manifiesta
que tales reuniones se llevaron a cabo.
Porque Job estuvo sentado en silencio por siete días junto con sus amigos (Job 2:13);
esto fue una larga reunión en silencio.
También puede ver Esdras 9:4, y Ezequiel 14:1 y 20:1.

Así, habiendo mostrado la excelencia de esta adoración,
probándola desde la Escritura y la razón,
y habiendo respondido a las objeciones que por lo general se hacen en contra de ella,
agregaré algo más particular concerniente a la predicación, a la oración, y al canto.

=== La Predicación

La predicación,
tal como se practica tanto entre los Católicos Romanos como en los Protestantes,
es cuando un hombre toma un pasaje de la Escritura,
y luego habla del mismo por una hora o dos según
lo que ha estudiado y premeditado en su aposento,
y ha recogido a partir de sus propias invenciones,
o a partir de los escritos y observaciones de otros.
Luego, tras haberlo memorizado (como hace un escolar con su lección),
lo lleva y lo repite delante de la congregación). Y cuanto
más agradable y fuerte sea la invención del hombre,
y cuanto más productivo y laborioso sea en reunir sus consideraciones
y en expresarlas con la excelencia de palabras y elocuencia humana,
más es considerado como un predicador excelente y capaz.

A esto nos oponemos, creyendo que cuando los santos están reunidos,
cada uno debería estar vuelto internamente al don y gracia de Dios dentro de sí mismo,
y el que ministra debe ser movido a ello por el surgimiento de la gracia en sí mismo.
El debe hablar lo que el Espíritu de Dios le proporciona,
sin prestar atención a la elocuencia y la sabiduría de las palabras,
sino a la demostración del Espíritu y poder.
Aquí él puede interpretar algo de la Escritura que
el Espíritu trae a su mente y le dirige,
u ofrecer palabras de exhortación, consejo, reprobación e instrucción,
o relatar el significado de algunas experiencias espirituales,
todo lo cuál estará de acuerdo con la Escritura,
aunque quizás no esté basado en algún capítulo o versículo en particular como texto.

Ahora,
examinemos y consideremos cuál de estos dos tipos de predicación está
más de acuerdo con los preceptos y prácticas de Cristo y Sus apóstoles,
y de la iglesia primitiva como se registra en la Escritura.
Primero, con respecto a la predicación basada en un texto,
si esta no fuera meramente habitual y premeditada,
sino llevada a cabo por la operación del Espíritu, no tendríamos nada en su contra.
Pero hacerlo de la manera que es común entre la mayoría
de los Cristianos profesantes de hoy día,
no hay ni precepto ni práctica en todo el Nuevo Testamento, por lo que puedo observar.

[.discourse-part]
Objeción: Sin embargo ellos alegan que Cristo tomó el libro de Isaías y lo leyó,
y luego habló a partir de este.
Y del mismo modo que Pedro predicó desde el pasaje del profeta Joel.

[.discourse-part]
Respuesta: Yo respondo,
que Cristo y Pedro no lo hicieron excepto cuando fueron inmediatamente
influenciados y movidos por el Espíritu de Dios,
y sin premeditación (lo cuál supongo que nuestros adversarios no lo negarán);
cuyo caso aprobamos con gusto.
Pero esto está lejos de la forma acostumbrada e inventada que se practica hoy,
que no espera los movimientos ni la guía del Espíritu de Dios,
ni tiene su expectativa en ellos.
Además,
está claro que ni Cristo ni Pedro hicieron esto como una costumbre o forma establecida
para ser practicada constantemente por todos los ministros de la Iglesia,
porque esto no aparece en la mayoría de los sermones de Cristo y Sus apóstoles,
registrados en la Escritura (véase Mateo 5:1, Marcos 4:1,
las predicaciones de Pablo a los Atenienses y a los Judíos, etc.). Muy por el contrario,
cuando Cristo envió a Sus discípulos,
expresamente mencionó que ellos no debían hablar a partir de ellos mismos,
o preparar algo de antemano,
sino más bien decir aquello que "`el Espíritu Santo les enseñará en la misma hora,`"
tal como es mencionado particularmente por los tres evangelistas (Mateo 10:20;
Marcos 13:11; Lucas 12:12). Ahora,
si Cristo les dio esta orden a Sus discípulos antes
de apartarse de ellos como lo que debían practicar,
con mucho más razón tenían que hacerlo después de Su partida,
ya que entonces iban a recibir más especialmente al Espíritu que los "`guiaría
a toda la verdad`" y "`recordaría todo lo que Él les había dicho.`"
(Juan 14:26) Y si eso tenían que hacer cuando se presentaban
ante los magistrados y príncipes de la tierra,
mucho más debían hacerlo en su adoración a Dios cuando estaban delante de Él,
viendo que Su adoración debe realizarse en Espíritu.
Por tanto, después de que recibieron el Espíritu Santo, se dice que,
"`comenzaron a hablar, según el Espíritu les daba que hablasen`" (Hechos 2:4),
y no lo que habían estudiado y reunido de los libros de una forma premeditada.

Francis Lambert lo habla bien, y muestra su hipocresía, diciendo:

[quote]
____
Dónde están ahora aquellos que se glorían en sus invenciones espirituales,
diciendo,
"`¡Una gran invención! ¡Una gran invención!`" refiriéndose
a eso que han inventado de la Escritura.
Pero, ¿qué tiene que ver el creyente fiel con tales invenciones?
No, no tendremos invenciones, sino más bien cosas que sean sólidas, invencibles, eternas,
y celestiales--no eso que los hombres han inventado, sino lo que Dios ha revelado.
Porque si creemos la Escritura,
nuestros inventos no hacen más que provocar a Dios para nuestra destrucción.
____

Y después él escribe,

[quote]
____
Ten cuidado, que no determines precisamente hablar lo que antes has meditado,
cualquier cosa que sea.
Porque aunque es lícito determinar el texto que debes exponer,
no es así con la interpretación; no sea que, si lo hace,
le quites al Espíritu lo que es Suyo, a saber,
dirigir tus discursos para que profetices en el nombre del Señor,
despojado de todo conocimiento, meditación y experiencia.
Debes comprometer tu corazón, tu lengua, y a ti mismo por completo a Su Espíritu,
no poniendo confianza alguna en tu estudio o meditación previa,
sino diciendo dentro de ti mismo (con gran confianza en la divina promesa),
"`El Señor dará la palabra con poder a los que verdaderamente predican el evangelio.`"

Pero sobre todas las cosas ten cuidado de no seguir la costumbre de los hipócritas,
quienes han escrito casi palabra por palabra lo que van a decir,
como si fueran a repetir algunas líneas en el teatro.
De hecho, éstos oran al Señor que dirija su lengua,
pero mientras tanto obstaculizan el camino del Espíritu Santo,
habiendo decidido no decir nada excepto lo que han escrito.
¡Oh infeliz clase de profetas!
Sí,
¡son verdaderamente malditos los que no dependen del Espíritu de Dios
sino de sus propios escritos y meditaciones! ¿Por qué ora usted al Señor,
profeta falso,
para que le dé Su Espíritu Santo mediante el cual hablar cosas provechosas,
y aún así rechazas Su Espíritu?^
footnote:[Trat. 5, de la Profecía, capítulo 3]
____

Ahora, esta manera de predicación premeditada (como todos afirman) puede ser,
y por lo general es, llevada a cabo por hombres malos o vacíos de la gracia verdadera,
por ende no solo falla en edificar a la iglesia o en engendrar y nutrir la fe verdadera,
sino que es destructiva para ella,
siendo directamente contraria a la naturaleza del ministerio
Cristiano y apostólico mencionado en las Escrituras.
Porque el apóstol predicó el evangelio "`no con sabiduría de palabras,
para que no se haga vana la cruz de Cristo`" (1 Corintios 1:17). Mas esta predicación,
al no ser hecha por la obra y movimiento del Espíritu de Dios,
sino por la invención y elocuencia del hombre,
en su propia voluntad y por medio de su aprendizaje y habilidades naturales y adquiridas,
está claramente basada en la sabiduría de palabras,
y por lo tanto la cruz de Cristo se hace vana.
La palabra y predicación del apóstol no fueron "`con
palabras persuasivas de humana sabiduría,
sino con demostración del Espíritu y de poder,`" para que la fe
de los oyentes "`no esté fundada en la sabiduría de los hombres,
sino en el poder de Dios`" (1 Corintios 2:3-5). Pero esta predicación,
no teniendo nada del Espíritu y del poder en sí (porque tanto los predicadores
como los oyentes confiesan libremente que no esperan tal cosa,
ni son a menudo conscientes de ella),
debe necesariamente consistir en las palabras persuasivas de la sabiduría del hombre.
Y dado que esta predicación es buscada por dicha sabiduría del hombre,
y usada por la fuerza de la elocuencia del hombre y en las palabras persuasivas,
por lo tanto no es de extrañar que la fe de esos que oyen y dependen de
tales predicadores y predicaciones esté fundada en la sabiduría humana,
y no en el poder de Dios.
Los apóstoles declararon que ellos hablaron "`no
con palabras enseñadas por sabiduría humana,
sino con las que enseña el Espíritu`" (1 Corintios 2:13). Sin embargo estos predicadores
confiesan que son ajenos al Espíritu Santo y a Sus movimientos y operaciones,
ni tampoco esperan sentirlos.
Por eso ellos hablan las palabras que su propia sabiduría
natural y conocimiento les enseña,
mezclándolas y añadiéndoles las palabras que han
hurtado de la Escritura y de otros libros,
y por tanto no hablan lo que enseña el Espíritu Santo.

Además,
esta predicación es contraria al método y orden de la iglesia
primitiva mencionada por el apóstol en 1 Corintios 14:30,
etc.,
donde en la predicación cada uno debía esperar su revelación
y darse lugar el uno al otro según se revelaran las cosas.
Pero ahora, nadie espera la revelación, no obstante,
el predicador tiene que hablar--no lo que le ha sido revelado,
sino lo que ha preparado y premeditado de antemano.

Finalmente, mediante este tipo de predicación,
el Espíritu de Dios (quién debería ser el instructor
y maestro principal del pueblo de Dios,
y cuya influencia es la única que hace que toda predicación sea efectiva
y beneficiosa para la edificación de las almas) queda excluido,
y la sabiduría, el conocimiento,
y la habilidad naturales del hombre son establecidos y exaltados.
Esto (sin duda) es una gran y principal razón de por qué la predicación
entre la mayoría de los Cristianos es tan infructuosa e ineficaz.
De hecho, según esta doctrina el diablo puede predicar, y debe ser también oído,
viendo que conoce la verdad y tiene tanta elocuencia como cualquier otro.
Pero, ¿en qué aprovecha la excelencia de palabras,
si la demostración y el poder del Espíritu que toca la consciencia no está presente?
Vemos en la Escritura que cuando el diablo confesó la verdad,
aún así Cristo no recibió su testimonio.
Y así como estos testimonios de la Escritura prueban que esta clase
de predicación es contraria a la doctrina de Cristo,
asimismo prueban que la nuestra es afirmada.

[.discourse-part]
Objeción: pero algunos pueden objetar de esta manera:
¿No han sido muchos los beneficiados, sí,
siendo tanto convertidos como edificados por el ministerio
de aquellos que han premeditado sus predicaciones?
¿Y el Espíritu, a menudo,
no ha concurrido por Su influencia divina con las predicaciones premeditadas,
de modo que algunas han impactado poderosamente las
almas de los oyentes para su beneficio?

[.discourse-part]
Respuesta: Yo respondo, aunque esto sea concedido (lo cual no voy a negar),
no infiere que la practica sea buena en sí misma,
lo cual sería como sugerir que la aparición de Cristo a Pablo en el camino
a Damasco pruebe que él hizo bien en su labor de perseguir a los santos.
Porque, como hemos dicho en otro lugar, ni acciones particulares,
ni las congregaciones enteras,
deberían ser evaluadas por los actos de condescendencia de Dios en tiempos de ignorancia.
De hecho, ha pasado a menudo que Dios,
teniendo consideración por la simplicidad e integridad
ya sea del predicador o de los oyentes,
ha descendido sobre el corazón del predicador por Su poder y santa influencia,
y por ellos le ha guiado a hablar cosas que no estaban en su discurso premeditado,
o quizás cosas que nunca antes había concebido.
Y estas exclamaciones pasajeras y exhortaciones no premeditadas pero vivas,
han probado a menudo ser más beneficiosas y refrescantes tanto para el
predicador como para los oyentes que todos sus sermones premeditados.
Y aún así,
la amable condescendencia del Señor de esta manera no debería animar
la continuación de aquellas cosas que en sí mismas no son aprobadas,
sino que, de hecho, son contrarias a la práctica de los apóstoles,
especialmente ahora que Dios está levantando a un pueblo
para que le sirva según la pureza y espiritualidad primitiva.
En realidad,
tales actos de la misericordia de Dios en los tiempos de tinieblas e ignorancia debería
comprometernos más a seguirle según Él revela Su camino más perfecto y espiritual.

=== La Oración

Habiendo hablado de la predicación, ahora es conveniente hablar de la oración,
acerca de la cual surge una controversia similar.
Nuestros adversarios, cuya religión es principalmente externa,
y cuyas acciones son el simple producto de la voluntad y habilidades naturales del hombre,
pueden orar así como predican--cuando lo deseen--y por ende,
tienen sus oraciones particulares determinadas.
Yo no pretendo entrometerme en las controversias
que tienen entre ellos mismos concerniente a esto,
algunos de ellos prefieren oraciones establecidas, como la liturgia, y otros,
oraciones que son concebidas de forma extemporánea.
Me basta que todos ellos estén de acuerdo en esto--que los movimientos
e influencias previas del Espíritu de Dios no son necesarios.
Por tanto, ellos tienen tiempos de oración establecidos en su adoración pública,
tales como antes y después de la predicación, y también en sus devociones privadas,
tanto en las mañanas como en las tardes, o antes y después de las comidas,
y en otras ocasiones similares en las cuales realizan
sus oraciones hablando palabras a Dios,
ya sea que sientan algún movimiento o influencia del Espíritu o no.
De hecho,
algunos de los principales han confesado que han orado de
esta forma sin los movimientos y asistencia del Espíritu,
reconociendo que han pecado al hacerlo, sin embargo consideran que es su deber hacerlo.

Confesamos libremente que la oración es un deber muy provechoso y necesario,
ordenado y apropiado para que todos los Cristianos lo practiquen frecuentemente.
Sin embargo, así como no podemos hacer nada sin Cristo,
tampoco podemos orar sin la concurrencia y asistencia de Su Espíritu.
Ahora, para que el estado de esta controversia pueda ser mejor entendido,
primero considere que la oración es en dos maneras: interna y externa.
La oración interna es ese volver secreto de la mente hacia Dios por el cual,
siendo secretamente tocada y despertada por la Luz de Cristo en la consciencia,
y humillada bajo el sentido de sus iniquidades, su indignidad, y su miseria,
levanta su mirada hacia a Dios, y luego,
uniéndose con los destellos secretos de la Semilla de Dios,
constantemente exhala secretos deseos y aspiraciones hacia Él. Es en este sentido que
con tanta frecuencia en las Escrituras se nos ordena "`orar sin cesar`" (Lucas 18:1;
1 Tesalonicenses 5:17; Efesios 6:18; Lucas 21:36),
lo cual no se puede entender como si se refiriera a la oración externa,
porque es imposible que los hombres estén siempre de rodillas,
expresando palabras de oración, etc.
De hecho,
esto les impediría a los hombres el ejercicio de aquellos
deberes no menos positivamente ordenados en la Escritura.
Entonces,
la oración externa es cuando el alma (ya estando en el ejercicio del retiro interno,
y sintiendo el aliento del Espíritu de Dios levantarse poderosamente) recibe
fuerza y libertad por un movimiento e influencia adicional del Espíritu,
para producir ya sea suspiros, gemidos, o palabras audibles, en reuniones públicas,
o en privado, en las comidas, etc.

Ahora, la oración interna es necesaria en todos los tiempos,
y por lo tanto el hombre nunca carece de alguna influencia
(en diversos grados) para la práctica de ella,
mientras dure el día de su visitación. Porque tan pronto
retira su mente y se considera en la presencia de Dios,
enseguida se encuentra a sí mismo en la práctica de ella.

Pero el ejercicio de la oración externa (como necesita
de una influencia mayor y movimiento adicional del Espíritu),
no puede ser practicada efectivamente hasta que la mente
se familiarice de alguna manera con la oración interna.
Por esta razón, los que son diligentes y vigilantes en sus mentes,
y muy retirados en el ejercicio de esta oración interna,
son más capaces de ser frecuentes en el uso de la externa,
porque esta influencia santa los acompaña más constantemente.
Y ellos, estando mejor familiarizados con los movimientos del Espíritu de Dios,
y acostumbrados a ellos, pueden percibir y discernir fácilmente Sus influencias.
Y puesto que aquellos que son más diligentes de esta forma,
experimentan un acceso cercano a Dios,
así Él toma más deleite en atraerlos por Su Espíritu para que se acerquen y le invoquen.

Así que,
cuando muchos están reunidos en este estado retirado y vigilante de la mente,
Dios frecuentemente derrama el Espíritu de oración entre ellos,
y los mueve a orar verbalmente para la edificación de unos a otros en amor.
Pero, debido a que esta oración externa depende de la interna,
y no puede llevarse a cabo aceptablemente excepto
por una influencia adicional y moción del Espíritu,
por lo tanto no podemos establecer tiempos determinados para orar externamente,
o hacer que sea obligatorio hablar palabras en tales y cuales momentos
ya sea que sintamos esta influencia y asistencia celestial o no.
Porque esto, según nuestro juicio,
sería tentar a Dios y acercarse a Él sin la debida preparación. En lugar de esto,
creemos conveniente primero presentarnos delante
de Él por medio de este retiro interno de la mente,
procediendo hacia adelante solo cuando Su Espíritu nos ayude y guíe. En verdad,
encontramos que el Señor acepta esto,
aunque algunas veces Él considera oportuno ejercitarnos
en silencio sin permitirnos hablar para probar nuestra paciencia,
para enseñarnos a no depender de actos externos,
o satisfacernos (como muchos lo hacen) con hablar muchas palabras u oraciones.
De esta manera, nuestra dependencia hacia Él se vuelve más firme y constante,
mientras esperamos que nos extienda Su cetro,
y nos conceda la habilidad de orar por medio de Su Espíritu.
No obstante, no negamos que Dios, bajo ocasiones particulares,
muy de repente (incluso cuando la mente apenas ha comenzado a volverse a Él),
pueda dar poder y libertad para producir palabras o actos de oración externa,
de modo que el alma apenas discierna cualquier movimiento previo.
Sin embargo, en todos los casos, el dicho de Bernard es verdadero, que "`toda oración,
que no tenga inspiración divina que la preceda, es tibia.`"

Ahora,
aunque afirmamos que nadie debe orar sin que el Espíritu lo mueva a hacerlo,
también sostenemos que desatender la oración es pecado,
siendo el pecado no venir al lugar donde ciertamente
se sentiría al Espíritu llevar a ella.
De hecho, no dudamos que muchos, al desatender este velar y retiro interno de la mente,
pierden muchas oportunidades preciosas para orar,
y de este modo incurren en culpa ante los ojos de Dios; y aún así,
también sería pecado si se pusieran a orar antes
de sentir primero la influencia del Espíritu.
Porque un sirviente claramente ofende a su amo cuando se acuesta en su cama y duerme,
y se niega a hacer los negocios de su señor. No obstante,
si se levanta de repente sin haberse puesto sus vestidos o sin tomar consigo
sus herramientas e instrumentos necesarios (sin los cuales no podría trabajar),
y se empeña a trabajar mucho sin propósito,
estaría tan lejos de rectificar su falta previa,
que incurriría justamente en una nueva reprimenda.
Y como alguien que es descuidado y está ocupado con otros asuntos,
puede que no escuche a alguien más hablarle,
o incluso falle en escuchar el repicar de un reloj, de la misma manera,
muchos por negligencia pueden dejar de escuchar las llamadas frecuentes de Dios,
dándoles acceso para orarle a Él. Sin embargo,
esto de ninguna manera les permite orar en sus propias
voluntades sin recibir la libertad de Dios.

Finalmente, aunque este es el método verdadero y correcto de oración,
y el único que es aceptable para Dios, sin embargo,
no negamos que muchas veces ha respondido a las oraciones y ha consentido
los deseos de aquellos (especialmente en tiempos de oscuridad),
que se han equivocado grandemente en estas cosas.
No dudamos que muchos se han conformado con oraciones formales,
y a pesar de que están muy equivocados tanto en el tema como en la manera de orar,
y sin la asistencia o influencia del Espíritu de Dios,
todavía han encontrado que Él aprovecha la ocasión para irrumpir en sus almas,
enterneciéndolos y refrescándolos maravillosamente.
Con todo ello, como se observó anteriormente con la predicación,
la amable condescendencia de Dios no significa Su
aprobación de las formalidades supersticiosas y vacías,
ni debería impedirle a nadie venir a practicar esa oración pura,
espiritual y aceptable que nuevamente Dios está restaurando
y a la que está guiando a Su pueblo.

Ahora, tengo la intención de probar primero,
lo apropiado de esta oración espiritual a través
de algunas consideraciones breves de las Escrituras,
y luego responder a las objeciones comunes de nuestros oponentes,
que también servirán para refutar su método y manera.

Primero, la necesidad de un retiro interno previo de la mente,
a fin de que pueda sentirse al Espíritu llevando a la oración,
se ve claramente en numerosas Escrituras.
De hecho, en la mayoría de los lugares donde se ordena la oración,
se menciona "`velar`" como aquello que necesariamente debe preceder.
Ver, por ejemplo, Mateo 24:42; Marcos 13:33, y 14:38; Lucas 21:36,
donde es evidente que este velar debe preceder a la oración. Ahora,
¿para qué es este velar?
¿O qué es,
sino un esperar para sentir el Espíritu de Dios guiándonos
a la oración para que pueda ser hecha aceptablemente?
Puesto que se nos dice que debemos "`orar en todo tiempo en el Espíritu,`"
y no podemos orar por nosotros mismos aceptablemente sin Él,
este velar debe ser recomendado para este propósito, a saber:
para velar y esperar el momento oportuno para orar,
que es cuando el Espíritu nos mueva a hacerlo.

Segundo, esta necesidad de que el Espíritu mueva y haga posible orar,
aparece abundantemente del lenguaje del apóstol Pablo en Romanos 8:26-27:
"`Y de igual manera el Espíritu nos ayuda en nuestra debilidad;
pues qué hemos de pedir como conviene, no lo sabemos,
pero el Espíritu mismo intercede por nosotros con gemidos indecibles.
Mas el que escudriña los corazones sabe cuál es la intención del Espíritu,
porque conforme a la voluntad de Dios intercede por los santos.`"
Primero, esta escritura muestra la incapacidad de los hombres, por sí mismos,
de orar o invocar a Dios en sus propias voluntades,
incluso quienes han recibido la fe de Cristo y están en medida
santificados por ella (como fue el caso de la iglesia en Roma,
a quién el apóstol se dirigió). Segundo,
este pasaje de las Escrituras nos señala al único
que puede ayudar y asistir a los hombres a orar,
el cual es el Espíritu,
e insiste en que sin esto no pueden orar aceptablemente
a Dios o provechosamente para sus propias almas.
Tercero, establece la manera y la forma de la intercesión del Espíritu,
que es "`con gemidos indecibles.`"
Y cuarto,
afirma que Dios recibe misericordiosamente las oraciones
que se presentan y se ofrecen a Sí mismo por el Espíritu,
sabiendo que son según Su voluntad.
Y puesto que lo que se afirma aquí por el apóstol es más consistente con los otros testimonios
de la Escritura que nos ordenan y recomiendan el uso de la oración,
yo argumento lo siguiente:

[.discourse-part]
_Argumento:_ Si el hombre no sabe orar, ni puede hacerlo sin la ayuda del Espíritu,
entonces para él no tiene ningún propósito y le es inútil orar sin Él.

Tercero,
la necesidad del Espíritu en la verdadera oración aparece desde
Efesios 6:18 y Judas 1:20. Porque en su carta a los Efesios,
el apóstol nos ordena a "`orar en todo tiempo en el Espíritu,`" y añade,
"`velando en ello;`" que es lo mismo como si hubiera
dicho que no debemos orar sin el Espíritu o sin velar.
Y Judas nos muestra que solo las oraciones que son "`en el Espíritu Santo`" tienden
a la "`edificación de nosotros mismos sobre nuestra santísima fe.`"

Cuarto,
el apóstol Pablo dice expresamente en 1 Corintios
12:3 que "`nadie puede llamar a Jesús Señor,
sino por el Espíritu Santo.`"
Entonces, si Jesús no puede ser nombrado correctamente excepto por el Espíritu Santo,
mucho menos puede ser invocado aceptablemente en oración. En consecuencia,
el mismo apóstol declara (en la misma carta,
1 Corintios 14:15) que él "`orará con el Espíritu,`" dejando una
evidencia clara de que su método no era orar sin Él.

Quinto, La confianza que los santos tienen de que Dios los escuchará,
es si "`pedimos alguna cosa conforme a Su voluntad`" (1
Juan 5:14). Así que si la oración no es según Su voluntad,
no habrá motivo de confianza de que Él escuchará. Porque de hecho,
pedirle a un hombre que ore sin el Espíritu es lo mismo que pedirle ver sin ojos,
trabajar sin manos, o caminar sin pies.
Y esperar que un hombre comience a orar antes de
sentir que el Espíritu lo mueve y lo capacita,
es esperar que un hombre vea antes de abrir los ojos, camine antes de levantarse,
o trabaje antes de mover las manos.

Por último, a partir de esta práctica de orar sin el Espíritu,
y de creer que no es necesario esperar ser movido y capacitado por Él,
han procedido todas las formas de superstición, idolatría,
y abominación entre los llamados Cristianos,
por los cuales el Señor es a menudo provocado y Su Espíritu contristado.
De hecho,
muchos se engañan a sí mismos ahora (como lo hicieron
antes los Judíos) en una paz falsa con Dios,
pensando que todo está bien porque ellos han ofrecido
sus sacrificios de oraciones matutinas y vespertinas.
No obstante,
es manifiesto que el uso constante de tal oración
no influye en sus vidas y conducta ni un poco,
porque permanecen en su mayor parte, tan mal como siempre.
Sí, es frecuente tanto entre Católicos Romanos como en los Protestantes,
que salten (por así decirlo) de sus conversaciones vanas,
ligeras y profanas para entrar en su acostumbrada devoción,
en sus tiempos y momentos señalados.
Luego, cuando esto recién termina, y sus palabras hacia Dios apenas salen de sus bocas,
ellos regresan inmediatamente a su previa manera y profana de hablar.
Por lo tanto,
es evidente que el mismo espíritu malvado de este
mundo está actuando en ellos en ambas actividades.
Ahora,
si existiera algo como vanas ofrendas u oraciones que son una abominación
que Dios no escucha (como ciertamente lo hay,
porque la Escritura así lo testifica, Isaías 66:3; Jeremías 14:12),
ciertamente estas oraciones que son llevadas a cabo
en la voluntad del hombre y en su propia fuerza,
sin el Espíritu de Dios, deben ser de ese número.

Permita que esto sea suficiente como prueba.
Ahora, voy a proceder a responder algunas objeciones de nuestros oponentes.

[.discourse-part]
Objeción: Primero,
ellos objetan que si tales influencias particulares del
Espíritu son necesarias para actos externos de adoración,
entonces deberían ser también necesarias para actos internos, como esperar, desear,
y amar a Dios,
como también para los deberes morales externos como
honrar a los padres o hacer lo correcto al prójimo, etc.

[.discourse-part]
Respuesta: Yo respondo,
que lo que ya se ha dicho suficientemente responde a esta objeción. Porque,
con respecto a los deberes generales del hombre hacia Dios y hacia el prójimo,
el hombre nunca carece de una influencia celestial mientras el día de su visitación dure;
durante ese tiempo Dios está siempre cercano a él y está luchando
con él por medio de Su Espíritu para volverlo a Él. Pero en cuanto
a los actos externos de la predicación y oración,
los cuales son ordenados por Dios para que se lleven
a cabo por Su Espíritu (ver 1 Corintios 12:4-11;
1 Pedro 4:11), y son para el beneficio de la reunión pública,
estos necesitan un mover y una influencia más especial, como ha sido demostrado.

[.discourse-part]
Objeción: Segundo, ellos objetan que, de acuerdo con esta doctrina,
los hombres perversos pueden descuidar por años la oración,
alegando que carecen del mover de Dios para hacerlo.

[.discourse-part]
Respuesta: Yo respondo,
que las falsas pretensiones de los hombres malvados
no hacen nada para invalidar la verdad de esta doctrina.
Pues aunque concedemos que ellos no deberían orar sin el Espíritu, aún así ellos,
en efecto,
deberían venir al lugar de velar donde son capaces de sentir las mociones del Espíritu.
Es cierto que, ellos pecan al no orar,
pero la causa de este pecado es que no están velando para poder orar.

[.discourse-part]
Objeción: Tercero,
ellos objetan que muchas oraciones que inician sin el Espíritu han demostrado ser efectivas,
e incluso que las oraciones de los hombres malvados han sido escuchadas
y aceptadas en ocasiones (como en el caso de Acab).

[.discourse-part]
Respuesta: Esta objeción se resolvió anteriormente;
porque los hechos de la compasión e indulgencia de
Dios en ciertas ocasiones y con ciertas personas,
sobre ocasiones singulares o extraordinarias, no deben ser la regla de nuestras acciones.
Porque si hacemos tales cosas nuestra regla, se producirán grandes dificultades,
como es evidente y será reconocido por todos.
Además,
no negamos que los hombres malvados son algunas veces conscientes de los movimientos
y operaciones del Espíritu de Dios antes de que el día de su visitación haya expirado.
Y a partir de estas influencias del Espíritu, ellos algunas veces oran aceptablemente,
aunque no para permanecer en iniquidad, sino para crecer en piedad.

[.discourse-part]
Objeción: Por último,
algunos objetan que el llamado Padrenuestro es una forma prescrita
de oración o adoración dada por Cristo a Sus discípulos.

[.discourse-part]
Respuesta: Yo respondo, primeramente,
que esta oración fue dada a los discípulos mientras ellos se encontraban aún débiles,
antes de que recibieran la dispensación del Espíritu del nuevo pacto,
y no fue dada como un método o formalidad, ni como el único medio para dirigirse a Dios,
sino para que Cristo pudiera mostrarles a Sus discípulos, por medio de un ejemplo,
cómo sus oraciones deberían diferenciarse de las
oraciones largas y sin vida de los Fariseos.
Segundo,
que la Oración del Señor no fue dada a la iglesia como un método prescrito
se puede apreciar claramente en las oraciones registradas de los apóstoles,
quienes nunca hicieron uso de esta oración, ni la repitieron,
sino que usaron otras palabras según el Espíritu les daba que hablasen.
Tercero, el apóstol dice, "`qué hemos de pedir como conviene, no lo sabemos,
pero el Espíritu mismo intercede por nosotros.`"
Pero si la Oración del Señor hubiera sido dada como
una forma prescrita de oración a la iglesia,
entonces esta Escritura no sería cierta, ni ellos serían ignorantes respecto a qué orar,
ni habrían necesitado la ayuda del Espíritu para que les enseñara.

=== El Canto

En cuanto al canto de los Salmos, no es necesario algún discurso largo,
ya que el caso es el mismo como en los dos primeros,
de predicación y oración. Admitimos que esto es una parte de la adoración de Dios,
y es muy dulce y refrescante cuando procede de un
verdadero sentido del amor de Dios en el corazón,
y surge a partir de la influencia divina de Su Espíritu.
Porque a veces el Espíritu guía a las almas a exhalar una suave melodía,
o palabras adecuadas a su condición actual,
que pueden consistir en palabras que han sido previamente usadas por los santos y registradas
en las Escrituras (como los Salmos de David) u otras palabras que ha sido espontáneamente
dadas por el Espíritu (como los himnos y canciones de Zacarías,
Simeón y la virgen María).

Más en cuanto a la acostumbrada manera formal del canto que abunda en este día,
no tiene ninguna base en la Escritura, ni fundamento en el verdadero cristianismo.
Y además de todos los abusos que usualmente acompañan a la oración y predicación,
esta forma de canto tiene otra ofensa más peculiar--que muchas veces se
cantan grandes y horrendas mentiras en la presencia de Dios.
Porque toda clase de personas malvadas y profanas,
se toman la atribución de cantar las experiencias y condiciones del bendito David,
que son completamente falsas en cuanto a ellos.
De hecho en sus himnos algunas veces cantan,
"`Fueron mis lágrimas mi pan de día y de noche,`" o "`Como un tiesto se secó mi vigor,
y mi lengua se pegó a mi paladar,
y me has puesto en el polvo de la muerte,`" o "`Me he consumido a fuerza de gemir;
todas las noches inundo de llanto mi lecho, riego mi cama con mis lágrimas.`"
Muchas otras cosas similares son las que le cantan hombres y mujeres a Dios,
sabiendo que son falsas en cuanto a ellos.
Ahora, ¿quién puede suponer que Dios acepta tales engaños? Verdaderamente,
tales cantos agradan más a los oídos carnales de
los hombres que a los oídos puros del Señor,
que aborrece toda mentira e hipocresía.

Entonces, el canto que complace a Dios,
debe proceder de aquello que es puro en el corazón (es decir,
desde la Palabra de Vida interior).
Es en y por medio de esta Palabra que habita abundantemente en nosotros,
que las cánticos e himnos espirituales regresan al Señor,
de acuerdo con las palabras del apóstol (Colosenses 3:16).

=== Conclusión

La última gran ventaja de esta verdadera adoración a Dios
que profesamos y practicamos es que no consiste en la sabiduría,
artes, o industria del hombre, ni necesita de la gloria, pompa,
riquezas o esplendor de este mundo para embellecerla.
De hecho,
esta adoración es de una naturaleza espiritual y celestial y por lo tanto parece
muy simple y despreciable para la mente y voluntad natural del hombre,
que no se deleita en ella,
porque no encuentran allí lugar para sus imaginaciones e invenciones,
ni oportunidad para gratificar sus sentidos externos y carnales.
Por esta razón,
es probable que ninguno permanezca en esta adoración por
mucho tiempo sin un sentido acompañante del poder de Dios;
porque sin el poder, está desnuda y vacía,
sin tener nada en sí misma para invitar y tentar a los hombres a estimarla.

Sin embargo, la adoración de nuestros adversarios,
al ser realizada en sus propias voluntades, es autocomplaciente,
siendo una actividad en la cual ellos pueden ejercitarse
ampliamente en sus destrezas e invenciones naturales.
Y debido a que tiene algo de esplendor externo y mundano
(tentador para los sentidos carnales y mundanos),
ellos pueden continuar placenteramente en esto y
satisfacerse incluso sin el Espíritu y Poder,
los cuales admiten que no son esenciales para ser llevada a cabo,
y por ende ni los esperan ni ponen sus expectativas en ellos.

Entonces para concluir: la adoración, la predicación,
la oración y el canto por los cuales abogamos,
son tales como proceden del Espíritu de Dios y siempre están acompañados de Su influencia.
Comienzan por el movimiento del Espíritu,
son llevados a cabo únicamente por su poder y fuerza
y entonces son una adoración puramente espiritual,
como la Escritura declara (Juan 4:23-24; 1 Corintios 14:15; Efesios 6:18, etc.).

Pero la adoración, la predicación,
la oración y el canto que nuestros adversarios abogan, y lo cual nos oponemos,
es una adoración que comienza,
continúa y concluye en la propia voluntad y fuerza naturales del hombre,
sin el movimiento o influencia del Espíritu de Dios,
lo cual ellos juzgan que no es necesario esperar, y por lo tanto puede llevarse a cabo,
tanto en la materia como en la manera, por el más perverso de los hombres.
Esto es como el culto y las ofrendas vanas que Dios siempre rechazó,
como se muestra en Isaías 66:3; Jeremías 14:12, etc.; Proverbios 15:29; Juan 9:31.
