== Un Breve Comentario con Respecto a las Reuniones en Silencio

[.chapter-subtitle--blurb]
Por Isaac Penington

Este es un gran misterio, escondido del ojo del hombre,
quien ha huido de la vida interior hacia las observaciones externas.
Él no puede ver que esto es requerido por el Señor de Su pueblo,
ni reconocer edificación alguna en ello, ni beneficio alguno por este medio.
Pero para la mente que es atraída al interior, el asunto está claro,
y en ello son dulcemente sentidas la verdadera edificación
en la vida de Dios y la comunión unos con otros.
Porque en estas reuniones,
aquellos que esperan atentamente en Él según la guía y requerimientos de Su Santo Espíritu,
reciben un precioso refrigerio procedente de la presencia del Señor. Ahora,
si al Señor le place, abriré un poco más este asunto para los de corazón recto.

Después de que la mente se vuelve al Señor en alguna medida,
y se sienten Sus vivificaciones,
y Su semilla comienza a levantarse y a brotar en el corazón,
entonces la carne debe guardar silencio delante de Él,
y el alma debe esperar en Él (para Sus siguientes
apariciones) en esa medida de vida que ha sido revelada.
Ahora bien, esto es muy grande: experimentar la carne silenciada,
sentir los pensamientos y razonamientos de la mente carnal acallados,
y esperar la sabiduría, luz y guía del Espíritu de Dios.
Porque el hombre debe llegar a la pobreza de sí mismo, a la verdadera humildad,
a la nadedad,
y al silencio de su espíritu delante el Señor. Debe despojarse de todo su conocimiento,
sabiduría, entendimiento y habilidades; de todo lo que es, ha hecho o pueda hacer,
para ser vestido y llenado de la naturaleza, el Espíritu y el poder del Señor.

Entonces, en esta medida de vida que es de Cristo,
en la cual está Cristo y se manifiesta al alma, está el poder de la vida y de la muerte.
Está el poder para matar la carne y el poder para vivificar para Dios.
Está el poder para hacer que el alma cese de sus propias obras,
y el poder para obrar en y para el alma lo que Dios
requiere y es aceptable delante de Sus ojos.
En esta medida de vida se debe esperar a Dios y adorarle continuamente,
tanto en privado como en público, según Su Espíritu guíe y enseñe.

Porque el Señor requiere de Su pueblo no sólo que lo adore privadamente,
sino también que se reúnan a adorarle,
en los tiempos y conforme los movimientos de Su Espíritu.
Y aquellos que son enseñados por Él no se atreven a dejar de congregarse,
como muchos tienen por costumbre,
sino que velan contra tales tentaciones y trampas del enemigo.

Y esta es la manera de su adoración: Deben esperar en el Señor,
reunirse en el silencio de la carne,
y estar atentos a los movimientos de Su vida y a las apariciones de Su poder entre ellos.
Y en las manifestaciones de ese poder pueden orar, hablar, exhortar, reprender, cantar,
gemir, etc., según el Espíritu les enseñe, requiera y les dé hablar.
Pero si el Espíritu no requiere que se hable, ni da ninguna palabra,
entonces todos deben sentarse quietos en su lugar (en su lugar celestial, quiero decir),
cada uno sintiendo su propia medida, alimentándose de ella,
y recibiendo de ella en su espíritu lo que el Señor le dé.

En esto hay edificación, edificación pura, edificación preciosa.
El alma que espera de esta manera es edificada individualmente
por el Espíritu del Señor en cada reunión;
y además,
la vida del cuerpo se puede sentir en cada vasija
que está vuelta internamente hacia su medida.
Porque la calidez de la vida en cada vasija no sólo calienta a la individual,
sino que son como un montón de carbones frescos y vivos que se calientan unos a otros,
y una gran fuerza, frescura y vigor de vida fluye en todos.
Y si alguno está agobiado; es tentado, abofeteado por Satanás; está doblegado,
sobrecargado, desfalleciente, afligido, angustiado, etc.,
el estado del tal es sentido en el Espíritu y clamores secretos ascienden al Señor por
él. Muchas veces este encuentra tranquilidad y alivio en unas pocas palabras habladas,
o incluso cuando no hay palabras.

Ahora bien, en cuanto a reuniones completamente en silencio,
en las que se ha resuelto no hablar, estas son desconocidas para nosotros.
Por el contrario, esperamos en el Señor, ya sea para sentirlo en palabras,
o en silencio de espíritu, sin palabras, como a Él le plazca.
En lo que se refiere a nuestras reuniones, lo que procuramos,
y a lo que somos instruidos por el Espíritu,
es que la carne de cada uno sea mantenida en silencio,
y que no haya edificación sino en el Espíritu y poder del Señor.

Existen varios estados de personas.
Algunas sienten poco de la presencia del Señor,
y más bien sienten tentaciones y pensamientos,
con muchos vagabundeos y desvíos de la mente.
Estas todavía no están familiarizadas con el poder, o al menos, no conocen su dominio,
sino que aún sienten el dominio del mal sobre el bien en ellas.
Este es un estado penoso y de mucho dolor,
y nuestras reuniones para tales personas (muchas veces)
pueden parecer más para lo peor que para lo mejor.
Sin embargo, incluso estas personas,
mientras se vuelven tan lejos como pueden de estas cosas,
y se aferran (o al menos con sinceridad de corazón
desean aferrarse) a lo que testifica contra la carne,
tienen aceptación del Señor en ello.
Y al continuar esperando en esta tribulación y angustia
(no dejando de asistir a las reuniones,
en temor y sujeción al Señor que requiere esto,
aunque con un beneficio aparentemente pequeño),
cosechan un beneficio escondido en el presente,
y cosecharán un beneficio más claro y manifiesto después,
conforme el Señor va consumiendo y desgastando en
ellas la parte donde las tinieblas tienen su fuerza.

Dios debe ser adorado en Espíritu, en Su propio poder y vida,
y esto está a Su propia disposición. Su iglesia es una reunión en el Espíritu.
Si algún hombre habla allí, debe hablar como oráculo de Dios (1 Pedro 4:11),
como la vasija a partir de la cual Dios habla,
como la trompeta a partir de la cual Él da sonido.
Por lo tanto, se debe esperar en silencio hasta que el Espíritu del Señor mueva a hablar,
y también dé las palabras para hablar.
Porque un hombre no debe hablar sus propias palabras, o en su propia sabiduría o tiempo,
sino las palabras del Espíritu, en la sabiduría y tiempo del Espíritu,
que es cuando Él mueve y da para hablar.
Y puesto que el Espíritu alimenta internamente incluso
cuando no mueve a hablar con palabras,
este sentido y alimento internos deben ser esperados y recibidos cuando no hay palabras.
Sí,
el ministerio del Espíritu y vida está más cerca y es más directo cuando es sin palabras,
que cuando es con palabras,
como ha sido a menudo sentido y fielmente testificado por muchos testigos.
El ojo no ha visto, ni el oído ha oído,
ni ha entrado en el corazón del hombre cómo y qué
cosas revela Dios a Sus hijos por el Espíritu,
cuando ellos esperan en Él en Su temor puro, y adoran y conversan con Él en Espíritu.
Porque entonces la fuente del gran abismo es abierta y los manantiales
eternos ciertamente entregan el agua viva y pura.^
footnote:[De [.book-title]#Los Escritos de Isaac Penington#]
