== Un Breve Comentario con Respecto a las Reuniones en Silencio

Por Isaac Penington

Esto es un gran misterio,
que está escondido del ojo del hombre que ha huido
de la vida interior hacia las observaciones externas.
Él no puede ver que esto es requerido por el Señor de Su pueblo,
no reconoce ninguna edificación en esto, ni beneficio alguno por este medio.
Pero para la mente que es atraída al interior, el asunto está claro,
y en ello la verdadera edificación en la vida de Dios y
la comunión unos con otros son dulcemente sentidas.
Porque en estas reuniones es recibido un precioso refrigerio procedente
de la presencia del Señor por aquellos que atentamente esperan en Él,
según la guía y requerimientos de Su Santo Espíritu.
Ahora, si al Señor le place, abriré esto un poco más para el de corazón recto.

Después de que la mente se vuelva al Señor en alguna medida,
se sientan Sus vivificaciones y Su semilla empiece a levantarse y a brotar en el corazón,
la carne debe ser silenciada delante de Él,
y el alma debe esperar en Él (por Sus siguientes
apariciones) en esa medida de vida que ha sido revelada.
Ahora bien, es algo muy grande experimentar la carne silenciada,
sentir los razonamientos y los discursos de la mente carnal aquietados,
y la expectativa puesta en la sabiduría, luz y guía del Espíritu de Dios.
Porque el hombre tiene que experimentar su propia pobreza, su nadedad,
la verdadera humildad y el silencio de su espíritu ante
el Señor. Debe despojarse de todo su conocimiento,
sabiduría, entendimiento, habilidades, de todo lo que es, ha hecho o pueda hacer,
para ser vestido y llenado de la naturaleza, Espíritu y poder del Señor.

Entonces, en esta medida de vida que es de Cristo,
en la cual está Cristo y aparece al alma, está el poder de la vida y de la muerte.
Está el poder para matar la carne y el poder para vivificar para Dios.
Está el poder para hacer que el alma cese de sus propias operaciones,
y el poder para obrar en y para el alma lo que Dios requiera y sea aceptable a Su vista.
En esta medida de vida debe ser esperado y adorado continuamente Dios,
tanto en privado como en público, según Su Espíritu guíe y enseñe.

Porque el Señor requiere de Su pueblo, no sólo que lo alaben privadamente,
sino también que se reúnan a adorarlo en los tiempos
y de acuerdo a los movimientos de Su Espíritu.
Y aquellos que son enseñados por Él no se atreven a dejar de congregarse,
como muchos tienen por costumbre,
sino que vigilan contra tales tentaciones y trampas del enemigo.

Y esta es la manera en que deben adorar: Deben esperar en el Señor,
reunirse en el silencio de la carne,
y estar atentos a los movimientos de Su vida y a las apariciones de Su poder entre ellos.
Y en los levantamientos de dicho poder pueden orar, hablar, exhortar, reprender, cantar,
llorar, etc., según el Espíritu les enseñe y requiera,
y les dé que hablen.. Pero si el Espíritu no requiere que se hable,
ni da nada para que sea declarado,
entonces todos deben sentarse quietos en su lugar (en su lugar celestial,
es lo que quiero decir), sintiendo cada uno su propia medida, alimentándose de ella,
y recibiendo de ella en su espíritu lo que el Señor le dé.

En esto hay edificación, edificación pura, edificación preciosa.
El alma que espera en esta forma es, por este medio,
particularmente edificada por el Espíritu del Señor en cada reunión,
y también se siente la vida de todos en cada vasija
que está vuelta internamente hacia su medida.
Porque la calidez de la vida en cada vasija no sólo calienta la individual, no;
ellas son como un montón de carbones frescos y vivos que se calientan unos a otros,
y una gran fuerza, frescura y vigor de vida fluye en todos.
Y si alguno es agobiado, tentado, abofeteado por Satanás, y está doblegado, sobrecargado,
decayendo, afligido, angustiado, etc.,
el estado de este es sentido en el Espíritu y clamores secretos ascienden al Señor por
él. Muchas veces este encuentra tranquilidad y alivio en unas pocas palabras habladas,
o incluso, cuando no hay palabras.

Ahora, en cuanto a reuniones completamente en silencio,
en las que hay una resolución a no hablar, estas son desconocidas para nosotros.
Al contrario, nosotros esperamos en el Señor, ya sea para sentirlo en palabras,
o en silencio de espíritu sin palabras, como a Él le plazca.
En lo que se refiere a nuestras reuniones,
lo que queremos y lo que el Espíritu nos ha enseñado a buscar,
es que la carne de cada uno sea mantenida en silencio,
y a que no haya edificación excepto en el Espíritu y poder del Señor.

Hay varios estados de personas.
Algunas sienten poco de la presencia del Señor,
y más bien sienten tentaciones y pensamientos,
con muchos vagabundeos y desvaríos de mente.
Estas todavía no están familiarizadas con el poder, o al menos, no conocen su dominio,
sino que aún sienten dominio del mal sobre el bien en ellas.
Este es un estado penoso y de mucho dolor,
y nuestras reuniones para tales personas (muchas veces)
pueden parecer más para lo peor que para lo mejor.
Sin embargo, incluso estas personas, mientras se vuelven,
tan lejos como puedan de estas cosas,
y se adhieren (o al menos con sinceridad de corazón
desean adherirse) a lo que testifica contra la carne,
tienen aceptación del Señor en esto.
Y al continuar esperando en esta dificultad y angustia
(no dejando de asistir a las reuniones,
en temor y sujeción al Señor que requiere esto,
aunque con un beneficio aparentemente pequeño),
obtienen un beneficio escondido en el momento presente,
y cosecharán un beneficio más claro y manifiesto después,
conforme el Señor consuma y desgaste en ellas la
parte en donde las tinieblas tienen su fuerza.

Dios debe ser adorado en Espíritu, en Su propio poder y vida,
y esto está a Su propia disposición. Su iglesia es una reunión en el Espíritu.
Si algún hombre habla ahí, debe hablar como oráculo de Dios (1 Pedro 4:11),
como la vasija a partir de la cual Dios habla,
como la trompeta a partir de la cual Él da sonido.
Por lo tanto, debe esperarse en silencio hasta que el Espíritu del Señor mueva a hablar,
y dé también las palabras para hablar.
Porque un hombre no debe hablar sus propias palabras, o en su propia sabiduría o tiempo,
sino las palabras del Espíritu, en la sabiduría y tiempo del Espíritu,
que es cuando Él mueve y da para hablar.
Y puesto que el Espíritu alimenta internamente incluso
cuando no mueve a hablar con palabras,
por lo tanto,
este sentido y alimento internos deben ser esperados y recibidos cuando no hay palabras.
Sí, el ministerio del Espíritu y vida está más cerca e inmediato cuando es sin palabras,
que cuando es con palabras,
como ha sido a menudo sentido y fielmente testificado por muchos testigos.
El ojo no ha visto, ni el oído ha oído,
ni ha entrado en el corazón del hombre cómo y qué
cosas revela Dios a Sus hijos por el Espíritu,
cuando ellos esperan en Él en Su temor puro, y adoran y conversan con Él en Espíritu.
Porque entonces la fuente del gran abismo es abierta y los manantiales
eternos ciertamente entregan el agua viva y pura.^
footnote:[De Los Escritos de Isaac Penington, Volumen 4, pg. 47.]
