== Prefacio

Robert Barclay (1648-1690) fue un cuáquero escocés,
y uno de los escritores más eminentes de la primitiva Sociedad de los Amigos.
Su Apología de la Verdadera Teología Cristiana, fue publicada por primera vez en 1675,
y llegó a ser considerada la mejor exposición y defensa de los
principios de los cuáqueros durante los siguientes 200 años.

Barclay nació rodeado de abundancia,
y fue educado en algunas de las mejores escuelas de la época,
en las que su ingenio natural ganó la admiración de maestros y compañeros.
Además del inglés, pronto dominó los idiomas griego, hebreo, francés y latín,
y se destacó tanto en sus estudios,
que su tío (el Rector de la Universidad Escocés en París) le ofreció hacerlo su heredero.
Pero a los diecisiete años de edad, al entrar a una reunión del pueblo llamado cuáqueros,
Robert Barclay dijo:
"`Sentí un poder secreto entre ellos que tocó mi corazón.`" Y al continuar con ellos,
llegó "`a recibir y a dar testimonio de la Verdad,`" no siendo convencido, según dijo,
"`por la fuerza de los argumentos, o por una discusión en particular de cada doctrina,
sino porque fui alcanzado secretamente por la Vida.
Y a medida que le abría paso,
sentía que el mal se debilitaba en mí y que el bien se levantaba,
y así llegué a estar ligado y unido a este pueblo,
deseando que el poder y la vida de Cristo se incrementaran cada vez más,
por medio de lo cual podría sentirme perfectamente redimido.`"

La Apología de la Verdadera Teología Cristiana (de la cual
se extrajo este libro) fue escrita por primera vez en latín,
cuando Barclay tenía sólo veintisiete años de edad,
y después él mismo la tradujo al inglés. En el prefacio
de la edición original encontramos los siguientes comentarios:

"`Es posible que mi método de escribir no sólo parezca diferente,
sino incluso contrario al que es comúnmente usado por los hombres que se llaman teólogos;
pero esto no me preocupa.
Pues no sólo confieso que no soy un imitador ni un admirador de los académicos,
sino también, que soy un opositor y menospreciador de aquellos,
por cuya labor la religión cristiana está tan lejos de ser mejor,
que más bien es destruida.
Tampoco he tratado de acomodar mi obra para los que tienen comezón de oír,
quienes desean comprender en su cabeza las sublimes doctrinas de la Verdad,
en lugar de abrazarlas en su corazón. Porque lo que
he escrito procede más de mi corazón que de mi cabeza;
surge de lo que he escuchado con los oídos de mi alma, visto con los ojos de mi corazón,
y de lo que mis manos han tocado de la Palabra de Vida.
Yo declaro lo que se me ha revelado internamente acerca de las cosas de Dios,
ocupándome poco en la elocuencia y excelencia de mis palabras,
y más en la demostración de la eficacia y operación de la Verdad.
Y si erro algunas veces en lo primero, no es gran cosa,
porque aquí no hago el papel del gramático o del orador, sino del cristiano;
por lo tanto,
en esto he seguido la regla segura de la Luz Divina y de las Sagradas Escrituras.
De hecho, lo que he escrito, no está escrito para alimentar la sabiduría,
el conocimiento y el orgullo vano de este mundo, sino todo lo contrario,
para matar de hambre y contradecir estas cosas.`"

"`A ustedes les ofrezco las siguientes proposiciones,
y si las leen y consideran en el temor del Señor,
podrán percibir esa verdad simple y evidente,
que el hombre ha hecho tan oscura y misteriosa por medio de su sabiduría. Por desgracia,
el hombre ha agobiado al mundo con grandes y voluminosos tratados y comentarios,
y ha hecho la verdad cien veces más oscura y complicada de lo que es en sí misma.
Todo el aprendizaje escolar del hombre, que toma casi toda la vida aprender,
no lo acerca más a Dios, ni hace que sea menos impío o más justo de lo que era.
Por lo tanto, Dios ha desechado al sabio,
al entendido y a los disputadores de este mundo,
y ha escogido a unos pocos instrumentos despreciables y
sin estudio (como lo hizo con los pescadores de la antigüedad),
para publicar su Verdad pura y desnuda,
y para liberarla de las brumas y neblinas con las que el clero la ha oscurecido.
Y entre muchos otros que Dios ha escogido para dar
a conocer estas cosas--viendo que también he recibido,
en medida, gracia para ser un administrador del mismo evangelio--me pareció bien,
de acuerdo con mi deber, ofrecerles las siguientes proposiciones.
Aunque son cortas, son muy importantes,
pues abarcan mucho y declaran cuál es el verdadero fundamento del conocimiento; sí,
de ese conocimiento que conduce a la Vida Eterna.
De esta Vida doy testimonio,
y deseo que dicho testimonio sea considerado en la Luz de Cristo en todas sus consciencias.
Me despido`".

Robert Barclay

Ury, Escocia, 25 del mes 9, 1675

Las siguientes páginas contienen cinco de las quince
proposiciones originales de la Apología de Barclay,
que tratan de la caída, redención, justificación y perfección del hombre.
En la traducción de este libro al español,
se tuvo mucho cuidado para preservar el significado e intención originales de sus palabras.
Todas las citas de las Escrituras en inglés fueron
tomadas de la versión King James (KJV) 1611;
por lo tanto, han sido usadas diferentes versiones de las Escrituras en español,
con el fin de comunicar la misma idea y conservar la fuerza de sus argumentos.
Cuando no se especifica la versión al pie de página,
quiere decir que ha sido usada la Reina Valera 1960. Sin embargo,
algunas veces se escogió la Reina Valera de Gómez (RVG),
Reina Valera 1602 Purificada (RV1602P),
La Biblia de Las Américas (LBLA) y otras traducciones,
porque concuerdan con más exactitud con la KJV o con los manuscritos originales.

Jason Henderson

Noviembre, 2019
