== Capítulo II. La Oferta Universal de Redención

Habiendo considerado el estado caído, perdido, corrupto y degenerado del hombre,
ahora debemos inquirir cómo y por qué medio,
puede ser liberado de esta condición miserable y depravada.

=== Condenación Predestinada--Una Doctrina de Demonios

Debemos empezar atacando la doctrina de _la elección y condenación predestinadas,_
por causa de la cual, muchos no temen afirmar que Dios,
por un decreto eterno e inmutable,
ha predestinado a la condenación eterna a la mayor parte de la humanidad,
sin tener en cuenta su desobediencia o pecado,
sino únicamente la demostración de la gloria de Su justicia.
Ellos dicen que estas almas miserables están destinadas
a caminar en sus propios caminos perversos,
hasta que la justicia de Dios finalmente los alcance.
Dicen,
que Él no sólo ha retenido la predicación del evangelio
y el conocimiento de Cristo en muchas partes del mundo,
sino que incluso,
en aquellos lugares donde se predica el evangelio
y se ofrece la salvación por medio de Cristo,
Dios condena justamente por desobediencia a grandes multitudes,
a quienes les ha negado la gracia por la cual podrían haber sido salvas.
Se dice que esto se debe a que Él,
por una voluntad secreta y desconocida para todos los hombres,
ha predeterminado y decretado (sin tener en cuenta
la desobediencia o el pecado) que muchos no obedezcan,
y que la oferta del evangelio no resulte efectiva para su salvación,
sino que sólo sirva para ocasionar su mayor condenación.

Ahora bien, con respecto a esta horrible y blasfema doctrina,
nuestro punto de vista es el mismo que el de muchos otros,
quienes la han refutado de manera sabia y entendida, de acuerdo con la Escritura,
la razón y la antigüedad.
Y viendo que ya se ha escrito tanto contra esta doctrina, que se puede añadir muy poco,
seré breve al respecto; pero como se interpone en mi camino,
no la puedo dejar pasar por completo.

En primer lugar, podemos afirmar con seguridad que esta doctrina es una novedad,
ya que durante los primeros cuatrocientos años después de Cristo,
no se hace ninguna mención de ella.
Porque dado que es contraria tanto al testimonio de la Escritura como al tenor del evangelio,
todos los antiguos escritores,
maestros y padres de la iglesia la pasaron por alto con profundo silencio.
Sus primeros cimientos fueron establecidos en los últimos escritos de Agustín,
quien en su contienda contra Pelagio, dejó caer algunas expresiones que algunos,
desafortunadamente, tomaron para establecer este error.
Posteriormente,
esta doctrina fue promovida por un fraile llamado Dominicus y por los monjes de su orden;
y por último,
lamentablemente fue adoptada por Juan Calvino (un hombre admirable en algunos otros
aspectos) para la gran mancha de su reputación y la difamación del Cristianismo Protestante.
Y aunque fue confirmada por los decretos del Sínodo de Dort,
desde entonces ha perdido terreno,
y está siendo desacreditada por la mayoría de los hombres
de conocimiento y piedad en todas las iglesias protestantes.
Sin embargo, no contendemos contra ella por el silencio de los antiguos,
la escasez de los que la afirman, o la erudición de sus opositores,
sino porque creemos que no tiene fundamento real en los escritos o palabras de Cristo,
ni de los apóstoles, y la encontramos sumamente ofensiva para con Dios,
para con Jesucristo nuestro Mediador y Redentor, para con el poder, virtud,
nobleza y excelencia de Su bendito evangelio, y por último, para con toda la humanidad.

Primero que todo, es sumamente ofensiva para con Dios,
porque lo convierte en el autor del pecado, que de todas las cosas,
es la más contraria a Su naturaleza.
Sé que los que afirman este principio niegan esta consecuencia;
pero su negación es pura ilusión,
puesto que esto se deduce muy naturalmente de su doctrina.
Porque si Dios ha decretado que ciertas personas predestinadas a la condenación perezcan,
sin que esto tenga nada que ver con sus malas obras,
sino únicamente con Su propio beneplácito; y además,
si esto lo decretó Él mucho antes de que tuvieran existencia
o alguna capacidad de hacer el bien o el mal,
de modo que no pueden evitar andar en sus caminos de iniquidad,
por los cuales son llevados a la condenación; entonces, ¿quién es, les pregunto yo,
el primer autor y causa de esto sino Dios,
que así lo quiso y lo decretó? Esta es la conclusión más natural, y de hecho,
la única que puede existir.
Y a pesar de que muchos de los predicadores de esta doctrina han buscado diversas,
extrañas,
torcidas y engañosas distinciones para defender su opinión y evitar esta horrible conclusión,
algunos de los más eminentes entre ellos han sido tan francos en el asunto,
que la han puesto más allá de toda duda.
Daré algunos ejemplos de estos predicadores, entre muchos:

[quote]
____
Las siguientes son expresiones de Juan Calvino: "`Por orden y voluntad de Dios,
Adán cayó. Dios quiso que el hombre cayera.`"^
footnote:[Calvino en el capítulo 3 de Génesis.]
"`El hombre está cegado por la voluntad y el mandamiento de Dios.`"^
footnote:[Id.1 Inst. cap.18. s.1.]
"`Atribuimos la causa de nuestro endurecimiento a Dios.`"^
footnote:[Id. dib. de praed.]
"`La causa más alta o fundamental del endurecimiento es la voluntad de Dios.`"^
footnote:[Idem. lib. de provid.]
"`Se concluye que el consejo secreto de Dios es la causa del endurecimiento.`"^
footnote:[Id. 3 Inst. cap.23. s.1.]

Theodor Beza escribe: "`Dios no sólo ha predestinado a la condenación,
sino también las causas de ella, a quien Él vio apropiado.`"^
footnote:[Beza, lib. de praed.]
"`El decreto de Dios no puede ser excluido de las causas de la corrupción.`"^
footnote:[Id. de praed. ad art. 1.]

"`Es cierto,`" dice Jerome Zanchi,
"`que Dios es la primera causa de la dureza del corazón.`"^
footnote:[Zanchi, de excaecat. q. 5.]
"`Los predestinados a la condenación están tan firmemente
sujetos bajo el decreto del Dios todopoderoso,
que no pueden evitar pecar y perecer.`"^
footnote:[Idem, lib. 5 de nat. Dei cap. 2. de praed.]

"`Es la opinión,`" dice David Pareus, "`de nuestros eruditos,
que Dios decretó inevitablemente la tentación y la caída del hombre.
De hecho, la criatura peca necesariamente, por el más justo juicio de Dios.
Nuestros hombres afirman con toda razón,
que la caída del hombre fue necesaria e inevitable debido al decreto de Dios.`"^
footnote:[Pareus, lib. 3. de amiss. gratiae. C. 2. Ibid., c. 1.]

"`Dios,`" dice Ulrich Zwingli, "`mueve al ladrón a matar.
Él mata, Dios lo fuerza a ello.
Pero ustedes dirán que es forzado a pecar; confieso que en verdad es forzado.`"^
footnote:[Zwingli, lib. de prov. c. 5.]

"`Las personas predestinadas a la condenación,`" dice Piscator,
"`están ordenadas de manera absoluta a este doble fin:
a experimentar el castigo eterno y a pecar necesariamente; y por lo tanto pecan,
para que puedan ser justamente castigadas.`"^
footnote:[Resp. ad Vorst. part 1, p. 120.]
____

Tales dichos hacen a Dios clara y evidentemente el autor del pecado.
Algunos han tratado de evadir esta inevitable consecuencia,
afirmando que los hombres pecan _voluntariamente;_ pero esto no los ayuda en lo absoluto,
ya que la voluntad y la propensión del hombre al mal, según su propio juicio,
son necesariamente impuestas sobre él por la voluntad y el decreto de Dios.
Este artificio es como si yo tomara a un niño que es incapaz
de resistirme y lo arrojara desde un gran precipicio.
En efecto, el peso del cuerpo del niño lo hace descender con rapidez,
y la violencia de la caída lo mata de inmediato.
Ahora pregunto, aunque el niño desciende voluntariamente debido al peso de su cuerpo,
y no por un golpe directo de mi mano (quizás yo esté a gran distancia
cuando muera) ¿soy yo o el niño la causa verdadera de su muerte?
Por tanto, que cualquier hombre de razón juzgue,
si las citas anteriores no sólo hacen a Dios el autor directo del pecado,
sino también más injusto que el más injusto de los hombres.

Segundo, esta doctrina es sumamente ofensiva para con Dios,
porque sugiere que se complace en la muerte de los pecadores, sí;
y que desea que muchos mueran en sus pecados, contrario a muchas escrituras, tales como:
"`Vivo yo, dice Jehová el Señor, que no me complazco en la muerte del malvado,
sino en que se vuelva el malvado de su camino y viva.
¡Volveos, volveos de vuestros malos caminos! ¿Por qué habéis de morir,
oh casa de Israel?`"^
footnote:[Ezequiel 33:11 RV2009]
Y: "`Porque esto es bueno y agradable delante de Dios nuestro Salvador,
el cual quiere que todos los hombres sean salvos y vengan al conocimiento de la verdad.`"^
footnote:[1 Timoteo 2:3-4]
Y: "`El Señor no retarda su promesa, según algunos la tienen por tardanza,
sino que es paciente para con nosotros, no queriendo que ninguno perezca,
sino que todos procedan al arrepentimiento.`"^
footnote:[2 Pedro 3:9]
Pero si Dios ha creado a los hombres para mostrar Su justicia y poder en ellos,
como estos hombres afirman,
y si para efectuar esto no sólo les ha negado los medios para hacer el bien,
sino que también ha predestinado el mal para que caigan en él,
en verdad debe complacerse en su muerte y desear que mueran,
puesto que no hacen nada en contra de Su propia voluntad.

Tercero, es sumamente ofensiva para con Cristo nuestro Mediador,
y para con la eficacia y excelencia de Su evangelio,
porque hace que Su mediación sea ineficaz; es decir,
como si no hubiera derribado por completo la pared intermedia con Sus sufrimientos,
ni quitado la ira de Dios, ni comprado Su amor para toda la humanidad; como si, de hecho,
hubiera sido predeterminado que Su muerte no sería de ningún
servicio para la mayor parte de la humanidad.

Cuarto, hace que la predicación del evangelio sea una mera burla e ilusión,
si por un decreto irrevocable,
muchos de aquellos a quienes se les predica están excluidos de su beneficio.
Hace que la predicación de la fe y del arrepentimiento,
junto con todas las promesas y advertencias del evangelio no tengan ninguna utilidad.
Porque, ¿de que servirían,
si todo depende de un previo decreto por el cual un hombre elegido no puede evitar
ser salvo en el tiempo señalado (aunque sea en la última hora de su vida),
y otro no puede evitar ser condenado, aunque busque y espere en el Señor con diligencia?

Quinto, es sumamente ofensiva para con la venida de Cristo y Su sacrificio propiciatorio,
sobre lo cual, las Escrituras afirman que fueron fruto del amor de Dios al mundo,
y que fueron ejecutados por los pecados y para la salvación de todos los hombres.
Porque si fue predeterminado que la venida de Cristo salvara a muy pocos,
y que además sirviera para endurecer y aumentar la condenación de la mayor parte de
los hombres que no creen en ella (ya que no pueden creer por causa de la predestinación),
entonces la cruz más bien serviría como un testimonio de la ira de Dios hacia el mundo,
y como un acto de indignación hacia la mayor parte de la humanidad.

Sexto, esta doctrina es sumamente ofensiva para con la humanidad,
ya que deja a los hombres en una condición mucho peor que la de los demonios en el infierno.
Porque los demonios alguna vez estuvieron en su estado correcto,
y tenían la capacidad de permanecer así; por lo tanto,
estos sufren por su propia rebelión y culpa.
Pero según esta doctrina,
muchos millones de hombres son atormentados para siempre por el pecado de Adán,
del cual no saben nada, y del que no son responsables.
De hecho, esta doctrina los hace peores que las bestias del campo,
a las que sus amos no exigen más de lo que pueden hacer.
Y cuando una bestia es sacrificada, la muerte es el final de su dolor;
pero los elegidos para condenación son atormentados para
siempre por no hacer lo que nunca fueron capaces de hacer.
Sí,
esto pone al hombre en una condición mucho peor que
la condición en que Faraón puso a los israelitas;
porque a pesar de que les negaba la paja,
con mucho trabajo y dolor existía la posibilidad de obtenerla.
¡Pero esta doctrina hace que Dios retenga todos los medios de salvación, de modo tal,
que no hay forma de que el hombre la pueda alcanzar!

=== La Muerte de Cristo Por Todos los Hombres

Después de haber removido de manera breve esta falsa
doctrina que se interponía en mi camino,
he llegado al tema de nuestra proposición, el cual es: "`Que Dios,
que no se complace en la muerte del pecador, sino en que todos vivan y sean salvos,
por Su infinito amor ha enviado a Su Hijo unigénito al mundo,
para que todo aquel que en Él crea, sea salvo.`"
La verdad de esta declaración,
siendo prácticamente las palabras expresas de la Escritura, no requerirá mucha prueba.
Y debido a que tenemos en común esta afirmación con muchos otros,
que han abogado de manera ferviente y sana, según la Escritura,
a favor de la oferta universal de redención de Dios,^
footnote:[Nota del editor:
Ha habido muchos malentendidos y conclusiones erróneas derivadas
del uso que hacen los Cuáqueros del término "`universal,`" en relación
con la redención. Esta palabra era utilizada por los Amigos,
para establecer un deliberado contraste contra la idea predominante,
de que Dios ofrece el conocimiento salvador de Cristo _sólo a unos pocos predestinados._
Los Cuáqueros rechazaban la idea de la predestinación
individual y de una "`expiación limitada`",
insistiendo en que Cristo había muerto por todos los hombres,
y en que una oferta de redención se extendía a todos los hijos de Adán.
Es esta invitación interior y misericordiosa la que es universal.
Cuando se recibe, se sigue y se obedece,
la luz de Cristo se convierte en la vida y salvación del alma.
Cuando se rechaza, la misma luz se convierte en la condenación eterna del hombre.
Ver Juan 3:19-21. Los primeros Cuáqueros no eran en absoluto partidarios del universalismo,
o la reconciliación universal.]
seré breve hasta llegar a esas afirmaciones que son más particularmente nuestras.

La verdad de que Cristo murió por todos los hombres es por
sí misma tan evidente según el testimonio de la Escritura,
que difícilmente se encuentre algún otro artículo
de la fe cristiana que sea afirmado tan frecuente,
clara y positivamente.
Esto es lo que hace que la predicación de Cristo sea verdaderamente llamada el evangelio,
o el anuncio de buenas nuevas para todos.
Por lo tanto, el ángel declaró el nacimiento y la venida de Cristo a los pastores,
diciendo: "`He aquí os doy nuevas de gran gozo, que será para __todo el pueblo;__`"^
footnote:[Lucas 2:10]
noten que no les dice "`para unas cuantas personas.`"
Ahora bien,
si esta venida de Cristo no hubiera traído una posibilidad de salvación para todos,
este anuncio habría sido considerado nuevas de gran
tristeza para la mayoría de las personas;
ni el ángel habría tenido razón para cantar: "`en la tierra paz,
buena voluntad para con los hombres`"^
footnote:[Lucas 2:14],
si la mayor parte de la humanidad hubiera sido inevitablemente
excluida de recibir algún beneficio de ella.
¿Y para qué enviaría Cristo a Sus discípulos a "`predicar el evangelio a toda criatura?`"^
footnote:[Marcos 16:15]
En verdad, les mandó a predicar el arrepentimiento,
la remisión de pecados y la salvación a cada hijo e hija de la humanidad,
advirtiendo y amonestando _a todo hombre,_ como Pablo hizo en Colosenses 1:28.

Ahora bien,
¿cómo habrían podido predicar estos ministros de Cristo el evangelio a todo hombre,
"`en plena certidumbre,`"^
footnote:[1 Tesalonicenses 1:5]
si la salvación no era posible para todos a través del evangelio?
¿Qué si alguien les hubiera preguntado:
"`Ha muerto Cristo por mí`"? Los que niegan la muerte
universal de Cristo no pueden responder nada a esto,
y sólo dan vueltas en círculo.
Pero está escrito: "`¡Cuán hermosos son los pies de los que anuncian la paz,
de los que anuncian buenas nuevas!,`"^
footnote:[Romanos 10:15; Isaías 52:7]
porque predican una salvación común, arrepentimiento para todos,
la oferta de una puerta de misericordia y esperanza para todos a través de Jesucristo,
"`el cual se dio a sí mismo en rescate por todos.`"^
footnote:[1 Timoteo 2:6]
Sí, el evangelio invita a todos;
y ciertamente Cristo no tenía la intención de engañar a la mayor parte de la humanidad,
ni de burlarse de ellos cuando los invitó y clamó, diciendo:
"`Venid a mí todos los que estáis trabajados y cargados, y yo os haré descansar.`"^
footnote:[Mateo 11:28]
Entonces, si todos deben buscarlo a Él y esperar Su salvación,
Él tuvo que haberla hecho posible para todos.
En efecto,
no sería nada más que una burla pedirles a los hombres
que busquen lo que es imposible de obtener.
Y por eso,
los que niegan que por la muerte de Cristo se hizo
posible la salvación para todos los hombres,
blasfeman de la manera más grave, pues sugieren que Dios se burla del mundo.
Porque ellos admiten que Dios les ha dado a Sus siervos
una comisión de predicar el evangelio de salvación a todos,
y sin embargo,
sostienen que Él ha decretado previamente que es imposible que la mayoría lo reciba.

Pero viendo que Cristo, después de resucitar y perfeccionar la obra de nuestra redención,
dio la comisión de predicar el arrepentimiento,
la remisión de pecados y la salvación a todos,
es evidente que Él en verdad murió por todos.
Porque Aquel que ha mandado a Sus siervos a predicar así, es el Dios de la Verdad,
y no un burlador de la pobre humanidad,
ni exige de ningún hombre lo que es simplemente imposible que haga.

Además, si consideramos el testimonio de la Escritura en este asunto,
no hay ni un solo texto, que yo sepa,
que afirme de manera clara que Cristo no murió por todos,
mientras que hay muchos que afirman positiva y expresamente que sí lo hizo, por ejemplo:
"`Exhorto ante todo, a que se hagan rogativas, oraciones,
peticiones y acciones de gracias,
por todos los hombres...
Porque esto es bueno y agradable delante de Dios nuestro Salvador,
el cual quiere que todos los hombres sean salvos y vengan al conocimiento
de la verdad... el cual se dio a Sí Mismo en rescate por todos,
de lo cual se dio testimonio a su debido tiempo.`"^
footnote:[1 Timoteo 2:1,3,4,6]
Nada podría confirmar más claramente lo que hemos afirmado;
porque el apóstol primero les recomienda "`orar por todos los hombres,`" y luego,
como si tratara de evitar cualquier objeción con
respecto a la voluntad de Dios en este asunto,
les dice que "`eso es bueno y agradable delante de Dios,
pues Él quiere que todos los hombres sean salvos.`"
Luego manifiesta con estas palabras la razón por la que
Su voluntad es que todos los hombres sean salvos,
porque Él "`se dio a sí mismo en rescate por todos.`"
Es como si dijera: "`Puesto que Cristo murió por todos,
y puesto que se dio a Sí mismo en rescate por todos, desea, entonces,
que todos los hombres sean salvos.`"
Y Cristo mismo muestra el amor de Dios para con el mundo con estas palabras:
"`Porque de tal manera amó Dios al mundo, que ha dado a su Hijo unigénito,
para que todo aquel que en él cree, no se pierda, mas tenga vida eterna.`"
Esta frase "`todo aquel,`" es un término indefinido del cual ningún hombre es excluido.

Esto mismo se afirma de manera muy positiva con las siguientes palabras:
"`Pero vemos a Aquel que fue hecho un poco menor que los ángeles, a Jesús,
coronado de gloria y de honra, a causa del padecimiento de la muerte,
para que por la gracia de Dios gustase la muerte por todos.`"^
footnote:[Hebreos 2:9]
Es evidente que si "`gustó la muerte por todos,
`" entonces no hay hombre por quien no haya gustado la muerte,
ni hay quien no pueda volverse un participante de su beneficio;
porque Él no vino "`para condenar al mundo, sino para que el mundo sea salvo por Él.`"^
footnote:[Juan 3:17]
Él no vino "`a juzgar al mundo, sino a salvar al mundo.`"^
footnote:[Juan 12:47]
Pero según la doctrina de nuestros adversarios, Él no vino con la intención de salvar,
sino al contrario, para juzgar y condenar a la mayor parte del mundo,
en contra de Su expreso testimonio.

Y tal como el apóstol Pablo (en las palabras citadas arriba)
afirma positivamente que Dios _quiere_ la salvación de todos,
el apóstol Pedro afirma lo mismo negativamente, que Dios __"`no quiere__ que nadie perezca.`"
Él escribe: "`El Señor no retarda su promesa, según algunos la tienen por tardanza,
sino que es paciente para con nosotros, no queriendo que ninguno perezca,
sino que todos procedan al arrepentimiento.`"^
footnote:[2 Pedro 3:9]
Esto coincide con las palabras de Ezequiel: "`Vivo yo, dice Jehová el Señor,
que no quiero la muerte del impío, sino que se vuelva el impío de su camino,
y que viva.`"^
footnote:[Ezequiel 33:11]
Por lo tanto, si es seguro poner nuestra confianza en Dios,
no podemos creer que tenga la intención de engañarnos
con todas estas expresiones tan claras de Sus siervos.
Y si Su manifiesta voluntad por nuestra salvación no ha tenido efecto,
la culpa debe ser nuestra, como se mostrará después.

Aparte de estas cosas, ¿cómo deberíamos entender la multitud de fervientes invitaciones,
de serias acusaciones y dolorosas lamentaciones que
llenan las páginas de las Sagradas Escrituras?
Tales como: "`¿Por qué moriréis, casa de Israel?`"^
footnote:[Ezequiel 18:31, 33:11]
Por qué "`¿no queréis venir a mí para que tengáis vida?`"^
footnote:[Juan 5:40]
"`Aguardaré para otorgaros mi gracia.`"^
footnote:[Isaías 30:18 RV 1977]
"`¡Cuántas veces quise juntar tus hijos.`"^
footnote:[Mateo 23:37]
"`He aquí, yo estoy a la puerta`"^
footnote:[Apocalipsis 3:20]
de sus corazones.
"`Te destruiste a ti mismo, oh Israel.`"^
footnote:[Oseas 13:9 RVG]
"`Extendí mis manos todo el día.`"^
footnote:[Isaías 65:2]
Si los que son invitados de esta manera por el Señor
no tienen realmente la capacidad de ser salvos,
entonces debemos suponer que Dios es como el autor de una novela o comedia,
que se entretiene a Sí Mismo despertando los afectos y las pasiones de los hombres,
llevándolos a la esperanza unas veces y a la desesperación otras,
habiendo determinado desde siempre cual iba a ser el fin.

Además, esta doctrina es confirmada ampliamente por las palabras del apóstol Juan:
"`Si alguno hubiere pecado, abogado tenemos para con el Padre, a Jesucristo el justo.
Y Él es la propiciación por nuestros pecados; y no solamente por los nuestros,
sino también por los de todo el mundo.`"^
footnote:[1 Juan 2:1-2]
La manera por la que nuestros adversarios intentan
evitar este claro testimonio es muy tonta y ridícula;
ellos dicen que aquí "`mundo`" se refiere sólo al mundo _de los creyentes._
Para respaldar esto, no tienen nada más que su propia afirmación; porque muéstrenme,
si pueden, en toda la Escritura,
dónde la frase "`todo el mundo`" se refiere sólo a los creyentes solamente.
Yo puedo mostrarles donde ella muchas veces significa lo contrario.^
footnote:[Nota de Barclay: Tales como: "`El mundo no me conoce.`"
"`El mundo no me recibe.`"
"`Yo no soy de este mundo.`"
Además de todas estas escrituras: Salmos 17:14; Isaías 13:11; Mateo 18:7; Juan 7:7, 8:26,
12:19, 14:17, 15:18-19, 17:14 y 18:20; 1 Corintios 1:21, 2:12 y 6:2; Gálatas 6:14;
Santiago 1:27; 2 Pedro 2:20; 1 Juan 2:15, 3:1 y 4:4-5, y muchas más.]

Es más, el apóstol, en este mismo lugar, hace una distinción entre el mundo y los santos,
diciendo: "`Y no solamente por los nuestros, sino también por los de todo el mundo.`"
¿Qué quiere decir el apóstol con "`nuestros`" aquí? ¿No
está hablando claramente de los pecados de los creyentes?
¿Y no es necesariamente "`todo el mundo,`" una referencia a aquellos fuera de la iglesia,
por quienes Cristo también murió, y a quienes se extiende la invitación del evangelio?
Pero no necesitamos mejor intérprete para el apóstol que él mismo,
porque él usa la misma expresión en el quinto capítulo de la misma epístola, diciendo:
"`Sabemos que somos de Dios y que todo el mundo yace en la maldad.`"^
footnote:[1 Juan 5:19]
Viendo entonces que el apóstol Juan nos dice claramente,
que Cristo no sólo murió por los santos y miembros de la iglesia de Dios a quienes escribió,
sino también por todo el mundo,
entonces sostengámosla como una verdad cierta e indudable,
a pesar de las disputas de aquellos que se oponen.

Se podría probar lo mismo con muchos otros testimonios de las Escrituras,
si fuera necesario.
De hecho,
todos los Padres de la iglesia durante los primeros cuatro siglos predicaron esta doctrina.
Ellos declaraban con audacia el evangelio de Cristo y la eficacia de Su muerte,
invitando y suplicándoles a los paganos que vinieran y participaran de sus beneficios.
No les decían que Dios había predestinado a algunos de ellos para la condenación,
o que les había hecho imposible la salvación,
al negarles el poder y la gracia necesarios para creer; sino todo lo contrario,
declaraban que se había abierto una puerta para que toda
la humanidad viniera y fuera salva a través de Jesucristo.

Viendo entonces,
que esta doctrina de la universalidad de la muerte de Cristo es tan cierta,
estando de acuerdo tanto con el testimonio de las
Escrituras como con la antigüedad cristiana,
alguien podría preguntarse,
¿cómo es posible que tantos (algunos de los cuales no sólo han sido estimados sabios,
sino también piadosos) han sido capaces de caer en tan craso y extraño error?
Existen, en efecto, unos pocos textos difíciles,
que la mente no regenerada puede torcer y malinterpretar fácilmente,
pero la causa principal surge de un malentendido general sobre la manera o método,
mediante el cual la virtud y eficacia de la muerte de Cristo se ofrece a todos los hombres.
Aquí los hombres han tropezado y recurrido a varias invenciones teológicas.
Por no haber entendido la manera,
algunos se han alejado del claro testimonio de la Escritura, y como hemos visto,
han limitado la expiación de Cristo a unos pocos predestinados.
Otros se han equivocado en dirección opuesta,
afirmando que aquellos que nunca han escuchado la proclamación externa acerca de Cristo,
no están obligados a creer en Él,
o que todos son salvos independientemente de su fe y obediencia al evangelio.
