== Capítulo III. La Semilla, Luz y Gracia de Dios

Así como la oscuridad de la gran apostasía no vino
sobre el mundo cristiano toda a la vez,
sino más bien en varios grados, una cosa dándole paso a otra,
hasta que ese velo grueso y pesado se extendió (con el que las naciones fueron
cubiertas y dejadas en gran parte ciegas desde los siglos VII y VIII,
hasta el XVI);
y así como la oscuridad de la noche no cae sobre la creación externa toda a la vez,
sino gradualmente, a medida que el sol declina en el horizonte;
tampoco la Luz y el conocimiento pleno y claro de
la gloriosa dispensación del evangelio de Cristo,
han vuelto a aparecer en el mundo todo de una vez.
De hecho,
la labor de los primeros testigos en la reforma tuvo que ver más
con testificar contra los abusos de la apostasía y descubrirlos,
que establecer la Verdad en pureza.
El que quiera construir una nueva ciudad,
deberá remover primero los viejos escombros antes
de poder ver cómo colocar un nuevo fundamento;
y el que llega a una casa que está muy contaminada y llena de basura,
barrerá y eliminará primero la suciedad antes de poner sus muebles buenos y nuevos.
La luz del amanecer es suficiente para despejar las
tinieblas y hacernos ver las cosas más obvias;
pero el claro descubrimiento y discernimiento de las cosas,
como para hacer observaciones acertadas y perfectas,
está reservado para cuando se levanta el sol y brilla con todo su resplandor.

Ahora bien, a partir de cierta experiencia, podemos afirmar con confianza,
que muchos de los errores lamentables y perjudiciales entre los protestantes,
han surgido por no haber esperado a que este sol saliera más;
y han construido con y entre muchos viejos escombros católicos,
antes de que el fundamento estuviera completamente purificado.
Pero ahora, en esta nuestra época,
a nuestro Señor Dios le ha complacido comunicar y nuevamente dar a conocer,
un conocimiento más completo, evidente y perfecto de Su Verdad eterna,
y de la dispensación de Su evangelio (aunque diversos testimonios
de lo mismo han sido dados por personas notables en varias épocas,
como se verá más adelante).
Y con el fin de magnificar la gloria de Su Gracia y de excluir toda causa de jactancia,
ha levantado a unos pocos hombres despreciables y sin educación,
en su mayor parte obreros, para que sean Sus mensajeros.
Mediante este evangelio, todos los escrúpulos, dudas,
confusiones y objeciones mencionados anteriormente,
se responden de manera fácil y evidente,
y tanto la justicia como la misericordia de Dios, en perfecta armonía divina y celestial,
son exhibidas, establecidas y confirmadas.
Y es de acuerdo con esta Luz y evangelio verdaderos--según el conocimiento
que se nos ha manifestado por la revelación de Jesucristo en nosotros,
fortalecido por nuestra propia experiencia viva,
y sellado por el testimonio del Espíritu en nuestros
corazones--que podemos afirmar con confianza,
y exponer claramente, de acuerdo con el testimonio de las Sagradas Escrituras,
los siguientes puntos:

I+++.+++ Que Dios, quien por Su infinito amor envió a Su Hijo al mundo, el Señor Jesucristo,
para gustar la muerte por todo hombre, ha dado a cada hombre--sea judío o gentil,
turco o escita, indio o bárbaro, de cualquier nación,
país o lugar--un día o tiempo determinado de visitación,
durante el cual es posible que sean salvos y participen del fruto de la muerte de Cristo.

II. Que Dios, para este fin,
ha comunicado y dado a cada hombre una medida de la Luz de Su propio Hijo,
una medida de Gracia, o una medida del Espíritu,
que la Escritura describe con varios nombres como: "`la semilla del reino;`"^
footnote:[Mateos 13:18-19]
"`la Luz que manifiesta todo;`"^
footnote:[Efesios 5:13]
"`la Palabra de Dios;`"^
footnote:[Romanos 10:17; Santiago 1:21]
"`manifestación del Espíritu dada para provecho;`"^
footnote:[1 Corintios 12:7]
"`un talento o mina;`"^
footnote:[Mateos 25:15; Lucas 19:11]
"`una pizca de levadura;`"^
footnote:[Mateos 13:33]
"`el evangelio predicado en toda criatura.`"^
footnote:[Colosenses 1:23,
// lint-disable invalid-characters
Traducción Literal "`εν παση τη  κτισει]

III.
Que Dios, en y por medio de esta Luz y Semilla invita, llama,
exhorta y contiende con cada hombre con la intención de salvarlo.
A medida que esta obra de gracia es recibida, y no es resistida,
es capaz de efectuar la salvación de todos--incluso de aquellos
que no conocen la historia de la muerte y sufrimientos de Cristo,
ni de la caída de Adán--al llevarlos a un sentido de su propia miseria,
y a la comunión con los padecimientos de Cristo internamente,
y al hacerlos partícipes de Su resurrección, llegando a ser santos, puros y justos,
y libres de sus pecados.
Por esta misma Luz y Semilla,
también se obra la salvación en aquellos que sí tienen
el conocimiento externo e histórico de Cristo,
abriendo su entendimiento para usar y aplicar correctamente
las cosas descritas en las Escrituras,
y para recibir el beneficio salvador de ellas.
Sin embargo, este don de Gracia puede ser resistido y rechazado en ambos casos,
en los cuales se dice que Dios es resistido^
footnote:[Véase Hechos 7:51; Hebreos 2:3; Gálatas 2:21, etc.]
y oprimido;^
footnote:[Amos 2:13, "`He aquí,
yo estoy oprimido debajo de vosotros como está oprimida una carreta llena de gavillas.`"
LBLA]
y que Cristo es crucificado de nuevo y expuesto a vituperio en y entre los hombres;^
footnote:[Hebreos 6:6]
y para aquellos que lo resisten y rechazan de esta manera, Él se vuelve su condenación.^
footnote:[Juan 3:19]

Ahora bien, de acuerdo con esta doctrina:

Primero: Esta doctrina exhibe magníficamente la misericordia de Dios,
ya que nadie queda necesariamente excluido de la salvación. Y Su justicia se demuestra,
en que Él no condena a nadie,
excepto a aquellos a quienes realmente les hizo una oferta de salvación,
habiéndoles proporcionado los medios suficientes para obtenerla.

Segundo: Se encontrará que esta doctrina, si se considera debidamente,
es el verdadero fundamento del cristianismo y de la salvación,
y la auténtica certidumbre.

Tercero: Concuerda y encaja con todo el tenor de las promesas y amenazas del Evangelio,
y con la naturaleza del ministerio de Cristo,
de acuerdo con el cual se ordena que el Evangelio,
la salvación y el arrepentimiento se prediquen a toda criatura, sin acepción de naciones,
tribus, familias o lenguas.

Cuarto: Magnifica y exalta los méritos y la muerte de Cristo,
ya que no sólo los considera suficientes para salvar a todos,
sino que establece que han sido puestos tan cerca de todos los hombres,
que los pone en una capacidad real de ser salvos.

Quinto: Exalta la Gracia de Dios por encima de todo,
como la fuente de todo lo que es verdaderamente bueno--desde
el menor y más pequeño movimiento del bien,
hasta la total conversión y salvación del alma.

Sexto: Contradice,
invalida y anula la falsa doctrina de los que exaltan la
luz de la naturaleza del hombre y la fuerza de su voluntad,
al excluir por completo al hombre natural de tener
algún lugar o porción en su propia salvación,
por cualquier tipo de acto, movimiento u obra por su cuenta,
hasta que primero sea vivificado, levantado y movido por el Espíritu de Dios.

Séptimo:
Así como hace que la totalidad de la salvación del
hombre dependa única y completamente de Dios,
también hace que la condenación del hombre sea enteramente y en todos los aspectos,
por causa de sí mismo.
Porque el hombre que niega y resiste el don de Dios que lucha y contiende con su corazón,
al final se ve forzado a reconocer el justo juicio
de Dios cuando es rechazado y abandonado después.

Octavo: Quita todo motivo de desesperación,
y le da a cada hombre un motivo de esperanza y una
confianza firme de que puede ser salvo.
Sin embargo, no alimenta a nadie con una seguridad falsa,
ya que ninguno sabe con certeza cuán pronto expirará su día. Por lo tanto,
está constantemente incitando, provocando y estimulando vívidamente a todos los hombres,
para que abandonen el mal y se vuelvan a lo que es bueno.

Noveno: Exalta maravillosamente la religión cristiana entre los incrédulos,
manifestándoles su verdad a todos,
ya que esta doctrina es confirmada y establecida por la experiencia de todos los hombres.
Porque nunca se ha encontrado a un hombre en algún lugar de la tierra,
sin importar cuán bárbaro o salvaje sea,
que no haya sentido y reconocido que en algún momento y en alguna medida,
algo en su corazón lo reprende por causa de algunas cosas malas que ha hecho.
Este testigo interno es el mismo en todos;
amenaza con cierto horror mientras el hombre continúa en el mal,
y le promete y comunica cierta paz y dulzura,
a medida que le da paso a la Gracia y no la resiste.

Décimo: Muestra maravillosamente la excelente sabiduría de Dios,
ya que por ella ha hecho los medios de salvación tan universales y completos.
Por lo tanto, no está obligado a hacer uso de milagros externos,
ni del ministerio de los ángeles, ni de otros medios inusuales,
puesto que según esta doctrina verdadera, el evangelio alcanza a todos,
cualquiera que sea la condición, edad o nación.

Undécimo:
Es real y efectivamente establecida y confirmada por todos los
predicadores y promotores del cristianismo en todo el mundo,
aunque quizás no con las mismas palabras, pero sí con sus hechos.
Porque, a pesar de que en su opinión se oponen a esta doctrina,
aun así le predican a cada individuo que puede ser salvo,
implorándole y deseando que crea en Cristo, quien murió por él;
diciéndole que Jesucristo lo llama y quiere que crea y sea salvo;
y que si se niega será condenado, y que su condenación será por causa de sí mismo.
En efecto, tal es la evidencia y virtud de la Verdad,
que constriñe a sus adversarios a abogar por ella, incluso contra su propia voluntad.

=== Consideraciones Adicionales sobre las Proposiciones Anteriores.

Primera,
cuando hablamos de que Dios le da un día o tiempo de visitación a todos los hombres,
durante el cual pueden ser salvos,
no nos referimos a la duración total de vida de cada hombre--aunque para algunos,
dicha visitación podría extenderse incluso hasta la misma hora de su muerte,
como vemos en el ejemplo del ladrón que se convierte en la cruz.
Mas bien,
entendemos este tiempo de visitación como una temporada en la que el Espíritu contiende
con el hombre por la salvación de su alma (para algunos más corta y para otros más larga,
según lo que el Señor en Su sabiduría considere apropiado),
lo cual exonera a Dios más que suficientemente de la condenación de cada hombre.
Además,
es evidentemente posible que los hombres pueden seguir viviendo
después de que haya pasado su tiempo de visitación,
después del cual no tienen ninguna posibilidad de salvación. Dios justamente
permite que éstos se endurezcan como el debido castigo de su incredulidad,
y en ocasiones hasta los utiliza como instrumentos de ira,
y los convierte en un azote unos contra otros.^
footnote:[Nota de Barclay:
A los hombres en esta condición se les puede aplicar apropiadamente
aquellas Escrituras que a menudo se usan erróneamente,
para probar que Dios incita necesariamente a los hombres a pecar.]

El apóstol expresa esta doctrina de manera clara en Romanos 1,
desde el versículo 17 hasta el final, pero especialmente en el versículo 28:
"`Y como a ellos no les pareció bien tener a Dios en su conocimiento,
Dios los entregó a una mente reprobada, para hacer cosas que no convienen.`"^
footnote:[Romanos 1:28 RV1602P]
El ejemplo de Esaú muestra que muchos pueden vivir después de este
día de la visitación misericordiosa de Dios para con ellos,
porque él tuvo una vez la primogenitura, y ciertamente pudo haberla conservado;
pero después, cuando deseó heredar la bendición fue rechazado.^
footnote:[Hebreos 12:16-17]
Esto también se evidencia del llanto de Cristo sobre Jerusalén, diciendo: "`¡Oh,
si también tú conocieses, a lo menos en este tu día, lo que es para tu paz!
Mas ahora está encubierto de tus ojos.`"^
footnote:[Lucas 19:42]
Esto demuestra claramente que hubo un tiempo en el
que habrían podido conocer estas cosas;
tiempo que ahora les había sido quitado, aunque todavía estaban vivos.

Segunda, nosotros decimos que hay una Semilla o medida de Gracia, una Palabra de Dios,
o Luz, por la cual todo hombre es iluminado (habiendo recibido una medida de ella),
que contiende con ellos con el fin de salvarlos,
y que por la dureza e iniquidad de la voluntad del hombre, puede ser apagada, ahogada,
herida, oprimida, inmolada y crucificada.
Ahora bien,
nosotros no entendemos esta Semilla como la esencia y naturaleza propia de Dios,
tomadas estrictamente, las cuales no son divisibles en partes ni medidas,
puesto que Él es el más puro y simple ser, sin composición y división; y en este sentido,
no puede ser resistido, golpeado, herido,
crucificado ni asesinado por los esfuerzos y fuerza de los hombres.
Pero entendemos que esta Semilla es una emanación espiritual,
celestial e invisible en la cual Dios habita (como Padre, Hijo y Espíritu);
de cuya vida divina y gloriosa es sembrada una medida en todos los hombres,
y que de su propia naturaleza atrae, invita e inclina hacia Dios.
A esto lo llamamos la carne y sangre espiritual de Cristo, que descendió del cielo,
de la cual todos los santos se alimentan y se nutren para vida eterna.
Y así como esta Luz o Semilla testifica contra cada pensamiento o acción injusta,
y la reprueba, así también se dice que es herida,
crucificada o asesinada por esas acciones perversas,
y por lo tanto se retira o huye de ellas.

Por tanto, debido a que esta Semilla nunca se separa de Dios,
sino que donde sea que esté, Dios y Cristo están como envueltos en ella,
en este sentido decimos, por un lado, que cuando la Semilla es resistida,
entonces Dios es resistido; y donde es oprimida,
se dice que Dios es oprimido como una carreta que está llena de gavillas,^
footnote:[Amos 2:13 LBLA, y H. B. Pratt (1929)]
y que Cristo es asesinado y crucificado en los hombres.^
footnote:[Hebreos 6:6]
Y por otro lado decimos, que a medida que esta Semilla es recibida en el corazón,
y se le permite producir Su efecto natural y propio,
Cristo llega a ser formado y resucitado.
La Escritura frecuentemente hace mención de esto llamándolo "`el nuevo hombre,`"^
footnote:[Efesios 4:24; Colosenses 3:10]
"`Cristo formado en vosotros,`"^
footnote:[Gálatas 4:19]
o "`Cristo en vosotros, la esperanza de gloria.`"^
footnote:[Colosenses 1:27]
Y este es ese Cristo interno, de quién tan a menudo hablamos y declaramos, predicándolo;
y exhortamos a las personas a creer en la Luz y a obedecerla,
para que puedan conocer a Cristo dentro de ellos liberándolos de todo pecado.

Pero al predicar esta Luz o Semilla en el interior, no pretendemos en definitiva,
ni igualarnos al Señor Jesucristo--que nació de la virgen María,
y en quien habitaba corporalmente toda la plenitud de la
Deidad--ni destruir la realidad de Su existencia actual.
Porque aunque afirmamos que Cristo mora en nosotros,
Su presencia en nosotros es en una medida, y a través de la mediación de Su Semilla.
Pero en aquel Hombre santo, el Señor Jesucristo,
la Palabra eterna (que estaba con Dios y era Dios)
moraba en plenitud y sin mediación. Así pues,
Él es la cabeza y nosotros los miembros; Él es la vid y nosotros los pámpanos.

Tercera, entendemos que esta Semilla, Luz o Gracia es una sustancia espiritual y real,
que el alma del hombre es capaz de sentir y percibir,
y de la cual surge un nacimiento real, espiritual e interno en los creyentes,
que la Escritura llama la nueva criatura,
o el nuevo hombre en el corazón. Esto parece extraño para los hombres
de mente carnal debido a que no están familiarizados con ella,
pero nosotros la conocemos y estamos conscientes de ella,
por una verdadera y genuina experiencia.
En verdad, es imposible que un hombre la comprenda en su sabiduría natural,
hasta que llega a sentirla en sí mismo, y entonces,
se da cuenta que afirmarla como un mero concepto le es de muy poco provecho.
Sin embargo, aunque los hombres la nieguen, somos capaces de demostrar que es verdadera,
y que nuestra fe al respecto no carece de un fundamento sólido.
Porque es en y por medio de esta Semilla interna y sustancial en nuestros corazones,
conforme ella recibe alimento y nace en nosotros,
que llegamos a tener esos sentidos espirituales desarrollados
por los que somos capaces de gustar,
oler, ver y tocar las cosas de Dios.
Porque el hombre no puede alcanzar estas cosas por
medio de su espíritu y de sus sentidos naturales,
como se ha declarado anteriormente.

Cuarta, al insistir en estas cosas, no pretendemos de ninguna manera,
restarle importancia a la expiación y sacrificio de Jesucristo, ni menospreciarlo;
sino al contrario, lo magnificamos y exaltamos.
Porque,
así como creemos todas las cosas que están registradas
en las Sagradas Escrituras respecto al nacimiento,
vida, milagros, sufrimientos, resurrección y ascensión de Cristo,
también creemos que es el deber de todos aquellos,
a quienes les han sido declaradas estas verdades, creer en ellas.
De hecho, consideramos que es una incredulidad digna de condenación no creer,
cuando estas cosas han sido presentadas correctamente.
Porque la Semilla santa que es sembrada en el hombre, cuando se le presta atención,
lleva e inclina a cada corazón a creer en las verdades
de la Escritura tal como son dadas a conocer.
Porque aunque no revela el conocimiento externo e histórico de Cristo en cada corazón,
siempre asiente a él cuando es declarado.

Y así como firmemente creemos que era necesario que Cristo viniera,
para que a través de Su muerte y padecimientos se ofreciera
a Sí mismo como un sacrificio a Dios por nuestros pecados,
"`quien llevó Él mismo nuestros pecados en su cuerpo sobre el madero;`"^
footnote:[1 Pedro 2:24]
asimismo, creemos que la remisión de los pecados experimentada por cualquier persona,
es únicamente en y por la virtud de ese sacrificio tan satisfactorio;
porque es "`por la justicia de uno que vino la gracia
a todos los hombres para justificación de vida.`"^
footnote:[Romanos 5:18 RV1602P]

También afirmamos,
que así como todos los hombres participan del fruto de la caída de Adán,
debido a esa semilla maligna que les es comunicada a través de él,
haciéndolos propensos e inclinados al mal,
a pesar de que millones no saben nada acerca de la caída de Adán,
ni jamás han oído que comió del fruto prohibido--así también,
muchos pueden llegar a sentir la influencia de esta Semilla y Luz santa y divina,
y por medio de ella convertirse del mal al bien,
a pesar de que no sepan nada de la venida de Cristo en la carne,
por cuya obediencia y sufrimientos les es comprado este don.
Y así como afirmamos que es absolutamente necesario que aquellos a quienes Dios le ha
placido darles el conocimiento de la historia de la aparición externa de Cristo,
crean en ella; asimismo confesamos libremente,
que el conocimiento externo es muy reconfortante
para los que están sujetos a la Semilla y Luz interna,
y son guiados por ella.
Porque escuchar sobre el amor y los sufrimientos de Cristo, no sólo tiende a humillarlos,
sino que también los fortalece en su fe y los alienta
a seguir ese excelente patrón que Él nos ha dejado.
Como dice el apóstol Pedro: "`Quien padeció por nosotros, dejándonos ejemplo,
para que sigamos sus pisadas.`"^
footnote:[1 Pedro 2:21]
En verdad,
muchas veces somos grandemente edificados y animados
por los dichos piadosos que han procedido de Su boca.
Por lo tanto,
la historia es verdaderamente provechosa y reconfortante
cuando se conoce junto con el misterio,
y nunca sin él;
pero el misterio puede ser provechoso sin el conocimiento
explícito y externo de la historia.

Quinta, pero esto nos lleva a otra pregunta, a saber:
¿Está Cristo entonces en todos los hombres?
Hemos dicho antes que una Luz divina,
espiritual y sobrenatural ha sido dada a todos los hombres,
que Dios y Cristo moran en ella y nunca se separan de ella, y también,
que a medida que esta Luz es recibida en el corazón y se le cede paso,
Cristo llega a ser revelado y formado.
Pero estamos muy lejos de haber dicho alguna vez
que Cristo es recibido por todos los hombres,
y mucho menos, formado en todos los hombres; porque eso es un gran logro,
por el cual el apóstol sufría dolores de parto para que fuera formado en los Gálatas.
Tampoco está Cristo en todos los hombres en el sentido de estar unido a ellos,
ni tampoco, para hablar estrictamente, en el sentido de habitar o morar en ellos;
porque este habitar implica una unión, o la manera en que Cristo reside en los santos.
Como está escrito "`Yo moraré en ellos, y andaré en ellos;`"^
footnote:[2 Corintios 6:16 RV 1602P]

Sin embargo, en un sentido más general, viendo que Cristo nunca está,
ni puede estar separado de esa Semilla y Luz pura que testifica en todos los hombres,
se puede decir que Él está en todos.
Como se observó anteriormente,
es en este sentido que la Escritura dice que Dios es oprimido
como una carreta llena de gavillas (Amos 2:13),^
footnote:[Amos 2:13 LBLA, y H. B. Pratt (1929)]
y que Cristo es crucificado en los impíos (Hebreos 6:6);
aunque si hablamos de manera correcta y estricta, Dios no puede ser oprimido, ni Cristo,
como Dios, crucificado.
Pero en este respecto,
podemos dirigir a todos los hombres a buscar a Cristo dentro de sí mismos,
quien yace crucificado en ellos por causa de sus pecados e iniquidades,
para que puedan "`mirarlo a Él, a quien traspasaron,`"^
footnote:[Zacarías 12:10]
y arrepentirse.
Entonces, Aquel que ahora yace crucificado y enterrado en ellos (por así decirlo),
puede llegar a ser resucitado, y tener dominio sobre todo en sus corazones.
De esta manera,
también les predicó el apóstol Pablo a los Corintios y Gálatas acerca
de "`Cristo crucificado en ellos,`" (en humin como lo tiene el griego.)^
footnote:["`Pues me propuse no saber en vosotros cosa alguna sino a Jesucristo,
y a éste crucificado.`"
1 Corintios 2:2. "`¡Oh gálatas insensatos! ¿quién os fascinó para no obedecer a la verdad,
a vosotros ante cuyos ojos Jesucristo fue ya presentado
claramente en vosotros como crucificado?`"
Gálatas 3:1 -- Traducciones literales del griego.]
Este Jesucristo era el que el apóstol deseaba conocer en ellos, y manifestarles a ellos,
para que pudieran llegar a ser conscientes de cómo
habían estado resistiendo y crucificando a Cristo,
y así pudieran arrepentirse y ser salvos.
Y debido a que Cristo es llamado "`la luz verdadera, que alumbra a todo hombre,`"^
footnote:[Juan 1:9]
y "`la luz del mundo,`"^
footnote:[Juan 8:12]
esta Luz es tomada, por lo tanto, como Cristo,
quien es verdaderamente la fuente de toda luz, y tiene Su morada en ella para siempre.
Así, la Luz de Cristo algunas veces es llamada Cristo, es decir,
aquello en lo que Cristo está, y de lo que nunca se separa.

Sexta, se ve claramente por lo dicho anteriormente,
que no vemos esta Semilla o Luz divina como algo
que sea parte de la naturaleza del hombre,
ni como el vestigio de algún bien que Adán perdió por su caída;
porque sabemos que es una cosa distinta y separada del alma
del hombre y de todas las facultades de ella.
Sin embargo, tal es la malicia de nuestros adversarios, que no dejan de criticarnos,
como si predicáramos una luz natural, o la luz de la conciencia natural del hombre.
Pero nosotros sabemos con certeza, que la Luz de la cual hablamos no sólo es distinta,
sino de una naturaleza diferente al alma del hombre,
y a todas sus operaciones y capacidades.

No negamos que el hombre, como una criatura racional,
tiene la razón como una facultad natural de su alma,
mediante la cual puede discernir cosas que son racionales.
De hecho, esta es una propiedad natural y esencial para él,
por la cual puede conocer y aprender muchas artes y ciencias,
más allá de lo que cualquier otro animal puede hacer con meras facultades animales.
Tampoco negamos que el hombre, por este principio racional,
puede captar con su cerebro y entendimiento,
un conocimiento de Dios y de cosas espirituales; sin embargo,
al no ser este el órgano correcto para el verdadero conocimiento espiritual,
no le sirve para salvación, sino que a menudo lo estorba.
Y en efecto,
la gran causa de la apostasía ha sido que el hombre ha tratado de comprender
las cosas de Dios en y por este principio natural y racional,
y edificar una religión en él,
negando y despreciando la Luz y Semilla de Dios en el corazón.
De este modo se ha "`exaltado`" el Anticristo en cada hombre,
"`sentándose en el templo de Dios, haciéndose pasar por Dios.`"^
footnote:[2 Tesalonicenses 2:4 RV1602P]
Porque siendo que los hombres son "`el templo del Espíritu Santo,`"^
footnote:[1 Corintios 3:16]
como dice el apóstol,
siempre que la razón natural se establece por encima de la Semilla y Luz de Dios,
para reinar y gobernar como príncipe en las cosas espirituales
(mientras la Semilla Santa es herida y maltratada),
allí está el Anticristo en cada hombre, o algo exaltado sobre Cristo y en contra de Él.

Sin embargo,
con esto no sugerimos que el hombre haya recibido su razón sin ningún propósito,
o que no le sea de utilidad; de ninguna manera.
Porque consideramos que la razón es apta para ordenar
y gobernar al hombre en las cosas naturales.
Y así como Dios dio dos grandes lumbreras para gobernar el mundo exterior,
el sol y la luna,
la lumbrera mayor para gobernar el día y la lumbrera menor para gobernar la noche;
asimismo le ha dado al hombre la Luz de Su Hijo, una Luz divina y espiritual,
para gobernarlo en las cosas espirituales, y la luz menor de la razón,
para gobernarlo en cosas naturales.
Y así como la luna toma prestada su luz del sol, eso mismo deben hacer los hombres;
si quieren estar correcta y felizmente ordenados en las cosas naturales,
deberán tener su razón iluminada por esta Luz divina y pura.
Porque nosotros confesamos que la razón iluminada puede
ser útil a los que obedecen y siguen esta Luz verdadera,
incluso en cosas espirituales,
siempre y cuando permanezca subordinada y sujeta a la verdadera Luz;
de la misma manera que la vida biológica en el hombre
lo ayuda en el manejo de las cosas que son racionales,
cuando está regulada y ordenada por su razón.

Además,
nosotros hacemos correctamente una distinción entre
la Luz de Cristo y la conciencia natural del hombre;
porque la conciencia,
siendo aquello que surge de las facultades naturales del alma humana,
puede ser contaminada y corrompida.
El apóstol Pablo, hablando de los impuros, dice claramente,
que "`hasta su mente y su conciencia están corrompidas.`"^
footnote:[Tito 1:15]
Sin embargo, esta Luz no puede ser corrompida ni contaminada,
ni ha consentido jamás el mal o la iniquidad en nadie; porque se dice expresamente,
que ella "`hace manifiestas todas las cosas que son reprobadas,`"^
footnote:[Efesios 5:13 RVG]
y por lo tanto,
es un testigo fiel para Dios contra toda manifestación de injusticia en el hombre.

Ahora bien, la palabra conciencia, para definirla correctamente,
viene del latín conscire, y es ese conocimiento que surge en el corazón del hombre,
a partir de lo que está de acuerdo o es contrario a cualquier cosa que crea,
por medio del cual se da cuenta de que trasgrede,
al hacer algo de lo que está convencido que no debería hacer.
Entonces, cuando la mente ha sido cegada o contaminada con una creencia incorrecta,
de esta creencia surge una conciencia que perturba
dicho corazón cada vez que actúa en su contra.
Por ejemplo, cuando un musulmán,
que ha aceptado la falsa creencia de que para él es ilícito tomar vino,
actúa contra su creencia y bebe, su conciencia lo golpea por ello;
pero si posee muchas concubinas, su conciencia no lo perturba,
porque su juicio ya está corrompido con la falsa opinión de que
es lícito para él hacer una cosa e ilícito hacer la otra.
Sin embargo, si prestara atención a la Luz de Jesucristo en su interior,
ésta lo reprendería, no sólo por cometer fornicación,
sino que también le informaría (a medida que se volviera
más obediente a ella) que Mahoma es un impostor,
de la misma manera que Sócrates, en su día,
fue informado por ella de la falsedad de los dioses paganos.

Del mismo modo, si un católico romano comiera carne durante la Cuaresma,
o no fuera suficientemente diligente en la adoración de santos e imágenes,
su conciencia lo heriría por ello,
porque su juicio ya está cegado con la falsa creencia acerca de estas cosas.
Sin embargo, la Luz de Cristo nunca ha aprobado ninguna de esas abominaciones.
Por lo tanto, la conciencia natural del hombre se distingue claramente de la Luz,
porque la conciencia sigue el juicio; no lo informa.
Pero esta Luz, en la medida que es recibida y obedecida,
quita la ceguera del falso juicio,
abre el entendimiento y rectifica tanto el juicio como la conciencia.
Así pues, confesamos que la conciencia es algo excelente,
siempre y cuando esté correctamente informada e iluminada desde lo alto.
De hecho, algunos de nosotros la hemos comparado apropiadamente con una linterna,
y a la Luz de Cristo con la vela en su interior.
Una linterna es útil cuando la vela arde y brilla en su interior,
de lo contrario de nada sirve.
Por eso, es a la Luz de Cristo en la conciencia, y no a la conciencia natural del hombre,
que continuamente encomendamos a los hombres.
Ella es su guía segura a la vida eterna.

Por último, es evidente que esta Luz, Semilla, etc.,
no es ningún poder o facultad natural de la mente del hombre,
porque un hombre sano puede, cuando quiera, agitar,
mover y ejercitar las facultades de su alma; de hecho, es dueño de ellas,
y a no ser que haya alguna causa o impedimento natural en su camino,
puede usarlas a su antojo.
Pero esta Luz o Semilla de Dios en el hombre,
no se mueve ni se despierta cuando el hombre lo desee; al contrario, se mueve,
hiere y contiende con el hombre conforme el Señor lo considere oportuno.
Porque aunque hay una posibilidad de salvación concedida
a todo hombre durante el día de su visitación,
aun así, el hombre no puede, en cualquier momento que le plazca,
o cada vez que tenga un sentido de su miseria,
despertar esa Luz o Gracia para procurarse una verdadera
ternura de corazón. Por el contrario,
debe esperarla, ya que viene a todos en ciertos tiempos y temporadas,
obrando poderosamente en el alma, enterneciéndola y quebrantándola fuertemente.
En tales momentos, si un hombre no la resiste, sino que la recibe y la sigue,
llega a experimentar la salvación por medio de ella.
Así como el estanque de Betesda no sanaba a todos,
sino únicamente a los que esperaban el movimiento de las aguas, así se mueve Dios,
en ciertos momentos, en amor a la humanidad mediante Su Semilla en sus corazones,
poniendo sus pecados en orden delante de ellos, invitándolos seriamente a arrepentirse,
y ofreciéndoles remisión de pecados y salvación; lo cual, si el hombre acepta,
puede ser salvo.

Ahora bien, no existe un hombre vivo, y estoy seguro de que nunca existirá,
que si lidiara con su propio corazón fiel y honestamente,
no se vería obligado a confesar que ha sido consciente de esto en alguna medida;
lo cual es algo que el hombre no puede producir en sí mismo con todo su esfuerzo y diligencia.
Esto, oh hombre y mujer, es el día de la misericordiosa visitación de Dios a tu alma,
y serás feliz para siempre si no lo resistes.
Este es el día del Señor, el cual, como dice Cristo,
es como el relámpago que resplandece desde el oriente hasta el occidente,
y como el viento o Espíritu, que sopla sobre el corazón,
y ningún hombre sabe de dónde viene, ni adónde va.

=== La Operación de la Semilla en el Corazón

Esto me lleva a hablar sobre la manera en que esta
Semilla o Luz opera en el corazón de todos los hombres,
lo cual demostrará aún más claramente,
cuán ampliamente diferimos de todos aquellos que
exaltan el poder o luz natural en el hombre,
y cómo nuestro principio lleva, por encima de todos los demás,
a atribuir toda nuestra salvación únicamente al poder, Espíritu y Gracia de Dios.

Algunos nos han planteado la siguiente pregunta:
Si dos hombres tienen igual y suficiente Luz y Gracia,
y uno es salvo por ella y el otro no, ¿no es, entonces,
la voluntad del hombre la verdadera causa por la cual uno fue salvo y el otro no?
A esta pregunta respondemos:
Que así como la Gracia y Luz en todos es suficiente para salvar a todos,
y por Su propia naturaleza salvaría a todos,
así contiende y lucha con todos para salvarlos.
Aquel que resiste Su obra es la causa de su propia condenación; él que no la resiste,
encuentra que se convierte en su salvación. De manera que, en el que se salva,
la obra es de la Gracia y no del hombre, y esto se debe a su rendición y pasividad,
más que a su propia actividad.
Sin embargo, después, conforme el hombre es trabajado por la Gracia,
se levanta en él una voluntad por la que llega a ser colaborador de la Gracia; porque,
como dijo Agustín: "`El que nos hizo sin nosotros, no nos salvará sin nosotros.`"

Por lo tanto, el primer paso no es por obra del hombre,
sino por no obrar en contra de la Luz y Gracia de Dios.
Y durante estas temporadas de visitación en cada hombre,
aunque el hombre por sí mismo es completamente incapaz de colaborar con la Gracia,
o de dar un paso hacia afuera de su condición natural
hasta que la Gracia se apodere de él,
aun así, le es posible ser pasivo y no resistirla, o ser duro y resistirla.
Por lo tanto,
nosotros decimos que la Gracia de Dios obra en y sobre la naturaleza del hombre, la cual,
aunque en sí misma completamente corrupta y contaminada, y propensa al mal,
es capaz de ser trabajada por la Gracia de Dios; tal como el hierro,
a pesar de que en sí mismo es un metal duro y frío,
puede ser calentado y ablandado por el calor del fuego; y la cera derretida por el sol.
Y al igual que el hierro o la cera,
cuando se quitan del fuego o del sol vuelven a su condición anterior de frialdad y dureza,
asimismo, cuando el corazón del hombre resiste o se retira de la Gracia de Dios,
regresa a su condición anterior otra vez.
A menudo he tenido la manera en que Dios trabaja la salvación
de todos los hombres ilustrada en mi mente,
por medio de una o dos analogías claras que añadiré
aquí para la información de los demás.

La primera trata de un hombre gravemente enfermo,
a quien comparo con el hombre en su condición caída y natural.
Ahora bien, algunos suponen que Dios, el gran médico,
le ofrece medicina a este pobre hombre sólo después
de que él ha hecho todo lo que estaba en su poder,
mediante cualquier habilidad o conocimiento propio, para obtener su propia sanidad.
Estos son aquellos que dicen,
que si un hombre cultiva su razón o sus facultades naturales,
entonces Dios vería apropiado proporcionarle gracia.
Otros dicen que Dios viene y le ofrece un remedio al hombre enfermo,
pero deja a la voluntad del hombre recibirlo o rechazarlo.
Pero nosotros decimos que Él, es decir, el Señor, este gran médico,
viene y vierte el remedio en la boca del hombre enfermo y lo acuesta en su cama,
de modo que, si el enfermo se mantiene pasivo,
el remedio necesariamente lo curará. Pero si es terco y rebelde,
e insiste en levantarse y salir al frío,
y en comer cosas que le son dañinas mientras que la medicina opera; entonces,
aunque por su naturaleza la medicina tienda a curarlo,
al final resultará destructiva para él. Así, pues, en este ejemplo,
el hombre que perece sería ciertamente la causa de su propia muerte;
y el hombre que es sanado debería su salud enteramente al médico,
y no a alguna obra propia.

La segunda trata de varios hombres que están juntos en un pozo oscuro,
donde todos sus sentidos están tan aturdidos,
que apenas son conscientes de su propia miseria.
A esto comparo al hombre en su condición natural, corrupta y caída. Nuevamente,
nosotros no pensamos que Dios mire hacia abajo,
y al ver que uno está haciendo todo lo que está en su poder para liberarse,
decida que ese merece ser ayudado.
Tampoco pensamos que un libertador llegue al borde del pozo,
descuelgue una escalera y espere que asciendan por su propia fuerza,
entendimiento y voluntad.
En lugar de esto, creemos que el libertador llega en ciertos tiempos,
y les revela e informa plenamente a los hombres la
gran miseria y peligro en el que están,
si continúan en ese lugar horrible e insalubre.
De hecho,
este libertador los obliga a cierta conciencia de su miseria (porque incluso
los hombres más impíos a veces son conscientes de ella por la visitación de Dios),
y no sólo eso, sino que a veces se apodera de ellos y les da un jalón,
con el fin de sacarlos de su miseria; lo cual los salvará si no se resisten;
aunque tienen la capacidad de resistirse.

Estas dos analogías, ilustran en cierta medida el asunto,
demostrando que la Gracia de Dios alcanza a todos,
aunque su efecto difiere según el objeto con el que se encuentre.
Porque esta Gracia es una ministración de misericordia
y amor en todos los que no la rechazan,
sino que la reciben (Juan 1:12);
pero es una ministración de ira y condenación en los que la rechazan (Juan 3:19);
así como el sol, que por un solo acto u operación, derrite y suaviza la cera,
pero seca y endurece la arcilla.
La naturaleza del sol es beneficiar la creación,
y por lo tanto los seres vivos se refrescan con él,
y las flores despiden un buen aroma mientras brilla sobre ellas,
y los frutos de los árboles maduran.
Sin embargo, con un cadáver muerto, una cosa sin vida,
los mismos rayos del sol harán que hieda, y se pudra.
Así, pues, cada hombre, durante el día de su visitación,
es iluminado por el sol de justicia y es capaz de ser influenciado por él,
para producir buen fruto,
y un buen aroma y ser derretido por él. Pero cuando un hombre ha rechazado la luz,
y ha perdido su día por su pecado, entonces el mismo sol lo endurece,
como lo hace con la arcilla, y hace que su iniquidad se manifieste más,
se pudra y despida un mal aroma.
