== Capítulo V. Respecto a la Justificación

Después de hablar de la muerte de Cristo y de la
gracia que fue comunicada por dicha muerte,
la doctrina de la justificación es lo siguiente en el orden.
Muchas son las disputas entre los llamados Cristianos acerca de la justificación;
pero sin duda, si todos le prestaran verdadera atención a ese poder que justifica,
habría menos ruido respecto a las diversas ideas y opiniones.
Primero, voy a examinar brevemente la controversia tal como se encuentra entre otros,
y tal como la he considerado a menudo y con seriedad.
Luego expondré la controversia en relación con nosotros,
mostrando nuestro entendimiento y juicio de ella.
Y por último,
probaré nuestra postura (si el Señor lo permite) con varios testimonios de las Escrituras,
y con la experiencia verdadera de todos los que alguna
vez fueron realmente justificados.

Yo supongo que ningún Cristiano Protestante niega que la doctrina
de la justificación haya sido corrompida por la iglesia de Roma,
porque se muestra de manera evidente, y se enseña abiertamente entre los católicos,
que la remisión de pecados y la justificación se obtienen por los méritos de Cristo
según les son aplicados a los individuos a través del uso de los sacramentos de la iglesia,
y son dispensados en la ejecución de diversas ceremonias, peregrinajes, indulgencias,
oraciones, penitencias y otras obras,
incluso cuando no haya renovación interna de la mente,
ni experiencia de Cristo formado internamente;
de modo que su justificación proviene de algo fuera de ellos,
y no de Alguien dentro de ellos.
Se dice que estos individuos son perdonados y hechos
justos por la virtud del sacramento mismo,
y por la autoridad de un sacerdote que los declara absueltos.
En verdad, Lutero tenía buenas razones para oponerse a ellos en este asunto,
y si él no hubiera corrido hacia el otro extremo (del cual
hablaremos después) su obra se habría mantenido mejor.
Porque en esto, como en muchas otras cosas,
él es más digno de elogio por lo que derribó de Babilonia que por lo que él mismo edificó.

Los Protestantes dicen que "`obtienen la remisión de sus
pecados y están justificados ante la vista de Dios,
en virtud de los méritos y sufrimientos de Cristo;
no por la infusión de Su justicia en ellos, sino por el perdón de sus pecados,
y por considerarlos y aceptarlos como justos; no por algo obrado en ellos,
o hecho por ellos,
sino por la imputación de la obediencia y satisfacción de Cristo a través de la fe;
fe que no tienen por sí mismos, pues es don de Dios.`"^
footnote:[Así dice la Confesión de Fe de Westminster, capítulo 11, sección 1.]

Por lo tanto, vemos que la justificación tanto de católicos como de protestantes,
no se basa en alguna renovación interna de la mente,
ni en la virtud de algún nacimiento o formación espiritual de Cristo dentro de ellos,
sino sólo en una simple aplicación de Su muerte y sufrimientos
que fueron realizados externamente por ellos.
Los protestantes se aferran a una fe que les es dada,
y esperan ser justificados únicamente por ella;
los católicos esperan hacer que la muerte de Cristo sea efectiva para
ellos mediante la realización de algunas oraciones y ceremonias externas.
Yo reconozco, sin embargo (porque no quiero agraviar a nadie),
que algunas cosas mejores se han dicho en cuanto a la necesidad
de la santidad interna por algunos católicos y protestantes modernos
que se han acercado más a la Verdad (tal como aparecerá más adelante,
en algunas citas de sus escritos).

=== Nuestra Postura en Este Asunto

En primer lugar,
renunciamos a la idea de que exista algún poder o habilidad natural en
nosotros mismos que nos pueda sacar de nuestra condición perdida y caída,
es decir, de nuestra primera naturaleza;
y confesamos que no somos capaces de hacer nada bueno por nosotros mismos.
Además,
afirmamos que somos completamente incapaces de obtener la remisión
de pecados o la justificación por cualquier acto propio,
de manera que la merezcamos o que se nos conceda como una deuda que Dios nos debe.
Por el contrario, reconocemos que todo es por causa de Su amor y que proviene de él,
porque Su amor es el origen y la causa fundamental de nuestra aceptación.

En segundo lugar,
Dios manifestó este amor para con nosotros al enviar al mundo a Su amado Hijo,
el Señor Jesucristo,
quien se entregó a Sí mismo por nosotros como una ofrenda y sacrificio a Dios,
en olor fragante, haciendo la paz mediante la sangre de Su cruz,
para reconciliarnos con Él. Jesucristo, mediante el Espíritu Eterno,
se ofreció a Sí mismo sin mancha a Dios, y sufrió por nuestros pecados,
el justo por los injustos, para llevarnos a Dios.

En tercer lugar,
en vista de que todos los hombres (que han llegado a la madurez) han pecado--con
la única excepción del Hombre Jesús--todos necesitan a este Salvador,
para quitar de ellos la ira de Dios debido a sus ofensas.
En este sentido,
está escrito que Él verdaderamente "`llevó nuestros pecados en Su cuerpo sobre el madero,`"^
footnote:[1 Pedro 2:24]
y por lo tanto, es el único Mediador, tras haber aplacado la ira de Dios hacia nosotros,
de modo que nuestros pecados pasados ya no se interponen en nuestro camino,
pues en virtud de Su muy satisfactorio sacrificio, fueron removidos y perdonados.
Y en verdad, la remisión de los pecados no debe esperarse,
buscarse ni obtenerse de ninguna otra manera,
ni por ninguna otra obra o sacrificio (aunque, como se dijo anteriormente,
algunos que no conocen la historia, pueden llegar a participar de esta remisión).

Así pues, Cristo nos reconcilia con Dios por medio de Su muerte y sufrimientos,
aun cuando somos enemigos; es decir, Él ofrece al mundo la reconciliación,
nos pone en la posibilidad de ser reconciliados,
Dios está dispuesto a perdonar nuestras iniquidades y a aceptarnos,
como bien lo expresa el apóstol: "`Dios estaba en Cristo reconciliando consigo al mundo,
no tomándoles en cuenta a los hombres sus pecados,
y ha puesto en nosotros la palabra de reconciliación.`"^
footnote:[2 Corintios 5:19 Traducción Literal.
Nota del Editor:
La mayoría de las traducciones modernas se leen "`nos encargó a nosotros la palabra
(o mensaje) de la reconciliación.`" Pero el griego se lee "`ha puesto en nosotros
// lint-disable invalid-characters
la palabra de reconciliación.`" θέμενος ἐν ἡμῖν τὸν λόγον τῆς καταλλαγῆς]
Y por eso el apóstol, en los siguientes versículos, les ruega, "`en nombre de Cristo:
Reconciliaos con Dios;`" dando a entender,
que la ira de Dios ha sido removida por la obediencia de Jesucristo,
que ahora Dios está dispuesto a reconciliarse con ellos,
y que está listo para remitir los pecados pasados, si se arrepienten.

Nosotros, por lo tanto, consideramos nuestra redención en un doble aspecto o estado,
ambos perfectos en su propia naturaleza, aunque en su aplicación a nosotros,
el uno no puede estar sin relación con el otro, como se observará.

El primer aspecto, pues,
es la redención que Cristo realizó y consumó _por nosotros_ en Su cuerpo crucificado,
fuera de nosotros.
El otro es la redención que obra Cristo _dentro de nosotros,_
la cual no es menos apropiadamente llamada y considerada una redención, que la primera.
El primero es aquel por el cual el hombre, estando en su condición caída,
es puesto en capacidad de ser salvo, y se le ha transmitido una medida de ese poder,
virtud, espíritu, vida y gracia que estaban en Jesucristo; medida que,
como don gratuito de Dios,
es capaz de vencer y desarraigar la semilla maligna con la cual estamos
leudados naturalmente desde la caída. El segundo es aquel mediante el
cual experimentamos y conocemos esta redención pura y perfecta en nosotros,
purificando, limpiando y redimiéndonos del poder de la corrupción,
y llevándonos a la unidad, favor y amistad con Dios.^
footnote:[Nota del Editor: Véase también Efesios capítulo 1,
donde Pablo escribe primero (versículo 7), "`en quien __tenemos redención__ por Su sangre,
el perdón de pecados según las riquezas de Su gracia;`" y luego
(versículo 14) declara que el Espíritu Santo es "`las arras de
nuestra herencia __hasta la redención__ de la posesión adquirida.`"]

Por el primero de estos dos aspectos, nosotros, que estábamos perdidos en Adán,
hundidos en la semilla amarga y corrupta,
incapaces por nosotros mismos de hacer algo bueno,
sino más bien naturalmente ligados y unidos al mal, prontos y propensos a toda iniquidad,
siervos y esclavos del poder y espíritu de las tinieblas, somos, a pesar de todo esto,
reconciliados con Dios por la muerte de Su Hijo cuando aún éramos enemigos,
al punto de ser puestos en capacidad de ser salvos,
y ofrecidos a las buenas nuevas del Evangelio de paz, a saber,
que Dios se ha reconciliado con nosotros en Cristo, y así nos llama e invita a Sí mismo.
En este aspecto de nuestra redención, es que entendemos las siguientes Escrituras:
"`Habiendo abolido en Sí mismo la enemistad;`"^
footnote:[Efesios 2:14-15 RV1602P]
"`Él nos amó primero;`"^
footnote:[1 Juan 4:19]
"`Viéndonos sucios en nuestras sangres, nos dijo: ¡Vive!;`"^
footnote:[Ezequiel 16:6]
"`Quien llevó Él mismo nuestros pecados en su cuerpo sobre el madero;`"^
footnote:[1 Pedro 2:24]
y "`también Cristo padeció una sola vez por los pecados, el justo por los injustos;`"^
footnote:[1 Pedro 3:18]
etc.

Por el segundo aspecto, experimentamos que esta capacidad comienza a actuar,
por medio de la cual,
si recibimos y no resistimos lo que Él compró con Su muerte (a saber, la Luz,
Espíritu y Gracia de Cristo revelada en nosotros),
atestiguamos y poseemos una redención real,
verdadera e interna del poder y dominio del pecado,
y así llegamos a ser verdadera y realmente redimidos, justificados y hechos justos,
y a experimentar una unión y amistad con Dios.
Así Él "`se dio a Sí mismo por nosotros para redimirnos de toda iniquidad,
y purificar para Sí un pueblo peculiar;`"^
footnote:[Tito 2:14 RVG]
y así "`lo conocemos, y el poder de Su resurrección, y la comunión de Sus padecimientos,
siendo hechos conforme a Su muerte.`"^
footnote:[Filipenses 3:10]
Este último aspecto sigue en orden al primero, y es consecuencia de él,
ya que procede del primero, como un efecto procede de su causa.
De modo que,
de la misma manera que nadie puede disfrutar del último sin que
el primero haya sido establecido (siendo esto la voluntad de Dios);
asimismo, nadie puede participar realmente del primero,
salvo en la medida que experimente el último.
Así que, para nosotros, ambos aspectos son causas de nuestra justificación.

Ahora bien, nosotros no entendemos por justificación la mera producción de buenas obras,
incluso las obras que vienen del Espíritu de Cristo;
porque estas (como afirman correctamente los protestantes)
son más un efecto de la justificación que la causa de ella.
En su lugar, entendemos esta justificación como la formación de Cristo en nosotros,
Cristo nacido y engendrado en nosotros, de donde proceden naturalmente las buenas obras,
así como procede el fruto de un árbol fructífero.
Este nacimiento interno en nosotros, que produce justicia y santidad en nuestro interior,
es lo que nos justifica,
ya que luego de haber removido y eliminado la naturaleza
y el espíritu contrarios que reinaban y traían condenación,
ahora ejerce dominio sobre todo en nuestros corazones.
Entonces, aquellos que llegan a experimentar a Cristo así formado en ellos,
disfrutan de Él plena e indivisiblemente, quien es "`el Señor justicia nuestra.`"^
footnote:[Jeremías 23:6]
Esto es lo que significa ser revestidos de Cristo y estar cubiertos por Él,
y a estos Dios en verdad los considera justos y rectos.

Esto difiere mucho de la doctrina de los católicos,
porque la causa formal de la justificación no son
las obras (siendo éstas sólo un efecto de ella),
sino más bien un nacimiento interior, Jesucristo engendrado en el corazón,
quien es el amado, a quien el Padre no puede sino aceptar,
junto con todos aquellos que están rociados con la
sangre de Jesús y verdaderamente lavados con ella.
Y por esto, (es decir,
por habernos revestido de Cristo internamente) también
experimentamos a Cristo comunicándonos Sus bienes,
por medio de lo cual llegamos "`a ser participantes de la naturaleza divina,`"^
footnote:[2 Pedro 1:4]
como dice Pedro, a ser hechos uno con Él, como el pámpano con la vid,
y así tener un título y derecho a todo lo que Él ha hecho y sufrido por nosotros.
De esta manera, Su obediencia se vuelve nuestra, Su justicia nuestra,
Su muerte y sufrimientos nuestros.
Y por esta cercanía a Él, a menudo llegamos a tener un sentido de Sus sufrimientos,
y de hecho,
sufrimos con Su Semilla que aún yace oprimida y crucificada en los corazones
de los impíos. Así nosotros sufrimos dolores de parto con Ella,
y por Su redención,
y por el arrepentimiento de esas almas que todavía están crucificando al Señor
de gloria--así como el apóstol Pablo escribe que con sus sufrimientos,
"`cumplo lo que falta de las aflicciones de Cristo por Su cuerpo, que es la iglesia,`"^
footnote:[Colosenses 1:24]
aunque esto sea un misterio sellado para todos los sabios,
que aún son ignorantes de esta Semilla en ellos mismos, y se oponen a Ella.

Finalmente,
aunque colocamos la remisión de los pecados en la justicia y obediencia de Cristo
realizadas por Él durante Su tiempo en la carne (como la causa principal),
y sostenemos que somos realmente justificados por
Cristo Jesús formado y engendrado en nosotros;
aun así, no podemos excluir las obras de la justificación,
como algunos protestantes han hecho imprudentemente.
Porque aunque, para hablar correctamente, no somos justificados _por_ ellas,
aun así somos justificados _en_ ellas, y por lo tanto son necesarias.
Negar esto no sólo es contrario al testimonio de las Escrituras,
sino que además ha causado un gran escándalo en la religión de los protestantes,
ha abierto las bocas de los acusadores,
y ha hecho que muchos sientan una seguridad falsa en una justificación sin buenas obras.
Además, aunque no es seguro decir que las buenas obras son meritorias,
aun así las Escrituras muestran claramente que son recompensadas,
de modo que muchos de los llamados Padres de la Iglesia,
no han tenido miedo de usar la palabra "`mérito`" en un
sentido limitado (aunque no como lo hacen los católicos).
Sin embargo, la mayoría de los protestantes no sólo niegan la necesidad de buenas obras,
sino que algunas veces no les avergüenza llamarlas dañinas,
diciendo a menudo que las mejores obras, incluso las de los santos,
son inmundas y corruptas.
Ahora bien,
aunque nosotros juzgamos que esto es cierto respecto
a las mejores obras hechas _por el hombre,_
que intenta conformarse a la ley externa por su propia fuerza y en su propia voluntad,
aun así,
creemos que las obras que proceden naturalmente de este
nacimiento espiritual y de Cristo formado en nosotros,
son puras y santas, así como la raíz de la cual surgen es pura.
Por esta razón Dios las acepta, nos justifica en ellas y nos recompensa por ellas,
por Su propia gracia gratuita.

=== La Prueba de Nuestra Postura

Habiendo descrito así el estado de la controversia,
deben probarse ahora las siguientes proposiciones:

[.numbered-group]
====

[.numbered]
_Primera proposición:_ Que la obediencia,
los sufrimientos y la muerte de Cristo es aquello
por lo cual el alma obtiene la remisión de los pecados,
y es también la causa procuradora de esa gracia por cuyas
obras internas Cristo llega a ser formado internamente,
y el alma hecha conforme a Él, y así hecha justa y justificada.
Por lo tanto, es con respecto a esta capacidad y oferta de gracia,
que se dice que Dios se ha "`reconciliado`" con nosotros;
aunque no en el sentido de estar realmente unido a nosotros,
o de considerar realmente a alguien justo o justificado
mientras todavía viva en sus pecados,
y continúe siendo impuro e injusto.

[.numbered]
_Segunda proposición:_
Que es por este nacimiento interno de Cristo en el hombre que somos hechos justos,
y por lo tanto, considerados así por Dios.
De modo que, para hablar claramente,
no somos verdaderamente justificados ante los ojos de Dios,
hasta que Cristo sea engendrado en nosotros; porque en las Escrituras,
el término justificación se usa más correcta y frecuentemente,
según su verdadero significado, que es:
"`hacer justo,`" y no simplemente considerar a alguien justo.

[.numbered]
_Tercera proposición:_
Que dado que las buenas obras fluyen naturalmente
de este nacimiento (como el calor del fuego),
son, por lo tanto, absolutamente necesarias para la justificación;
no como la causa de ella, sino como aquello en lo que somos justificados,
y sin lo cual no podemos ser justificados.
Y aunque estas buenas obras no son meritorias, ni imponen deuda alguna sobre Dios,
Él no puede sino aceptarlas y recompensarlas,
porque es contrario a Su naturaleza negar lo Suyo,
especialmente cuando estas pueden ser perfectas según su género,
al proceder de un nacimiento y raíz puros y santos.
Por lo tanto, es falso y contrario a la Verdad sugerir,
que las obras más santas de los santos están contaminadas
y que son pecaminosas ante los ojos de Dios;
porque las buenas obras que fluyen del nacimiento espiritual no son las obras de la ley,
las cuales el apóstol excluyó de la justificación.

====

=== En Cuanto a la Primera Proposición: La Obra de Cristo

_Primero;_ la puedo demostrar a partir de Romanos 3:25 que dice:
"`A quien Dios puso como propiciación por medio de la fe en su sangre,
para manifestar su justicia, a causa de haber pasado por alto, en su paciencia,
los pecados pasados.`"
Aquí el apóstol expone el alcance y la eficacia de la muerte de Cristo,
mostrando que por ella y por la fe en ella,
se obtiene la remisión de los pecados pasados;
y que en esto se manifiesta la paciencia de Dios para con la humanidad.
De modo que,
aunque los hombres merecen la muerte eterna por los pecados que cometen diariamente,
en virtud de ese muy satisfactorio sacrificio de Cristo Jesús,
la gracia y semilla de Dios se mueven por amor a ellos durante el día de su visitación,
buscando redimirlos del mal.

_Segundo;_ si Dios estuviera perfectamente reconciliado con los hombres,
y los estimara justos cuando en realidad son injustos y continúan en sus pecados,
entonces Él no tendría ninguna controversia con ellos.
Pero entonces,
cuál es la razón por la que a lo largo de todas las Escrituras Él se queja y razona
tan frecuentemente con aquellos que nuestros adversarios afirman que están justificados,
diciéndoles que "`sus iniquidades han hecho división entre ellos y su Dios.`"^
footnote:[Isaías 59:2]
Porque donde hay una perfecta y completa reconciliación,
no existe división. Pero sugerir que los hombres
pueden estar reconciliados plenamente con Dios,
incluso mientras continúan en sus pecados,
necesariamente implica que el pecado no hace la más mínima división entre ellos y Dios,
y que el hombre es justificado _en sus pecados._
Y a esto le seguiría la más abominable consecuencia,
que las buenas obras y los grandes pecados son lo mismo ante los ojos de Dios,
ya que ninguno sirve para justificar, ni para romper la reconciliación con Dios.
En verdad,
tal doctrina abre una puerta para la seguridad falsa y para toda práctica inmoral.

_Tercero;_ esto anularía toda la doctrina práctica del evangelio,
y haría completamente innecesarias cosas tales como la fe, el arrepentimiento,
la obediencia y las otras condiciones que son nuestro deber cumplir^
footnote:[Nota del Editor:
Estas se realizan en la gracia que nos llega a través del pacto,
como se mencionó anteriormente.]. Y ciertamente,
estas condiciones son de una naturaleza tal, que no se pueden cumplir de una sola vez,
sino que deben cumplirse durante toda la vida.
Pero si nosotros ya estamos reconciliados y justificados perfectamente
antes de que estas condiciones hayan sido cumplidas,
entonces no podría decirse que son necesarias,
lo cual es contrario al claro testimonio de las Escrituras
que todos los cristianos reconocen.
Porque leemos: "`Sin fe es imposible agradar a Dios;`"^
footnote:[Hebreos 11:6]
y "`porque si vivís conforme a la carne, moriréis;
más si por el Espíritu hacéis morir las obras de la carne, viviréis;`"^
footnote:[Romanos 8:13]
y el Señor les dijo a los que ya estaban convertidos: "`quitaré tu candelero de su lugar,
si no te arrepientes;`"^
footnote:[Apocalipsis 2:5 LBLA]
y Pablo clamó: "`Vosotros corríais bien;
¿quién os estorbó para no obedecer a la verdad?`"^
footnote:[Gálatas 5:7]
Si mencionara todas las Escrituras que prueban esto de manera positiva y evidente,
tendría que trascribir casi toda la parte doctrinal de la Biblia.
Porque Cristo dijo: "`Consumado es,`"^
footnote:[Juan 19:30]
y Él ciertamente terminó Su obra hace más de mil seiscientos años,
ofreciendo Su cuerpo como sacrificio por el pecado,
abriendo una puerta de misericordia para todos,
y comunicando una medida de Su gracia por medio de la cual todos pueden ver sus pecados,
tener la capacidad de arrepentirse,
y así experimentar en el presente Su obra interna de redención,
reconciliación y justificación. Pero si al decir:
"`Consumado es,`" se entiende que Él ha perfeccionado
y finalizado la redención del hombre,
y reconciliado completamente a todos los que serán salvos (ya sea antes de creer,
como algunos dicen, o después de confesar la verdad de la historia de Cristo,
o de ser rociados con agua, etc.) aún cuando continúen en sus pecados,
entonces toda la parte doctrinal de la Biblia es inútil y de ningún provecho.
En vano fueron enviados los apóstoles a predicar el evangelio;
en vano las Escrituras nos advierten que no nos desviemos,
que no hagamos nula la gracia de Dios, que no perdamos nuestro primer amor,
que no permitamos que nuestros corazones se endurezcan
y así quedemos cortos de nuestro descanso,
etc. y en vano todos los predicadores cristianos realizan su labor,
gastan sus pulmones y producen escritos,
sólo para hacer lo que ya está hecho perfectamente sin ellos.

Por último,
esta doctrina también hace nula la intercesión presente de Cristo por los hombres.
Porque ¿qué sería de ese gran artículo de fe por el cual afirmamos,
que "`Él está a la diestra de Dios, intercediendo diariamente por nosotros?`"^
footnote:[Romanos 8:34]
Y ¿con qué fin "`el Espíritu mismo intercede por nosotros con gemidos indecibles?`"^
footnote:[Romanos 8:26-27]
Porque es absurdo interceder por los que no tienen posibilidad de ser salvos.
Y es inútil orar por los que ya están reconciliados y perfectamente justificados.
En verdad, no veo una manera real de resolver esto,
excepto reconociendo la verdad del asunto, a saber: que Cristo, por Su muerte,
removió la ira de Dios hasta el punto de obtener la remisión de los pecados
para todos los que reciban la Gracia y Luz que Él les comunica,
y que ha comprado para ellos con Su sangre.
A medida que ellos creen en esto,
llegan a experimentar la remisión de sus pecados pasados
y el poder que los salva del dominio del pecado,
porque a "`todos los que lo reciben, les da el poder de llegar a ser hijos de Dios.`"^
footnote:[Juan 1:12 NBLH]
Estos también experimentan Su poder para borrar cualquier pecado presente,
en el cual puedan caer por no velar o por debilidad, si entregándose a esta gracia,
se arrepienten verdaderamente.
Entonces, ninguno es hijo, ninguno es justificado, ninguno es reconciliado,
hasta que recibe a Cristo en esa pequeña Semilla en su corazón;
y así se les ofrece la vida eterna "`a los que, perseverando en bien hacer,
buscan gloria y honra e inmortalidad.`"^
footnote:[Romanos 2:7]
Porque, según el profeta, "`si el justo se aparta de su justicia,
ninguna de las obras justas que ha hecho le serán recordadas.`"^
footnote:[Ezequiel 18:24 LBLA]
En consecuencia, ninguno permanece como hijo de Dios,
ni permanece justificado ante los ojos de Dios,
a menos que pacientemente persevere en la justicia y en bien hacer.
Y por eso Cristo vive perpetuamente,
para interceder durante el día de la visitación de cada hombre, para que se convierta.
Y cuando ha crecido en alguna medida en la vida, Él intercede para que continúe, avance,
no desmaye, ni se vuelva atrás. Se podría decir mucho más para confirmar esta verdad,
pero a continuación señalo las objeciones comunes en contra de ella.

=== Objeciones y Respuestas

[.discourse-part]
Objeción:
La primera y principal objeción es sacada de la afirmación del apóstol antes mencionada:
Dios "`nos ha reconciliado consigo mismo por Jesucristo; a saber,
Dios estaba en Cristo reconciliando el mundo consigo mismo,
no imputándoles sus pecados.`"^
footnote:[2 Corintios 5:18-19 RV1602P]
De aquí se deduce que Cristo perfeccionó por completo
la obra de reconciliación mientras estuvo en la tierra.

[.discourse-part]
Respuesta: Si por "`reconciliación`" se entiende la remoción de la ira,
y la compra de esa Gracia por medio de la cual podemos llegar
a ser completamente reconciliados y unidos con Dios,
entonces estamos de acuerdo.
Pero que el versículo no dice nada más que esto, se desprende del versículo mismo;
porque cuando el apóstol habla en pretérito perfecto diciendo: "`nos ha reconciliado`",
habla de sí mismo y de los santos,
quienes habiendo recibido la Gracia de Dios que Cristo compró,
fueron realmente reconciliados por medio de la fe en Él. Pero con respecto a los demás,
habla de la "`Palabra de reconciliación`" que fue "`puesta en ellos;`"^
footnote:[2 Corintios 5:19 Traducción Literal.
Nota del Editor: La mayoría de las traducciones modernas dicen:
"`nos encargó a nosotros la palabra de la reconciliación.`" Pero el griego dice "`poniendo
// lint-disable invalid-characters
en nosotros la Palabra de reconciliación`" -- θέμενος ἐν ἡμῖν τὸν λόγον τῆς καταλλαγῆς]
y en el siguiente versículo dice: "`Así que embajadores somos de Cristo,
como si Dios os rogase por nosotros; os rogamos en nombre de Cristo:
Reconciliaos con Dios.`"^
footnote:[2 Corintios 5:20 RV1602P]
Ahora bien, si su reconciliación ya se había llevado a cabo perfectamente,
¿qué necesidad habría de que alguien les rogará que se reconciliaran?
Los embajadores no son enviados después de que la paz ya
se ha establecido y se ha hecho la reconciliación,
sino para rogar la reconciliación.

[.discourse-part]
Objeción: En segundo lugar, objetan (a partir del versículo 21 del mismo capítulo):
"`Al que no conoció pecado, por nosotros lo hizo pecado,
para que nosotros fuésemos hechos justicia de Dios en Él.`" De aquí argumentan,
que así como nuestro pecado le es imputado a Cristo, quien no tenía pecado,
de la misma manera la justicia de Cristo nos es imputada,
sin que seamos realmente justos.

[.discourse-part]
Respuesta: Pero esta interpretación es fácilmente rechazada;
porque el apóstol mismo demuestra en múltiples ocasiones,
que nosotros tenemos que ser hechos _realmente_ justos por Cristo,
y no simplemente imputados o considerados justos.
De hecho, esto se ve en lo que se dice en los versículos 14-16 del siguiente capítulo,
donde él ampliamente argumenta en contra de cualquier
supuesto acuerdo entre la luz y las tinieblas,
o entre la justicia y la injusticia.
Pero si los hombres han de ser considerados injertados en Cristo,
y miembros verdaderos de Él, simplemente porque les es imputada una justicia externa,
mientras ellos mismos continúan en su injusticia,
¿no implicaría esto una comunión entre la justicia y la injusticia?
En efecto,
debería considerarse extraño cómo muchos han hecho de esta "`justicia
imputada`" un artículo tan fundamental de su fe,
a pesar de ser tan contrario a toda la tendencia del Evangelio.
Porque Cristo nunca deseó, en ninguno de Sus sermones y discursos piadosos,
que Sus oyentes pusieran su confianza en tal cosa,
sino que siempre los dirigió a la verdadera santificación,
a limpiar el vaso por dentro y por fuera, y a las buenas obras que glorifican al Padre,
diciendo: "`Sed, pues, vosotros perfectos,
como vuestro Padre que está en los cielos es perfecto.`"^
footnote:[Mateo 5:48]

=== En Cuanto a la Segunda Proposición: La Verdadera Justificación--Cristo Formado en el Interior

Paso entonces a la segunda proposición que debe ser probada, a saber:
Que es por este nacimiento interno, o por Cristo formado dentro de nosotros,
que somos formalmente (por así decirlo) justificados ante los ojos de Dios.
Supongo que ya he dicho lo suficiente para demostrar cuánto reconocemos la muerte y
los sufrimientos de Cristo como la ofrenda por la que se satisface la justicia de Dios,
se obtiene remisión de pecados,
y se compra la Gracia y Semilla de la que procede este nacimiento.
Queda por probar, que es por Cristo Jesús formado en nosotros que somos justificados,
o _hechos verdaderamente justos._
Tengan en cuenta que aquí uso el término "`justificación`" en este sentido.

Entonces,
primero pruebo esto con la Escritura del apóstol Pablo en 1 Corintios 6:11 que dice:
"`Y esto erais algunos; mas ya habéis sido lavados, ya habéis sido santificados,
ya habéis sido justificados en el nombre del Señor Jesús,
y por el Espíritu de nuestro Dios.`"
Aquí la palabra "`justificados`" debe necesariamente
significar ser hechos realmente justos,
y no simplemente ser imputados como tal; de lo contrario,
"`santificados`" y "`lavados`" podrían considerarse también como una mera imputación,
lo cual anularía toda la intención del contexto.
Porque en los versículos anteriores,
el apóstol les advierte a sus lectores que no se dejen engañar,
porque "`los injustos no heredarán el reino de Dios;`"^
footnote:[1 Corintios 6:9 NBLH]
y después de especificar varios tipos de iniquidad, concluye diciendo,
"`esto erais algunos de vosotros;`" es decir, que ya no lo son.
Y así, tras haber sido lavados y santificados, fueron verdaderamente justificados.
Por mi parte, no veo,
ni jamás he oído o leído nada que sugiera que la palabra "`justificados`" en este lugar
deba entenderse de otra manera que no sea según su apropiado y genuino significado,
que es: _ser hechos justos._

Ahora bien,
esta palabra "`justificar,`" que se deriva del sustantivo "`justicia,`"
o del adjetivo "`justo,`" sin lugar a duda significa hacer justo,
porque no es más que la composición del verbo _facio_ y del adjetivo _justus,_
que forman _justifico,_ o _hago justo._
De la misma manera, la palabra "`justificado`" proviene de _justus_ y _fio,_
que significa _me vuelvo justo._
Lo mismo ocurre con otros verbos de este tipo,
como _santifico_ que proviene de _sanctus_ (santo) y _facio,_ que significa _hago santo._
En cada caso se entiende que el sujeto está real y verdaderamente
dotado con esa virtud y cualidad de la que se deriva el verbo.
Porque así como no se dice que alguien está santificado cuando realmente no es santo;
así tampoco puede decirse que alguien está justificado, mientras siga siendo injusto.

Sin embargo, este verbo "`justificar`" ha sido usado, de manera metafórica y figurativa,
en un sentido legal,
como cuando un hombre realmente culpable de un crimen
es liberado del castigo de su pecado,
y se dice que está justificado, es decir, puesto en el lugar del justo,
como si fuera justo.
¿Pero no es extraño que los hombres sean tan superficiales en un asunto tan importante,
como para edificar el fundamento de su aceptación delante de Dios
sobre un simple significado prestado y metafórico de esta palabra,
excluyendo así (o al menos estimando innecesaria)
esa santidad sin la cual las Escrituras dicen:
"`nadie verá a Dios`"?^
footnote:[Hebreos 12:14]
De hecho,
¿no sería un gran error contentarnos con una justificación
imaginaria mientras Dios requiere una real?
Y téngase en cuenta, que en las cartas a los Romanos, Corintios,
Gálatas y en otros lugares en donde el apóstol trata este tema,
la palabra puede tomarse en su propio significado, sin cometer ninguna insensatez.
Por ejemplo, en sus epístolas a los Romanos y a los Gálatas,
Pablo afirma que ningún hombre puede ser justificado por la ley de Moisés,
ni por las obras de la ley.^
footnote:[Romanos 3:28; Gálatas 2:16, 3:11]
No es absurdo ni peligroso entenderla aquí según su significado correcto, es decir,
que un hombre no puede ser hecho justo por la ley de Moisés; especialmente,
cuando vemos cuán bien concuerda esto con lo dicho por el mismo apóstol:
"`La ley nada hace perfecto.`"^
footnote:[Hebreos 7:19 LBLA]
Además, donde está escrito que "`el hombre es justificado por fe,`"^
footnote:[Romanos 3:28; Gálatas 3:24]
puede entenderse muy bien como ser hecho justo,
puesto que también está escrito que la fe "`purifica el corazón;`"^
footnote:[Hechos 15:9]
y sin ninguna duda, los puros de corazón son justos, y "`el justo por la fe vivirá.`"^
footnote:[Habacuc 2:4; Romanos 1:17; Gálatas 3:11; Hebreos 10:38]
Nuevamente, donde está escrito que somos "`justificados por Su gracia,`"^
footnote:[Romanos 3:24; Tito 3:7]
o "`justificados por Cristo,`"^
footnote:[Gálatas 2:17]o "`justificados por el Espíritu;`"^
footnote:[1 Corintios 6:11]
no es de ninguna manera absurdo entender la palabra justificados como ser hechos justos,
ya que por Su Espíritu y gracia Él realmente hace a los hombres justos.
Pero entenderla universalmente de la otra manera, como una mera aceptación legal,
ocasionaría grandes incoherencias como podría probarse ampliamente;
pero debido a que considero que esto será reconocido,
me abstengo en este momento en aras de la brevedad.

Pero además,
en los lugares más importantes donde las Escrituras usan la palabra "`justificar,`"
nuestros adversarios no pueden sino reconocer que debe entenderse como hacer justo,
y no como una simple aceptación legal.
Esto lo hemos visto en 1 Corintios 6:11, que dice: "`Mas ya habéis sido lavados,
ya habéis sido santificados, ya habéis sido justificados.`"
Pero también lo vemos en Tito 3:5-7 que dice: "`Nos salvó,
no por obras de justicia que nosotros hubiéramos hecho, sino por su misericordia,
por el lavamiento de la regeneración y por la renovación en el Espíritu Santo,
el cual derramó en nosotros abundantemente por Jesucristo nuestro Salvador,
para que justificados por su gracia,
viniésemos a ser herederos conforme a la esperanza de la vida eterna.`"
Y también en esa excelente afirmación del apóstol en Romanos 8:30, "`a los que llamó,
a éstos también justificó; y a los que justificó,
a éstos también glorificó.`" Esto es comúnmente llamado la "`cadena de oro,`" y todos
reconocen que comprende el método y orden de la salvación. Pero si "`justificó`" no
se entendiera aquí en su significado apropiado--es decir,
realmente ser hecho justo--entonces un verdadero cambio de la iniquidad
a la santidad quedaría completamente excluido de esta cadena.
Pero efectivamente (como la mayoría reconoce), el apóstol, en esta descripción abreviada,
usa la palabra "`justificó`" para abarcar todo lo que viene entre el llamado y la glorificación,
dando a entender que ser hechos realmente justos es la manera
por la que pasamos del llamado a la glorificación.

De hecho, muchos padres de la Iglesia y protestantes famosos dicen lo mismo.
Beza dice: "`Yo considero el término justificación de manera general,
como el que abarca todo lo que adquirimos de Cristo,
ya sea por imputación o por la eficacia del Espíritu al santificarnos.
Así también debe entenderse la palabra justificación en Romanos 8:30.`"^
footnote:[In cap. 3. Ad Tit. Ver. 7.]
Melanchthon dice: "`Ser justificados por fe no sólo significa ser declarados justos,
sino también, de injustos ser hechos justos.`"^
footnote:[En Apol. Confess. Aug.]
Además, algunos prominentes protestantes, aunque no tan claramente,
han insinuado nuestra doctrina,
por la cual atribuimos a la muerte de Cristo la remisión de los pecados,
y la obra de justificación a la gracia del Espíritu adquirida mediante Su muerte.
Martin Borrhaus, en su comentario de Romanos 4:25 donde dice:
"`el cual fue entregado por nuestras transgresiones,
y resucitado para nuestra justificación,`" explica: "`Aquí se ven dos cosas en Cristo,
las cuales son necesarias para nuestra justificación; una es Su muerte,
la otra es Su resurrección de entre los muertos.
Por Su muerte, los pecados de este mundo fueron expiados.
Por Su resurrección de entre los muertos,
le plació a la misma bondad de Dios dar el Espíritu Santo,
por el cual se cree el Evangelio y se restaura la
justicia que se perdió por la caída del primer Adán.`"^
footnote:[En Gen. Cap. 15. Ad verb. Cred dit Abraham Deo+++.+++, p. 161]
Y más adelante dice: "`El apóstol expresa ambas partes en estas palabras,
'`el cual fue entregado por nuestras transgresiones,
y resucitado para nuestra justificación.`' En Su muerte se ve la expiación por el pecado;
en Su resurrección se ve el don del Espíritu Santo,
por el cual nuestra justificación es perfeccionada.`"^
footnote:[Lib. 3. Reg. Cap. 9. Ver. 4., p. 681]
William Forbes, obispo de Edinburgh, dice:
"`Siempre que la Escritura hace mención de la justificación ante Dios,
parece que la palabra justificar no sólo significa declarar justo, en un sentido legal,
sino también real e íntegramente hacer justo;
porque Dios justifica de forma diferente a los jueces terrenales.
En efecto,
tanto las Escrituras como los Padres afirman que en la justificación de un pecador,
sus pecados no sólo son remitidos, perdonados, cubiertos y no imputados,
sino también quitados, borrados, limpiados, lavados,
purificados y removidos muy lejos de nosotros,
tal como aparece en muchos lugares de las Sagradas Escrituras.`"^
footnote:[In considerat. modest. de Just. lib. 2. Sect. 8.]

=== La Revelación de Jesucristo en el Alma

Habiendo demostrado suficientemente que la palabra "`justificación`"
debe entenderse como ser realmente hechos justos,
ahora afirmo con confianza (no a partir de un conocimiento teórico,
sino de la experiencia verdadera,
interna y viva de la cosa misma) que la revelación
de Jesucristo en el alma es la causa inmediata,
directa o formal de la justificación de los hombres ante los ojos de Dios,
la cual cambia, reforma y renueva la mente.
Es por medio de Él (el Autor de esta obra interior),
revelado y formado así dentro de nosotros,
que somos verdaderamente justificados y aceptados ante los ojos de Dios.
Porque es en la medida que somos cubiertos y revestidos
de Aquel en quien el Padre siempre se complace,
que podemos acercarnos a Dios y presentarnos con confianza delante de Su trono,
siendo purificados por la sangre de Jesús derramada internamente en nuestras almas,
y revestidos con Su vida y justicia allí reveladas.
Y este es el orden y método de salvación que el apóstol expone en esa afirmación divina:
"`Porque si siendo enemigos, fuimos reconciliados con Dios por la muerte de su Hijo,
mucho más, estando reconciliados,
seremos salvos por su vida`" (Romanos 5:10). Aquí el apóstol primero
habla de la reconciliación llevada a cabo por la muerte de Cristo
(en la que Dios está cerca para recibir y redimir al hombre),
y luego de la salvación de los hombres y de la verdadera justificación
llevada a cabo por la vida de Jesús. Ahora bien,
esta vida es algo interno y espiritual revelada en el alma,
por la que el alma es renovada y sacada de la muerte
(donde naturalmente ha estado por la caída),
y así vivificada y resucitada para Dios.

Los apóstoles hablan frecuentemente de esta vida salvadora,
encomendando a todos los discípulos a la operación interna de su poder.
Pablo, al despedirse de los efesios dice: "`Y ahora, hermanos, os encomiendo a Dios,
y a la palabra de su gracia,
que tiene poder para sobreedificaros y daros herencia con todos los santificados.`"^
footnote:[Hechos 20:32]
Y en su carta a ellos les habla de "`la supereminente
grandeza de Su poder para con nosotros los que creemos.`"^
footnote:[Efesios 1:19]
Santiago dirige a sus lectores a "`la palabra implantada,
la cual puede salvar vuestras almas.`"^
footnote:[Santiago 1:21]
En otro lugar Pablo escribe: "`aun estando nosotros muertos en pecados,
nos dio vida juntamente con Cristo (por gracia sois salvos),
y juntamente con él nos resucitó.`"^
footnote:[Efesios 2:5-6]
Ahora bien, este "`dar vida`" y "`resucitar juntamente con él,`" se refiere,
sin ninguna duda, a la obra interna de renovación;
y por esta razón el apóstol menciona aquí que son salvos por gracia,
la cual es la virtud y poder interno de Cristo en el alma.
Además, el apóstol habla de esto en 2 Corintios 4:10:
"`Para que también la vida de Jesús se manifieste
en nuestros cuerpos;`" y en el versículo 11 repite:
"`Para que también la vida de Jesús se manifieste en nuestra carne mortal.`"
Y es por esta vida interior de Jesucristo revelada y formada en
nosotros (como se observó anteriormente) que "`somos salvos.`"

Además, la verdad de que somos justificados por esta revelación de Jesucristo,
y por la nueva creación engendrada en nosotros,
se muestra palpablemente en la excelente afirmación del apóstol en Tito 3:5 donde dice:
"`Nos salvó, no por obras de justicia que nosotros hubiéramos hecho,
sino por su misericordia,
por el lavamiento de la regeneración y por la renovación en el
Espíritu Santo, el cual derramó en nosotros abundantemente por
Jesucristo nuestro Salvador, para que justificados por su gracia,
viniésemos a ser herederos conforme a la esperanza de la vida eterna.`"
Así pues, es evidente que aquello que nos salva también es lo que nos justifica,
siendo estas palabras casi sinónimas en este contexto.
Aquí el apóstol claramente establece que la causa inmediata
de la justificación es esta obra interna de regeneración,
la cual es Jesucristo revelado y formado en el alma;
porque este lavamiento de la regeneración es, sin duda,
el poder y virtud interior por el que el alma es
lavada y revestida de la justicia de Cristo,
con el fin de ser preparada para presentarse delante de Dios.

Esta doctrina también se manifiesta en 2 Corintios 13:5:
"`Examinaos a vosotros mismos si estáis en la fe; probaos a vosotros mismos.
¿O no os conocéis a vosotros mismos, que Jesucristo está en vosotros,
a menos que estéis reprobados?`"
En primer lugar,
aquí se muestra con cuánto fervor quería el apóstol
que ellos conocieran a Cristo dentro de ellos,
porque lo enfatiza tres veces en esta exhortación. En segundo lugar,
hace que la causa de la reprobación (o no-justificación)
sea la falta de Cristo revelado y experimentado en el alma.
De esto se concluye necesariamente,
que dondequiera que Cristo es experimentado internamente,
allí las personas sujetas a Él son aprobadas y justificadas.
Nada podría ser más claro que esto;
porque si tenemos que experimentar a Cristo en nosotros,
para no estar reprobados (o ser personas no justificadas),
entonces los que _sí_ lo experimentan internamente _no_ están reprobados,
y por consiguiente son personas justificadas.
Por esta razón el mismo apóstol dice: "`Hijitos míos,
por quienes vuelvo a sufrir dolores de parto,
hasta que Cristo sea formado en vosotros,`"^
footnote:[Gálatas 4:19]
y usa también este lenguaje: "`Cristo en vosotros, la esperanza de gloria.`"^
footnote:[Colosenses 1:27-28]

Ahora bien, al insistir en esta obra interna,
estamos lejos de negar que el origen y la causa fundamental de nuestra justificación
es el amor de Dios manifestado en la aparición de Jesucristo en la carne,
quien por Su vida, muerte, sufrimientos y obediencia,
abrió un camino para nuestra reconciliación,
al volverse un sacrificio para la remisión de los pecados pasados.
Sin embargo, "`por la justicia de uno vino la gracia a todos los hombres,`"^
footnote:[Romanos 5:18 RVG, RV1602P]
porque Él compró para nosotros Su Semilla y Gracia
de la cual surge este nacimiento interior,
y en la que Jesucristo es recibido, formado y engendrado internamente en nosotros,
en Su imagen pura y santa de justicia.
Sólo por esto nuestras almas viven para Dios, y son revestidas y cubiertas con Él,
tal como lo dice la Escritura (Efesios 4:23-24;
Gálatas 3:27). Somos justificados y salvados en y por Él,
y por Su Espíritu y gracia (Romanos 3:24; 1 Corintios 6:11;
Tito 3:7). De este modo somos hechos partícipes de la plenitud de Sus méritos,
y ciertamente, Su sangre purificadora está cerca para lavar todo pecado y debilidad,
y para sanar todas nuestras rebeliones cada vez que nos volvemos a Él
con un arrepentimiento sincero para ser renovados por Su Espíritu.

Por lo tanto,
los que encuentran a Cristo resucitado y gobernando de esta manera en ellos,
tienen un verdadero motivo de esperanza para creer que están justificados por Su sangre.
Pero que ninguno se engañe a sí mismo,
alentándose con la vana esperanza o confianza de que por
la muerte y sufrimientos de Cristo están justificados,
aun cuando "`el pecado está a su puerta,`"^
footnote:[Génesis 4:7]
la iniquidad aún prevalece, y sus corazones permanecen sin ser renovados ni regenerados;
no sea que al final les sea dicho: "`Nunca os conocí; apartaos de Mí.`"^
footnote:[Mateo 7:23]
Recordemos esa declaración de Cristo: "`No todo el que me dice: Señor, Señor,
entrará en el reino de los cielos,
sino el que hace la voluntad de mi Padre que está en los cielos.`"^
footnote:[Mateo 7:21]
Y con esto consideremos aquellas excelentes palabras del discípulo amado: "`Hijitos,
nadie os engañe; el que hace justicia es justo, como él es justo.
El que practica el pecado es del diablo.`"^
footnote:[1 Juan 3:7-8]
Y "`si nuestro corazón nos reprende, mayor que nuestro corazón es Dios,
y él sabe todas las cosas.`"^
footnote:[1 Juan 3:20]

Muchos protestantes famosos dan testimonio de esta justificación por medio de Cristo,
revelado y formado internamente en el hombre.
Martin Borrahus dice: "`La forma de nuestra justificación es la justicia divina misma,
por la cual somos hechos justos y buenos.
Este es Jesucristo,
quien es llamado '`justicia nuestra,`' en parte por el perdón de pecados,
y en parte por la renovación y la restauración de esa integridad
que se perdió por la caída del primer Adán,
y así somos revestidos del nuevo y celestial Adán, de lo cual el apóstol dice:
'`de Cristo estáis revestidos.`'`"^
footnote:[En Gen, pagina 181]
Zwinglio también dice: "`La santificación del Espíritu es la verdadera justificación,
la única que es suficiente para justificar.`"^
footnote:[En su epístola a la princesa de Alemania,
como fue citada por Himelius, c. vii., p. 60.]
Estius, comentando 1 Corintios 6:11 dice:
"`Para que no se piense que la justicia cristiana consiste en el lavamiento solamente,
es decir, en la remisión de los pecados, Pablo añade el otro grado o parte,
'`ya habéis sido santificados;`' es decir, han alcanzado la pureza,
de modo que ahora son verdaderamente santos delante de Dios.
Por último, expresando la suma del beneficio recibido en una sola palabra,
que incluye ambas partes, el apóstol añade:
'`ya habéis sido justificados en el nombre del Señor Jesús,
y por el Espíritu de nuestro Dios.`'`" Finalmente, Richard Baxter,
el famoso predicador inglés dice:
"`Algunos desdichados ignorantes crujen sus dientes ante esta doctrina,
como si se tratara de puro catolicismo romano,
sin entender la naturaleza de la justicia del nuevo pacto;
la cual procede completamente de Cristo dentro de nosotros,
y es forjada por el poder del Espíritu de Cristo en nosotros.`"^
footnote:[En su libro llamado __Aphorisms of Justification__
(Aforismos de la Justificación), p. 80]

=== En Cuanto a la Tercera Proposición: La Necesidad de las Buenas Obras

La tercera proposición por considerar se refiere a las buenas obras, que,
como hemos dicho, fluyen naturalmente de este nacimiento espiritual,
como el calor del fuego, y son, por lo tanto,
absolutamente necesarias para la justificación; _no como la causa de ella,_
sino como aquello en lo que somos justificados,
y sin lo cual no podemos ser justificados.

Supongo que ya se ha dicho lo suficiente para librarnos de cualquier
acusación de ser similares a los católicos romanos en este asunto.
Pero si se nos pregunta, si afirmamos que el hombre es justificado por las obras,
le respondo:
Espero que ninguno se ofenda si en este asunto usamos
el lenguaje claro de las Sagradas Escrituras,
que dicen expresamente: "`Vosotros veis, pues,
que el hombre es justificado por las obras,
y no solamente por la fe,`" (Santiago 2:24). No necesito
ofrecer una prueba de la verdad de esta afirmación,
ya que lo que dice el apóstol en este capítulo es suficiente
para convencer a cualquier hombre que lo lea y lo crea.
Por lo tanto, solo extraeré este único argumento:

[.discourse-part]
_Argumento:_ Si ningún hombre puede ser justificado sin fe,
y ninguna fe puede considerarse viva o adecuada sin obras,
entonces las obras son necesarias para la justificación.

Esta verdad es tan clara y evidente en las Escrituras,
que para demostrarla podríamos transcribir la mayoría de los preceptos del Evangelio.
Voy a citar unos pocos que afirman el asunto en cuestión con tanta claridad,
que no se necesita ningún comentario ni más demostración,
y luego responderé las objeciones comunes que se hacen en contra de esto.
Hebreos 12:14: "`Seguid la paz con todos, y la santidad,
sin la cual nadie verá al Señor.`" Mateos 7:21: "`No todo el que me dice: Señor, Señor,
entrará en el reino de los cielos,
sino el que hace la voluntad de mi Padre que está en los cielos.`"
Juan 13:17: "`Si sabéis estas cosas, bienaventurados seréis si las hiciereis.`"
1 Corintios 7:19: "`La circuncisión nada es, y la incircuncisión nada es,
sino el guardar los mandamientos de Dios.`"
Apocalipsis 22:14: "`Bienaventurados los que hacen sus mandamientos,
para que tengan derecho al árbol de la vida,
y que entren por las puertas en la ciudad.`"^
footnote:[RV1602P]
Sin duda, se podrían dar muchos más ejemplos, de todos los cuales afirmo:

[.discourse-part]
_Argumento:_
Si sólo los que hacen la voluntad del Padre pueden entrar en el reino de los cielos;
si sólo los que hacen las palabras de Cristo son
considerados edificadores prudentes y bienaventurados;
si ninguna observación externa es de provecho, sino guardar los mandamientos;
y si sólo los que hacen sus mandamientos tienen derecho al Árbol
de la Vida y a la entrada por las puertas a la ciudad;
entonces las obras son absolutamente necesarias para la salvación y la justificación.

[.discourse-part]
Objeción:
Pero algunos objetan que las obras no son necesarias para la justificación
debido a la afirmación de Cristo en Lucas 17:10:
"`Cuando hubiereis hecho todo lo que os es mandado, decid: Siervos inútiles somos;`" etc.

[.discourse-part]
Respuesta: En cuanto a Dios, somos ciertamente inútiles, porque Él no necesita nada,
y nosotros no podemos añadirle nada.
Pero en cuanto a nosotros mismos, no somos inútiles,
de lo contrario podría decirse que a un hombre no
le es de provecho guardar los mandamientos de Dios,
lo cual es muy absurdo y contradice la doctrina de Cristo a lo largo de las Escrituras.
¿Acaso no llama Cristo "`siervos buenos y fieles,`"
a los hombres que incrementaron sus talentos?
^
footnote:[Mateo 25:14-23]¿No les fue de provecho a ellos el haberlos incrementado?
Está escrito de aquel que escondió su talento y no lo incrementó:
"`Echadle en las tinieblas de afuera.`"
Si no incrementar el talento hizo que este hombre fuera inútil, entonces,
que los demás incrementaran sus talentos los hizo verdaderamente siervos útiles,
especialmente cuando vemos la manera en que Cristo habló de ellos: "`Bien,
buen siervo y fiel; sobre poco has sido fiel, sobre mucho te pondré;
entra en el gozo de tu Señor.`"^
footnote:[Mateo 25:23]

[.discourse-part]
Objeción: En segundo lugar, objetan a partir de lo escrito por el apóstol Pablo,
donde excluye las obras de la ley de la justificación. Tal como en Romanos 3:20:
"`Ya que por las obras de la ley ningún ser humano será
justificado delante de él,`" y luego en el versículo 28:
"`Concluimos, pues, que el hombre es justificado por fe sin las obras de la ley.`"

[.discourse-part]
Respuesta: En respuesta a esta objeción,
digo que hay una gran diferencia entre las obras de la Ley,
y las obras de la gracia o del Evangelio.
Las primeras están excluidas, las segundas no, al contrario, son necesarias.
Las primeras son las que se realizan según la voluntad del hombre y por su propia fuerza,
en conformidad con la ley y la letra externas, y por lo tanto,
son las obras propias e imperfectas del hombre,
o las obras de la Ley que no perfeccionan nada.^
footnote:[Hebreos 7:19]
A este tipo de obras pertenecen todas las ceremonias, purificaciones,
lavamientos y tradiciones de los judíos. Las segundas
son las del Espíritu de Gracia en el corazón,
realizadas en conformidad a la ley interna y espiritual.
Estas obras no son hechas en la voluntad del hombre, ni por su poder y capacidad,
sino en y por el poder y Espíritu de Cristo en nosotros, y por lo tanto,
son puras y perfectas según su género.
De hecho, estas podrían ser llamadas las obras de Cristo,
porque Él es el autor y hacedor directo de ellas.^
footnote:[Véase Hebreos 13:20-21; Filipenses 1:11, 2:13]
Nosotros afirmamos absolutamente, que estas obras son necesarias para la justificación,
de modo que un hombre no puede ser justificado sin ellas;
porque toda fe que carezca de ellas es muerta e inútil, como dice el apóstol Santiago.

Ahora bien,
que esta distinción entre las obras de la Ley y las obras de la gracia debe ser admitida,
y que el apóstol excluye las primeras de la justificación pero no las segundas,
es claramente evidente cuando consideramos el contexto de estas afirmaciones.
Porque tanto en su carta a los Romanos como a los Gálatas donde habla sobre esto,
encontramos que muchos de los gentiles (que no eran de la semilla
de Abraham según la carne) se habían convertido a la fe cristiana,
y habían llegado a creer en Él. Sin embargo, algunos de los judíos convertidos a la fe,
intentaban hacer que los creyentes gentiles se sujetaran
a las ceremonias y observaciones legales de la Ley,
insistiendo en que éstas eran necesarias para su justificación.
Esto le dio al apóstol Pablo la oportunidad de mostrar ampliamente
el uso y la tendencia de la Ley y de sus obras,
y de distinguirlas de la fe de Cristo y de la justicia de dicha fe,
mostrando que las primeras habían cesado y se habían hecho ineficaces,
pero que las segundas permanecían y eran necesarias.
Y es evidente el tipo de obras que el apóstol excluyó,
por el hilo de pensamiento de su epístola a los Gálatas.
Porque en el cuarto capítulo,
los reprende por volverse a la observación de días y de tiempos,^
footnote:[Gálatas 4:10-11]
y en el quinto y sexto les muestra la necedad de aferrarse a la ceremonia de la circuncisión,
diciendo: "`Porque en Cristo Jesús ni la circuncisión vale algo, ni la incircuncisión,
sino la fe que obra por el amor.`"^
footnote:[Gálatas 5:6]
Y luego dice: "`Porque en Cristo Jesús ni la circuncisión vale nada,
ni la incircuncisión, sino una nueva creación.`"^
footnote:[Gálatas 6:15]
Cabe señalar,
que la palabra circuncisión a menudo se usa para abarcar la totalidad del antiguo pacto,
incluyendo sus ritos ceremoniales y legales.
Pablo dice que estas obras de la Ley están excluidas,
y que por ellas ningún hombre es justificado; pero que la fe que obra por amor,
o la nueva creación, _esto_ es lo que vale, y de hecho, es necesario.
Ahora, es evidente que el apóstol no intenta excluir en manera alguna,
las buenas obras de la nueva creación, porque en este mismo lugar les dice claramente:
"`No os engañéis; Dios no puede ser burlado: pues todo lo que el hombre sembrare,
eso también segará. Porque el que siembra para su carne, de la carne segará corrupción;
mas el que siembra para el Espíritu, del Espíritu segará vida eterna.
No nos cansemos, pues, de hacer bien; porque a su tiempo segaremos, si no desmayamos.`"^
footnote:[Gálatas 6:7-9]
¿No queda claro por lo dicho aquí cuán necesarias son estas buenas obras?
No las ceremonias y tradiciones externas de la Ley,
sino los frutos del Espíritu mencionados un poco antes (4:22);
por cuyo Espíritu Pablo deseaba que todos ellos fuesen guiados,
y en el que quería que todos caminaran.
Las primeras son "`obras de justicia hechas por nosotros,`"
realizadas en nuestra primera naturaleza caída,
por nuestra propia fuerza, en actos religiosos.
Las últimas son los frutos del "`lavamiento de la regeneración,
y de la renovación del Espíritu Santo.`"^
footnote:[Véase Tito 3:5]

[.discourse-part]
Objeción: Pero estas obras del Espíritu podrían también llamarse nuestras,
porque son hechas en nosotros y muchas veces por nosotros también como instrumentos.

[.discourse-part]
Respuesta: Aun así,
los dos tipos de obras difieren ampliamente entre sí. En el primer tipo--las obras de
justicia hechas por nosotros--todavía estamos vivos en nuestro propio estado natural,
sin ser renovados, obrando por nosotros mismos,
buscando salvarnos a nosotros mismos imitando y tratando
de conformarnos a la letra externa de la Ley,
y por lo tanto, esforzándonos y luchando en la mente carnal,
que es enemistad contra Dios,^
footnote:[Romanos 8:7 RV1602P]
y en esa voluntad condenada que aún no ha sido sometida.
Pero en el segundo tipo--los frutos de la obra del Espíritu
Santo--estamos "`crucificados juntamente con Cristo,`"^
footnote:[Gálatas 2:20]
habiendo llegado a estar "`muertos con Él,`"^
footnote:[Romanos 6:3]
siendo partícipes de "`la comunión de Sus padecimientos,`"
y "`hechos conforme a Su muerte.`"^
footnote:[Filipenses 3:10 RV1602P]
Aquí nuestro primer hombre, nuestro "`viejo hombre con sus hechos,`"^
footnote:[Colosenses 3:9]
(tanto los abiertamente perversos como los aparentemente justos),
es enterrado y clavado en la cruz de Cristo, de modo que ya no somos nosotros,
sino Cristo quien vive en nosotros; es decir, el Obrero vive en nosotros.
Así entonces, aunque en cierto sentido seamos nosotros,
es en el mismo sentido que el apóstol describe en Gálatas 2:20 donde dice:
"`Con Cristo estoy juntamente crucificado, y ya no vivo yo,
mas vive Cristo en mí,`" y en 1 Corintios 15:10: "`He trabajado más que todos ellos;
pero no yo, sino la gracia de Dios conmigo.`"
Estas obras deben ser absolutamente atribuidas al
Espíritu de Cristo y a la gracia de Dios en nosotros,
habiendo sido hechas,
habilitadas o dirigidas directamente por Él. Esta manera de hablar no es para nada extraña,
más bien era familiar para los apóstoles, como a menudo se ve en las Escrituras,
tal como en Gálatas 2:8:
"`Porque el que obró eficazmente en Pedro para el apostolado de la circuncisión,
obró también en mí para con los Gentiles;`"^
footnote:[RV1602P]
o en Filipenses 2:13:
"`Porque Dios es el que en vosotros produce así el querer como el hacer,
por su buena voluntad,`" etc.

[.discourse-part]
Objeción: Algunos objetan que ninguna obra, ni siquiera las obras de Cristo en nosotros,
pueden tener lugar en la justificación,
porque nada que sea impuro puede ser útil en ella;
y todas las obras realizadas en nosotros son impuras.
Para probar esto citan las palabras del profeta Isaías:
"`Todas nuestras justicias son como trapo de inmundicia;`"^
footnote:[Isaías 64:6]
añadiendo el siguiente razonamiento, que dado que somos impuros,
entonces nuestras obras deben serlo también; porque incluso las obras de Dios,
tal como son realizadas por nosotros, reciben una mancha de impureza,
así como el agua limpia se contamina cuando pasa a través de una tubería sucia.

[.discourse-part]
Respuesta: Confesamos que ninguna obra impura es útil para la justificación;
pero negamos que todas las obras hechas en los santos sean impuras.
Para responder a esta objeción,
la distinción mencionada anteriormente entre los dos tipos de obras,
también nos servirá aquí. Porque nosotros confesamos
que las obras del primer tipo son impuras,
pero no las del segundo; porque en el primer tipo,
las obras son hechas por el hombre en el estado no regenerado,
pero en el otro son hechas por el Espíritu y gracia de Dios.
En cuanto a esa escritura de Isaías, debe referirse al primer tipo,
porque aunque él dice: "`Nuestras justicias son como trapo de inmundicia,`" aun así,
esto no incluye la justicia de Cristo obrada en nosotros,
sino sólo aquella que nosotros obramos en nuestra propia fuerza y por nosotros mismos.
Porque si fuese lo contrario,
entonces tendríamos que desechar toda santidad y justicia como trapo de inmundicia,^
footnote:[Literalmente "`una prenda menstrual`"]
incluso los frutos del Espíritu mencionados en Gálatas 5. Pero contrario a esto,
está escrito que algunas de las obras de los santos han sido un "`perfume de dulce fragancia;`"^
footnote:[Filipenses 4:18; 2 Corintios 2:15]
y un "`adorno de grande estima delante de Dios;`"^
footnote:[1 Pedro 3:4 RV1602P]
y está escrito de dichas obras que "`prevalecen con Él`" y son "`aceptables para Él;`"^
footnote:[Véase Romanos 12:1-2 y 14:18; Filipenses 4:18; 1 Timoteo 2:3 y 5:4;
1 Pedro 2:5 y 2:30.]
y esto no se puede decir de un trapo de inmundicia
(como muchos protestantes famosos han reconocido).

En cuanto a la otra parte de esta objeción--dado que los
mejores hombres siguen siendo impuros e imperfectos,
por lo tanto, sus obras también deben serlo--esto involucra una gran suposición,
una que nosotros negamos,
como se discutirá ampliamente en la siguiente proposición. Sin embargo,
incluso en el caso de que un hombre no sea completamente perfecto en todos los aspectos,
esto no impedirá que las obras buenas o perfectas (según
su tipo) se engendren en él por el Espíritu de Cristo;
ni da en el blanco el ejemplo del agua pasando por una tubería sucia;
porque aunque el agua se puede contaminar con la suciedad, el Espíritu de Dios no puede,
de quien nosotros afirmamos que es el Autor directo de esas
obras que tienen valor en la justificación. En consecuencia,
decimos que las obras de Jesucristo en Sus hijos son puras y perfectas,
y que Él obra en y a través de aquello puro que Él mismo forma y crea en ellos.

Además, si la suposición de nuestros adversarios fuera cierta,
entonces tendríamos que concluir que los mismos milagros y obras de los apóstoles,
que Cristo obró en ellos y que ellos hicieron en y por el Poder,
Espíritu y Gracia de Cristo, también habrían sido impuros e imperfectos.
Y de hecho,
¿no habría sido también necesariamente impura e imperfecta la escritura de las
Sagradas Escrituras (que nuestros adversarios parecen magnificar tanto),
al provenir de vasijas impuras e imperfectas?)

Por último,
debido a que parece apropiado mencionar algo aquí
respecto al mérito y la recompensa de las obras,
añadiré algo en este lugar de nuestro entendimiento y creencia respecto a este asunto.
Estamos lejos de pensar o creer que el hombre merece algo de Dios por sus obras,
porque en verdad, todo es por la gracia gratuita,
y por eso siempre hemos negado la doctrina católica de __meritum ex condigno__.^
footnote:[Nota del Editor: __Meritum ex condigno,__
es la doctrina católica romana que afirma que hay un mérito intrínseco en las obras,
que Dios, si actúa de manera justa, no puede sino recompensar con la vida eterna.]
Sin embargo, no podemos dejar de reconocer que Dios,
por Su infinita bondad con la que ha amado a la humanidad,
después de comunicarle Su Santa Gracia y Espíritu, según Su propia voluntad,
recompensa y premia las buenas obras de Sus hijos.
Y por lo tanto, no podemos negar que existe una especie de recompensa merecida,
en el sentido en que las Escrituras lo afirman clara y positivamente.
Porque la misma palabra griega _axion,_
que significa "`mérito,`" se encuentra en esos lugares donde los
traductores la expresan como "`digno`" (como en Mateos 3:8;
1 Tesalonicenses 2:12; 2 Tesalonicenses 1:5,11).

Los llamados Padres de la Iglesia,
frecuentemente usaban la palabra "`mérito`" de esta manera,
y muchos protestantes no se han mostrado opuestos a dicha
palabra en el sentido en que nosotros la usamos.
La Apología de la Confesión de Augsburgo, art.
20, dice lo siguiente:
"`Estamos de acuerdo con que las obras son verdaderamente meritorias,
no de la remisión de los pecados o de la justificación;
sino meritorias de otras recompensas tanto naturales como espirituales,
y que se experimentan tanto en esta vida como en la por venir.`"
G+++.+++ Voss, en su tesis teológica respecto a los méritos de las buenas obras, dice:
"`No hemos ido tan lejos como para condenar por completo la palabra "`mérito,`"
pues es una palabra que muchos de los antepasados han usado,
y que también aparece en las confesiones de las iglesias reformadas.
Ahora bien, el hecho de que Dios juzga y acepta a los hombres de acuerdo con sus obras,
está más allá de toda duda para cualquiera que lea
y considere seriamente las siguientes escrituras:
Mateos 16:27; Romanos 2:6-7 y 10; 2 Corintios 5:10; Santiago 1:25; Hebreos 10:36;
1 Pedro 1:17; Apocalipsis 22:12.

=== Conclusión

Para concluir este tema: que nadie sea tan osado como para burlarse de Dios,
suponiéndose justificado y aceptado ante Sus ojos
en virtud de la muerte y sufrimientos de Cristo,
mientras permanece no santificado y no justificado en su propio corazón,
y contaminado en sus pecados; no sea que su esperanza termine siendo la del hipócrita,
que perece.^
footnote:[Job 8:13]
Por otro lado, que nadie imagine neciamente que puede, por sus propias obras,
o por la realización de algunas ceremonias o tradiciones, o por dar dinero,
o por un duro trato de su cuerpo en un culto voluntario y en una humildad falsa,
o por tontamente esforzarse por cumplir la letra externa de la ley,
halagarse a sí mismo pretendiendo que merece algo delante de Dios,
o que Dios está en deuda con él. De hecho,
que nadie piense que los hombres tienen poder para
hacer que tales cosas sirvan para justificarlos,
no sea que sean hallados como necios jactanciosos y extraños a Cristo y a Su Justicia.
Pero bienaventurados para siempre sean aquellos que verdaderamente
han sentido su propia indignidad y pecaminosidad,
y han visto que todos sus esfuerzos y obras son inútiles y vanos.
Sí, bienaventurados aquellos que han contemplado su propio vacío,
y la vanidad de su propia esperanza, fe y confianza, siendo compungidos,
perseguidos y condenados internamente por el testigo santo de Dios en sus corazones.
Porque estos, habiéndose entregado a este testigo interno,
y permitido que Su gracia obre en ellos,
han sido transformados y renovados en el espíritu de su mente,
han pasado de muerte a vida, y han llegado a experimentar a Jesús resucitado en ellos,
produciendo tanto el querer como el hacer.
Estos en verdad, se han "`vestidos del Señor Jesucristo,`"^
footnote:[Romanos 13:14]
y están cubiertos con Él, y participan de Su justicia y naturaleza, y por lo tanto,
pueden acercarse al Señor con confianza,
sabiendo que son aceptos en y por Aquel en quien el Padre tiene complacencia.
