== Capítulo VI. Respecto a la Perfección

Puesto que hemos colocado la justificación en la experiencia de Jesucristo revelado,
formado y manifestado en el corazón--haciendo allí Sus obras de justicia y produciendo
los frutos del Espíritu--ahora nos corresponde responder la siguiente pregunta:
¿Qué tanto puede prevalecer Él en nosotros mientras estamos en esta vida?
O ¿Qué tanto podemos prevalecer sobre los enemigos de nuestra alma, en y por Su fuerza?

Aquellos que abogan por una justificación completamente fuera de ellos,
mediante una justicia meramente imputada,
negando la necesidad de ser revestidos de la justicia real e interna,
como consecuencia afirman que es "`imposible`" para un hombre,
incluso "`para el mejor de los hombres, ser libre de pecado en esta vida,
lo cual,`" dicen ellos, "`nunca ha sucedido.`"
Por el contrario, insisten en que nadie, "`ni por sí mismo,
ni por ninguna gracia recibida en esta vida +++[+++¡Oh
perverso dicho contra el poder de la Gracia de Dios!],
puede guardar perfectamente los mandamientos de Dios,
sino que todos los hombres quebrantan los mandamientos de Dios en pensamiento,
palabra y obra.`"^
footnote:[Estas son las palabras de la versión completa del Catecismo de Westminster;
Sección IIIB, P 149.]
A partir de esto también afirman (como se observó anteriormente),
que hasta las mejores acciones de los santos, incluso sus oraciones y su adoración,
son impuras y están contaminadas.

Ahora bien,
nosotros reconocemos libremente que esto es cierto respecto al hombre natural y caído,
en su primer estado, sin importar cuál sea su creencia o pretensión,
mientras permanezca no convertido y no regenerado.
Sin embargo, creemos que para aquellos en quienes Cristo llega a ser formado,
y el nuevo hombre es engendrado y nace de la semilla incorruptible,
dado que ese nacimiento (y el hombre en unión con
él) hace naturalmente la voluntad de Dios,
les es posible permanecer en ella de manera tal que
no sean hallados transgrediendo diariamente Su ley.
Y para establecer de manera más clara la controversia, téngase en cuenta lo siguiente:

Primero,
nosotros no colocamos esta posibilidad en la propia voluntad y capacidad del hombre,
tal como es--hijo del Adán caído--es decir, tal como está en su estado natural,
por sabio o instruido que sea,
o por muy dotado que esté del conocimiento teórico y literal de Cristo,
tratando por sí mismo de conformarse a la letra de la ley externa.

Segundo, le atribuimos esto completamente al hombre según nace de nuevo,
es renovado en su mente, resucitado por Cristo, experimentando a Cristo vivo,
reinando y gobernando en él, guiándolo y dirigiéndolo por Su Espíritu,
y revelando en él la ley del Espíritu de vida--que
no sólo manifiesta y reprende el pecado,
sino que también da poder para salir de él.

Tercero, con esto no pretendemos una perfección tal que no permita un crecimiento diario,
y por lo tanto, no queremos decir que lleguemos a ser tan puros,
santos y perfectos como Dios en Sus atributos divinos de sabiduría,
conocimiento y pureza.
Más bien hablamos de una perfección proporcional y adecuada a la medida del hombre,
mediante la cual somos guardados de transgredir la ley de Dios
y capacitados para responder a lo que Él requiera de nosotros.
Así como un poco de oro es tan perfecto (en su género) como una gran cantidad;
y como un niño tiene un cuerpo tan perfecto como el de un hombre,
aunque cada día crece más y más. De la misma manera
se dice que Cristo "`crecía en sabiduría y en estatura,
y en gracia para con Dios y los hombres`" (Lucas 2:52),
aunque nunca había pecado antes de ese tiempo, y sin duda era perfecto,
en un sentido verdadero y correcto.

Cuarto,
aunque un hombre puede experimentar esto por un tiempo
(y por lo tanto todos deben esforzarse por lograrlo),
aun así,
aquellos que lo han alcanzado en cierta medida pueden caer
en iniquidad por las artimañas y tentaciones del enemigo,
y a veces perderlo,
si no son vigilantes y no atienden con diligencia a esa Semilla
de Dios en el corazón. Y no nos cabe la menor duda de que muchos
hombres buenos y santos han tenido altibajos de este tipo,
porque, aunque cada pecado debilita a un hombre en cuanto a su condición espiritual,
aun así, no necesariamente lo destruye por completo,
ni lo incapacita para levantarse otra vez.

Por último,
aunque afirmo que después de que un hombre ha llegado
a dicha condición en la que está libre de pecado,
aun así, puede caer y pecar de nuevo, sin embargo,
no voy a negar que existe un estado alcanzable en esta vida,
en el que hacer justicia se vuelva tan natural para el alma regenerada,
que en la estabilidad de esta condición no puede pecar.
Otros quizás puedan hablar con mayor certeza de este estado,
si han llegado a él. Con respecto a mí mismo, hablaré modestamente,
reconociendo que no he llegado a él. Sin embargo,
no me atrevo a negar que exista tal estado,
porque el apóstol lo afirma muy claramente en las siguientes palabras:
"`Todo aquel que es nacido de Dios, no practica el pecado,
porque la simiente de Dios permanece en él; y no puede pecar,
porque es nacido de Dios.`"^
footnote:[1 Juan 3:9]

Habiendo expuesto la controversia,
procederé primero a demostrar cuán absurda es esa doctrina
que aboga por el pecado durante toda la vida,
incluso en los santos.
Luego,
probaré nuestra doctrina de la perfección a partir
de muchos testimonios claros de las Sagradas Escrituras.
Y por último, responderé a los argumentos y objeciones de nuestros adversarios.

=== La Locura de Defender el Pecado

En primer lugar,
la doctrina que establece que los santos nunca podrán ser libres de pecar en esta vida,
es inconsistente con la sabiduría de Dios y con Su glorioso poder y majestad,
quien es "`de ojos demasiado puros para mirar el mal,
y no puede contemplar la iniquidad.`"^
footnote:[Habacuc 1:13 Versión Moderna H.B. Pratt (1929)]
Pues Aquel que se propuso en Sí mismo reunir a un
pueblo para que le adore en Espíritu y en verdad,
y dé testimonio de Él en la tierra,
es sin ninguna duda capaz de santificarlos y purificarlos.
Dios no se deleita en la iniquidad, sino que aborrece la transgresión,
y aunque considera al hombre en la transgresión hasta el punto
de compadecerse de él y proporcionarle un medio para salir de ella,
aun así no se deleita en el hombre mientras permanece en ese estado.
Porque si los hombres tienen que estar siempre unidos a su pecado,
entonces Dios debería estar distanciado de ellos siempre, como está escrito:
"`Vuestras iniquidades han hecho división entre vosotros y vuestro Dios,
y vuestros pecados han hecho ocultar de vosotros su rostro`" (Isaías 59:2). De hecho,
está escrito expresamente que no hay "`comunión entre la luz y las tinieblas.`"^
footnote:[2 Corintios 6:14]
Ahora bien, Dios es Luz, y todo pecado es, en una medida, tinieblas.
Entonces, ¿qué podría manchar más la sabiduría de Dios,
que decir que Él carece de un medio por el cual Sus
hijos puedan servirle y adorarle perfectamente;
o que no ha provisto una manera por medio de la cual puedan dejar de servir al diablo?
Porque "`el que hace pecado, esclavo es del pecado,`"^
footnote:[Juan 8:34; Romanos 6:16]
y todo pecado es un acto de servicio y obediencia al diablo.
Entonces, si los santos deben continuar pecando diariamente, en pensamiento,
palabra y obra;
y si su propio servicio a Dios está mezclado con pecado (como insisten nuestros oponentes),
entonces sin duda ¡sirven al diablo tanto o más de lo que sirven al Señor!

Ahora bien, ¿qué amo entre los hombres no sería considerado necio,
si estando dispuesto y en condiciones de proporcionar un medio
por el cual sus hijos y siervos pudieran servirle enteramente,
se negara a hacerlo,
y en lugar de eso permitiera que sus siervos le sirvieran
con más fidelidad y plenitud a su enemigo declarado?
Entonces,
¿qué deberíamos pensar de una doctrina que atribuyera esta insensatez al omnipotente,
único y sabio Dios?

En segundo lugar, esta doctrina es inconsistente con la justicia de Dios.
Porque dado que Dios requiere que Sus hijos sean puros,
y con frecuencia les ordena que se abstengan de toda iniquidad (como se verá más adelante),
y dado que Su "`ira se revela contra toda impiedad e injusticia de los hombres,`"^
footnote:[Romanos 1:18]
debe necesariamente concluirse que les ha dado a
los hombres la capacidad de responder a Su voluntad;
o bien, que les demanda más del poder que les ha dado para cumplir.
De hecho, esto sería declarar abiertamente que Él es injusto,
y decir con el siervo negligente: "`¡Tú eres un maestro duro!`"
Hemos hablado anteriormente de la injusticia que nuestros oponentes le atribuyen a Dios,
al alegar que Él condena a los impíos sin jamás haberles
proporcionado los medios para ser salvos.
Pero esta es una acusación aún más irracional e inconsistente:
decir que Dios no quiere proporcionarles a Sus propios escogidos
(a quienes ellos confiesan que Él ama) los medios para agradarle.

¿Qué resultaría de una doctrina tan extraña? Esta
imperfección en los santos o bien procede de Dios,
o bien de ellos mismos.
Si procede de ellos,
debe ser porque quedan cortos en el uso del poder que se les ha dado:
la gracia por la cual son capacitados para obedecer.
Pero si la imperfección no es de ellos, entonces debe ser de Dios,
quien no ha considerado apropiado conceder suficiente
gracia para cumplir Su propio requerimiento.
¡De nuevo, esto no es más que atribuirle a Dios la más grande injusticia,
al decir que Él requiere que Sus hijos abandonen el pecado,
incluso cuando no les provee los medios para hacerlo!
En verdad,
esto hace a Dios más injusto que los "`hombres malos`"
de quienes Cristo habló en Su sermón del monte;
porque hasta ellos, cuando "`sus hijos les piden pan, no les darán una piedra,
o si les piden un pescado, no les darán una serpiente.`"^
footnote:[Mateo 7:9-11]
Y aunque nuestros adversarios dicen que todos deben
buscar de Dios el poder para ser redimidos del pecado,
creen y enseñan que nadie debería esperar recibir tal poder.
¿No es esto hacer a Dios tan injusto con Sus hijos como lo fue Faraón con los Israelitas,
al exigirles ladrillo y no darles paja?
Pero bendito sea Dios,
Él no trata de esta manera a los que verdaderamente confían y esperan en Él,
como estos hombres vanamente imaginan.
Porque los fieles verdaderamente encuentran que Su gracia es suficiente para ellos,
y saben cómo vencer al maligno por medio del don de Su poder y Espíritu.

En tercer lugar, esta perversa doctrina es sumamente difamatoria para Jesucristo,
y menoscaba en gran medida el poder y virtud de Su sacrificio,
quitando eficacia a Su venida y ministerio.
Porque una de las principales razones de la venida
de Cristo en la carne fue eliminar el pecado,
y reunir a una generación justa para servir al Señor con pureza de mente,
y caminar delante de Él en temor.
Es Él quien "`trajo la justicia perdurable,`"^
footnote:[Daniel 9:24]
y la perfección del evangelio que la Ley no podía efectuar.^
footnote:[Véase Colosenses 1:28; Hebreos 7:19; 9:9; 10:1]
Por eso está escrito que Él "`se dio a sí mismo por nosotros para
redimirnos de toda iniquidad y purificar para sí un pueblo propio,
celoso de buenas obras.`"^
footnote:[Tito 2:14]
Estas palabras del apóstol ciertamente se refieren a los santos,
mientras todavía están en la tierra.
Pero contrario a esto,
nuestros adversarios afirman que nunca seremos realmente redimidos de toda iniquidad,
y por lo tanto anulan y dejan sin efecto el hecho de que Cristo "`se dio a Sí mismo
por nosotros,`" al negar que Él realmente "`purifica para sí un pueblo propio.`"
Pero pregunto,
¿cómo puede un pueblo ser celoso de buenas obras cuando comete malas obras diariamente?
¿Y cómo puede ser un pueblo purificado si todavía vive en impureza y peca continuamente?
Está expresamente escrito: "`El Hijo de Dios se manifestó con este propósito:
para destruir las obras del diablo,`"^
footnote:[1 Juan 3:8 LBLA]
y "`sabéis que Él apareció para quitar nuestros pecados.`"^
footnote:[1 Juan 3:5]
Pero estos hombres anulan este propósito,
porque no están dispuestos a creer que el Hijo de
Dios destruye las obras del diablo en este mundo,
ni que Cristo apareció para quitar nuestros pecados,
ya que abogan por la necesidad de vivir siempre en ellos.
Y para que nadie tuerza esta Escritura diciendo que
habla sólo de quitar la culpa del pecado,
el apóstol (como si tratara intencionalmente de evitar tal objeción) añade de inmediato:
"`Todo aquel que permanece en él, no peca;`" e "`Hijitos, nadie os engañe;
el que hace justicia es justo, como él es justo.
El que practica el pecado es del diablo.`"^
footnote:[1 Juan 3:6-8]

Ahora bien, si Cristo apareció para quitar el pecado,
¿no es extraño que estos hombres invalidan la doctrina de
Cristo al decir que el pecado nunca será quitado aquí? ¡Oh,
consideren cuán ofensivo es esto para la eficacia y poder de la aparición de Cristo!
¿No vino Cristo a sacar a un pueblo fuera del pecado para llevarlo a la justicia;
fuera del reino de Satanás para trasladarlo al reino del amado Hijo de Dios?
Y aquellos que son reunidos por Él, ¿no se convierten en Sus siervos, Sus hijos,
Sus hermanos y Sus amigos?
En efecto, está escrito: "`Como Él es, así son ellos en este mundo;`"^
footnote:[1 Juan 4:17]--santos, puros y sin mancha.
¿Acaso no continúa Cristo velando sobre ellos, permanece al lado de ellos, ora por ellos,
los preserva con Su Poder y Espíritu, anda y habita entre ellos, así como el diablo,
por otro lado, lo hace entre los reprobados?
¿Por qué habrían de ser los siervos de Cristo menos capaces
de servir a su Maestro que los siervos del diablo al suyo?
¿O es que Cristo no quiere que Sus siervos sean completamente
puros (una blasfemia terrible y contraria a muchas escrituras)?
¿Acaso no es Cristo capaz de preservar y capacitar por medio de Su poder
a Sus hijos para que le sirvan (una blasfemia igualmente terrible)?
Porque ciertamente, si los santos pecan diariamente en pensamiento,
palabra y obra--como estos hombres afirman--entonces sirven
al diablo diariamente y continúan sujetos a su poder,
de modo que él prevalece más en ellos que Cristo, y los mantiene en esclavitud,
incluso en contra de la voluntad de Cristo.
Pero cuán grandemente contradice esto el propósito de la venida de Cristo,
porque el apóstol dice: "`Así como también Cristo amó a la iglesia,
y se entregó a sí mismo por ella; para santificarla,
purificándola en el lavamiento del agua por la palabra,
para que la presentase a sí mismo, iglesia gloriosa, que no tuviese mancha, ni arruga,
ni cosa semejante; sino que fuese santa y sin mancha.`"^
footnote:[Efesios 5:25-27 RV1602P]
Ahora bien, si Cristo realmente cumplió el propósito por el cual vino,
entonces los miembros de Su cuerpo no deben estar pecando siempre en pensamiento,
palabra y obra.
De lo contrario, no hay diferencia entre ser santificado y no ser santificado,
ser limpio o ser inmundo, santo o impío,
estar manchado diariamente de pecado o estar sin mancha.

En cuarto lugar, esta doctrina hace que la obra del ministerio,
la predicación de la Palabra,
los textos de las Escrituras y las oraciones de los hombres santos,
sean completamente inútiles e ineficaces.
En cuanto a lo primero,
está escrito que los pastores y maestros son dados para "`perfeccionar a los santos...hasta
que todos lleguemos a la unidad de la fe y del conocimiento del Hijo de Dios,
a un varón perfecto,
a la medida de la estatura de la plenitud de Cristo`" (Efesios 4:11-13). Ahora bien,
si es imposible dejar de pecar diariamente y en todas las cosas,
entonces no puede haber perfección. Además, estos ministros,
que nos aseguran que no debemos esperar ser liberados del pecado,
¿no hacen que su propia labor sea innecesaria?
Pues ¿qué necesidad hay de predicar contra el pecado, si nunca se puede dejar de pecar?
Y con respecto a las Escrituras,
nuestros adversarios las exaltan muchísimo con sus palabras,
a menudo elogiando su utilidad y perfección. En efecto,
el apóstol nos dice que la "`Escritura es útil para enseñar, para redargüir,
para corregir, para instruir en justicia, a fin de que el hombre de Dios sea perfecto,
enteramente preparado para toda buena obra`" (2 Timoteo 3:17).
Pero si se niega que esto sea alcanzable en esta vida,
entonces las Escrituras no tienen ningún beneficio,
porque ¿qué utilidad tendrán en la próxima vida?
Además,
esta doctrina también hace que las oraciones de los santos sean completamente inútiles;
pues,
¿por qué hemos de orar diariamente para que Dios por Su Espíritu y gracia
nos libre del mal y nos libere del pecado (como todos confiesan que es
nuestro deber) si tal cosa es inalcanzable en esta vida?
Sin embargo, los santos apóstoles oraban fervientemente con este propósito,
y por lo tanto,
no cabe duda de que creían que era posible alcanzarlo aquí. Porque ellos
estaban "`siempre esforzándose intensamente a favor de ellos en sus oraciones,
para que estuvieran firmes,
perfectos y completamente seguros en toda la voluntad de Dios.`"^
footnote:[Colosenses 4:12 LBLA]
Oraban a fin de que Dios "`afirmara sus corazones irreprensibles en santidad`"^
footnote:[1 Tesalonicenses 3:13 LBLA]
y los "`santificara por completo; espíritu, alma y cuerpo,`"^
footnote:[1 Tesalonicenses 5:23]
etc.

En quinto lugar,
esta doctrina es contraria al sentido común y a la razón.
Porque el pecado y la justicia son como dos semillas opuestas:
una gobierna en los hijos de las tinieblas, la otra en los hijos de la Luz.
Y conforme los hombres son respectivamente leudados y gobernados por una o la otra,
así son considerados reprobados o justificados, ya que "`el que justifica al impío,
y el que condena al justo, ambos son igualmente abominación al Señor.`"^
footnote:[Proverbios 17:15 LBLA]
Ahora bien,
decir que los hombres no pueden ser leudados por una semilla
de tal manera que lleguen a ser liberados de la otra,
es, en palabras claras, afirmar que el pecado y la justicia son compatibles,
y que un hombre puede ser verdaderamente considerado justo,
aunque peque diariamente en todo lo que hace.
Y entonces, ¿qué diferencia hay entre lo bueno y lo malo?
¿No es esto caer en la gran abominación de "`tener las tinieblas por luz
y la luz por tinieblas,`" y de "`llamar al mal bien y al bien mal?`"^
footnote:[Isaías 5:20 LBLA]
Porque dicen que hasta las mejores acciones de los
hijos de Dios están contaminadas y corrompidas,
y que aquellos que pecan diariamente en pensamiento,
palabra y acción son hombres y mujeres buenos,
incluso son los santos y los siervos puros del Dios santo y puro.
¿Puede haber algo más repugnante para la razón común que esto?
¿Dónde están los purificados de quienes hablan las Escrituras?
¿Dónde están aquellos que antes eran impíos, pero ahora han sido lavados y santificados;^
footnote:[1 Corintios 6:11]
que antes eran tinieblas pero ahora son luz en el Señor?^
footnote:[Efesios 5:8]
Según esta doctrina pecaminosa no puede haber ninguno.

=== Evidencia de la Escritura

Para mayor demostración de la verdad, proseguiré a lo segundo que propuse, a saber:
probar nuestra postura a partir de varios testimonios de las Sagradas Escrituras.

En primer lugar,
la pruebo a partir del mandato absoluto y positivo
de Cristo y Sus apóstoles a guardar los mandamientos,
y a ser perfectos en este sentido, sabiendo que Dios no demanda nada imposible.
Ahora bien, que esto está claramente ordenado en el Nuevo Testamento,
sin necesidad de comentarios o deducciones,
es evidente en los siguientes testimonios de las Escrituras: "`Sed, pues,
vosotros perfectos,
como vuestro Padre que está en los cielos es perfecto`"
Mateo 5:48. "`La circuncisión nada es,
y la incircuncisión nada es,
sino el guardar los mandamientos de Dios`" 1 Corintios
7:19. "`Y en esto sabemos que nosotros le conocemos,
si guardamos sus mandamientos.
El que dice: Yo le conozco, y no guarda sus mandamientos, el tal es mentiroso,
y la verdad no está en él; pero el que guarda su palabra,
en éste verdaderamente el amor de Dios se ha perfeccionado;
por esto sabemos que estamos en él`" 1 Juan 2:3-6.
"`Y sabéis que él apareció para quitar nuestros pecados,
y no hay pecado en él. Todo aquel que permanece en él, no peca; todo aquel que peca,
no le ha visto, ni le ha conocido.
Hijitos, nadie os engañe; el que hace justicia es justo, como él es justo.
El que practica el pecado es del diablo; porque el diablo peca desde el principio.
Para esto apareció el Hijo de Dios, para deshacer las obras del diablo.
Todo aquel que es nacido de Dios, no practica el pecado,
porque la simiente de Dios permanece en él; y no puede pecar, porque es nacido de Dios.
En esto se manifiestan los hijos de Dios, y los hijos del diablo:
todo aquel que no hace justicia, y que no ama a su hermano,
no es de Dios`" 1 Juan 3:5-10. Véase también Mateo 7:21; Juan 13:17;
2 Corintios 13:11. Todas estas Escrituras implican un mandato positivo
de guardar Sus mandamientos y declaran la necesidad absoluta de hacerlo.
Por lo tanto,
como si hubieran sido escritas intencionalmente para
responder a las objeciones de nuestros opositores,
muestran la necedad de aquellos que se atreven a
considerarse a sí mismos hijos o amigos de Dios,
mientras hacen lo contrario.

En segundo lugar,
tal libertad del pecado es posible porque recibimos
el Evangelio precisamente con ese propósito.
Esto se nos promete claramente según llegamos a estar bajo el dominio de la gracia,
como se muestra en estas Escrituras: "`Porque el pecado no se enseñoreará de vosotros;
pues no estáis bajo la ley,
sino bajo la gracia`" Romanos 6:14. "`Pues lo que la ley no pudo hacer,
ya que era débil por causa de la carne, Dios lo hizo:
enviando a su propio Hijo... para que el requisito
de la ley se cumpliera en nosotros`" Romanos 8:3-4;^
footnote:[Romanos 8:3-4 LBLA]
etc.
Porque si esto no fuera una condición necesaria y posible bajo el Evangelio,
no habría diferencia entre "`la ley, que nada hizo perfecto,`"^
footnote:[Hebreos 7:19 LBLA]
y "`la introducción de una mejor esperanza,`"^
footnote:[Hebreos 7:19]
ni entre aquellos que están bajo el Evangelio y los que están bajo la ley.
Pero el apóstol argumenta a lo largo de todo el capítulo seis de Romanos,
no sólo la posibilidad,
sino la necesidad de ser libres del pecado al llegar
a estar bajo el Evangelio y la Gracia,
y ya no bajo la Ley.
En los versículos 2-7 declara que esta es su propia
condición y la de aquellos a quienes escribe;
y luego en el 11-13 y 16-18 argumenta tanto la posibilidad
como la necesidad de ser libres del pecado,
diciendo: "`No reine, pues, el pecado en vuestro cuerpo mortal,
de modo que lo obedezcáis en sus concupiscencias,`" y "`habiendo sido librados del pecado,
sois hechos siervos de la justicia.`"^
footnote:[Romanos 6:18 RV1602P]
Finalmente,
en el versículo 22 declara que sus lectores en cierta medida
habían alcanzado esta condición con estas palabras:
"`Mas ahora que habéis sido libertados del pecado y hechos siervos de Dios,
tenéis por vuestro fruto la santificación, y como fin, la vida eterna.`"

Ahora bien,
así como esta perfección o libertad del pecado se alcanza y se hace posible
donde el Evangelio y la ley interna del Espíritu son recibidos y experimentados,
asimismo desconocer esta vida y poder interno ha sido, y sigue siendo,
la razón por la que muchos se oponen a esta verdad.
Porque el hombre, por no prestar atención a la Luz o Ley dentro de su corazón,
que no sólo descubre el pecado, sino que lo conduce fuera de él,
sigue siendo ajeno a esa nueva Vida y Nacimiento que procede de Dios,
que naturalmente hace Su voluntad, y que no puede, por su propia naturaleza,
transgredir Sus mandamientos.
Tal hombre, en su estado natural, mira los mandamientos de Dios como algo fuera de él,
en la letra, y se halla a sí mismo reprobado y condenado, y por la letra muerto,
pero no vivificado.
Y así, hallándose a sí mismo herido,
y sin acudir internamente a esa Luz y Gracia que puede sanarlo,
se esfuerza en su propia voluntad por conformase a la Ley según está escrita en palabras,
lo cual nunca podrá lograr, sino que descubre que cuanto más se esfuerza,
más corto queda.
Y aunque estos tengan una noción del cristianismo y una fe externa en Cristo,
en realidad, todavía están en el estado del judío, con su mandamiento carnal,
su ley externa, en el estado del primer pacto que "`no puede hacer perfecto,
en cuanto a la conciencia,
al que lo practica`" (Hebreos 9:9). Esto los ha hecho forzar y torcer las Escrituras
en busca de una justicia imputada procedente completamente de afuera,
a fin de cubrir su continua impureza,
e imaginar que una aceptación por parte Dios es posible,
aun cuando sostienen que es imposible obedecer los mandamientos de Cristo.

¡Pero ay, oh almas engañadas!
Esto no servirá en el Día en el que Dios juzgue a "`cada uno según lo que haya hecho,
sea bueno o sea malo.`"^
footnote:[2 Corintios 5:10]
Decir que era necesario pecar diariamente en pensamiento, palabra y obra, no te salvará;
porque aquellos que lo hacen ciertamente han '`obedecido a la injusticia.`'^
footnote:[Romanos 2:8]
¿Y cuál es el fin de estos sino tribulación y angustia, indignación e ira?
Así como se promete gloria, honor,
paz e inmortalidad a quienes han hecho lo bueno y han perseverado en bien hacer.
Entonces,
si tú deseas experimentar esta perfección y libertad del pecado hecha posible para ti,
vuelve tu mente a la Luz y Ley espiritual de Cristo en el corazón,
y sométete a sus reprensiones.
Soporta el juicio y la indignación de Dios sobre
la naturaleza injusta en ti según sea revelada,
lo cual Cristo ha hecho tolerable para ti,
y entonces permite que el "`juicio`" en ti sea '`llevado a la victoria.`'^
footnote:[Mateo 12:20 LBLA]
De esta manera serás participes de los padecimientos de
Cristo y llegarás a ser semejante a Él en Su muerte.^
footnote:[Filipenses 3:10]
Te sentirás crucificado con Él al mundo por el poder de Su cruz obrando en ti,
para que esa vida que antes estaba viva en ti para este mundo, su amor y sus deseos,
pueda morir,
y se levante una nueva vida por la cual puedas vivir de
ahora en adelante para Dios y no para o por ti mismo.
Entonces realmente podrás decir con el apóstol:
"`Con Cristo estoy juntamente crucificado, y ya no vivo yo, mas vive Cristo en mí.`"^
footnote:[Gálatas 2:20]
Entonces serás un cristiano de verdad, y no sólo uno de nombre, como lo son muchos.
Entonces sabrás qué es haberse "`despojado del viejo hombre con
sus hechos,`" quien ciertamente peca a diario en pensamiento,
palabra y obra; y qué es ser "`revestido del nuevo,
el cual es renovado en conocimiento conforme a la imagen de Aquel que lo creó,`"^
footnote:[Colosenses 3:9-10 RV1602P]
y "`es creado en justicia y santidad verdadera.`"^
footnote:[Efesios 4:24 Versión Moderna H.B. Pratt (1929)]
Así podrás sentirte como "`hechura de Dios, creado en Cristo Jesús para buenas obras.`"^
footnote:[Efesios 2:10]
Para este nuevo hombre '`el yugo de Cristo es fácil, y su carga ligera,`'^
footnote:[Mateo 11:30]
aunque para el viejo Adán es pesado.
Sí, los mandamientos de Dios no son gravosos para este nuevo hombre;
porque su comida y bebida es ser hallado cumpliendo la voluntad de Dios.

=== Objeciones Consideradas

Ahora procederé a responder las objeciones y argumentos de nuestros oponentes.

Objeción: Comenzaré con su principal y más grande argumento,
el cual está basado en las palabras del apóstol Juan: "`Si decimos que no tenemos pecado,
nos engañamos a nosotros mismos, y la verdad no está en nosotros.`"^
footnote:[1 Juan 1:8]
Ellos piensan que esto es invencible.

Respuesta: Pero esta objeción no concuerda con el propósito de ellos,
porque Juan no dice que pecamos diariamente en pensamiento, palabra y obra,
y mucho menos,
que las buenas obras que Dios mismo obra en nosotros por medio de Su Espíritu sean pecado.
De hecho,
el siguiente versículo muestra claramente que sobre la base de la confesión
y el arrepentimiento no sólo somos perdonados sino también limpiados:
"`Él es fiel y justo para perdonar nuestros pecados, y limpiarnos de toda maldad.`"
Aquí hay tanto un perdón y una remoción de la culpa,
como una limpieza o remoción de la inmundicia;
porque sería absurdo y redundante sugerir que tanto el perdón
como la limpieza se refieran a la eliminación de la culpa.
Por esta razón, habiendo experimentado que la culpa y la inmundicia han sido removidas,
el apóstol continúa en tiempo pasado en el versículo 10, diciendo:
"`Si decimos que no hemos pecado, le hacemos a él mentiroso.`"

Además, como Agustín bien observó en su exposición sobre la epístola a los Gálatas:
"`Una cosa es no pecar, y otra cosa no tener pecado.`"
Las palabras del apóstol no son: "`Si decimos que no cometemos pecado diariamente,
nos engañamos a nosotros mismos;`" sino "`si decimos que no tenemos pecado.`"
¡Hay una gran diferencia entre estas dos declaraciones!
Porque reconocemos libremente que todos han pecado,
y que en este sentido se puede decir que todos tienen pecado.
Además,
aquí la palabra "`pecado`" puede ser tomada como una referencia
a la semilla de pecado que está en todos los hombres,
incluso en aquellos que ya han sido redimidos de vivir en pecado.
Pero en cuanto a las tentaciones y provocaciones que proceden de esta semilla,
cuando los siervos de Dios las resisten por la gracia de Dios en ellos y no ceden,
el pecado se atribuye al diablo que tienta, y no al hombre que es preservado.

Pero toda esta controversia es innecesaria, ya que el mismo apóstol,
en varios lugares de la misma epístola,
afirma de manera clara y positiva la posibilidad de la libertad del pecado,
como ya ha sido mencionado.

Objeción:
Su segunda objeción viene de dos lugares de las Escrituras
que dicen prácticamente lo mismo.
Uno es 1 Reyes 8:46, "`porque no hay hombre que no peque.`"
El otro es Eclesiastés 7:20, "`Ciertamente no hay hombre justo en la tierra,
que haga el bien y nunca peque.`"

Respuesta: En primer lugar,
estos versículos no dicen nada de un pecado diario y continuo,
del cual nunca seremos redimidos, sino únicamente que todos han pecado,
o que no hay nadie que no peque.
En segundo lugar,
hay algo que decir sobre el pacto y la dispensación en que fueron escritos;
porque aunque se concediera que en el tiempo de Salomón no había nadie que no pecara,
esto no implicaría necesariamente que no haya nadie ahora que no peque,
o que no sea alcanzable hoy, por medio de la gracia de Dios bajo el Evangelio, no pecar.
Por último, toda esta objeción se basa en una falsa interpretación de la Escritura,
porque la palabra Hebrea yekhta`' se puede leer en el modo potencial, traduciéndose así:
"`No hay hombre que no pueda pecar,`"^
footnote:[El modo potencial se refiere a construcciones verbales que expresan posibilidad,
probabilidad o capacidad en un contexto hipotético; como es el caso en 1 Reyes.
Literalmente expresa algo como: "`No hay hombre que no tenga la posibilidad de pecar`".]
que de hecho, es como Junius, Tremellius y también Vatablus la traducen del hebreo.
La misma palabra se traduce de manera similar en el modo potencial, en Salmos 119:11,
"`En mi corazón he guardado tus dichos, para no pecar contra ti.`"^
footnote:["`En mi corazón he guardado tus dichos,
para no tener que pecar contra ti;`" o "`para que pueda dejar de pecar contra ti.`"]
Y puesto que esta traducción es más congruente con la tendencia universal de las Escrituras,
con el testimonio de la Verdad y con el sentido de casi todos los intérpretes,
sin duda debe entenderse así.

Objeción: En tercer lugar,
ellos objetan basados en algunas expresiones del apóstol Pablo en Romanos capítulo 7:
"`Porque no hago el bien que quiero, sino el mal que no quiero, eso hago.`"^
footnote:[Romanos 7:19]
Y "`¡Miserable de mí! ¿quién me librará de este cuerpo de muerte?`"^
footnote:[Romanos 7:24]

Respuesta:
No hay nada en el texto que indique que él esté hablando de su condición presente,
o de una condición bajo la que deba estar siempre.
Por el contrario, en el capítulo anterior (como se mencionó ampliamente),
él insiste en que los cristianos,
al estar "`muertos al pecado,`" ya no deben vivir en él. Es evidente, entonces,
que aquí el apóstol habla de una condición que había experimentado anteriormente,
o que (por el bien de sus lectores) él personifica la condición
de alguien que aún no ha alcanzado la madurez,
lo cual es común en las Escrituras.

Ahora bien, es evidente que Pablo no habla aquí de su condición presente,
porque antes en este capítulo dice: "`Porque mientras estábamos en la carne,
las pasiones pecaminosas que eran por la ley obraban en nuestros
miembros llevando fruto para muerte`" (versículo 5);
"`Y yo sin la ley vivía en un tiempo; pero venido el mandamiento,
el pecado revivió y yo morí`" (versículo 9). Y luego dice:
"`Porque sabemos que la ley es espiritual; más yo soy carnal,
vendido al pecado`" (versículo 14). ¿Es que vamos a creer que el
apóstol Pablo era un hombre carnal al momento de escribir su epístola?
¿Acaso no nos informa claramente de que no fue dejado en esta condición,
sino que en verdad experimentó la libertad de ella?
Porque después de exclamar, "`¿quién me librará de este cuerpo de muerte?`"
contesta alegremente su propia pregunta, diciendo: "`Gracias doy a Dios,
por Jesucristo Señor nuestro;`"^
footnote:[Romanos 7:25]
y luego afirma que "`la ley del Espíritu de vida en Cristo Jesús`"
lo había "`librado de la ley del pecado y de la muerte,`" para
que "`la justicia de la ley se cumpliese en nosotros,
que no andamos conforme a la carne, sino conforme al Espíritu.`"^
footnote:[Romanos 8:2-4]

Objeción: En cuarto lugar,
ellos objetan basados en las faltas y pecados de varios santos eminentes, como Noé,
David, etc.

Respuesta: Esto no prueba en lo absoluto el argumento de nuestros oponentes;
porque la cuestión no es si los hombres buenos no
pueden caer en pecado (lo cual no negamos),
sino si es imposible para ellos no pecar.
Además, el hecho de que estos hombres hayan pecado en ciertas ocasiones,
no significa que nunca dejaron de pecar y, por lo tanto,
que nunca experimentaron tiempos de verdadera libertad del pecado.

Objeción: Finalmente, objetan basados en la oración de nuestro Señor,
donde les enseñó a Sus discípulos a decir: "`Perdónanos nuestras deudas,
como también nosotros perdonamos a nuestros deudores.`"^
footnote:[Mateo 6:12]

Respuesta: Nosotros no negamos que "`todos pecaron,
y están destituidos de la gloria de Dios,`"^
footnote:[Romanos 3:23]
y por lo tanto, que todos necesitan rogar que sus pecados pasados sean borrados,
y ser preservados diariamente de pecar.
Pero si alguno se atreve a decir que tener la esperanza
de ser libres de pecado y creer que esto es posible,
impide orar por el perdón del pecado,
se concluiría por la misma regla que debemos "`perseverar
en el pecado para que la gracia abunde;`"^
footnote:[Romanos 6:1]
porque cuanto más pecado cometan los hombres,
mayor será la ocasión de pedir perdón de pecado.
Pero el apóstol, en su respuesta a esta misma controversia,
ha refutado suficientemente esas tonterías con las que pretenden defender el pecado,
diciendo: "`En ninguna manera.
Porque los que hemos muerto al pecado, ¿cómo viviremos aún en él?`"^
footnote:[Romanos 6:2]

Para concluir:
Bienaventurados los que creen en Aquel que tiene
tanto el poder como el deseo de redimir de todo pecado,
a todos los que acuden a Él por medio de un verdadero arrepentimiento,
y que deciden no ser siervos del diablo durante toda
su vida (como lo hacen nuestros adversarios),
sino que diariamente siguen adelante, dejando la injusticia,
olvidando lo que queda atrás y "`prosiguiendo la meta,
al premio del supremo llamamiento de Dios en Cristo Jesús.`"^
footnote:[Filipenses 3:14]
Éstos encontrarán que su fe y confianza no han sido en vano, y que, a su debido tiempo,
serán hechos vencedores por medio de Aquel en quien han creído; y así, habiendo vencido,
serán establecidos como "`columnas en el templo de
Dios,`" de tal modo que "`nunca más saldrán de allí.`"^
footnote:[Apocalipsis 3:12]
